coveo/ui-kit

packages/atomic/src/pages/accessibility/commerce-full.html

https://coveord.atlassian.net/browse/KIT-1884

docs(atomic): sorted all facets in commerce-full.html

---

packages/atomic/cypress/integration/result-list/result-components/result-link.cypress.ts
packages/atomic/src/pages/examples/folding.html
packages/atomic/src/pages/index.html
packages/atomic/src/pages/visualTests.html
packages/atomic/src/utils/slot-utils.ts
packages/samples/angular/src/app/atomic-angular-page/atomic-angular-page.component.html
packages/samples/vuejs/src/components/ResultsList.vue
packages/samples/vuejs/src/components/SearchPage.vue

https://coveord.atlassian.net/browse/KIT-1878

fix(atomic): result link default slot should not create a warning

---

.github/workflows/masterbot.yml
.github/workflows/snyk.yml
lerna.json

https://coveord.atlassian.net/browse/KIT-1864

ci: add [skip ci] on bump commits

---

.github/workflows/masterbot.yml
.github/workflows/snyk.yml

https://coveord.atlassian.net/browse/KIT-1864

fix: remove "needs: allow-workflow"

---

packages/atomic/src/components/facets/atomic-segmented-facet-scrollable/atomic-segmented-facet-scrollable.tsx

https://coveord.atlassian.net/browse/KIT-1855

feat(atomic): fix scrollable mobile view overscrolling

---

.github/ISSUE_TEMPLATE/bug_report.yml

Added a new template for people to fill when creating a bug report. Let me know if something's missing!

chore: added new issue template

---

packages/headless/src/api/analytics/search-analytics.ts
packages/headless/src/features/case-field/case-field-actions.ts
packages/headless/src/features/configuration/analytics-params.ts
packages/headless/src/features/configuration/configuration-slice.ts
packages/headless/src/features/configuration/configuration-state.ts
packages/headless/src/features/document-suggestion/document-suggestion-actions.ts
packages/headless/src/features/product-listing/product-listing-actions.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts
packages/headless/src/features/query-suggest/query-suggest-actions.ts
packages/headless/src/features/recommendation/recommendation-actions.ts
packages/headless/src/features/result-preview/result-preview-request-builder.ts
packages/headless/src/features/search-and-folding/search-and-folding-request.ts
packages/headless/src/features/standalone-search-box-set/standalone-search-box-set-actions.ts

https://coveord.atlassian.net/browse/KIT-1891

fix(headless): provide runtimeEnvironment for all Analytics Clients

---

JenkinsfileProductionRelease

https://coveord.atlassian.net/browse/KIT-1890

ci: use npx for ts-node during prod release

---

packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx

https://coveord.atlassian.net/browse/KIT-1630

fix(atomic): change timeout message from error to warning

---

packages/samples/angular/README.md
packages/samples/headless-react/README.md

https://coveord.atlassian.net/browse/KIT-1674

chore: update some readmes

---

packages/atomic/cypress/integration/search-box/search-box.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx
packages/atomic/src/components/search/search-box-suggestions/suggestions-common.ts
packages/headless/src/controllers/core/search-box/headless-core-search-box-options.ts
packages/headless/src/controllers/core/search-box/headless-core-search-box.test.ts
packages/headless/src/controllers/core/search-box/headless-core-search-box.ts
packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.test.ts
packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.ts
packages/headless/src/features/search/search-actions.ts
packages/samples/angular/README.md
packages/samples/headless-react/README.md

https://coveord.atlassian.net/browse/KIT-1505

feat(atomic,headless): add clearFilters option on search box

---

packages/atomic/cypress/integration/facets/category-facet/category-facet-selectors.ts
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/search/facets/facet-common.ts
packages/atomic/src/components/search/facets/facet-value-link/facet-value-link.tsx
packages/headless/src/features/facets/category-facet-set/interfaces/response.ts
packages/headless/src/test/mock-category-facet-value.ts

https://coveord.atlassian.net/browse/KIT-1888

feat(atomic): add leaf and node value part for category facet

---

packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/search/facets/atomic-popover/atomic-popover.tsx
packages/atomic/src/components/search/facets/atomic-popover/popover-event.ts
packages/atomic/src/index.ts
packages/atomic/src/pages/index.html

https://user-images.githubusercontent.com/97299176/182834182-7a194e6c-652a-4120-930c-54a79fcfebf5.mov

feat(atomic): add count label on popover

---

packages/headless/src/features/debug/ranking-info-parser.test.ts
packages/headless/src/features/debug/ranking-info-parser.ts

https://coveord.atlassian.net/browse/KIT-1914

fix(headless): allow for negative score for QRE weights

---

packages/atomic/src/utils/initialization-utils.tsx

https://coveord.atlassian.net/browse/KIT-1915

fix(atomic): introduce forceUpdate to InitializeBindings decorator

---

packages/atomic/src/components/search/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/pages/accessibility/commerce-full.html

https://coveord.atlassian.net/browse/KIT-1925

fix(atomic): sort order for numeric facets in commerce page

---

packages/atomic/src/components/common/refine-modal/refine-modal-common.pcss
packages/atomic/src/components/common/refine-modal/refine-modal-common.tsx
packages/atomic/src/components/insight/atomic-insight-refine-modal/atomic-insight-refine-modal.pcss
packages/atomic/src/components/insight/atomic-insight-refine-modal/atomic-insight-refine-modal.tsx
packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.pcss
packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx

https://coveord.atlassian.net/browse/KIT-1893

refactor(atomic): extract code for atomic refine modals

---

packages/atomic/src/components/common/atomic-icon/atomic-icon.tsx

https://coveord.atlassian.net/browse/KIT-1931

fix(atomic): add force update to atomic-icon

---

packages/atomic/src/components/common/facets/facet-common.tsx
packages/atomic/src/components/common/facets/numeric-facet-common.tsx
packages/atomic/src/components/common/facets/timeframe-facet-common.tsx
packages/atomic/src/components/search/atomic-layout/__snapshots__/search-layout.spec.ts.snap
packages/atomic/src/components/search/atomic-layout/search-layout.ts
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/search/facets/atomic-popover/atomic-popover.tsx
packages/atomic/src/components/search/facets/atomic-popover/popover-type.ts
packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/pages/examples/horizontal-facets.html

https://coveord.atlassian.net/browse/KIT-1935

feat(atomic): make all facet types work with atomic-popover

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/common/interface/bindings.ts
packages/atomic/src/components/common/pager/pager-common.tsx
packages/atomic/src/components/common/types.ts
packages/atomic/src/components/insight/atomic-insight-interface/atomic-insight-interface.pcss
packages/atomic/src/components/insight/atomic-insight-pager/atomic-insight-pager.pcss
packages/atomic/src/components/insight/atomic-insight-pager/atomic-insight-pager.tsx
packages/atomic/src/components/insight/index.ts
packages/atomic/src/components/search/atomic-pager/atomic-pager.tsx
packages/atomic/src/pages/examples/insights.html
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1938
turned out to be easier than I thought, so I did it!
https://user-images.githubusercontent.com/30511433/183876043-4d7fd106-1c78-4f0d-9228-1c8f3f349f5c.mov

feat(atomic): add pager to insight panel

---

packages/atomic/src/components/common/facets/numeric-facet-common.tsx
packages/atomic/src/components/common/facets/timeframe-facet-common.tsx
packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx

https://coveord.atlassian.net/browse/KIT-1935

fix(atomic): use valuesToRender for hasValues (range facets)

---

packages/atomic/src/components/insight/atomic-insight-search-box/atomic-insight-search-box.pcss

https://coveord.atlassian.net/browse/KIT-1945

fix(atomic): align search button in insight search box

---

packages/atomic/cypress/integration/segmented-facet-scrollable-actions.ts
packages/atomic/cypress/integration/segmented-facet-scrollable-assertions.ts
packages/atomic/cypress/integration/segmented-facet-scrollable-selectors.ts
packages/atomic/cypress/integration/segmented-facet-scrollable.cypress.ts
packages/atomic/src/components/search/atomic-layout/atomic-search-layout.pcss
packages/atomic/src/components/search/facets/atomic-segmented-facet-scrollable/atomic-segmented-facet-scrollable.pcss
packages/atomic/src/components/search/facets/atomic-segmented-facet-scrollable/atomic-segmented-facet-scrollable.tsx
packages/atomic/src/pages/examples/horizontal-facets.html

see jira
https://coveord.atlassian.net/browse/KIT-1942

fix(atomic): a few segmented scrollable glitches

---

packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/cypress/integration/facets/segmented-facet/segmented-facet.cypress.ts

https://coveord.atlassian.net/browse/KIT-1960

test(atomic): skip facet occurences test (temporary)

---

package-lock.json
packages/atomic/package.json
packages/atomic/src/components/common/facets/facet-common.pcss
packages/atomic/src/components/common/facets/facet-search/facet-search-input.tsx
packages/atomic/src/components/insight/atomic-insight-facet/atomic-insight-facet.pcss
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.pcss
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.pcss
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/search/facets/atomic-popover/atomic-popover.pcss
packages/atomic/src/components/search/facets/atomic-popover/atomic-popover.tsx
packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.pcss
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.pcss
packages/atomic/src/components/search/facets/atomic-segmented-facet/atomic-segmented-facet.pcss

https://coveord.atlassian.net/browse/KIT-1936

feat(atomic): add popperjs for atomic-popover positioning

---

.prettierrc.js
package.json
packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic-angular/projects/atomic-angular/src/public-api.ts
packages/atomic-react/src/components/index.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.tsx
packages/atomic/src/pages/accessibility/commerce-full.html
packages/samples/angular/src/app/atomic-angular-page/atomic-angular-page.component.html
packages/samples/angular/src/app/atomic-angular-page/atomic-angular-page.component.ts
packages/samples/atomic-react/src/components/AtomicPageWrapper.tsx

https://coveord.atlassian.net/browse/KIT-1909
Also added examples for react and angular.

feat(atomic): allowed customization of instant results aria-label

---

packages/headless/src/controllers/core/search-box/headless-core-search-box.test.ts
packages/headless/src/features/breadcrumb/breadcrumb-actions-loader.ts
packages/headless/src/features/breadcrumb/breadcrumb-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/search/search-actions.ts

https://coveord.atlassian.net/browse/KIT-1965

feat(atomic,headless): deselect facets with hasBreadcrumbs=false on new query

---

packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.test.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ts

https://coveord.atlassian.net/browse/KIT-1962

fix(headless): prevent undefined enableQuerySyntax value to be added to the params manager

---

packages/headless/src/features/search/search-request.test.ts
packages/headless/src/features/search/search-request.ts

https://coveord.atlassian.net/browse/KIT-1964
Discuss https://discuss.coveo.com/t/headless-atomic-numeric-range-facet-are-not-updating-as-expected/8309

fix(headless): remove idle range when generateAutomaticRanges is true

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/common/atomic-focus-trap.tsx
packages/atomic/src/components/search/facets/atomic-popover/atomic-popover.tsx
packages/atomic/src/components/search/facets/atomic-popover/popover-type.ts

https://coveord.atlassian.net/browse/KIT-1937
Now has
- semi-transparent backdrop which closes on click
- close on ESC key
- focus trap for the button/facet

feat(atomic): improve atomic-popover interaction

---

packages/atomic/cypress/integration/search-box/instant-results/search-box-instant-results.cypress.ts
packages/atomic/cypress/integration/search-box/search-box-actions.ts
packages/atomic/cypress/utils/mock-result.ts

https://coveord.atlassian.net/browse/KIT-1968

test(atomic): added tests for ariaLabelGenerator

---

packages/atomic/src/components/insight/atomic-insight-timeframe-facet/atomic-insight-timeframe-facet.tsx

There will be quite a bit of work with KIT-1952 😄 
https://coveord.atlassian.net/browse/KIT-1947

fix(atomic): pass insight-timeframe-facet id

---

packages/quantic/cypress/integration/pager/pager-selectors.ts
packages/quantic/force-app/main/default/labels/CustomLabels.labels-meta.xml
packages/quantic/force-app/main/default/lwc/quanticNumberButton/quanticNumberButton.html
packages/quantic/force-app/main/default/lwc/quanticNumberButton/quanticNumberButton.js
packages/quantic/force-app/main/default/lwc/quanticPager/quanticPager.html
packages/quantic/force-app/main/default/lwc/quanticPager/quanticPager.js
packages/quantic/force-app/main/default/lwc/quanticResultsPerPage/quanticResultsPerPage.html
packages/quantic/force-app/main/default/lwc/quanticResultsPerPage/quanticResultsPerPage.js
packages/quantic/force-app/main/translations/fr.translation-meta.xml

[SVCC-2300](https://coveord.atlassian.net/browse/SVCC-2300)
Added ariaLabel for quantic
NumberButton

feat(quantic): added ariaLabel for quanticNumberButton

---

packages/quantic/force-app/main/default/labels/CustomLabels.labels-meta.xml
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.html
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.js
packages/quantic/force-app/main/translations/fr.translation-meta.xml

[SVCC-2301](https://coveord.atlassian.net/browse/SVCC-2301)
feat(quantic): added ariaLabel for timeframeFacet.

feat(quantic): added ariaLabel for timeframeFacet.

---

packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx

https://coveord.atlassian.net/browse/KIT-1924

docs(atomic): fix jsdoc for some instant-result parts

---

packages/atomic/src/components/search/facets/atomic-popover/atomic-popopver.stories.tsx
packages/atomic/src/components/search/facets/atomic-segmented-facet-scrollable/atomic-segmented-facet-scrollable.stories.tsx
packages/atomic/src/components/search/facets/atomic-segmented-facet/atomic-segmented-facet.stories.tsx

https://coveord.atlassian.net/browse/KIT-1980

docs(atomic): add stories for horizontal facets components

---

packages/quantic/.prettierrc.js
packages/quantic/cypress/integration/tab-bar/tab-bar-selectors.ts
packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.html
packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.js

[SVCC-2375](https://coveord.atlassian.net/browse/SVCC-2375)
feat(quantic): added keydown listener for tab dropdown menu items.

feat(quantic): added keydown listener for tab dropdown menu items

---

packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx

https://coveord.atlassian.net/browse/KIT-2002

fix(atomic): text-align left for recent queries content

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/facets/atomic-segmented-facet/atomic-segmented-facet.tsx

https://coveord.atlassian.net/browse/KIT-2011

fix(atomic): cleanup unused prop for segmented facet and add support for depends on

---

packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js

[SVCC-2293](https://coveord.atlassian.net/browse/SVCC-2293)
change sortCriteria to "score" for facetValue in order to keep the same order of facetValues after "Show More" or "Show Less" is clicked.

feat(quantic): change sortCriteria for facetValue

---

packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.css
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
packages/quantic/force-app/main/default/lwc/quanticFacetValue/quanticFacetValue.js

[SVCC-2292](https://coveord.atlassian.net/browse/SVCC-2292) 
Add focus control for facetValue. Focus now will be set to first item in the element after `showMore` or `showLess` is clicked.

feat(quantic): add focus control for facetValue

---

packages/atomic/src/components/common/refine-modal/refine-modal-common.tsx
packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx

https://coveord.atlassian.net/browse/KIT-2007
I tried to add parts to every element in the refine modal that didn't have one (except those with `display: contents;`).

fix(atomic): added missing parts to refine modal

---

packages/atomic/src/components/insight/atomic-insight-refine-modal/atomic-insight-refine-modal.tsx

https://coveord.atlassian.net/browse/KIT-2008
Copied from `atomic-refine-modal`'s:

feat(atomic): added "filters" header with clear button to insight refine modal

---

packages/quantic/force-app/main/default/labels/CustomLabels.labels-meta.xml
packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.html
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.html
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.html
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.js
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.html
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.js

[SVCC-2299](https://coveord.atlassian.net/browse/SVCC-2299)
feat(quantic): add labels for buttons
After:

feat(quantic): add labels for buttons

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/common/atomic-icon-button/atomic-icon-button.tsx
packages/atomic/src/components/insight/atomic-insight-refine-toggle/atomic-insight-refine-toggle.tsx
packages/atomic/src/global/global.pcss

https://coveord.atlassian.net/browse/KIT-2019

fix(atomic): disable atomic-insight-refine-toggle button on no results

---

packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.html

[SVCC-2383](https://coveord.atlassian.net/browse/SVCC-2383)
add focus to selected category facet
After:

feat(quantic): add focus to selected category facet

---

packages/atomic/cypress/integration/facets/popover-facet/popover-facet-actions.ts
packages/atomic/cypress/integration/facets/popover-facet/popover-facet.cypress.ts
packages/atomic/src/components/common/facets/numeric-facet-common.tsx
packages/atomic/src/components/common/facets/timeframe-facet-common.tsx

https://coveord.atlassian.net/browse/KIT-2021

fix(atomic): make atomic-popover compatible with input only range facets

---

packages/atomic-react/package.json

https://coveord.atlassian.net/browse/KIT-2022
Use to be accepted with `1.4.15`

fix(atomic-react): add peer deps for react version 18

---

packages/atomic/cypress/integration/breadbox.cypress.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet-action.ts

https://coveord.atlassian.net/browse/KIT-2023

test(atomic): flaky breadbox cypress test

---

packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet-action.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts

My bad! Changed the setup a bit recently
https://coveord.atlassian.net/browse/KIT-2026

fix(atomic): timefrace facet test

---

packages/atomic-react/package.json

https://coveord.atlassian.net/browse/KIT-2022

fix(atomic-react): only have react 18 as peer dependency

---

packages/atomic/cypress/integration/result-list/folded-result-list-assertions.ts
packages/atomic/cypress/integration/result-list/folded-result-list.cypress.ts

https://coveord.atlassian.net/browse/KIT-2028

test(atomic): fix folding tests

---

packages/atomic/cypress/integration/common-assertions.ts
packages/atomic/cypress/integration/icon.cypress.ts
packages/atomic/src/components/common/atomic-icon/atomic-icon.tsx

https://coveord.atlassian.net/browse/KIT-1652

feat(atomic): add warning for possible rendering issues with atomic-icon

---

packages/atomic/src/components/insight/atomic-insight-result-list/atomic-insight-result-list.tsx

https://coveord.atlassian.net/browse/SVCC-2470

fix(atomic): add rendering condition to insight result list

---

packages/atomic/cypress/integration/result-list/result-components/result-text.cypress.ts
packages/atomic/src/components/search/result-template-components/atomic-result-text/atomic-result-text.tsx

https://coveord.atlassian.net/browse/KIT-2031

feat(atomic): add error message when result-value-text is used with multi value field

---

packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-2038

fix(atomic): fix default template for atomic-result-text on language

---

packages/headless/src/controllers/core/facets/facet-conditions-manager/headless-facet-conditions-manager.test.ts
packages/headless/src/controllers/core/facets/facet-conditions-manager/headless-facet-conditions-manager.ts

https://coveord.atlassian.net/browse/KIT-1995
I did a big refactor of the facet conditions manager to make it simpler to read and make it react when a facet which is relevant is initialized.

fix(headless): made facet conditions manager initializable before facets

---

packages/atomic/src/components/search/search-box-suggestions/suggestions-common.ts

https://coveord.atlassian.net/browse/KIT-2037

chore(atomic): add doc for exported suggestions types, add support for insight search box

---

packages/atomic/src/components/search/result-template-components/atomic-result-multi-value-text/atomic-result-multi-value-text.stories.tsx

https://coveord.atlassian.net/browse/KIT-1929

docs(atomic): fix multi value text storybook

---

packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx

Follow up to yesterday's PR with `ArrayProp` utils
https://coveord.atlassian.net/browse/KIT-2041

fix(atomic): use ArrayProp for facet allowed values option

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/search/atomic-load-more-children-results/atomic-load-more-children-results.tsx
packages/atomic/src/components/search/result-lists/atomic-result-children/atomic-result-children.tsx
packages/atomic/src/pages/examples/folding.html

https://coveord.atlassian.net/browse/KIT-2050
Just renaming, did part of this when I had to solve an issue (KIT-1856)

chore(atomic): small folding renaming/refactor

---

.github/workflows/masterbot.yml

https://coveord.atlassian.net/browse/KIT-2063

fix(atomic): masterbot cypress config

---

packages/atomic/cypress/e2e/facets/category-facet/category-facet.cypress.ts

https://coveord.atlassian.net/browse/KIT-2063

fix(atomic): flaky category focus tests

---

.github/workflows/masterbot.yml

https://coveord.atlassian.net/browse/KIT-2065
The formatting was invalid 🙈

fix: masterbot

---

.github/workflows/masterbot.yml

https://coveord.atlassian.net/browse/KIT-2065

fix: masterbot again

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/common/atomic-result-placeholder/atomic-result-placeholder.tsx
packages/atomic/src/components/common/atomic-result-placeholder/placeholders.tsx
packages/atomic/src/components/common/interface/interface-common.tsx
packages/atomic/src/components/common/interface/store.ts
packages/atomic/src/components/common/result-list/result-list-common.tsx
packages/atomic/src/components/common/result/result-row-desktop.pcss
packages/atomic/src/components/common/result/result-row-mobile.pcss
packages/atomic/src/components/insight/atomic-insight-facet/atomic-insight-facet.tsx
packages/atomic/src/components/insight/atomic-insight-interface/atomic-insight-interface.tsx
packages/atomic/src/components/insight/atomic-insight-numeric-facet/atomic-insight-numeric-facet.tsx
packages/atomic/src/components/insight/atomic-insight-pager/atomic-insight-pager.tsx
packages/atomic/src/components/insight/atomic-insight-result-list/atomic-insight-result-list.tsx
packages/atomic/src/components/insight/atomic-insight-timeframe-facet/atomic-insight-timeframe-facet.tsx
packages/atomic/src/components/recommendations/atomic-recs-interface/atomic-recs-interface.tsx
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx
packages/atomic/src/components/search/result-lists/atomic-result-children/atomic-result-children.tsx
packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/pages/examples/recommendations.html
packages/atomic/src/utils/accessibility-utils.tsx
packages/headless/src/insight.index.ts

https://coveord.atlassian.net/browse/KIT-2050 (last PR for this task)

feat(atomic): fields to include refactor

---

packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.css

[SVCC-2298](https://coveord.atlassian.net/browse/SVCC-2298)
Issue found in the QuanticTabBar component, this component is causing an unnecessary horizontal scroll bar when displayed in smaller screens
https://user-images.githubusercontent.com/86681870/194086998-aa5e96ca-c08e-468d-880b-85f7322e39be.mov
https://user-images.githubusercontent.com/86681870/194087016-eb248cbb-d77e-41ed-848a-3ae0a2323d6b.mov

fix(quantic):  overflow hidden added to prevent horizontal scroll in the QuanticTabBar

---

packages/atomic/cypress/e2e/search-box/instant-results/search-box-instant-results.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/common/interface/result.ts
packages/atomic/src/components/common/result-list/grid-display-results.tsx
packages/atomic/src/components/common/result-list/list-display-results.tsx
packages/atomic/src/components/common/result-list/result-list-common-interface.ts
packages/atomic/src/components/common/result-list/table-display-results.tsx
packages/atomic/src/components/insight/atomic-insight-result-list/atomic-insight-result-list.tsx
packages/atomic/src/components/insight/atomic-insight-result/atomic-insight-result.tsx
packages/atomic/src/components/insight/index.ts
packages/atomic/src/components/recommendations/atomic-recs-interface/atomic-recs-interface.tsx
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx
packages/atomic/src/components/recommendations/atomic-recs-result/atomic-recs-result.tsx
packages/atomic/src/components/recommendations/index.ts
packages/atomic/src/components/search/atomic-result/atomic-result.tsx
packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx
packages/atomic/src/components/search/result-lists/atomic-result-children/atomic-result-children.tsx
packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/search/result-template-components/atomic-result-link/atomic-result-link.tsx
packages/atomic/src/components/search/result-template-components/result-template-decorators.tsx
packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.tsx
packages/headless/src/controllers/recommendation/result-list/headless-recommendation-interactive-result.test.ts
packages/headless/src/controllers/recommendation/result-list/headless-recommendation-interactive-result.ts
packages/headless/src/features/recommendation/recommendation-analytics-actions.ts
packages/headless/src/recommendation.index.ts

https://coveord.atlassian.net/browse/KIT-2079

feat(atomic,headless): use different InteractiveResult per engine/interface

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/common/carousel.tsx
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.pcss
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx
packages/atomic/src/pages/examples/recommendations.html
packages/headless/src/recommendation.index.ts

https://coveord.atlassian.net/browse/KIT-2075

feat(atomic): add pagination to recommendations

---

packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js
packages/quantic/force-app/main/default/lwc/quanticRefineModalContent/quanticRefineModalContent.js
packages/quantic/force-app/main/default/lwc/quanticRefineToggle/quanticRefineToggle.js
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.js

[SFINT-4655](https://coveord.atlassian.net/browse/SFINT-4655)
The LWC event names need to be all in lowercase in order to respect the LWC standards.

fix(quantic): event name updated to respect LWC standards

---

packages/atomic/.storybook/default-init.ts
packages/atomic/.storybook/default-story-shared.tsx
packages/atomic/.storybook/default-story.tsx
packages/atomic/.storybook/dispatch-addons.ts
packages/atomic/.storybook/preview.js
packages/atomic/.storybook/recommendation/recs-init.ts
packages/atomic/.storybook/recommendation/recs-story.tsx
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.stories.tsx

https://coveord.atlassian.net/browse/KIT-2077

chore(atomic): add recslist to storybook

---

packages/atomic/cypress/e2e/facets/category-facet/category-facet-assertions.ts
packages/atomic/cypress/e2e/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/e2e/search-box/search-box.cypress.ts

https://coveord.atlassian.net/browse/KIT-2095

test(atomic): fix flaky search box test; remove category facet focus test

---

packages/atomic/src/components/common/facets/facet-common.tsx
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx

https://coveord.atlassian.net/browse/KIT-2094
I'm surprised no test(s) failed 🤔 
Thinking of adding one, but now that there's no additional condition (canShowMoreValues) it doesn't really make sense

feat(atomic): always show facet search when enabled

---

packages/headless/src/features/index.ts
packages/headless/src/features/tab-set/tab-set-actions-loader.ts
packages/headless/src/features/tab-set/tab-set-actions.ts

https://coveord.atlassian.net/browse/KIT-2098

chore(headless): export tab actions

---

packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/controllers/core/facets/facet-search/category/headless-category-facet-search.test.ts
packages/headless/src/controllers/core/facets/facet-search/category/headless-category-facet-search.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet-search.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/field-suggestions/category-facet/headless-category-field-suggestions.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet-search.ts
packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet.ts
packages/headless/src/features/facets/facet-search-set/category/category-facet-search-request-builder.test.ts
packages/headless/src/features/facets/facet-search-set/category/category-facet-search-request-builder.ts
packages/headless/src/features/facets/facet-search-set/generic/generic-facet-search-actions.ts
packages/headless/src/integration-tests/category-field-suggestions.test.ts
packages/headless/src/integration-tests/field-suggestions.test.ts
packages/headless/src/test/functional-test-utils.ts

https://coveord.atlassian.net/browse/KIT-2073
Follow-up to https://github.com/coveo/ui-kit/pull/2508

fix(headless): made category field suggestions not inherit the search context

---

packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.tsx

https://coveord.atlassian.net/browse/KIT-1966

doc(atomic): link to IR accessibility doc from IR component

---

packages/headless/package.json

- `coveo.analytics` version `2.22.3` installed.

chore(headless): coveo.analytics.js updated

---

packages/atomic/src/components/common/facets/facet-search/facet-search-input.tsx
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-2113

feat(atomic): decouple label for facet search and search box input

---

packages/headless/package.json
packages/headless/src/controllers/insight/result-list/headless-insight-interactive-result.test.ts
packages/headless/src/features/result/result-insight-analytics-actions.ts
packages/headless/src/features/triggers/trigger-analytics-actions.ts

https://coveord.atlassian.net/browse/KIT-2055
Related PR: https://github.com/coveo/coveo.analytics.js/pull/381

fix(headless): made trigger notify and execute events plural

---

packages/headless/package.json
packages/headless/src/features/triggers/trigger-analytics-actions.ts

https://coveord.atlassian.net/browse/KIT-2115
This is a copy of https://github.com/coveo/ui-kit/pull/2533, but I just realized that when somebody inevitably updates coveo.analytics in v1, they're gonna have an error, so I'm doing it early here to avoid the confusion.

chore(headless): update coveo.analytics

---

packages/headless/src/features/folding/folding-slice.ts

https://coveord.atlassian.net/browse/KIT-2127
Description of the issue / steps to reproduce in Jira above.
I didn't add tests because I don't think they'd provide much value, even with a refactor it would be doubtful that we'd re-introduce this issue.

fix(headless): made updating results per page update folded collections

---

packages/samples/angular/.eslintrc.json
packages/samples/angular/scripts/link-hoisted-dependencies.mjs
scripts/deploy/invalidate-cloudfront.mjs
scripts/deploy/update-npm-tag.mjs
scripts/notify-docs/published-ui-kit.mjs
scripts/packages.mjs

https://coveord.atlassian.net/browse/KIT-2114
Paths are no longer relative to the JS file.

ci: fix package.json paths

---

scripts/deploy/invalidate-cloudfront.mjs
scripts/packages.mjs

https://coveord.atlassian.net/browse/KIT-2150
Not sure how I missed this. Merging ASAP because it could break other things.

ci: fix invalidate cloudfront getMajorVersion

---

README.md
package.json
packages/atomic-angular/package.json
packages/quantic/package.json
packages/samples/angular/package.json
packages/samples/atomic-next/package.json
packages/samples/headless-react/package.json
packages/samples/stencil/package.json
packages/samples/vuejs/package.json

https://coveord.atlassian.net/browse/KIT-282

chore: update dependencies & change private repo names

---

packages/atomic-angular/package.json
packages/atomic-react/package.json
packages/atomic/package.json
packages/atomic/src/components.d.ts

https://coveord.atlassian.net/browse/KIT-2166

fix(atomic,atomic-angular,atomic-react): add headless to dev dependencies

---

packages/atomic/src/components/search/atomic-layout/__snapshots__/search-layout.spec.ts.snap
packages/atomic/src/components/search/atomic-layout/search-layout.ts

https://coveord.atlassian.net/browse/KIT-2148

fix(atomic): close search layout tag properly

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/cypress/e2e/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/common/facets/facet-date-input/facet-date-input.tsx
packages/atomic/src/components/common/facets/timeframe-facet-common.tsx
packages/atomic/src/components/search/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx

https://coveord.atlassian.net/browse/KIT-2108

feat(atomic): add support for min and max for atomic-timeframe-facet

---

packages/samples/angular/package.json
packages/samples/atomic-next/package.json
packages/samples/atomic-react/package.json
packages/samples/headless-react/package.json
packages/samples/stencil/package.json
packages/samples/vuejs/package.json

https://coveord.atlassian.net/browse/KIT-2181

fix: made dependencies in private packages use carets

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/cypress/e2e/refine-toggle.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/common/facets/facet-common.tsx
packages/atomic/src/components/common/refine-modal/refine-modal-common.tsx
packages/atomic/src/components/insight/atomic-insight-refine-modal/atomic-insight-refine-modal.tsx
packages/atomic/src/components/ipx/atomic-ipx-refine-modal/atomic-ipx-refine-modal.tsx
packages/atomic/src/components/ipx/atomic-ipx-refine-toggle/atomic-ipx-refine-toggle.tsx
packages/atomic/src/components/search/atomic-facet-manager/atomic-facet-manager.tsx
packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/components/search/atomic-refine-toggle/atomic-refine-toggle.tsx

https://coveord.atlassian.net/browse/KIT-2137
I forgot this for a while, woops. It's a simple change and it was clear in my mind so I took a moment to make it. I also didn't want to commit to anything long this morning until planif.
This is not a v2/prerelease change.

feat(atomic): added collapseFacetsAfter option to refine toggle

---

packages/atomic/cypress/e2e/search-interface.cypress.ts
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-2188

test(atomic): fix language keys

---

packages/atomic/cypress/e2e/search-interface.cypress.ts
packages/atomic/src/components/recommendations/atomic-recs-interface/atomic-recs-interface.tsx
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx

https://coveord.atlassian.net/browse/KIT-2211

fix(atomic): removed console warning when pipeline or search hub aren't configured

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/search/result-template-components/atomic-quickview-modal/atomic-quickview-modal.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview/atomic-quickview.tsx
packages/atomic/src/components/search/result-template-components/quickview-iframe/quickview-iframe.tsx

https://coveord.atlassian.net/browse/KIT-2203

feat(atomic): add new prop to allow to control the iframe sandbox attribute

---

packages/atomic/cypress/e2e/common-assertions.ts
packages/atomic/cypress/e2e/icon.cypress.ts
packages/atomic/cypress/support/commands.ts
packages/atomic/package.json
packages/atomic/src/components/common/atomic-icon/atomic-icon.tsx

https://coveord.atlassian.net/browse/KIT-2196
Also added a util so we can retrieve the exact error thrown.

fix(atomic): improved atomic-icon error handling

---

packages/atomic/src/components/search/result-template-components/atomic-quickview-modal/atomic-quickview-modal.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview-sidebar/atomic-quickview-sidebar.tsx

Fix scroll issue when the list of keywords is very long, or the available vertical space is very small.
https://coveord.atlassian.net/browse/KIT-2217

fix(atomic): fix quickview column keywords scroll

---

packages/atomic/cypress/e2e/refine-toggle.cypress.ts
packages/atomic/src/components/common/atomic-modal/atomic-modal.tsx

https://coveord.atlassian.net/browse/KIT-2218

feat(atomic): add support to close modal on escape

---

packages/atomic/src/components/search/result-template-components/atomic-quickview-sidebar/atomic-quickview-sidebar.tsx

https://coveord.atlassian.net/browse/KIT-2223

fix(atomic): format keyword occurence number in quickview

---

packages/atomic/src/components/search/result-template-components/atomic-quickview-modal/atomic-quickview-modal.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview-sidebar/atomic-quickview-sidebar.tsx

https://coveord.atlassian.net/browse/KIT-2215

fix(atomic): empty highlight keywords column should not be visible

---

renovate.json

Group up React & Angular for dependencies updates, which will create PRs akin to https://github.com/coveo/cli/pull/1086. (divide and conquer)
https://coveord.atlassian.net/browse/KIT-2231

chore(renovate): create group for react and ng

---

scripts/reports/github-client.mjs

https://coveord.atlassian.net/browse/KIT-2232
Not a huge fix 😂

fix: adapt octokit rest

---

renovate.json

In [labs/angular-15](https://github.com/coveo/ui-kit/tree/labs/angular-15) I tried to update straight to 15.
I think Stencil ain't ready yet, so let's try 14 first eh.

chore(renovate): lock angular to 14

---

.github/workflows/snyk.yml

https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated
https://github.com/coveo/cli/blob/master/.github/workflows/snyk-master.yml
KIT-282

chore(ci): update codeql

---

packages/atomic/src/components/search/result-template-components/quickview-iframe/quickview-iframe.tsx

https://coveord.atlassian.net/browse/KIT-2229

fix(atomic): scroll top on new quickview

---

packages/atomic/src/components/search/atomic-breadbox/atomic-breadbox.tsx

https://coveord.atlassian.net/browse/KIT-2252
https://discuss.coveo.com/t/missing-shadow-parts-custom-properties/7355/35

feat(atomic): add container part to breadbox

---

packages/atomic/cypress/e2e/search-box/instant-results/search-box-instant-results-assertions.ts
packages/atomic/cypress/e2e/search-box/instant-results/search-box-instant-results.cypress.ts
packages/headless/src/features/instant-results/instant-results-actions.ts
packages/headless/src/features/instant-results/instant-results-slice.test.ts
packages/headless/src/features/query/query-analytics-actions.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/features/search/search-slice.test.ts
packages/headless/src/features/search/search-slice.ts

https://coveord.atlassian.net/browse/KIT-2247

feat(headless): add instant results analytics

---

packages/atomic/src/components/search/atomic-search-box/search-suggestion.tsx

https://coveord.atlassian.net/browse/KIT-2257

fix(atomic): make suggestion (button) text left align by default

---

packages/headless/src/controllers/quickview/headless-quickview.ts

Seems we forgot a random annotation string hehe

doc(headless): remove asd string

---

packages/atomic/cypress/e2e/search-box/standalone-search-box.cypress.ts
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/pages/examples/standalone-results.html
packages/atomic/src/pages/examples/standalone.html
packages/headless/src/controllers/core/search-parameter-manager/headless-core-search-parameter-manager.test.ts
packages/headless/src/controllers/core/search-parameter-manager/headless-core-search-parameter-manager.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.test.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ts

https://coveord.atlassian.net/browse/KIT-2239
https://coveord.atlassian.net/browse/KIT-2248

fix(atomic,headless): update history with replaceState (before search) or pushState (after search) & validate tab values

---

packages/headless/src/api/analytics/instant-result-analytics.ts
packages/headless/src/features/instant-results/instant-result-analytics-actions.ts
packages/headless/src/features/instant-results/instant-results-slice.test.ts
packages/headless/src/features/instant-results/instant-results-slice.ts

https://coveord.atlassian.net/browse/KIT-2247

fix(headless): provide proper instant results query for analytics

---

packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx

https://coveord.atlassian.net/browse/KIT-2288

chore(atomic): add new refine modal title parts

---

.deployment.config.json
.github/actions/commit-generated-files/action.yml
.github/actions/setup/action.yml
.github/workflows/manual-package.yml
Jenkinsfile
packages/atomic-hosted-page/LICENSE
packages/atomic-hosted-page/README.md
packages/atomic-hosted-page/package.json
scripts/packages.mjs

Let me know if I'm forgetting anything 🕵️ 
https://coveord.atlassian.net/browse/KIT-2266

feat(atomic-hosted-page): get ready for deployment

---

packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx

Thee shall follow [the spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance)
https://coveord.atlassian.net/browse/KIT-2326
Automated testing is tricky: it would require to setup E2E tests that uses [the `dist-custom-element` output](https://stenciljs.com/docs/custom-elements)
There are other issues and improvements that I required before we can 'properly' do this kind of automated test.
So for testing:
- Clone https://github.com/louis-bompart/ideal-octo-umbrella
- Run `npm install`
- Run `npm run dev`
- In the browser, see the error in the console `Failed to construct 'CustomElement': The result must not have attributes`
- Build atomic from this branch, copy the resulting `dist` into the `node_modules/@coveo/atomic/dist`
- Delete vite cache: `npx …

fix(atomic): do not modify host dom in ctor

---

packages/headless/src/integration-tests/field-suggestions.test.ts

Most probably some content changed in the index.
https://coveord.atlassian.net/browse/KIT-2347

test(headless): fix failing tests for headless field suggestions

---

packages/atomic-hosted-page/src/components/atomic-hosted-page/hosted-pages.ts

https://coveord.atlassian.net/browse/KIT-2350

fix(atomic-hosted-page): insert inline CSS in a style tag

---

packages/atomic/cypress/e2e/breadbox.cypress.ts
packages/atomic/cypress/e2e/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/e2e/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/e2e/facets/facet-common-actions.ts
packages/atomic/cypress/e2e/facets/facet-common-assertions.ts
packages/atomic/cypress/e2e/facets/facet/facet-actions.ts
packages/atomic/cypress/e2e/facets/facet/facet-selectors.ts
packages/atomic/cypress/e2e/facets/facet/facet.cypress.ts
packages/atomic/cypress/e2e/facets/segmented-facet/segmented-facet-selectors.ts
packages/atomic/cypress/e2e/pager.cypress.ts
packages/atomic/cypress/e2e/search-box/standalone-search-box.cypress.ts

https://coveord.atlassian.net/browse/KIT-2377

test(atomic): work on flaky tests for breadbox, segmented facets

---

packages/headless/src/app/engine-configuration.ts
packages/headless/src/app/engine.ts

https://coveord.atlassian.net/browse/KIT-2411

docs(headless): add links in orgEndpoints warnings

---

package-lock.json
package.json
packages/atomic-hosted-page/package.json
packages/atomic-hosted-page/src/components.d.ts

https://coveord.atlassian.net/browse/KIT-2429
Also 
* fix headless version in hosted pkg
* add a npm script to perform clean install

ci: regenerate package lock file

---

packages/headless/src/controllers/core/context/headless-core-context.ts
packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet.ts
packages/headless/src/controllers/core/facets/facet/headless-core-facet.ts

Made some minor updates to strings for certain controllers to link to a better article added a string where there wasn't any before

docs(headless): random improvements

---

packages/atomic/cypress/e2e/search-box/search-box.cypress.ts

https://coveord.atlassian.net/browse/KIT-2432
In prep for upgrading to cypress v12 with test isolation enabled by default.

test: isolate search box tests

---

.github/workflows/release.yml
utils/release/common/constants.mjs
utils/release/git-publish-all.mjs
utils/release/lock-master.mjs

https://coveord.atlassian.net/browse/KIT-2472

ci: replaced automatic auth with app auth

---

packages/headless/src/api/analytics/coveo-analytics-utils.ts
packages/headless/src/api/analytics/insight-analytics.ts
packages/headless/src/api/analytics/search-analytics.ts
packages/headless/src/app/case-assist-engine/case-assist-engine.ts
packages/headless/src/controllers/case-field/headless-case-field.ts
packages/headless/src/controllers/case-input/headless-case-input.ts
packages/headless/src/controllers/core/quickview/headless-core-quickview.ts
packages/headless/src/controllers/document-suggestion-list/headless-document-suggestion-list.ts
packages/headless/src/controllers/quickview/case-assist-headless-quickview.ts
packages/headless/src/features/case-field/case-field-actions-loader.ts
packages/headless/src/features/case-field/case-field-actions.ts
packages/headless/src/features/case-input/case-input-actions-loader.ts
packages/headless/src/features/configuration/analytics-params.ts
packages/headless/src/features/configuration/configuration-slice.test.ts
packages/headless/src/features/configuration/configuration-slice.ts
packages/headless/src/features/document-suggestion/document-suggestion-actions-loader.ts
packages/headless/src/features/document-suggestion/document-suggestion-actions.ts
packages/headless/src/features/insight-search/insight-query-suggest-request.ts
packages/headless/src/features/insight-search/insight-result-preview-request-builder.ts
packages/headless/src/features/insight-search/insight-search-actions.ts
packages/headless/src/features/product-listing/product-listing-actions.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts
packages/headless/src/features/query-suggest/query-suggest-actions.ts
packages/headless/src/features/recommendation/recommendation-actions.ts
packages/headless/src/features/result-preview/result-preview-request-builder.ts
packages/headless/src/features/search-and-folding/search-and-folding-request.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/features/standalone-search-box-set/standalone-search-box-set-actions.ts

Next PR in the ongoing bundle saga, isolating case-assist bundle in headless
https://coveord.atlassian.net/browse/KIT-2466

refactor(headless): isolate case assist bundle

---

packages/atomic-hosted-page/cypress/integration/stencil/smoke-test.cypress.ts

https://coveord.atlassian.net/browse/KIT-2342

test(atomic): unskip test for simple builder

---

utils/atomic-storybook/.storybook/preview.js

This is needed for the links that appear in our doc website and storybook published on the CDN to work properly.
https://coveord.atlassian.net/browse/KIT-2482

docs(atomic): sort stories by length

---

packages/headless/README.md
packages/headless/contributors/troubleshooting-bundles-content.md

https://coveord.atlassian.net/browse/KIT-2484

docs(headless): document troubleshooting headless bundle process

---

packages/atomic/cypress/e2e/breadbox.cypress.ts
packages/atomic/cypress/e2e/did-you-mean.cypress.ts
packages/atomic/cypress/e2e/external.cypress.ts
packages/atomic/cypress/e2e/notifications.cypress.ts
packages/atomic/cypress/e2e/pager.cypress.ts
packages/atomic/cypress/e2e/results-per-page.cypress.ts
packages/atomic/cypress/e2e/segmented-facet-scrollable.cypress.ts
packages/atomic/cypress/e2e/smart-snippet-suggestions.cypress.ts
packages/atomic/cypress/e2e/smart-snippet.cypress.ts

In prep for [upgrade to cypress v12](https://github.com/coveo/ui-kit/pull/2935)
https://coveord.atlassian.net/browse/KIT-2432

test: apply test isolation to cypress/e2e/* test suites

---

package.json

Deleting package-lock.json is not recommended. Change the script to not delete pkg lock. 
https://coveord.atlassian.net/browse/KIT-2506

chore: refactor npm script to not delete pkg lock

---

JenkinsfileProductionRelease
packages/quantic/package.json
packages/quantic/project.json

https://coveord.atlassian.net/browse/KIT-2493
Did this mostly just because it's a very easy improvement.
New tasks graph in prod Jenkins:

ci(quantic): build only quantic in prod Jenkins

---

.eslintrc.json
package-lock.json
package.json

Copied from coveo/cli, migrated to ESM, workflow adapted to fit in ui-kit existing workflow.
https://coveord.atlassian.net/browse/KIT-2502

build(lockfile): add lockfile=3 gate

---

.deployment.config.json

Prevent multiple Jira issues from being associated with a PR which causes issues during deployment.
> Stop after the first Jira issue key has been found. Order of lookup is: branch name, pull request title, pull request description, and commit message.
Also remove obsolete snyk config.
https://coveord.atlassian.net/browse/KIT-2528

ci: fix issues discovery to stop after first issue

---

packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/components/search/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/quantic/force-app/examples/main/lwc/exampleQuanticTabBar/exampleQuanticTabBar.js
packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.js

Per the Microsoft style guide, we should write dropdown, and not drop-down. 
See https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/dropdown.

docs(atomic,quantic): DOC-12878-drop-down-to-dropdown

---

.eslintrc.json
utils/atomic-storybook/.eslintrc.json
utils/atomic-storybook/.storybook/map-props-to-args.ts

https://coveord.atlassian.net/browse/KIT-2540

docs(storybook): fix controls for array properties 

---

packages/atomic-react/package.json

https://coveord.atlassian.net/browse/KIT-2496
The file we pointed was not right, so this fix that
Fixes: #2928
See: https://www.npmjs.com/package/@coveo/atomic-react?activeTab=code

fix(atomic-react): fix pjson module path

---

packages/headless/src/api/analytics/product-listing-analytics.ts
packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.ts
packages/headless/src/features/analytics/analytics-utils.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-product-listing-analytics-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-product-listing-analytics-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-product-listing-utils.ts
packages/headless/src/features/product-listing/product-listing-actions-loader.ts
packages/headless/src/features/product-listing/product-listing-analytics.ts

https://coveord.atlassian.net/browse/KIT-2546

fix(headless): add missing controllers for product listing facets

---

.github/workflows/release.yml

ci: auto release every wednesday

---

packages/atomic/src/components/search/facets/atomic-automatic-facet/atomic-automatic-facet.tsx

https://coveord.atlassian.net/browse/KIT-2595

fix(atomic): fix internationalization in atomic automatic facet

---

.github/workflows/masterbot.yml
.github/workflows/prbot.yml

chore: disable vue e2e

---

packages/atomic/cypress/e2e/search-box/instant-results/search-box-instant-results.cypress.ts
packages/atomic/src/components/common/result-list/result-list-common-interface.ts
packages/atomic/src/components/insight/result-lists/atomic-insight-folded-result-list/atomic-insight-folded-result-list.tsx
packages/atomic/src/components/insight/result-lists/atomic-insight-result-list/atomic-insight-result-list.tsx
packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx

https://coveord.atlassian.net/browse/KIT-2656
Accidentally auto-merged before pushing my final commit 🤦

fix(atomic): Make gridCellLinkTarget optional

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/common/facets/facet-common-store.ts
packages/atomic/src/components/common/facets/facet-common.tsx
packages/atomic/src/components/common/facets/numeric-facet-common.tsx
packages/atomic/src/components/common/facets/timeframe-facet-common.tsx
packages/atomic/src/components/search/atomic-facet-manager/atomic-facet-manager.tsx
packages/atomic/src/components/search/facets/atomic-automatic-facet-generator/atomic-automatic-facet-generator.tsx
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/utils/automatic-facet-generator-utils.ts

Just updating the work I did on my fork to the right branch in @coveo.

updating KIT-2652 with work done in fork

---

package-lock.json

https://coveord.atlassian.net/browse/KIT-2681

ci(atomic,headless): fix package-lock missing dep

---

package-lock.json
packages/atomic/cypress/utils/analyticsUtils.ts
packages/headless/package.json
packages/quantic/cypress/e2e/common-expectations.ts
packages/quantic/cypress/e2e/default-2/recommendation-list/recommendation-list-expectations.ts
packages/quantic/cypress/e2e/default-2/result-list/folded-result-list/folded-result-list-expectations.ts
packages/quantic/cypress/e2e/default-2/result-quickview/result-quickview-expectations.ts
packages/quantic/cypress/e2e/default-2/smart-snippet-suggestions/smart-snippet-suggestions-expectations.ts
packages/quantic/cypress/e2e/default-2/smart-snippet/smart-snippet-expectations.ts
packages/quantic/cypress/page-objects/search.ts

Here is the accompanying PR on coveo.analytics that describe the issue in more details: https://github.com/coveo/coveo.analytics.js/pull/435
https://coveord.atlassian.net/browse/KIT-2699

fix(headless): bump coveo.analytics to fix click tracking issue on ios safari

---

packages/atomic/cypress/e2e/breadbox.cypress.ts
packages/atomic/cypress/e2e/facets/facet/facet.cypress.ts
packages/atomic/src/components/common/facets/facet-common.tsx
packages/atomic/src/components/common/facets/facet-header/facet-header.tsx
packages/atomic/src/components/common/facets/numeric-facet-common.tsx
packages/atomic/src/components/common/facets/timeframe-facet-common.tsx
packages/atomic/src/components/search/facets/atomic-automatic-facet/atomic-automatic-facet.tsx
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/search/facets/atomic-popover/atomic-popover.tsx
packages/atomic/src/components/search/facets/atomic-popover/popover-type.ts
packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx

Display "Clear all" button when a value is excluded.
https://coveord.atlassian.net/browse/KIT-2687

feat(atomic): support facet exclude clear

---

packages/atomic/src/locales.json

Doing the PR of [kstarnaud@coveo.com](mailto:kstarnaud@coveo.com) (he doesnt have a gh account) per request of capital group

Fix translation issue for zh-tw

---

.github/actions/e2e-atomic-angular/action.yml

https://coveord.atlassian.net/browse/KIT-2732

ci: add timeout for atomic-angular e2e

---

packages/atomic/cypress/e2e/recommendations/recs-list-assertions.ts
packages/atomic/cypress/e2e/recommendations/recs-list.cypress.ts

https://coveord.atlassian.net/browse/KIT-2750
This PR Remove most of the unnecessary 'it' statements. This improves flakiness and also fixes new issues with the update of cypress.
Following the best practices guide on cypress -> https://docs.cypress.io/guides/references/best-practices#Creating-Tiny-Tests-With-A-Single-Assertion

test: rewrite recs-list.cypress.ts with better practices 

---

package-lock.json
packages/headless/package.json

In order to pickup the changes here: https://github.com/coveo/coveo.analytics.js/pull/436
https://coveord.atlassian.net/browse/KIT-2748

fix(headless): bump coveo.analytics version

---

packages/atomic-angular/package.json
packages/atomic-angular/project.json
packages/atomic-angular/scripts/release-phase2.mjs

The link seems to fail, replaced by a dumber thing, should work tm (untested)

chore(angular): fix release:phase2

---

package-lock.json
packages/headless/package.json

Latest pino has (arguably) a bug causing a bypass of the level setting.
For now 🧊 
No renovate lock: Will investigate/fix upstream 🔜 (this week)
___
KIT-282

chore(headless): revert to pino 8.11.0

---

utils/release/bump-package.mjs

keys are here, should work :tm:
KIT-2766

chore(release): call createPreset (default export) from conventional-changelog-angular

---

.github/actions/e2e-quantic/action.yml
packages/quantic/cypress.config.ts

Ref: https://github.com/cypress-io/cypress/issues/27804
https://coveord.atlassian.net/browse/KIT-2771

test(e2e): fix cypress 10 with new version of chrome for quantic

---

packages/atomic/cypress/e2e/refine-toggle-actions.ts
packages/atomic/cypress/e2e/refine-toggle.cypress.ts

Limit the # of static facet & auto facet for more reliable api returns
KIT-2793

test: less automatic facets

---

package.json
packages/atomic-hosted-page/package.json
packages/atomic-react/package.json
packages/atomic/package.json
packages/bueno/package.json
packages/headless/package.json
packages/quantic/package.json
utils/release/package.json

Source: https://github.com/coveo/ui-kit/actions/runs/6398635946/job/17369187911
Docs: https://docs.npmjs.com/cli/v10/commands/npm-pkg
https://coveord.atlassian.net/browse/KIT-2794

chore: run npm pkg fix

---

renovate.json

Visibility and filtering.
KIT-282

chore(renovate): add label on PR

---

packages/headless/src/commerce.index.ts

[CAPI-92]
[CAPI-92]: https://coveord.atlassian.net/browse/CAPI-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(commerce): expose sort on commerce module

---

.github/workflows/prbot.yml
packages/samples/headless-ssr/README.md
packages/samples/headless-ssr/app-router/cypress/e2e/ssr-search-parameter-manager.cy.ts

https://coveord.atlassian.net/browse/KIT-2782
The tests were failing both in dev and prod locally.

test: fix ssr-search-parameter-manager e2e tests fails

---

packages/headless/src/controllers/facets/automatic-facet-generator/headless-automatic-facet-generator.ts

https://coveord.atlassian.net/browse/DOC-13563
There was one remaining note about automatic facets still being in beta.

doc(atomic): removed beta note

---

.deployment.config.json

Because we can amend them after the fact.
KIT-2821

chore: only discover issues from PR title/desc

---

.cspell.json
packages/atomic/cypress/e2e/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/e2e/facets/facet/facet.cypress.ts
packages/atomic/cypress/e2e/facets/segmented-facet/segmented-facet.cypress.ts
packages/atomic/cypress/e2e/result-list/result-components/quickview.cypress.ts

:finnadie: 
[KIT-2823](https://coveord.atlassian.net/browse/KIT-2823)
[KIT-2823]: https://coveord.atlassian.net/browse/KIT-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: various stabilization after source modifications

---

package-lock.json
package.json
renovate.json

See https://github.com/bahmutov/cypress-repeat/issues/52 for the RCA.
https://coveord.atlassian.net/browse/KIT-2833

chore: revert cypress-repeat to 1.5.0

---

package-lock.json
packages/headless/src/api/search/search-api-params.ts
packages/headless/src/features/analytics/analytics-utils.test.ts
packages/headless/src/features/analytics/analytics-utils.ts
packages/headless/src/features/configuration/analytics-params.ts

https://coveord.atlassian.net/browse/KIT-2829

feat: add trackingId if analyticsMode=next

---

packages/atomic/src/components/search/result-template-components/atomic-quickview/atomic-quickview.tsx

https://coveord.atlassian.net/browse/KIT-2850

feat(atomic): add parts to customize quickview icon and button

---

packages/quantic/force-app/main/default/lwc/quanticNotifications/quanticNotifications.js
packages/quantic/package.json

[SFINT-4901](https://coveord.atlassian.net/browse/SFINT-4901)
- Added the JSON file containing our automatically generated Quantic documentation to the Quantic NPM package so that it can be used by the Doc team's workflows to automatically publish this documentation.
we figured that the best way to automate the process of publishing the Quantic automatically generated documentation would be to include the JSON file containing the documentation in the Quantic NPM package.
After that Github Workflows owned by the doc team would take care of fetching this JSON file on each new NPM release and would proceed to update the documentation accordingly.
This process is the same process currently being used with the Atomic and Headless library. 
[SFINT-4901]: …

chore(quantic): json documentation file added to the quantic npm package

---

packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet-search.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-facet.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-filter.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-facet.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-filter.ts

https://coveord.atlassian.net/browse/KIT-2908
This will simplify the migration process of search events.

fix(headless): import correct analytics in product listing

---

packages/headless/src/features/analytics/analytics-utils.ts
packages/headless/src/features/result/__snapshots__/result-analytics-actions.test.ts.snap
packages/headless/src/features/result/result-analytics-actions.test.ts
packages/headless/src/features/result/result-analytics-actions.ts
packages/headless/src/features/result/result-insight-analytics-actions.test.ts
packages/headless/src/test/mock-result.ts

https://github.com/coveo/analytics-migration-project/issues/54

feat(relay): add support for analytics/result/open

---

renovate.json

NX ugprade is a bit tedious here, I want to isolate it.

chore: lock nx-devkit

---

packages/atomic/cypress/e2e/search-box/search-box.cypress.ts
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx

https://coveord.atlassian.net/browse/KIT-2921

fix(atomic-search-box): close suggestions when clicking search button

---

.cspell.json
packages/atomic/cypress/e2e/breadbox.cypress.ts
packages/headless/src/features/analytics/insight-analytics-actions-loader.ts
packages/headless/src/features/analytics/search-analytics-actions-loader.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-utils.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-utils.ts
packages/headless/src/features/search-parameters/search-parameter-analytics-actions.test.ts
packages/headless/src/features/search-parameters/search-parameter-analytics-actions.ts

https://coveord.atlassian.net/browse/KIT-2935

fix(exclude): use unexclude actionCause when unexcluding

---

packages/headless/src/controllers/recommendation/headless-recommendation.test.ts
packages/headless/src/controllers/recommendation/result-list/headless-recommendation-interactive-result.test.ts
packages/headless/src/test/mock-engine-v2.ts
packages/headless/src/test/mock-engine.ts

same story as #3519 for doc recs

test(recommendation): test with new practices

---

packages/atomic/cypress/e2e/facets/color-facet/color-facet.cypress.ts

https://coveord.atlassian.net/browse/KIT-2964
I'll make the test more robust in another PR.

fix(atomic): quick fix for failing color-facet cypress test

---

packages/headless/src/features/did-you-mean/did-you-mean-actions-loader.ts

https://coveord.atlassian.net/browse/KIT-2966

docs(headless): fix doc typo

---

renovate.json

https://coveord.atlassian.net/browse/KIT-2968

chore(deps): isolate redux and undici

---

renovate.json

v6 appears to be making Jest tests fail
https://coveord.atlassian.net/browse/KIT-2971

chore(deps): isolate @lwc/compiler

---

packages/atomic/src/components/search/result-template-components/atomic-result-multi-value-text/atomic-result-multi-value-text.tsx

https://coveord.atlassian.net/browse/KIT-2909

feat(atomic): add shadow part of result-multi-value-text list element

---

packages/atomic/cypress/e2e/search-box/search-box-selectors.ts
packages/atomic/cypress/e2e/search-box/search-box.cypress.ts
packages/atomic/cypress/e2e/search-box/text-area-search-box.cypress.ts
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx

https://coveord.atlassian.net/browse/KIT-2973

fix(atomic): fix input minimum length behaving incorrectly with clear button

---

patches/eslint-plugin-canonical+4.18.0.patch

The patch is the build of https://github.com/gajus/eslint-plugin-canonical/pull/28 applied to our repo.
https://coveord.atlassian.net/browse/KIT-2987

chore(eslint): patch eslint-plugin-canonical for win compat

---

packages/headless/src/controllers/core/facets/facet-conditions-manager/headless-facet-conditions-manager.test.ts
packages/headless/src/controllers/core/facets/facet-search/category/headless-category-facet-search.test.ts
packages/headless/src/controllers/core/facets/facet-search/facet-search.test.ts
packages/headless/src/controllers/core/facets/facet-search/specific/headless-facet-search.test.ts
packages/headless/src/controllers/core/facets/range-facet/date-facet/headless-core-date-facet.test.ts

test(headless): more controller test refactor for rtk2

---

packages/headless/src/app/search-engine/search-engine.ssr.ts
packages/headless/src/controllers/core/facets/range-facet/date-facet/headless-core-date-filter.test.ts
packages/headless/src/controllers/core/facets/range-facet/headless-core-range-facet.test.ts
packages/headless/src/controllers/core/facets/range-facet/numeric-facet/headless-core-numeric-facet.test.ts
packages/headless/src/controllers/core/facets/range-facet/numeric-facet/headless-core-numeric-filter.test.ts
packages/headless/src/controllers/core/folded-result-list/headless-core-folded-result-list.test.ts
packages/headless/src/controllers/core/generated-answer/headless-core-generated-answer.test.ts
packages/headless/src/controllers/core/generated-answer/headless-core-interactive-citation.test.ts
packages/headless/src/controllers/core/interactive-result/headless-core-interactive-result.test.ts
packages/headless/src/controllers/core/query-summary/headless-core-query-summary.test.ts
packages/headless/src/controllers/core/quickview/headless-core-quickview.test.ts
packages/headless/src/utils/utils.ts

test(headless): couple more controller tests refactor for redux toolkit v2

---

packages/headless/src/controllers/core/result-list/headless-core-result-list.test.ts
packages/headless/src/controllers/core/result-list/headless-core-result-list.ts
packages/headless/src/controllers/core/results-per-page/headless-core-results-per-page.test.ts
packages/headless/src/controllers/core/search-box/headless-core-search-box.test.ts
packages/headless/src/controllers/core/search-parameter-manager/headless-core-search-parameter-manager.test.ts
packages/headless/src/controllers/core/smart-snippet-questions-list/headless-core-smart-snippet-questions-list.test.ts
packages/headless/src/controllers/core/smart-snippet/headless-core-smart-snippet.test.ts
packages/headless/src/controllers/core/sort/headless-core-sort.test.ts
packages/headless/src/controllers/core/status/headless-core-status.test.ts
packages/headless/src/controllers/core/tab/headless-core-tab.test.ts
packages/headless/src/controllers/dictionary-field-context/headless-dictionary-field-context.test.ts
packages/headless/src/controllers/facets/automatic-facet/headless-automatic-facet.test.ts

test(headless): more controller tests refactor for rtk2

---

packages/headless/src/controllers/core/facets/facet/headless-core-facet-options.ts
packages/headless/src/controllers/facets/facet/headless-facet-options.ts
packages/headless/src/features/facet-options/facet-options-actions-loader.ts
packages/headless/src/features/facets/facet-set/facet-set-actions.ts
packages/headless/src/features/pagination/pagination-actions-loader.ts
packages/headless/src/features/sort-criteria/sort-criteria-actions-loader.ts
packages/headless/src/features/sort/sort-actions-loader.ts
packages/headless/src/state/state-sections.ts

Page 1461 swill soon be removed from the docs site, so I update the affected links preemptively.

docs(headless): update some links

---

packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.test.ts
packages/headless/src/controllers/recent-results-list/headless-interactive-recent-result.test.ts
packages/headless/src/controllers/recent-results-list/headless-recent-results-list.test.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.test.ts
packages/headless/src/controllers/result-list/headless-interactive-result.test.ts
packages/headless/src/controllers/results-per-page/headless-results-per-page.test.ts
packages/headless/src/controllers/search-box/headless-search-box.test.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ssr.test.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.test.ts
packages/headless/src/controllers/sort/headless-sort.test.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.test.ts
packages/headless/src/controllers/tab/headless-tab.test.ts
packages/headless/src/controllers/triggers/headless-execute-trigger.test.ts
packages/headless/src/controllers/url-manager/headless-url-manager.test.ts
packages/headless/src/test/mock-engine-v2.ts

test(headless): controller test refactor for rtk2

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/cypress/e2e/result-list/folded-result-list-assertions.ts
packages/atomic/cypress/e2e/result-list/folded-result-list-children.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx

https://coveord.atlassian.net/browse/KIT-2985

feat(atomic): exposes numberOfFoldedResults

---

package-lock.json
packages/headless-react/package.json
packages/headless/package.json
renovate.json

chore: bump undici

---

JenkinsfileProductionRelease

https://coveord.atlassian.net/browse/KIT-3008
There was a confusion when we updated the env variables, the Jenkinsfile was not updated with the changes to the env variables.

fix(quantic): Fix production release script

---

renovate.json

chore: lock sfdx-lwc-jest

---

.github/actions/e2e-quantic-setup/action.yml
.github/workflows/prbot.yml
packages/headless/src/controllers/facets/automatic-facet-generator/headless-automatic-facet-generator-options.ts
packages/quantic/scripts/build/deploy-community.ts

chore: enable merge queue on ci workflow

---

packages/headless/src/api/commerce/commerce-api-client.test.ts
packages/headless/src/controllers/commerce/context/headless-context.test.ts
packages/headless/src/controllers/commerce/context/headless-context.ts
packages/headless/src/features/commerce/common/actions.ts
packages/headless/src/features/commerce/context/context-actions.ts
packages/headless/src/features/commerce/context/context-slice.test.ts
packages/headless/src/features/commerce/context/context-state.ts
packages/headless/src/features/commerce/context/context-validation.ts
packages/headless/src/features/commerce/facets/facet-search-set/commerce-facet-search-request-builder.ts
packages/headless/src/features/commerce/product-listing/product-listing-actions.ts
packages/headless/src/features/commerce/query-suggest/query-suggest-actions.ts
packages/headless/src/features/commerce/search/search-actions.ts
packages/headless/src/integration-tests/commerce.test.ts

Reverting the [revert](https://github.com/coveo/ui-kit/pull/3639) to fix the build!
Context: https://coveord.atlassian.net/browse/LENS-1525
Original PR: https://github.com/coveo/ui-kit/pull/3628

feat(headless-commerce): set clientId with storage value

---

JenkinsfileProductionRelease

https://coveord.atlassian.net/browse/KIT-3015

chore: add sf cli into jenkins

---

.github/actions/e2e-atomic-angular/action.yml
.github/actions/e2e-atomic-hosted-page/action.yml
.github/actions/e2e-atomic-next/action.yml
.github/actions/e2e-atomic-react/action.yml
.github/actions/e2e-atomic-screenshots/action.yml
.github/actions/e2e-atomic/action.yml
.github/actions/e2e-headless-ssr-app-dev/action.yml
.github/actions/e2e-headless-ssr-app-prod/action.yml
.github/actions/e2e-headless-ssr-pages-dev/action.yml
.github/actions/e2e-headless-ssr-pages-prod/action.yml
.github/actions/e2e-iife/action.yml
.github/actions/e2e-quantic/action.yml
.github/actions/e2e-stencil/action.yml
.github/actions/e2e-vuejs/action.yml
renovate.json

https://github.com/actions/upload-artifact/blob/main/README.md#not-uploading-to-the-same-artifact
https://coveord.atlassian.net/browse/KIT-3017

chore: return upload-artifact to v3

---

scripts/ci/hasFileChanged.mjs

[CDX-1527](https://coveord.atlassian.net/browse/CDX-1527)
[CDX-1527]: https://coveord.atlassian.net/browse/CDX-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: trim filename in `hasFileChanged`

---

package-lock.json
package.json

`@commitlint/load` is being used in scripts\reports\title\verify-title.mjs and is not installed directly

chore: add missing deps

---

packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-filter.test.ts
packages/headless/src/controllers/folded-result-list/headless-folded-result-list.test.ts
packages/headless/src/controllers/generated-answer/headless-generated-answer.test.ts
packages/headless/src/controllers/insight-interface/insight-interface.test.ts
packages/headless/src/controllers/insight/results-per-page/headless-insight-results-per-page.test.ts
packages/headless/src/controllers/insight/search-parameter-manager/headless-insight-search-parameter-manager.test.ts
packages/headless/src/controllers/pager/headless-pager.test.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-filter.test.ts
packages/headless/src/controllers/static-filter/headless-static-filter.test.ts
packages/headless/src/controllers/triggers/headless-notify-trigger.test.ts
packages/headless/src/controllers/triggers/headless-redirection-trigger.test.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-insight-analytics-actions.test.ts
packages/headless/src/features/generated-answer/generated-answer-actions.test.ts
packages/headless/src/features/generated-answer/generated-answer-insight-analytics-actions.test.ts
packages/headless/src/features/pagination/pagination-insight-analytics-actions.test.ts
packages/headless/src/features/query/query-insight-analytics-actions.test.ts

test(headless): more rtk2 test refactor

---

packages/headless/src/controllers/facets/automatic-facet-generator/headless-automatic-facet-generator.test.ts
packages/headless/src/controllers/facets/facet/headless-facet.test.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.test.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-filter.test.ts
packages/headless/src/controllers/field-suggestions/category-facet/headless-category-field-suggestions.test.ts
packages/headless/src/controllers/insight/attach-to-case/headless-attach-to-case.test.ts
packages/headless/src/controllers/insight/breadcrumb-manager/headless-insight-breadcrumb-manager.test.ts
packages/headless/src/controllers/insight/did-you-mean/headless-insight-did-you-mean.test.ts
packages/headless/src/controllers/insight/facets/category-facet/headless-insight-category-facet.test.ts
packages/headless/src/controllers/insight/facets/facet/headless-insight-facet.test.ts
packages/headless/src/controllers/insight/result-list/headless-insight-interactive-result.test.ts
packages/headless/src/controllers/insight/search-box/headless-insight-search-box.test.ts
packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet.test.ts
packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.test.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-facet.test.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-facet.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-filter.test.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-filter.ts
packages/headless/src/controllers/product-listing/sort/headless-product-listing-sort.test.ts
packages/headless/src/features/facets/automatic-facet-set/automatic-facet-set-slice.test.ts

test(headless): migrate tests rtk2

---

.github/workflows/release.yml

https://github.com/coveo/ui-kit/actions/runs/8234502159/job/22516369547

chore: add id-token write perm

---

packages/atomic-angular/projects/atomic-angular/package.json

https://github.com/coveo/ui-kit/actions/runs/8235364306/job/22519275216

chore: add missing repository.url

---

package-lock.json
packages/headless/.eslintrc.js
packages/headless/package.json

https://coveord.atlassian.net/browse/KIT-2954

chore(headless): remove redux-mock-store dependency

---

utils/release/npm-publish-package.mjs

First PR "in-the-dark". Logs were cut short :finnadie:

chore: avoid provenance with github reg

---

.github/workflows/release.yml

I didn't [RT(F)M](https://coveord.atlassian.net/wiki/spaces/CM/pages/2887155886/Using+the+Deployment+Pipeline+from+GitHub+Actions) enough 🤦

chore: do setup dep-pipeline cli

---

scripts/deploy/execute-deployment-pipeline.mjs

The deployment pipeline is available thru docker.

chore: use docker to wrap deployment-pipeline

---

.github/workflows/release.yml

Did not remove the uses that didn't work

chore: remove uses for dep pipeline setup

---

packages/headless/src/app/case-assist-engine/case-assist-engine.ts
packages/headless/src/app/commerce-engine/commerce-engine.ts
packages/headless/src/app/engine.ts
packages/headless/src/app/insight-engine/insight-engine.ts
packages/headless/src/app/product-listing-engine/product-listing-engine.ts
packages/headless/src/app/product-recommendation-engine/product-recommendation-engine.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.ts
packages/headless/src/app/search-engine/search-engine.ts
packages/headless/src/app/store.ts
packages/headless/src/app/thunk-extra-arguments.ts
packages/headless/src/controllers/commerce/context/cart/headless-cart-selectors.test.ts
packages/headless/src/controllers/commerce/context/cart/headless-cart-selectors.ts
packages/headless/src/controllers/commerce/context/cart/headless-cart.test.ts
packages/headless/src/controllers/commerce/context/cart/headless-cart.ts
packages/headless/src/features/commerce/context/cart/cart-actions.ts
packages/headless/src/features/commerce/context/cart/cart-selector.ts
packages/headless/src/features/commerce/context/cart/cart-slice.test.ts
packages/headless/src/features/commerce/context/cart/cart-slice.ts
packages/headless/src/features/commerce/context/context-selector.ts
packages/headless/src/features/insight-search/insight-search-actions-thunk-processor.test.ts
packages/headless/src/features/insight-search/legacy/insight-search-actions-thunk-processor.test.ts
packages/headless/src/features/search/legacy/search-actions-thunk-processor.test.ts

Prototype to handle analytics actions related to state changes, like the purchase action for e.g.
https://coveord.atlassian.net/browse/KIT-3038

chore(relay): make relay available in Actions as extra

---

scripts/deploy/execute-deployment-pipeline.mjs

chore: docker mount, missing resolve.

---

scripts/deploy/execute-deployment-pipeline.mjs

chore: resolve is in path, not fs.

---

JenkinsfileProductionRelease
scripts/deploy/approve-production-release.mjs
utils/release/git-publish-all.mjs

I can't put a multiline secrets into a string secret in jenkins, it got mangled.
So instead, I use a filesecret
https://coveord.atlassian.net/browse/KIT-3025

chore: fixup approve job

---

packages/quantic/scripts/build/deploy-community.ts

Following @mmitiche advice, but automatedish
https://coveord.atlassian.net/browse/KIT-3044

chore(quantic): skip authorize outside CI

---

packages/atomic/src/components/commerce/product-list/product-template-provider.ts

https://coveord.atlassian.net/browse/KIT-3033

refactor(atomic): fix bad import

---

.github/workflows/prbot.yml

https://coveord.atlassian.net/browse/KIT-3078

chore: fix syntax error in prbot.yml

---

packages/headless/src/controllers/commerce/recommendations/headless-recommendations.test.ts
packages/headless/src/controllers/commerce/recommendations/headless-recommendations.ts

[CAPI-724](https://coveord.atlassian.net/browse/CAPI-724)
Add configuration reducer, so Recommendations API contain organization id.
[CAPI-724]: https://coveord.atlassian.net/browse/CAPI-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(commerce): Add back configuration reducer

---

packages/headless/src/api/search/product-recommendations/product-recommendations-request.ts
packages/headless/src/api/search/recommendation/recommendation-request.ts
packages/headless/src/api/search/search-api-client.test.ts

https://coveord.atlassian.net/browse/KIT-3081

chore(headless): improve search api client test reliability with stricter typing

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/result-template-components/atomic-field-condition/atomic-field-condition.tsx

https://coveord.atlassian.net/browse/KIT-3077

docs(atomic): turn conditions prop into private member on atomic-field-condition component

---

.github/actions/e2e-quantic-setup/action.yml
.github/workflows/create-quantic-package.yml
.github/workflows/release.yml

https://coveord.atlassian.net/browse/KIT-3071

chore(quantic): prepare quantic workflows to use new environment variables / secrets

---

.github/workflows/prbot.yml

This ensure the status is always reported, and always properly reported

chore(ci): always report failure or success

---

patches/@microsoft+fetch-event-source+2.0.1.patch

Ensure `window.*`, `document.*` and the like don't blow up in our faces while running on NodeJS
https://coveord.atlassian.net/browse/KIT-3097

fix: patch event source to safeguard window.* calls

---

.github/actions/e2e-atomic-csp/action.yml
.github/actions/e2e-vuejs/action.yml
packages/atomic/cypress/e2e/result-list/result-components/result-multi-value-text.cypress.ts

tests: disable flaky tests

---

packages/headless/src/api/search/date/date-format.ts

fix: remove double quote

---

packages/atomic/src/components/common/generated-answer/generated-answer-common.tsx
packages/atomic/src/components/common/generated-answer/styles/generated-answer.pcss

[SVCC-3630](https://coveord.atlassian.net/browse/SVCC-3630)
Change feedback buttons position for small layout.
Normal layout:
[SVCC-3630]: https://coveord.atlassian.net/browse/SVCC-3630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(genQa): change feedback buttons position for small layout

---

packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/commerce/facets/facet-set/interfaces/response.ts
packages/headless/src/test/mock-commerce-facet-response.ts

https://coveord.atlassian.net/browse/KIT-3122

fix(headless/commerce): use numberOfValues from response when setting initialNumberOfValues / numberOfValues in facet request

---

packages/quantic/cypress/e2e/default-2/smart-snippet/smart-snippet.cypress.ts

These will be fixed in the SFINT- 5514 ticket

fix(quantic): skipping temporarily failing smart snippets cypress tests

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/commerce/atomic-commerce-pager/atomic-commerce-pager.pcss
packages/atomic/src/components/commerce/atomic-commerce-pager/atomic-commerce-pager.tsx
packages/atomic/src/components/commerce/atomic-commerce-pager/commerce-pager-utils.ts
packages/atomic/src/pages/examples/commerce-website/listing-pants.html
packages/atomic/src/pages/examples/commerce-website/listing-surf-accessories.html
packages/atomic/src/pages/examples/commerce-website/listing-towels.html
packages/atomic/src/pages/examples/commerce-website/search.html

For load more result: Need to add support in Headless first.
https://coveord.atlassian.net/browse/KIT-3049

feat(atomic): add atomic commerce pager

---

.github/workflows/prbot.yml

A naive approach, but well worth a try.

chore: bump cypress timeout

---

packages/headless/src/app/commerce-engine/commerce-engine.ts
packages/headless/src/commerce.index.ts
packages/headless/src/controllers/commerce/triggers/headless-commerce-notify-trigger.test.ts
packages/headless/src/controllers/commerce/triggers/headless-commerce-notify-trigger.ts
packages/headless/src/controllers/core/triggers/headless-core-notify-trigger.ts
packages/headless/src/controllers/triggers/headless-notify-trigger.ssr.ts
packages/headless/src/controllers/triggers/headless-notify-trigger.test.ts
packages/headless/src/index.ts
packages/headless/src/state/commerce-app-state.ts
packages/headless/src/test/mock-commerce-state.ts

https://coveord.atlassian.net/browse/KIT-3166

feat(headless/commerce) add notify trigger controller

---

.github/actions/e2e-vuejs/action.yml
packages/samples/vuejs/cypress.config.ts

https://coveord.atlassian.net/browse/KIT-3104

test(vue): enable back + experimentalMemoryManagement

---

.github/actions/e2e-vuejs/action.yml

The fix didn't work :/ I don't have an immediate answer/clue on how to fix that, so for now ⏸️ again

test(vue): disable again

---

packages/headless/src/commerce.index.ts
packages/headless/src/features/commerce/query/query-actions-loader.ts

https://coveord.atlassian.net/browse/KIT-3175

feat(headless/commerce): add and export query actions loader

---

packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.tsx
packages/headless/src/commerce.index.ts
packages/headless/src/controllers/commerce/core/sub-controller/headless-sub-controller.test.ts
packages/headless/src/controllers/commerce/core/sub-controller/headless-sub-controller.ts
packages/headless/src/controllers/commerce/product-listing/headless-product-listing.test.ts
packages/headless/src/controllers/commerce/product-listing/headless-product-listing.ts
packages/headless/src/controllers/commerce/search/headless-search.test.ts
packages/headless/src/controllers/commerce/search/headless-search.ts
packages/headless/src/features/commerce/product-listing/product-listing-selectors.test.ts
packages/headless/src/features/commerce/product-listing/product-listing-selectors.ts
packages/headless/src/features/commerce/search/search-selectors.test.ts
packages/headless/src/features/commerce/search/search-selectors.ts

[CAPI-907]
[CAPI-907]: https://coveord.atlassian.net/browse/CAPI-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(commerce): expose url parameter manager as sub-controller

---

packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx

https://coveord.atlassian.net/browse/KIT-3185
Just some 🧹 to make sure we don't forget.

chore: add todo J#

---

packages/headless/src/api/commerce/commerce-api-client.ts
packages/headless/src/features/commerce/search/search-actions.ts

https://coveord.atlassian.net/browse/KIT-3163

fix(headless): use productSuggestion endpoint for instant products feature

---

packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx
packages/headless/src/features/commerce/pagination/pagination-slice.test.ts
packages/headless/src/features/commerce/pagination/pagination-slice.ts

https://coveord.atlassian.net/browse/KIT-3178

fix(atomic,headless): fix placeholder display issue for atomic-product-list

---

.github/workflows/dependency-review.yml

adapt for https://github.com/coveo/public-actions/commit/10e7528a14438b38a1bc6b80578b0a6b76c347c0

chore: ensure we use gh runners

---

packages/atomic-react/package.json

https://coveord.atlassian.net/browse/KIT-3201

fix(atomic-react): distribute commerce folder on npm for atomic-react

---

packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx
packages/headless/src/features/commerce/search/search-selectors.test.ts
packages/headless/src/features/commerce/search/search-selectors.ts

https://coveord.atlassian.net/browse/KIT-3209

fix(headless): handle null or undefined for query correction in commerce search action

---

packages/headless/src/commerce.index.ts
packages/headless/src/controllers/commerce/triggers/headless-commerce-redirection-trigger.test.ts
packages/headless/src/controllers/commerce/triggers/headless-commerce-redirection-trigger.ts
packages/headless/src/controllers/core/triggers/headless-core-redirection-trigger.ts
packages/headless/src/controllers/triggers/headless-redirection-trigger.ssr.ts
packages/headless/src/controllers/triggers/headless-redirection-trigger.test.ts
packages/headless/src/index.ts

https://coveord.atlassian.net/browse/KIT-3208

feat(headless/commerce): add commerce redirection trigger controller

---

.devcontainer/devcontainer.json
.github/dependabot.yml

Add a basic dev container in the repo

chore: add devcontainer

---

packages/headless/src/commerce.index.ts
packages/headless/src/controllers/commerce/triggers/headless-commerce-redirection-trigger.ts

https://coveord.atlassian.net/browse/KIT-3218
🤦

fix(headless/commerce): Use correct buildRedirectionTrigger export

---

packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.test.ts
packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.ts

https://coveord.atlassian.net/browse/KIT-3120

fix(headless/commerce): correctly support breadcrumb category facet values

---

packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.test.ts
packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.ts
packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/commerce/facets/facet-set/interfaces/request.ts
packages/headless/src/test/mock-commerce-facet-request.ts

https://coveord.atlassian.net/browse/KIT-3204
Before:
<video src="https://github.com/coveo/ui-kit/assets/23503066/20e14636-895e-463c-8940-2f9f6b4a6e4d" />
After:
<video src="https://github.com/coveo/ui-kit/assets/23503066/4b0f2fb6-0037-4cf1-86a5-5d3deeea4496" />

fix(headless/commerce): Set freezeCurrentValues as needed

---

packages/atomic/src/components/commerce/product-template-components/atomic-product-link/atomic-product-link.pcss

https://coveord.atlassian.net/browse/KIT-3189

fix(atomic): fix style for atomic-product-link

---

packages/atomic/src/components/commerce/atomic-commerce-layout/atomic-commerce-layout.pcss
packages/atomic/src/components/commerce/facets/atomic-commerce-facet/atomic-commerce-facet.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-facets/atomic-commerce-facets.tsx

https://coveord.atlassian.net/browse/KIT-3216

fix(atomic): fix some padding and margin issue for commerce facets

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx
packages/atomic/src/components/commerce/atomic-commerce-recommendation-interface/atomic-commerce-recommendation-interface.tsx
packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
packages/atomic/src/components/commerce/atomic-product/atomic-product.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-link/atomic-product-link.tsx
packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.tsx
packages/atomic/src/pages/examples/commerce-website/cart.html
packages/atomic/src/pages/examples/commerce-website/homepage.html
packages/headless/src/controllers/commerce/instant-products/headless-instant-products.ts
packages/headless/src/features/commerce/product-templates/product-templates-helpers.ts

https://coveord.atlassian.net/browse/KIT-3165
Depends on helpers created in https://github.com/coveo/ui-kit/pull/4034

feat(commerce): support interactive product in instant product & list / table display modes

---

packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.test.ts
packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.ts

https://coveord.atlassian.net/browse/KIT-3287

fix(headless commerce): dispatch fetchProductsActionCreator when calling core breadcrumb manager deselectAll

---

.github/actions/setup/action.yml
.github/workflows/release.yml

chore: remove fail-on-cache-miss

---

packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.tsx
packages/atomic/src/components/commerce/atomic-commerce-layout/commerce-layout.ts
packages/atomic/src/components/common/atomic-layout-section/search-layout.ts
packages/atomic/src/components/search/atomic-layout/search-layout.ts
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx

Grid system (search-layout/commerce-layout) relies on specific css classes being toggled on the container interface when there are no products/results or when there is an error, in order to align the columns properly.
https://coveord.atlassian.net/browse/KIT-3239

fix(atomic): fix grid system for commerce when no results or error

---

packages/headless/src/api/platform-client.test.ts
packages/headless/src/api/platform-client.ts

https://coveord.atlassian.net/browse/KIT-3322

feat(headless): handle 401 like 419

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/commerce/facets/atomic-commerce-category-facet/atomic-commerce-category-facet.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-facet/atomic-commerce-facet.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-facets/atomic-commerce-facets.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-timeframe-facet/atomic-commerce-timeframe-facet.tsx

https://coveord.atlassian.net/browse/KIT-3336

feat(atomic): add identifier on atomic commerce generated facets

---

packages/atomic/src/components/commerce/facets/atomic-commerce-facets/e2e/atomic-commerce-facets.e2e.ts

https://coveord.atlassian.net/browse/KIT-3334

chore(tests): adjust failing commerce facet e2e tests

---

packages/atomic/src/components/common/facets/facet-search/facet-search-utils.spec.ts
packages/atomic/src/components/common/facets/facet-search/facet-search-utils.ts

https://coveord.atlassian.net/browse/KIT-3337

fix(atomic): escape searchQuery in regex

---

packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx

https://coveord.atlassian.net/browse/KIT-3341

fix(atomic): resolve result to full collection in context of folded result list

---

packages/atomic/src/components/insight/atomic-insight-generated-answer/atomic-insight-generated-answer.tsx

[SVCC-3897](https://coveord.atlassian.net/browse/SVCC-3897)
This PR enables rich formatting for the Atomic insight panels.
Validated that the right content format is passed down to the search request.
[SVCC-3897]: https://coveord.atlassian.net/browse/SVCC-3897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(atomic): add RGA rich formatting to the insight interface

---

packages/atomic/playwright-utils/base-page-object.ts
packages/atomic/src/components/commerce/atomic-commerce-load-more-products/e2e/atomic-commerce-load-more-products.e2e.ts
packages/atomic/src/components/commerce/atomic-commerce-load-more-products/e2e/page-object.ts
packages/atomic/src/components/commerce/atomic-commerce-pager/e2e/atomic-commerce-pager.e2e.ts
packages/atomic/src/components/commerce/atomic-commerce-product-list/e2e/atomic-commerce-product-list.e2e.ts
packages/atomic/src/components/commerce/atomic-commerce-query-summary/e2e/atomic-commerce-query-summary.e2e.ts
packages/atomic/src/components/commerce/atomic-commerce-search-box/e2e/atomic-commerce-search-box.e2e.ts
packages/atomic/src/components/commerce/facets/atomic-commerce-facets/e2e/atomic-commerce-facets.e2e.ts
packages/atomic/src/components/search/atomic-search-box/e2e/atomic-search-box.e2e.ts

https://coveord.atlassian.net/browse/KIT-3367
I kept running into issues like this :

test(atomic): rework the interface of "load" in base-page-object

---

packages/quantic/cypress/e2e/default-2/generatedAnswer/generated-answer-expectations.ts

[SFINT-5634]: https://coveord.atlassian.net/browse/SFINT-5634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(quantic): rga rephrase e2e test fixed

---

packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-client.ts
packages/headless/src/app/recommendation-engine/recommendation-engine-configuration.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.ts

https://coveord.atlassian.net/browse/KIT-3370

feat(atomic): add middleware preprocessor  for the recommendation engine

---

packages/atomic/src/components/commerce/atomic-commerce-query-error/atomic-commerce-query-error.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-query-error/e2e/atomic-commerce-query-error.e2e.ts
packages/atomic/src/components/commerce/atomic-commerce-query-error/e2e/fixture.ts
packages/atomic/src/components/commerce/atomic-commerce-query-error/e2e/page-object.ts

This PR adds tests for atomic-commerce-query-error
https://coveord.atlassian.net/browse/KIT-3253

test(atomic): add tests for atomic-commerce-query-error

---

packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.test.ts
packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.ts

https://coveord.atlassian.net/browse/KIT-3382

fix(headless/commerce): schema validation error when calling deselect method on hierarchical breadcrumb

---

packages/atomic/src/components/commerce/atomic-commerce-breadbox/atomic-commerce-breadbox.tsx
packages/atomic/src/components/commerce/atomic-commerce-interface/store.ts
packages/atomic/src/components/commerce/facets/atomic-commerce-category-facet/atomic-commerce-category-facet.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-facet/atomic-commerce-facet.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-timeframe-facet/atomic-commerce-timeframe-facet.tsx
packages/atomic/src/pages/examples/commerce-website/cart.html
packages/atomic/src/pages/examples/commerce-website/homepage.html
packages/atomic/src/pages/examples/commerce-website/listing-pants.html
packages/atomic/src/pages/examples/commerce-website/listing-surf-accessories.html
packages/atomic/src/pages/examples/commerce-website/listing-towels.html

https://coveord.atlassian.net/browse/KIT-3383

fix(atomic/commerce): fix breadbox labels / values

---

packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.new.stories.tsx
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.new.stories.tsx
packages/atomic/src/components/search/facets/atomic-segmented-facet/atomic-segmented-facet.new.stories.tsx
packages/atomic/src/components/search/result-template-components/atomic-result-rating/atomic-result-rating.new.stories.tsx

https://coveord.atlassian.net/browse/KIT-3353

docs: add missing attributes-* prefix

---

packages/headless/src/features/configuration/analytics-params.ts

https://coveord.atlassian.net/browse/KIT-3386

fix: remove pageId from analyticsPayload

---

.github/workflows/prbot.yml

https://coveord.atlassian.net/browse/KIT-3412

ci: fix PR artifact spam

---

.github/workflows/prbot.yml
packages/atomic/src/index.ts

https://coveord.atlassian.net/browse/KIT-3388

fix(atomic): breaking change in `SearchBoxSuggestionsEvent`

---

packages/headless/src/controllers/results-per-page/__snapshots__/headless-results-per-page.test.ts.snap
packages/headless/src/controllers/results-per-page/headless-results-per-page.test.ts
packages/headless/src/controllers/results-per-page/headless-results-per-page.ts

https://coveord.atlassian.net/browse/KIT-3387

fix: use browseResults for results-per-page

---

packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
packages/atomic/src/components/common/formats/format-common.ts
packages/atomic/src/components/search/formats/atomic-format-currency.tsx

https://coveord.atlassian.net/browse/KIT-3414

feat(atomic): format commerce numeric facet for price with currency by default

---

packages/atomic/src/components/search/result-template-components/atomic-quickview-modal/atomic-quickview-modal.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview/atomic-quickview.new.stories.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview/e2e/atomic-quickview.e2e.ts
packages/atomic/src/components/search/result-template-components/atomic-quickview/e2e/fixture.ts
packages/atomic/src/components/search/result-template-components/atomic-quickview/e2e/page-object.ts

https://coveord.atlassian.net/browse/KIT-3331

fix: ensure quickview minimize

---

packages/headless/src/controllers/insight/facets/category-facet/headless-insight-category-facet.ts
packages/headless/src/controllers/insight/facets/facet/headless-insight-facet.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts
packages/headless/src/features/insight-search/insight-search-actions.ts
packages/headless/src/features/search/search-actions-thunk-processor.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/integration-tests/analytics-migration.test.ts
packages/headless/src/integration-tests/insight-analytics-migration.test.ts

https://coveord.atlassian.net/browse/KIT-3401

fix(ep): remove actionCause for fetchFacetValues

---

packages/headless/src/controllers/insight/facets/category-facet/headless-insight-category-facet.ts
packages/headless/src/controllers/insight/facets/facet/headless-insight-facet.ts
packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts
packages/headless/src/features/insight-search/insight-search-actions.ts
packages/headless/src/features/recent-queries/recent-queries-analytics-actions.ts
packages/headless/src/features/search/search-actions-thunk-processor.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/integration-tests/analytics-migration.test.ts
packages/headless/src/integration-tests/insight-analytics-migration.test.ts

https://coveord.atlassian.net/browse/KIT-3402

fix(ep): do not send actionCause w/ recentQueriesClick

---

packages/atomic/cypress/e2e/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/e2e/facets/rating-facet/rating-facet.cypress.ts
packages/atomic/cypress/e2e/facets/rating-range-facet/rating-range-facet.cypress.ts

https://coveord.atlassian.net/browse/KIT-3475

ci: temporarily disable some tests failing due to SAPI

---

.github/workflows/prbot.yml

otherwise, statuscheck might get confused
https://coveord.atlassian.net/browse/KIT-3469

chore: ensure unicity of job name

---

.github/actions/setup/action.yml
.prettierignore

I have CI failing for fricky reasons, and I suspect it is a cache issue.
https://coveord.atlassian.net/browse/KIT-3484

ci: disable cache

---

packages/headless/src/app/engine-configuration.ts
packages/headless/src/features/configuration/configuration-actions.ts

docs(analytics): make trackingId & analyticsMode public

---

packages/headless/src/controllers/core/generated-answer/headless-searchapi-generated-answer.test.ts
packages/headless/src/controllers/core/generated-answer/headless-searchapi-generated-answer.ts

Ensure existing state is considered by the subscribeStateManager.
[SVCC-4080](https://coveord.atlassian.net/browse/SVCC-4080)
[SVCC-4080]: https://coveord.atlassian.net/browse/SVCC-4080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(genqa): ensure preloaded state can be used w/ rga

---

packages/samples/headless-commerce-react/src/pages/cart-page.tsx
packages/samples/headless-commerce-react/src/pages/home-page.tsx
packages/samples/headless-commerce-react/src/pages/product-description-page.tsx
packages/samples/headless-commerce-react/src/pages/product-listing-page.tsx
packages/samples/headless-commerce-react/src/pages/search-page.tsx

https://coveord.atlassian.net/browse/KIT-3444

docs(headless commerce react samples): add note regarding context + url manager

---

packages/samples/headless-commerce-react/src/components/products-per-page/products-per-page.tsx
packages/samples/headless-commerce-react/src/components/use-cases/search-and-listing-interface/search-and-listing-interface.css
packages/samples/headless-commerce-react/src/components/use-cases/search-and-listing-interface/search-and-listing-interface.tsx

https://coveord.atlassian.net/browse/KIT-3436

docs(headless commerce react samples): add products per page

---

packages/samples/headless-commerce-react/src/components/breadcrumb-manager/breadcrumb-manager.tsx
packages/samples/headless-commerce-react/src/components/facets/category-facet/category-facet.tsx
packages/samples/headless-commerce-react/src/components/facets/facet-generator/facet-generator.tsx
packages/samples/headless-commerce-react/src/components/facets/regular-facet/regular-facet.tsx

https://coveord.atlassian.net/browse/KIT-3432

docs(headless commerce react samples): add regular and category facet search

---

.github/workflows/prbot.yml

https://coveord.atlassian.net/browse/KIT-3494

ci: prevent concurrent tests run

---

.github/workflows/prbot.yml

- **ci: prevent concurrent tests run**
- **Revert "ci: prevent concurrent tests run"**

ci: disable concurrency

---

packages/headless/src/controllers/commerce/instant-products/headless-instant-products.ts

https://coveord.atlassian.net/browse/KIT-3491

feat(headless commerce): add totalCount to InstantProducts controller state

---

packages/atomic/playwright.config.ts

test: run only on chrome

---

packages/atomic/src/components/search/atomic-sort-dropdown/atomic-sort-dropdown.new.stories.tsx
packages/atomic/src/components/search/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/search/atomic-sort-dropdown/e2e/atomic-sort-dropdown.e2e.ts
packages/atomic/src/components/search/atomic-sort-dropdown/e2e/fixture.ts
packages/atomic/src/components/search/atomic-sort-dropdown/e2e/page-object.ts

Backport of #4308 
https://coveord.atlassian.net/browse/KIT-3480

fix(atomic): field sort should be applied when selected

---

.github/workflows/release.yml
packages/atomic-angular/projects/atomic-angular/project.json
packages/atomic-hosted-page/package.json
packages/atomic-react/package.json
packages/atomic/package.json
packages/auth/package.json
packages/bueno/package.json
packages/headless-react/package.json
packages/headless/package.json
packages/quantic/package.json
utils/release/npm-publish-package.mjs

KIT-3466, like #4346, renaming branch

ci: change npm tags for v2, disable sfdx release

---

packages/atomic/src/components/commerce/atomic-commerce-pager/atomic-commerce-pager.tsx
packages/atomic/src/components/commerce/atomic-commerce-pager/e2e/atomic-commerce-pager.e2e.ts

https://coveord.atlassian.net/browse/KIT-3514

fix(atomic): disable pager next button when reaching last pasge

---

.github/actions/e2e-atomic-screenshots/action.yml
.github/actions/e2e-atomic/action.yml

https://coveord.atlassian.net/browse/KIT-3518

ci: force cypress install

---

.github/actions/confirm-build-ok/action.yml
.github/workflows/prbot.yml

https://coveord.atlassian.net/browse/KIT-3519

ci: use github checks api

---

packages/atomic-hosted-page/package.json
packages/atomic-react/package.json
packages/atomic/package.json
packages/auth/package.json
packages/bueno/package.json
packages/headless-react/package.json
packages/headless/package.json
packages/quantic/package.json

https://coveord.atlassian.net/browse/KIT-3466

ci: ensure we tag on a non semver-range

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx

https://coveord.atlassian.net/browse/KIT-3490

feat(atomic): exposes product-id on atomic-com-recs-list

---

packages/headless/esbuild.mjs

https://coveord.atlassian.net/browse/KIT-3023

chore(headless): esm build for node will look for "module" files instead of "main"

---

scripts/deploy/trigger-ui-kit-cd.mjs

https://coveord.atlassian.net/browse/KIT-3553

chore(cd): provide version

---

renovate.json

Let's reduce the load for now
https://coveord.atlassian.net/browse/KIT-3556

chore: temporarly disable renovate

---

package-lock.json
packages/atomic/src/components/commerce/facets/atomic-commerce-facets/e2e/atomic-commerce-facets.e2e.ts
scripts/deploy/trigger-ui-kit-cd.mjs

https://coveord.atlassian.net/browse/KIT-3553

cd: provide version

---

.deployment.config.json

https://coveord.atlassian.net/browse/KIT-3567

chore: deployment pipeline update in ui-kit

---

.deployment.config.json
scripts/deploy/execute-deployment-pipeline.mjs
scripts/deploy/invalidate-cloudfront.mjs

This PR will add bueno to the list of resources that get deployed on the CDN.
https://coveord.atlassian.net/browse/KIT-3552

chore: add bueno to deploy config

---

packages/atomic/.storybook/main.mts
packages/atomic/stencil.config.ts

https://coveord.atlassian.net/browse/KIT-3575

chore: ensure absolute paths are not resolved as local when building for the CDN

---

packages/atomic/scripts/externalPackageMappings.ts

https://coveord.atlassian.net/browse/KIT-3600

fix: use correct pjson for bueno version replacement

---

packages/atomic-react/README.md
packages/atomic/README.md
packages/headless/README.md

https://coveord.atlassian.net/browse/KIT-3579

docs: document headless, atomic, and atomic-react entry points

---

packages/headless/esbuild.mjs

https://coveord.atlassian.net/browse/KIT-3601

chore(headless): ensure Bueno is loaded from the CDN, not from NPM specifier

---

packages/headless/contributors/adding-a-sub-package.md
packages/headless/esbuild.mjs

https://coveord.atlassian.net/browse/KIT-3581

docs(headless): update adding-a-sub-package

---

packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.new.stories.tsx
packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/atomic-tab-manager.e2e.ts
packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/fixture.ts
packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/page-object.ts

This PR adds tests for disabling/enabled atomic-generated-answer depending on the active tab
https://coveord.atlassian.net/browse/CDX-1557

test(atomic): add tests for generated answer tab support

---

package-lock.json

https://coveord.atlassian.net/browse/KIT-3624

chore: plock unsynced

---

packages/atomic/src/components/common/generated-answer/styles/generated-answer.pcss

[SVCC-4217](https://coveord.atlassian.net/browse/SVCC-4217)
**Before:**
**After:**
[SVCC-4217]: https://coveord.atlassian.net/browse/SVCC-4217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(genqa): fix rga feedback position with chrome

---

packages/atomic/src/components/search/facets/atomic-rating-facet/e2e/atomic-rating-facet.e2e.ts
packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.new.stories.tsx
packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/atomic-tab-manager.e2e.ts

This PR fixes the flaky generated answer test in the atomic-tab-manager tests.
https://coveord.atlassian.net/browse/CDX-1557

chore(atomic): fix atomic-tab-manager flaky test

---

package-lock.json

https://coveord.atlassian.net/browse/KIT-3638

chore: update plock

---

packages/atomic/src/components/search/atomic-did-you-mean/atomic-did-you-mean.new.stories.tsx
packages/atomic/src/components/search/atomic-did-you-mean/e2e/atomic-did-you-mean.e2e.ts
packages/atomic/src/components/search/atomic-did-you-mean/e2e/page-object.ts

https://coveord.atlassian.net/browse/CDX-1595
I am not sure what caused the failing instance but it's best to not leave our tests in the hands of the machine learning models.

test(atomic): fix flaky atomic did you mean tests

---

.github/workflows/prbot.yml

https://coveord.atlassian.net/browse/KIT-3653

ci: fix prepare-playwright-atomic not running in merge queue and not depending on build

---

packages/atomic/cypress/e2e/result-list/result-components/quickview.cypress.ts

https://coveord.atlassian.net/browse/KIT-3651
Did some manual tests and everything works fine..
cypress is randomly failing 1 to 3 tests in that suite. I think it is best to skip it and then rewrite in playwright another time.

test(atomic): skip quickview cypress tests

---

packages/atomic/src/components/commerce/atomic-product/atomic-product.pcss
packages/atomic/src/components/common/template-system/cell-desktop.pcss
packages/atomic/src/components/common/template-system/cell-mobile.pcss
packages/atomic/src/components/common/template-system/row-mobile.pcss

This PR ensures that the imageSize value is respected in grid display mode.
https://coveord.atlassian.net/browse/KIT-3609

fix(atomic): fix product image not always respect imageSize on grid display mode

---

packages/quantic/cypress/e2e/default-1/refine-modal-content/refine-modal-content.cypress.ts
packages/quantic/cypress/e2e/facets-2/timeframe-facet/timeframe-facet.cypress.ts

https://coveord.atlassian.net/browse/KIT-3658

chore(quantic): skip consistently failing quantic tests

---

packages/headless/src/api/commerce/search/response.ts
packages/headless/src/controllers/commerce/search/did-you-mean/headless-did-you-mean.ts
packages/headless/src/features/commerce/did-you-mean/did-you-mean-slice.test.ts
packages/headless/src/features/commerce/did-you-mean/did-you-mean-slice.ts
packages/headless/src/features/commerce/did-you-mean/did-you-mean-state.ts
packages/headless/src/features/commerce/search/search-actions-thunk-processor.ts

https://coveord.atlassian.net/browse/KIT-3655

fix(headless): set wasCorrectedTo to empty string unless query was automatically corrected

---

packages/atomic/cypress/e2e/facets/color-facet/color-facet.cypress.ts

https://coveord.atlassian.net/browse/KIT-3662

test(atomic): fix failing atomic-color-facet test because of source change

---

packages/atomic/project.json

https://coveord.atlassian.net/browse/KIT-3654

fix(atomic): delete ./loader/package.json when building atomic

---

package-lock.json
packages/atomic-react/package.json
packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-3646
Addresses https://github.com/coveo/ui-kit/security/dependabot/626

chore(deps): bump rollup

---

utils/release/bump-package.mjs

https://coveord.atlassian.net/browse/KIT-3668

chore: ensure we get the remote branch for getLastTag

---

patches/@coveo+semantic-monorepo-tools+2.4.43.patch
utils/release/bump-package.mjs
utils/release/common/constants.mjs
utils/release/git-publish-all.mjs

https://coveord.atlassian.net/browse/KIT-3668

chore: ensure we check only the tags from the current release branch

---

package-lock.json

chore: lockfile update

---

utils/release/bump-package.mjs
utils/release/common/constants.mjs
utils/release/npm-publish-package.mjs

https://coveord.atlassian.net/browse/KIT-3668

chore: ensure we use v2-beta instead of beta + refactor

---

.deployment.config.json

https://coveord.atlassian.net/browse/KIT-3677

chore: add smoke test on v2

---

packages/headless/doc-parser/use-cases/commerce.ts
packages/headless/src/commerce.index.ts
packages/headless/src/features/commerce/facets/location-facet/location-facet-actions-loader.ts

See: https://github.com/coveo/ui-kit/pull/4562
[COMHUB-247]
[COMHUB-247]: https://coveord.atlassian.net/browse/COMHUB-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(commerce): add location facets actions loader

---

.github/actions/e2e-atomic-angular/action.yml
.github/actions/e2e-atomic-insight-panel/action.yml
.github/actions/e2e-atomic-next/action.yml
.github/actions/e2e-atomic-react/action.yml
.github/actions/e2e-headless-ssr-app-dev/action.yml
.github/actions/e2e-headless-ssr-app-prod/action.yml
.github/actions/e2e-headless-ssr-pages-dev/action.yml
.github/actions/e2e-headless-ssr-pages-prod/action.yml
.github/actions/e2e-iife/action.yml
.github/actions/e2e-stencil/action.yml

https://coveord.atlassian.net/browse/KIT-3679
This will reduce flakiness like these cases : 
https://github.com/coveo/ui-kit/actions/runs/11487255737/job/31971899544
We already did it for atomic, quantic and some more. It was still missing for these actions.

chore: properly install cypress in every action using it

---

packages/atomic/src/components/commerce/atomic-commerce-breadbox/e2e/atomic-commerce-breadbox.e2e.ts
packages/atomic/src/components/commerce/atomic-commerce-breadbox/e2e/page-object.ts
packages/headless/src/features/commerce/facets/numeric-facet/manual-numeric-facet-slice.test.ts
packages/headless/src/features/commerce/facets/numeric-facet/manual-numeric-facet-slice.ts

https://coveord.atlassian.net/browse/KIT-3680
We were not handling the `clearAllCoreFacets` action in the `manualNumericFacetReducer`.

fix(headless,commerce): clear manual ranges on clearAllCoreFacets

---

packages/auth/package.json

https://coveord.atlassian.net/browse/KIT-3668

chore: migrate auth as well

---

packages/atomic/src/components/common/tabs/tab-bar.tsx
packages/atomic/src/components/insight/atomic-insight-tab/atomic-insight-tab.tsx
packages/atomic/src/components/ipx/atomic-ipx-tab/atomic-ipx-tab.tsx

** [SVCC-4285](https://coveord.atlassian.net/browse/SVCC-4285)
Simply added tooltip to insight tabs !
[SVCC-4285]: https://coveord.atlassian.net/browse/SVCC-4285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(atomic): add tooltip to insight tabs

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/search/atomic-generated-answer/atomic-generated-answer.tsx

https://coveord.atlassian.net/browse/KIT-3712
Small update following https://github.com/coveo/ui-kit/pull/4622/files#r1827700968

docs(atomic): generated answer update

---

packages/headless-react/src/ssr-commerce/common.tsx
packages/headless-react/src/ssr-commerce/types.ts
packages/headless-react/src/ssr/common.tsx
packages/headless-react/src/ssr/types.ts

https://coveord.atlassian.net/browse/KIT-3718

chore(headless): rename 'controllers' to 'methods' in ssr-commerce to stay consistent with ssr

---

scripts/deploy/execute-deployment-pipeline.mjs

https://coveord.atlassian.net/browse/KIT-3692
CD runs on node 22 we need this :)

chore: replace `assert` with `with` for Node 22 support

---

packages/samples/headless-ssr-commerce/app/_lib/navigatorContextProvider.ts
packages/samples/headless-ssr-commerce/middleware.ts

https://coveord.atlassian.net/browse/KIT-3722

docs(headless): add navigatorContext.location docs and implementation in ssr-commerce sample 

---

package-lock.json

https://coveord.atlassian.net/browse/KIT-282

chore: package-lock maintenance

---

.deployment.config.json

https://coveord.atlassian.net/browse/KIT-3724

chore: replace team jenkins phase by github phase

---

packages/atomic/storybookUtils/common/render-component.tsx

https://coveord.atlassian.net/browse/KIT-3682
Faulty commit is #4236

docs(atomic): fix empty html tab in storybook

---

packages/headless/src/controllers/commerce/product-list/headless-product-list.ssr.ts

https://coveord.atlassian.net/browse/KIT-3810

fix(headless commerce SSR): expose promoteChildToParent method on SSR ProductList type

---

renovate.json

https://coveord.atlassian.net/browse/KIT-3770
Lets try this. It should work with the coveo setup according to what I read.

chore: auto merge "all dependencies" PRs

---

scripts/deploy/execute-deployment-pipeline.mjs

chore: remove changeset

---

packages/headless/src/features/commerce/facets/facet-search-set/category/commerce-category-facet-search-request-builder.test.ts
packages/headless/src/features/commerce/facets/facet-search-set/category/commerce-category-facet-search-request-builder.ts
packages/headless/src/features/commerce/facets/facet-search-set/regular/commerce-regular-facet-search-request-builder.test.ts
packages/headless/src/features/commerce/facets/facet-search-set/regular/commerce-regular-facet-search-request-builder.ts

https://coveord.atlassian.net/browse/KIT-3857

fix(headless commerce): do not set query to empty string when building non field suggestions facet search requests

---

.deployment.config.json

copied from v2 branch
https://coveord.atlassian.net/browse/KIT-3871

chore: add missing nightly target

---

.github/workflows/e2e-quantic.yml

https://coveord.atlassian.net/browse/KIT-3877

ci(quantic): run playwright and cypress concurrently

---

.deployment.config.json
packages/samples/iife/build-assets.mjs

- **chore: add missing nightly target**
- **chore: parallel all s3 phases**

chore: run all s3 phases in parallel

---

packages/atomic/src/directives/localized-string.spec.ts
packages/atomic/src/directives/localized-string.ts

https://coveord.atlassian.net/browse/KIT-3895

test(atomic): test localized-string directive

---

packages/atomic/cypress/e2e/facets/facet/facet.1.cypress.ts

https://coveord.atlassian.net/browse/KIT-3882

chore: fix failing atomic test due to source change

---

.github/actions/commit-generated-files/action.yml

KIT-3929
This file does not exist since atomic-hosted-page moved to Lit
https://coveord.atlassian.net/browse/KIT-3929

chore: fix automated commit for generated files

---

packages/headless/src/commerce.index.ts
packages/headless/src/ssr-commerce.index.ts

https://coveord.atlassian.net/browse/KIT-3890
Those were forgotten and not exported. 
@fbeaudoincoveo Is this really all that was needed to complete this ticket ?

feat(headless): export the search/product-listing serializers

---

packages/atomic-angular/scripts/build-lit.mjs

https://coveord.atlassian.net/browse/KIT-3802
works fine in my branch when I tested with atomic-commerce-pager. Here is the final result:

chore(atomic-angular): various fixes for atomic-angular generation from lit components

---

packages/headless/src/app/commerce-engine/commerce-engine.ssr.test.ts
packages/headless/src/app/commerce-engine/commerce-engine.ssr.ts
packages/headless/src/app/commerce-ssr-engine/types/core-engine.ts

https://coveord.atlassian.net/browse/KIT-3985

feat(headless commerce SSR): allow setting / getting the access token on commerce SSR engine definitions

---

packages/atomic/src/components/commerce/atomic-commerce-breadbox/atomic-commerce-breadbox.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-load-more-products/atomic-commerce-load-more-products.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-no-products/atomic-commerce-no-products.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-pager/atomic-commerce-pager.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-query-summary/atomic-commerce-query-summary.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-text/atomic-commerce-text.new.stories.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-category-facet/atomic-commerce-category-facet.new.stories.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-facet/atomic-commerce-facet.new.stories.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-facets/atomic-commerce-facets.new.stories.tsx
packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.new.stories.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-description/atomic-product-description.new.stories.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-excerpt/atomic-product-excerpt.new.stories.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-image/atomic-product-image.new.stories.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-link/atomic-product-link.new.stories.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-numeric-field-value/atomic-product-numeric-field-value.new.stories.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-price/atomic-product-price.new.stories.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-rating/atomic-product-rating.new.stories.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-text/atomic-product-text.new.stories.tsx
packages/atomic/src/components/commerce/product-template/atomic-product-template.new.stories.tsx
packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.new.stories.tsx
packages/atomic/storybook-utils/commerce/commerce-interface-wrapper.tsx

https://coveord.atlassian.net/browse/KIT-4004

chore: better names commerce storybook utilities

---

.github/PULL_REQUEST_TEMPLATE/atomic-stencil-lit-migration.md

https://coveord.atlassian.net/browse/KIT-3986
I think those items are mandatory. What do you guys think ?

ci: add more items to the checklist for stencil-lit migration

---

packages/headless/src/features/recommendation/__snapshots__/recommendation-analytics-actions.test.ts.snap
packages/headless/src/features/recommendation/recommendation-analytics-actions.test.ts
packages/headless/src/features/recommendation/recommendation-analytics-actions.ts

https://coveord.atlassian.net/browse/KIT-4039
Tests were testing the wrong thing....

fix(headless): fix recommendation documentOpen event triggering an error for EP

---

packages/quantic/force-app/examples/main/lwc/exampleRelevantGenerativeAnswering/exampleRelevantGenerativeAnswering.html

[SFINT-6043](https://coveord.atlassian.net/browse/SFINT-6043?atlOrigin=eyJpIjoiZDQwMjA1ZjM0MTZhNDEzYjhlMGEzYzMwMjQzNzRlYWQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
- Removed Demo code that slipped in
[SFINT-6043]: https://coveord.atlassian.net/browse/SFINT-6043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(quantic): removing demo code 

---

package-lock.json
packages/atomic/.storybook/main.mts
packages/atomic/package.json
packages/atomic/vitest.config.ts

https://coveord.atlassian.net/browse/KIT-4046
Just a small plugin will do the job

chore(atomic): fix storybook & vitest integration with tailwindcss

---

packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts

Please refer to the comment section of the ticket for all the details about the issue, how to reproduce the issue locally, and how test the fix.
https://coveord.atlassian.net/browse/SVCC-4840

fix(generated answer): fix citation duplication issue in generated answer

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/atomic-angular.module.ts
packages/atomic-react/rollup.config.js
packages/atomic/project.json
utils/release/if-cdn.mjs
utils/release/package.json

- **fix(quantic): fixed issue with custom facet captions inside the refine modal (#5075)**
- **fix(quantic): delay caused by recent queries fixed (#5060)**
- **[Version Bump][skip ci]: ui-kit publish**
- **working**

KIT 4022 3

---

packages/atomic/src/components/commerce/atomic-commerce-interface/e2e/stencil-atomic-commerce-interface.e2e.ts
packages/atomic/src/components/commerce/facets/atomic-commerce-category-facet/e2e/atomic-commerce-category-facet.e2e.ts
packages/atomic/src/components/commerce/facets/atomic-commerce-category-facet/e2e/page-object.ts

This PR fixes some flaky atomic-commerce-interface and atomic-commerce-category-facet tests
https://coveord.atlassian.net/browse/KIT-4067

chore(atomic): fix flaky tests

---

vitest.workspace.js

https://coveord.atlassian.net/browse/KIT-4008

chore(tests): fix non-existing file reference error

---

.github/workflows/masterbot.yml

https://coveord.atlassian.net/browse/KIT-4069
For the Stencil to Lit migration, please tag the Pull Request with `new-lit-component`. Do not fill out the PR description initially; a template will be automatically generated for you to complete.
For all other contributors, please disregard this instruction.

chore: install NPM & dependencies when publishing to dev

---

packages/atomic/rollup.config.js

chore: move vendor directory

---

packages/quantic/package.json
packages/quantic/project.json

CDX-764
- Split build into two scripts, and uses dependsOn to weld them together
- Enforce DEBUG='' (to overwrite _any_ debug)

chore(quantic): disable debug on jsdoc

---

.github/PULL_REQUEST_TEMPLATE/atomic-stencil-lit-migration.md

For the Stencil to Lit migration, please tag the Pull Request with `new-lit-component`. Do not fill out the PR description initially; a template will be automatically generated for you to complete.
For all other contributors, please disregard this instruction.
https://coveord.atlassian.net/browse/KIT-4086

chore: add cypress removal into the todos

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic-angular/scripts/build-lit.mjs
packages/atomic/src/components/common/atomic-icon/atomic-icon.spec.ts
packages/atomic/src/components/common/load-more/button.spec.ts
packages/atomic/src/utils/initialization-utils.tsx
packages/atomic/src/utils/tailwind-utilities/components.tw.css
packages/atomic/storybook-utils/common/common-meta-parameters.ts
packages/atomic/vitest-utils/i18n-utils.ts
packages/atomic/vitest-utils/setup.ts
packages/atomic/vitest.config.ts

https://coveord.atlassian.net/browse/KIT-4092
There is currently a bunch of small changes spreaded around in my PRs. This PRs groups them all together to not bloat the already big PRs for the search-box & the pager.

chore(atomic): improvements for vitest, tailwind & storybook

---

packages/atomic/vitest.config.ts

https://coveord.atlassian.net/browse/KIT-4142

chore(atomic): add vitest timeout for playwright locators

---

packages/atomic/cypress/e2e/generated-answer.cypress.ts

too flaky
KIT-4140
https://coveord.atlassian.net/browse/KIT-4140

chore: skip copy button test suite

---

packages/atomic/src/components/commerce/atomic-commerce-sort-dropdown/atomic-commerce-sort-dropdown.spec.ts

https://coveord.atlassian.net/browse/KIT-4159
temp fix until the flaky test is fixed

ci: skip flaky test

---

.github/workflows/release.yml

Refines debug output to include scoped debug information for semantic…
Fix typo in actions/create-github-app-token
https://coveord.atlassian.net/browse/KIT-4166

chore: scope debug for release, fix typo

---

.github/workflows/release.yml

https://coveord.atlassian.net/browse/KIT-4166

chore: typo in release

---

packages/atomic/src/components/commerce/atomic-commerce-sort-dropdown/atomic-commerce-sort-dropdown.spec.ts
packages/atomic/vitest-utils/testing-helpers/fixtures/atomic/commerce/atomic-commerce-interface-fixture.ts

https://coveord.atlassian.net/browse/KIT-4165

test(atomic): mark fixture interface as ready

---

packages/atomic/src/decorators/bindings.spec.ts
packages/atomic/src/decorators/bindings.ts

This PR ensures that the bindings decorator is compatible with the errorguard decorator
https://coveord.atlassian.net/browse/KIT-4164

chore(atomic): fix error handling with bindings decorator

---

packages/atomic/src/components/commerce/atomic-commerce-no-products/e2e/atomic-commerce-no-products.e2e.ts

https://coveord.atlassian.net/browse/KIT-4170
Skip the test, https://coveord.atlassian.net/browse/KIT-4171 to fix it whenever.

test: skip no-products flaky test

---

CODEOWNERS

https://coveord.atlassian.net/browse/KIT-4185

chore: fix CODEOWNERS file

---

packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.new.stories.tsx
packages/atomic/storybook-utils/commerce/commerce-search-box-wrapper.tsx

https://coveord.atlassian.net/browse/KIT-4184
Needed for query-suggestions, recent-queries and instant-products

chore(atomic): add commerce-search-box storybook fixture

---

packages/atomic/vitest-utils/testing-helpers/fixtures/atomic/commerce/atomic-commerce-search-box-fixture.ts

https://coveord.atlassian.net/browse/KIT-4181
Needed for query-suggestions, recent-queries and instant-products

chore(atomic): add commerce-search-box vitest fixture

---

packages/atomic/src/autoloader/index.ts

This pull request enhances the autoloader functionality in `packages/atomic/src/autoloader/index.ts` by introducing a mechanism to observe and handle hydration of Stencil elements and improving the discovery process for Atomic components. These changes ensure better compatibility and efficiency when working with Stencil and Atomic elements.
* Added the `observeStencilElementHydration` function to monitor Stencil elements for hydration and discover their `shadowRoot` when hydrated. This ensures proper handling of Stencil components that are not immediately hydrated.
* Updated the `discover` function to filter and process all Atomic elements (`atomic-*`) in the DOM, including those that are not yet defined. This improves the robustness of the discovery process.
* Added logic to handle …

fix(atomic): ensure Stencil "late" ShadowDOM are observed.

---

packages/shopify/scripts/copy-types.mjs

For the Stencil to Lit migration, please tag the Pull Request with `new-lit-component`. Do not fill out the PR description initially; a template will be automatically generated for you to complete.
For all other contributors, please disregard this instruction.

feat(shopify): make type definition copying recursive

---

.github/workflows/manual-release.yml

A workflow needs steps to be valid.
https://coveord.atlassian.net/browse/KIT-4211

chore: fix manual release workflow syntax

---

packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx
packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
packages/atomic/src/components/common/item-list/display-wrapper.spec.ts
packages/atomic/src/components/common/item-list/display-wrapper.ts
packages/atomic/src/components/common/item-list/stencil-display-wrapper.tsx
packages/atomic/src/components/insight/result-lists/atomic-insight-folded-result-list/atomic-insight-folded-result-list.tsx
packages/atomic/src/components/insight/result-lists/atomic-insight-result-list/atomic-insight-result-list.tsx
packages/atomic/src/components/ipx/atomic-ipx-recs-list/atomic-recs-list/atomic-ipx-recs-list.tsx
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx
packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx
packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.tsx

https://coveord.atlassian.net/browse/KIT-4197

chore(atomic): migrate display-wrapper.tsx

---

packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx
packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
packages/atomic/src/components/common/atomic-result-placeholder/item-placeholders.spec.ts
packages/atomic/src/components/common/atomic-result-placeholder/item-placeholders.ts
packages/atomic/src/components/common/atomic-result-placeholder/stencil-placeholders.tsx
packages/atomic/src/components/common/item-list/styles/placeholders.pcss
packages/atomic/src/components/common/result-children/collection-guard.tsx
packages/atomic/src/components/insight/result-lists/atomic-insight-folded-result-list/atomic-insight-folded-result-list.tsx
packages/atomic/src/components/insight/result-lists/atomic-insight-result-list/atomic-insight-result-list.tsx
packages/atomic/src/components/ipx/atomic-ipx-recs-list/atomic-recs-list/atomic-ipx-recs-list.tsx
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx
packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx
packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/utils/functional-component-utils.ts

https://coveord.atlassian.net/browse/KIT-4199

chore(atomic): migrate placeholders.tsx

---

package-lock.json
packages/shopify/package.json
packages/shopify/src/headless.test.ts
packages/shopify/src/headless.ts

Allow passing a custom environment to relay instead of dropping a cookie to support serverside solutions

feat(shopify): support non browser environments

---

packages/headless/src/features/configuration/configuration-slice.ts

https://coveord.atlassian.net/browse/KIT-4222

fix(atomic): fix legacy analytics mode in hosted search pages

---

.deployment.config.json
.github/workflows/prbot.yml
package-lock.json
packages/atomic/.eslintrc.cjs
packages/atomic/.gitignore
packages/atomic/fake-loader/atomic.esm.js
packages/atomic/package.json
packages/atomic/project.json
packages/atomic/rollup.config.js
packages/atomic/src/components/insight/atomic-insight-interface/e2e/atomic-insight-interface.e2e.ts
packages/atomic/src/components/insight/atomic-insight-interface/e2e/page-object.ts
packages/atomic/src/utils/resource-url.ts
packages/atomic/stencil-proxy/esm/loader.js

We want hashes to avoid a mix-cache situation
Needs:
- #5305
- #5304
- #5303
- #5302

fix(atomic): ensure cdn files includes a hash

---

.github/actions/setup/action.yml
.github/workflows/masterbot.yml

chore: lock on 11.3.0 to 'fix' ln ws

---

packages/atomic/src/components/common/item-list/item-list-common.spec.ts
packages/atomic/src/components/common/item-list/item-list-common.ts

https://coveord.atlassian.net/browse/KIT-4204

chore(atomic): add tests for ItemListCommon class

---

packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.spec.tsx
packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.tsx

https://coveord.atlassian.net/browse/KIT-4243

fix(atomic): correctly localize tab label and don't localize tab name

---

packages/atomic/project.json
packages/atomic/scripts/build.mjs
packages/atomic/scripts/dev.mjs
packages/atomic/scripts/process-css.mjs

This PR moves the CSS post processing step inside the build script instead of a separate step.
https://coveord.atlassian.net/browse/KIT-4225

chore(atomic): simplify build process

---

packages/atomic/src/components/commerce/atomic-commerce-search-box-query-suggestions/atomic-commerce-search-box-query-suggestions.mdx

https://coveord.atlassian.net/browse/KIT-4249

docs(atomic): fix bad link in query-suggestions storybook

---

packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
packages/atomic/src/components/common/carousel.spec.ts
packages/atomic/src/components/common/carousel.ts
packages/atomic/src/components/common/stencil-carousel.tsx
packages/atomic/src/components/ipx/atomic-ipx-recs-list/atomic-recs-list/atomic-ipx-recs-list.tsx
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx

https://coveord.atlassian.net/browse/KIT-4247

chore(atomic): migrate carousel

---

packages/atomic/src/components/commerce/product-template-components/atomic-product-multi-value-text/e2e/atomic-product-multi-value-text.e2e.ts

https://coveord.atlassian.net/browse/KIT-4277
Will be addressed in Kit 4278

chore: skip flaky product-multi-value-text test

---

packages/atomic/src/components/commerce/atomic-commerce-search-box/e2e/atomic-commerce-search-box.e2e.ts

https://coveord.atlassian.net/browse/KIT-4285

chore: skip flaky atomic-commerce-search-box test

---

packages/atomic/src/components/commerce/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.spec.ts
packages/atomic/src/components/commerce/atomic-commerce-search-box-query-suggestions/atomic-commerce-search-box-query-suggestions.spec.ts
packages/atomic/src/decorators/bindings.spec.ts
packages/atomic/src/mixins/bindings-mixin.spec.ts

https://coveord.atlassian.net/browse/KIT-4282
add missing spy in the test

test(atomic): add missing spy to avoid unnecessary warnings in the console

---

packages/atomic/src/components/search/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/search/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx

https://coveord.atlassian.net/browse/KIT-4291
See repro steps in Jira.

fix(atomic): Ensure that only the correct range facets are included in SAPI requests based on active tab

---

packages/headless/package.json

This should help using the package with `ng`
https://coveord.atlassian.net/browse/KIT-4317

chore: map package.json into the exports

---

packages/atomic/src/utils/functional-component-utils.ts

https://coveord.atlassian.net/browse/KIT-4318
Was mistakenly merged into master

chore(atomic): remove TemplateResult[] from Lit interface

---

packages/atomic/src/components/commerce/atomic-commerce-recommendation-interface/store.spec.ts

https://coveord.atlassian.net/browse/KIT-4322
I'll add tests for the base store in another pull request.

chore(atomic commerce): add tests for createCommerceRecommendationStore

---

packages/atomic/src/components/commerce/atomic-product/atomic-product.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-children/atomic-product-children.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-description/atomic-product-description.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-excerpt/atomic-product-excerpt.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-field-condition/atomic-product-field-condition.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-image/atomic-product-image.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-link/atomic-product-link.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-multi-value-text/atomic-product-multi-value-text.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-numeric-field-value/atomic-product-numeric-field-value.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-price/atomic-product-price.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-rating/atomic-product-rating.tsx
packages/atomic/src/components/commerce/product-template-components/atomic-product-text/atomic-product-text.tsx
packages/atomic/src/components/commerce/product-template-components/product-template-decorators.spec.ts
packages/atomic/src/components/commerce/product-template-components/product-template-decorators.ts
packages/atomic/src/components/commerce/product-template-components/stencil-product-template-decorators.tsx
packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx
packages/atomic/src/index.ts

https://coveord.atlassian.net/browse/KIT-4312

chore(atomic): migrate product-template-decorators

---

packages/atomic/src/components/common/interface/store.spec.ts
packages/atomic/src/components/common/interface/store.ts

https://coveord.atlassian.net/browse/KIT-4321

chore(atomic): add tests for common store

---

packages/atomic/src/components/common/breadbox/breadcrumb-button.spec.ts
packages/atomic/src/components/common/breadbox/breadcrumb-button.ts
packages/atomic/src/components/common/breadbox/breadcrumb-clear-all.spec.ts
packages/atomic/src/components/common/breadbox/breadcrumb-clear-all.ts
packages/atomic/src/components/common/breadbox/breadcrumb-show-less.spec.ts
packages/atomic/src/components/common/breadbox/breadcrumb-show-less.ts
packages/atomic/src/components/common/breadbox/breadcrumb-show-more.spec.ts
packages/atomic/src/components/common/breadbox/breadcrumb-show-more.ts

https://coveord.atlassian.net/browse/KIT-4353
Just made a separate PR to pollute less https://github.com/coveo/ui-kit/pull/5459 since I dont need the ref as much

chore(atomic): adjust breadbox functional components

---

packages/atomic/src/utils/date-utils.ts

https://coveord.atlassian.net/browse/KIT-4354
The format argument was unused.

chore(atomic): remove unused argument from parseDate function

---

packages/atomic/src/components/commerce/product-template-components/product-template-decorators.ts
packages/atomic/src/components/common/item-list/context/interactive-item-context-controller.ts
packages/atomic/src/components/common/item-list/context/item-context-controller.ts

https://coveord.atlassian.net/browse/KIT-4400

chore(atomic): make product/item context controllers generic

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic-react/src/components/commerce/components.ts

https://coveord.atlassian.net/browse/KIT-4425
Happened because #5470 was merged after #5198 and did not sync in the changes

ci: fix generated files desync

---

packages/atomic/cypress/e2e/result-list/result-list.commons.ts

https://coveord.atlassian.net/browse/KIT-4435
Too much flakiness

test(atomic): skip flaky result list test

---

packages/atomic/src/components/common/breadbox/breadcrumb-content.spec.ts
packages/atomic/src/components/common/breadbox/breadcrumb-content.ts

https://coveord.atlassian.net/browse/KIT-4306

fix(atomic): Ensure special characters in breadcrumb label display correctly

---

packages/atomic/src/components/common/button.spec.ts

https://coveord.atlassian.net/browse/KIT-4464
bad mock, we must use the exact same path as it is used in the code file or it becomes flaky
https://arc.net/l/quote/mkictnjj

ci: fix flaky button unit test

---

packages/atomic-angular/biome.json
packages/atomic-angular/projects/atomic-angular/src/public-api.ts

https://coveord.atlassian.net/browse/KIT-4474

style: enable biome recommended rules in atomic-angular

---

packages/auth/biome.json
packages/auth/src/saml/saml-client.test.ts
packages/auth/src/saml/saml-flow.test.ts
packages/auth/src/saml/saml-flow.ts
packages/auth/src/saml/saml-state.test.ts
packages/auth/src/saml/saml-state.ts

https://coveord.atlassian.net/browse/KIT-4477

style: enable biome recommended rules in auth package

---

packages/samples/vuejs/biome.json
packages/samples/vuejs/src/App.vue
packages/samples/vuejs/src/components/ResultTextField.vue
packages/samples/vuejs/src/components/ResultTextFieldMultivalue.vue
packages/samples/vuejs/src/components/ResultsList.vue
packages/samples/vuejs/src/components/SearchPage.vue

https://coveord.atlassian.net/browse/KIT-4540

chore: enable recommended biome rules in samples/vue

---

packages/samples/stencil/biome.json
packages/samples/stencil/cypress/plugins/index.js
packages/samples/stencil/src/components/app-root/app-root.tsx
packages/samples/stencil/src/components/header/header.tsx
packages/samples/stencil/src/components/results-manager/results-manager.tsx
packages/samples/stencil/src/components/sample-component/sample-component.tsx
packages/samples/stencil/src/components/sample-result-component/sample-result-component.tsx
packages/samples/stencil/src/components/search-page/search-page.tsx
packages/samples/stencil/src/components/standalone-search-box/standalone-search-box.tsx
packages/samples/stencil/stencil.config.ts

https://coveord.atlassian.net/browse/KIT-4539

chore: enables recommended biome rules in samples/stencil

---

packages/create-atomic-template/package.json
packages/create-atomic/package.json

https://coveord.atlassian.net/browse/KIT-4551

ci(create-atomic): fix create-atomic release

---

packages/atomic/vitest-utils/testing-helpers/fixtures/atomic/commerce/atomic-commerce-interface-fixture.ts
packages/atomic/vitest-utils/testing-helpers/fixtures/atomic/search/atomic-search-interface-fixture.ts

https://coveord.atlassian.net/browse/KIT-4655

test(atomic): add search interface fixture

---

renovate.json5

https://coveord.atlassian.net/browse/KIT-4652
We'll then rebase https://github.com/coveo/ui-kit/pull/5727

chore: add "@whitespace/storybook-addon-html" to ignored dependencies

---

packages/atomic/src/components/commerce/atomic-commerce-query-summary/atomic-commerce-query-summary.ts
packages/atomic/src/components/commerce/atomic-commerce-query-summary/atomic-commerce-query-summary.tw.css

https://coveord.atlassian.net/browse/KIT-4669

chore(atomic): remove atomic-commerce-query-summary unnecessary stylesheets

---

packages/atomic/src/components/commerce/atomic-commerce-sort-dropdown/atomic-commerce-sort-dropdown.ts
packages/atomic/src/components/commerce/atomic-commerce-sort-dropdown/atomic-commerce-sort-dropdown.tw.css
packages/atomic/src/components/common/sort/select.ts

https://coveord.atlassian.net/browse/KIT-4671

chore(atomic): remove atomic-commerce-sort-dropdown unnecessary stylesheets

---

.devcontainer/devcontainer.json

https://coveord.atlassian.net/browse/KIT-4693
Another leftoever from https://github.com/coveo/ui-kit/pull/5793
I thought it was better to isolate this one.

chore: update typescript node image to 2-22-bookworm

---

packages/atomic/src/components/commerce/atomic-commerce-breadbox/e2e/atomic-commerce-breadbox.e2e.ts
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.new.stories.tsx
packages/atomic/src/components/search/atomic-search-box/e2e/page-object.ts
packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts

https://coveord.atlassian.net/browse/KIT-4697
BACKPORT of https://github.com/coveo/ui-kit/pull/5194

fix(headless): prevent selected facet search values from replacing idle values

---

packages/atomic/src/components/common/suggestions/instant-item.spec.ts

https://coveord.atlassian.net/browse/KIT-4707
I keep getting this 
https://github.com/coveo/ui-kit/actions/runs/16759896385/job/47452761535 
```
FAIL   chromium  src/components/common/suggestions/instant-item.spec.ts > #getPartialInstantItemElement > should call encodeForDomAttribute with the itemUniqueId
TypeError: [Function encodeForDomAttribute] is not a spy or a call to a spy!
Failure screenshot:
src/components/common/suggestions/__screenshots__/instant-item.spec.ts/-getPartialInstantItemElement-should-call-encodeForDomAttribute-with-the-itemUniqueId-1.png
❯ src/components/common/suggestions/instant-item.spec.ts:40:34
38|     getPartialInstantItemElement(i18n, 'itemTitle', itemUniqueId);
39| 
40|     expect(encodeForDomAttribute).toHaveBeenCalledWith(itemUniqueId);
| …
```

test(atomic): hopefully reduce flakiness in this file

---

packages/atomic/src/components/commerce/atomic-commerce-facet-number-input/atomic-commerce-facet-number-input.spec.ts

KIT-282
I don't know why but this file slipped through. Maybe because of the changes with turborepo. 🤷

style: lint forgotten files

---

packages/atomic/src/components/common/facets/facet-value-checkbox/facet-value-checkbox.spec.ts
packages/atomic/src/components/common/facets/facet-value-checkbox/facet-value-checkbox.ts
packages/atomic/src/components/common/facets/facet-value-link/facet-value-link.spec.ts
packages/atomic/src/components/common/facets/facet-value-link/facet-value-link.ts

https://coveord.atlassian.net/browse/KIT-4726

fix(atomic): badly formatted aria-label on facet values

---

packages/atomic/src/components/search/atomic-results-per-page/atomic-results-per-page.mdx
packages/atomic/src/components/search/atomic-results-per-page/atomic-results-per-page.new.stories.tsx

https://coveord.atlassian.net/browse/KIT-4750

docs(atomic): adjust atomic-results-per-page documentation

---

packages/atomic/src/components/commerce/atomic-product-link/atomic-product-link.ts

https://coveord.atlassian.net/browse/KIT-4719

docs(atomic): permanentid in lower case

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/src/components/commerce/atomic-product-template/atomic-product-template.ts

https://coveord.atlassian.net/browse/KIT-4812

feat: remove conditions attribute to fit with jsdoc

---

packages/samples/atomic-react/src/pages/CommerceSearchPage.tsx

https://coveord.atlassian.net/browse/KIT-3295

chore: add load more products to atomic-react sample

---

packages/atomic/src/components/commerce/atomic-product-description/atomic-product-description.spec.ts
packages/atomic/src/components/commerce/atomic-product-description/atomic-product-description.ts
packages/atomic/src/components/commerce/atomic-product-excerpt/atomic-product-excerpt.spec.ts

https://coveord.atlassian.net/browse/KIT-4832

chore(atomic): make isCollapsible false by default in `atomic-product-description`

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/src/components/commerce/atomic-commerce-layout/atomic-commerce-layout.new.stories.tsx
packages/atomic/src/components/commerce/atomic-commerce-layout/atomic-commerce-layout.ts
packages/atomic/src/decorators/inject-styles-for-no-shadow-dom.ts
packages/samples/angular/tests/smoke.spec.ts
packages/samples/atomic-react/tests/smoke.spec.ts

https://coveord.atlassian.net/browse/KIT-4829

fix(atomic-react): make `atomic-commerce-layout` work in atomic-react

---

packages/atomic/scripts/generate-component.mjs

https://coveord.atlassian.net/browse/KIT-4894

chore(atomic): remove unused template from component generation script

---

.vscode/extensions.json
README.md

- Added new vscode recommended extensions
- Removed extension recommendations from the README.md
- Added recommended vscode settings to fix import linting error with biome in the README.md
https://coveord.atlassian.net/browse/KIT-4905

chore: update default vscode extensions and recommended settings

---

packages/headless/src/ssr/commerce/types/engine.ts
packages/headless/src/ssr/common/types/engine.ts

Just some warnings
https://coveord.atlassian.net/browse/KIT-5069

chore(headless-ssr): add deprecation warning for navigator context provider

---

packages/atomic/src/components/common/formats/format-common.spec.ts
packages/atomic/src/components/common/formats/format-common.ts

This PR adds tests for the format-common util.
https://coveord.atlassian.net/browse/KIT-4947

chore(atomic): add tests for format-common
