coveo/ui-kit

packages/headless/package-lock.json
packages/headless/package.json
packages/headless/rollup.config.js
packages/headless/src/api/platform-client.test.ts
packages/headless/src/api/platform-client.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-client.ts
packages/headless/src/app/headless-engine.test.ts
packages/headless/src/app/headless-engine.ts
packages/headless/src/app/store.ts
packages/headless/src/features/redirection/redirection-slice.test.ts
packages/headless/src/integration-tests/search-app.test.ts
packages/headless/src/test/mock-engine.ts

Lots of files are affected, currently logging action as debug, and platform calls, will add analytics
https://github.com/pinojs/pino
https://coveord.atlassian.net/browse/KIT-86

feat(headless): add a logging library, pino

---

packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/api/platform-client.ts
packages/headless/src/api/search/search-api-client.ts
packages/headless/src/app/headless-engine.ts
packages/headless/src/app/store.ts
packages/headless/src/features/analytics/analytics-actions.ts
packages/headless/src/features/redirection/redirection-slice.test.ts

https://coveord.atlassian.net/browse/KIT-279

feat(headless): log analytics requests/responses

---

packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.test.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ts
packages/headless/src/features/debug/debug-slice.test.ts
packages/headless/src/features/debug/debug-slice.ts
packages/headless/src/features/history/history-slice.test.ts
packages/headless/src/features/history/history-slice.ts
packages/headless/src/features/search-parameters/search-parameter-actions.ts
packages/headless/src/features/search-parameters/search-parameter-schema.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/state/search-app-state.ts
packages/headless/src/test/mock-search-parameters.ts

https://coveord.atlassian.net/browse/KIT-291

feat(headless): add debug search parameter to be serializable/deserializable

---

packages/atomic/package-lock.json
packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/features/analytics/analytics-actions.ts
packages/quantic/package-lock.json

coveo.analytics version bump + use the dedicated `logCustomEventWithType`, which accept any arbitrary custom event, versus "predefined" ones.
https://coveord.atlassian.net/browse/KIT-299

fix(headless): fix log custom event with new ua version

---

.github/dependabot.yml

https://coveord.atlassian.net/browse/KIT-303

chore(headless): tweak dependabot PR cycle

---

packages/headless/package-lock.json
packages/headless/src/controllers/facets/category-facet/headless-category-facet.test.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/facets/facet-search/category/headless-category-facet-search.test.ts
packages/headless/src/controllers/facets/facet-search/category/headless-category-facet-search.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-actions.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-controller-actions.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.test.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.ts
packages/headless/src/features/facets/facet-search-set/category/category-facet-search-actions.ts
packages/quantic/package-lock.json

KIT-304
https://coveord.atlassian.net/browse/KIT-304

fix(headlesss): fixed number of values for Category facet

---

packages/headless/src/features/search/search-actions.ts
packages/headless/src/features/search/search-analytics-actions.ts
packages/headless/src/features/search/search-slice.test.ts
packages/headless/src/index.ts

https://coveord.atlassian.net/browse/KIT-311

feat(headless): logQueryError when there is a query error

---

packages/headless/src/features/search/search-actions.ts
packages/headless/src/features/search/search-slice.test.ts

https://coveord.atlassian.net/browse/KIT-313

feat(headless): dispatch analyticsAction before retrying query with correction

---

packages/headless/src/controllers/tab/headless-tab.ts

https://coveord.atlassian.net/browse/KIT-321

docs(headless): headless tab annotation/documentation

---

packages/headless/src/controllers/pager/headless-pager.ts

https://coveord.atlassian.net/browse/KIT-322

docs(headless): headless pager annotation/documentation

---

packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/app/headless-engine.ts
packages/headless/src/features/configuration/configuration-actions.ts
packages/headless/src/features/configuration/configuration-slice.ts
packages/headless/src/features/configuration/configuration-state.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts

KIT-247
https://coveord.atlassian.net/browse/KIT-247

feat(headless): add support for coveo analytics runtimes

---

packages/headless/src/controllers/breadcrumb-manager/headless-breadcrumb-manager.ts

https://coveord.atlassian.net/browse/KIT-323

docs(headless): headless breadcrumb manager annotation/documentation

---

packages/headless/src/controllers/query-summary/headless-query-summary.ts
packages/headless/src/controllers/sort/headless-sort.ts

https://coveord.atlassian.net/browse/KIT-325

docs(headless): improve documentation/annotation for headless query summary

---

packages/headless/src/controllers/sort/headless-sort.ts

https://coveord.atlassian.net/browse/KIT-326

docs(headless): minor improvement for sort documentation

---

packages/headless/src/features/sort-criteria/criteria.ts

https://coveord.atlassian.net/browse/KIT-327

docs(headless): documentation for sort criteria

---

packages/headless/src/controllers/facets/range-facet/date-facet/date-range.test.ts
packages/headless/src/controllers/facets/range-facet/date-facet/date-range.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.test.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.test.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-set-slice.test.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-set-slice.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-reducers.test.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-reducers.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-set-slice.test.ts
packages/headless/src/features/search-parameters/search-parameter-actions.ts
packages/headless/src/features/search-parameters/search-parameter-schema.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.test.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.ts
packages/headless/src/test/mock-search-parameters.ts

This PR adds support for selected date facet ranges in the url.
https://coveord.atlassian.net/browse/KIT-320

feat(headless): support #df url parameter

---

packages/headless/src/controllers/did-you-mean/headless-did-you-mean.ts
packages/headless/src/features/did-you-mean/did-you-mean-state.ts

https://coveord.atlassian.net/browse/KIT-331

docs(headless): didyoumean controller documentation

---

packages/atomic/package-lock.json
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-context-provider/atomic-context-provider.tsx
packages/atomic/src/index.html
packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/test/mock-search-state.ts

KIT-333
https://coveord.atlassian.net/browse/KIT-333
Still have to add unit tests

feat(headless): send context info inside analytics event payload

---

Jenkinsfile
package.json

https://coveord.atlassian.net/browse/KIT-342

ci: tag alpha releases when publishing to npm

---

packages/headless/src/features/facets/category-facet-set/category-facet-set-controller-actions.test.ts
packages/headless/src/features/facets/facet-set/facet-set-controller-actions.test.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-controller-actions.test.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-controller-actions.test.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-controller-actions.test.ts

KIT-329
https://coveord.atlassian.net/browse/KIT-329

feat(headless): add unit tests to controller action thunks

---

.gitignore
.vscode/extensions.json

See https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions
https://coveord.atlassian.net/browse/KIT-337

chore(all): add VSCode extension suggestions

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/atomic-context-provider/atomic-context-provider.tsx
packages/atomic/src/components/atomic-context-provider/readme.md
packages/atomic/src/components/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/atomic-did-you-mean/atomic-did-you-mean.tsx
packages/atomic/src/components/atomic-facet-manager/atomic-facet-manager.tsx
packages/atomic/src/components/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/atomic-history/atomic-history.tsx
packages/atomic/src/components/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-query-error/atomic-query-error.tsx
packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/atomic-tab/atomic-tab.tsx
packages/atomic/src/index.html
packages/atomic/src/utils/initialization-utils.spec.ts
packages/atomic/src/utils/initialization-utils.tsx

Instead of having them into separate properties

feat(atomic): create a "context" property in components that contains engine, i18n, and can be extended

---

scripts/deploy/bump-version.js

Woopsie !
https://coveord.atlassian.net/browse/KIT-353

build(headless): fix typo in build script

---

packages/headless/src/api/search/search-api-client.ts

https://coveord.atlassian.net/browse/KIT-357

fix(headless): make AbortController usable in locker service

---

packages/headless/src/api/platform-client.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-client.ts

https://coveord.atlassian.net/browse/KIT-355

fix(headless): improve PreprocessRequestMiddleware type; simplify PlatformClientCallOptions type

---

packages/atomic/.gitignore
packages/atomic/package.json
packages/atomic/scripts/split-locales.js
packages/atomic/src/components/atomic-search-interface/lang/dev.json
packages/atomic/src/components/atomic-search-interface/lang/en.json
packages/atomic/src/components/atomic-search-interface/lang/fr.json
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-351

feat(atomic): add build step which splits a main locales JSON file into 1 JSON file per locale

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-component-error/readme.md
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/atomic-text/atomic-text.tsx
packages/atomic/src/components/atomic-text/readme.md
packages/atomic/src/utils/initialization-utils.tsx

https://coveord.atlassian.net/browse/KIT-352

feat(atomic): add atomic-text component for localized strings

---

packages/headless/src/api/analytics/analytics.ts
packages/headless/src/features/recommendation/recommendation-actions.ts
packages/headless/src/features/recommendation/recommendation-slice.test.ts
packages/headless/src/features/recommendation/recommendation-slice.ts
packages/headless/src/features/recommendation/recommendation-state.ts
packages/headless/src/test/mock-recommendation.ts

https://coveord.atlassian.net/browse/KIT-363

fix(headless): pass searchUid for recommendation analytics events

---

.eslintrc.json

https://coveord.atlassian.net/browse/KIT-366

build(headless): ignore veracode folder for eslint

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/atomic-did-you-mean/atomic-did-you-mean.tsx
packages/atomic/src/components/atomic-facet-manager/atomic-facet-manager.tsx
packages/atomic/src/components/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/atomic-history/atomic-history.tsx
packages/atomic/src/components/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-query-error/atomic-query-error.tsx
packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/components/atomic-relevance-inspector/atomic-relevance-inspector.tsx
packages/atomic/src/components/atomic-relevance-inspector/readme.md
packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/atomic-result-template/atomic-result-template.tsx
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/atomic-search-box/readme.md
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/atomic-tab/atomic-tab.tsx
packages/atomic/src/components/atomic-text/atomic-text.tsx
packages/atomic/src/components/atomic-text/readme.md
packages/atomic/src/index.html
packages/atomic/src/utils/initialization-utils.spec.ts
packages/atomic/src/utils/initialization-utils.tsx

https://coveord.atlassian.net/browse/KIT-348

feat(atomic): split Initialization decorator

---

JenkinsfileProductionRelease
JenkinsfileQARelease

https://coveord.atlassian.net/browse/KIT-371

build(headless): recover from failed publish

---

packages/atomic/package-lock.json
packages/atomic/package.json
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx

KIT-370
https://coveord.atlassian.net/browse/KIT-370

feat(atomic): add option to disable search parameter serialization

---

packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.ts
packages/headless/src/controllers/pager/headless-pager.ts
packages/headless/src/controllers/product-recommendations/headless-base-product-recommendations.ts
packages/headless/src/controllers/product-recommendations/headless-cart-recommendations.ts
packages/headless/src/controllers/product-recommendations/headless-frequently-bought-together.ts
packages/headless/src/controllers/product-recommendations/headless-frequently-viewed-together.ts
packages/headless/src/controllers/product-recommendations/headless-popular-bought-recommendations.ts
packages/headless/src/controllers/product-recommendations/headless-popular-viewed-recommendations.ts
packages/headless/src/controllers/product-recommendations/headless-user-interest-recommendations.ts
packages/headless/src/controllers/recommendation/headless-recommendation.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.ts
packages/headless/src/controllers/result-list/headless-result-list.ts
packages/headless/src/controllers/results-per-page/headless-results-per-page.ts
packages/headless/src/controllers/search-box/headless-search-box.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ts
packages/headless/src/controllers/sort/headless-sort.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.ts
packages/headless/src/controllers/tab/headless-tab.ts

https://coveord.atlassian.net/browse/KIT-381

chore(headless): for controller errors, use string name instead of function reference

---

packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/atomic-did-you-mean/atomic-did-you-mean.tsx
packages/atomic/src/components/atomic-facet-manager/atomic-facet-manager.tsx
packages/atomic/src/components/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/atomic-history/atomic-history.tsx
packages/atomic/src/components/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-query-error/atomic-query-error.tsx
packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/atomic-tab/atomic-tab.tsx
packages/atomic/src/components/atomic-text/atomic-text.tsx
packages/atomic/src/utils/initialization-utils.spec.ts
packages/atomic/src/utils/initialization-utils.tsx

Stencil won't rerender properly if error doesn't have a state or prop
https://coveord.atlassian.net/browse/KIT-380

fix(atomic): add error internal state property to all components

---

JenkinsfileProductionRelease
JenkinsfileQARelease
package-lock.json
package.json
scripts/notify-docs/published-headless.js

This PR triggers a github action in the docs repo after an official publish.
Receiving github action: https://github.com/coveo/doc_jekyll-public-site/pull/5021

ci: notify docs after official publish

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/query-summary/query-summary.class.tsx
packages/samples/headless-react/src/components/query-summary/query-summary.fn.tsx

https://coveord.atlassian.net/browse/KIT-384

docs(headless): add React samples for headless query-summary

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.pcss
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx
packages/atomic/src/components/atomic-results-per-page/readme.md
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-373

feat(atomic): atomic-result-per-page component completion 

---

.prettierrc.js

KIT-400
https://coveord.atlassian.net/browse/KIT-400

chore(headless): fix prettier config to support windows

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/pager/pager.class.tsx
packages/samples/headless-react/src/components/pager/pager.fn.tsx

https://coveord.atlassian.net/browse/KIT-387

docs(headless): add React samples for headless pager

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/results-per-page/results-per-page.class.tsx
packages/samples/headless-react/src/components/results-per-page/results-per-page.fn.tsx

https://coveord.atlassian.net/browse/KIT-388

docs(headless): add React samples for headless results-per-page

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/sort/sort.class.tsx
packages/samples/headless-react/src/components/sort/sort.fn.tsx

https://coveord.atlassian.net/browse/KIT-389
New pull request since this is now a sort dropdown.

docs(headless): add React samples for headless sort

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/did-you-mean/did-you-mean.class.tsx
packages/samples/headless-react/src/components/did-you-mean/did-you-mean.fn.tsx

https://coveord.atlassian.net/browse/KIT-382
This currently logs an error in the console which is unrelated to the sample, I created [KIT-395](https://coveord.atlassian.net/browse/KIT-395) for it.

docs(headless): add React samples for headless did-you-mean

---

packages/atomic/cypress/integration/result-per-page.cypress.ts
packages/atomic/cypress/integration/search-box.cypress.ts
packages/atomic/cypress/utils/network.ts
packages/atomic/src/index.html
packages/atomic/src/pages/test.html
packages/headless/package.json

https://coveord.atlassian.net/browse/KIT-373

test(atomic): add cypress tests for resultPerPage

---

packages/headless/package.json
packages/samples/headless-react/package-lock.json
packages/samples/headless-react/package.json

https://coveord.atlassian.net/browse/KIT-396

fix(headless-react): made lerna bootstrap headless-react

---

packages/samples/headless-react/src/components/facet/facet-search.tsx
packages/samples/headless-react/src/components/facet/facet.class.tsx
packages/samples/headless-react/src/components/facet/facet.fn.tsx

https://coveord.atlassian.net/browse/KIT-409

docs(headless): add React samples for headless facet search

---

packages/atomic/src/components/atomic-pager/atomic-pager.pcss

Firefox can't handle not having it
https://coveord.atlassian.net/browse/KIT-406

fix(atomic): atomic-pager - add width/height to svgs

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/query-error/query-error.class.tsx
packages/samples/headless-react/src/components/query-error/query-error.fn.tsx

https://coveord.atlassian.net/browse/KIT-419

docs(headless): add React samples for headless query error

---

packages/atomic/src/components/atomic-no-results/atomic-no-results.tsx
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/utils/initialization-utils.spec.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/query-summary/headless-query-summary.ts
packages/headless/src/controllers/result-list/headless-result-list.ts
packages/headless/src/controllers/search-status/headless-search-status.test.ts
packages/headless/src/controllers/search-status/headless-search-status.ts

https://coveord.atlassian.net/browse/KIT-437

feat(atomic,headless): add search status controller and handle state

---

packages/headless/src/features/history/history-slice.test.ts
packages/headless/src/features/history/history-slice.ts

https://coveord.atlassian.net/browse/KIT-436

fix(headless): only compare selected values for facets history

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/query-summary/query-summary.class.tsx
packages/samples/headless-react/src/components/query-summary/query-summary.fn.tsx
packages/samples/headless-react/src/components/tab/tab.class.tsx
packages/samples/headless-react/src/components/tab/tab.fn.tsx

https://coveord.atlassian.net/browse/KIT-416

docs(headless): add React samples for headless tab

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/recommendation-list/recommendation-list.class.tsx
packages/samples/headless-react/src/components/recommendation-list/recommendation-list.fn.tsx
packages/samples/headless-react/src/engine.ts

https://coveord.atlassian.net/browse/KIT-421

docs(headless): add React sample for headless recommendation list

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/history/history.class.tsx
packages/samples/headless-react/src/components/history/history.fn.tsx

https://coveord.atlassian.net/browse/KIT-418

docs(headless): add React samples for headless history

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/src/interface-resolver.test.ts
packages/headless/doc-parser/src/interface-resolver.ts
packages/headless/src/controllers/did-you-mean/headless-did-you-mean.ts
packages/headless/src/controllers/index.ts

This PR adjusts the DidYouMean controller interfaces so that they can be documented.

docs(headless): adjust DidYouMean interfaces

---

packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/relevance-inspector/relevance-inspector.class.tsx
packages/samples/headless-react/src/components/relevance-inspector/relevance-inspector.fn.tsx

https://coveord.atlassian.net/browse/KIT-423
The checkbox doesn't work without https://github.com/coveo/ui-kit/pull/530.

docs(headless): add React sample for headless relevance inspector

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/src/interface-resolver.ts
packages/headless/src/controllers/facet-manager/headless-facet-manager.ts

https://coveord.atlassian.net/browse/KIT-461

docs(headless): extract FacetManager controller documentation.

---

packages/headless/doc-parser/src/function-resolver.ts
packages/headless/doc-parser/src/interface-resolver.test.ts
packages/headless/doc-parser/src/interface-resolver.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/controllers/context/headless-context.ts
packages/headless/src/controllers/index.ts
packages/headless/src/features/context/context-actions.ts
packages/headless/src/features/context/context-state.ts

https://coveord.atlassian.net/browse/KIT-465

docs(headless): export missing interfaces for Context controller; resolve type alias on function params

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.pcss
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/facets/facet-search/facet-search.tsx
packages/atomic/src/index.html

Fixed z-index issue and corners not rounding correctly, I also changed the facet-search's `border-divider` colour to be consistent with the JF's search box styles. 
KIT-477
https://coveord.atlassian.net/browse/KIT-477

fix(atomic): fix search box styles

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/controllers/controller/error-payload.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/query-error/headless-query-error.ts

https://coveord.atlassian.net/browse/KIT-470

docs: adjust QueryError interfaces to extract documentation

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/src/interface-resolver.test.ts
packages/headless/doc-parser/src/interface-resolver.ts
packages/headless/src/controllers/query-summary/headless-query-summary.ts

https://coveord.atlassian.net/browse/KIT-471

docs: extract QuerySummary controller documentation

---

packages/headless/doc-parser/doc-parser.ts
packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/facet/facet.class.tsx
packages/samples/headless-react/src/components/search-status/search-status.class.tsx
packages/samples/headless-react/src/components/search-status/search-status.fn.tsx

https://coveord.atlassian.net/browse/KIT-445

docs(headless): add React sample for search status

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/controllers/results-per-page/headless-results-per-page.test.ts
packages/headless/src/controllers/results-per-page/headless-results-per-page.ts

https://coveord.atlassian.net/browse/KIT-480

docs: extract results per page documentation

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/controllers/result-list/headless-interactive-result.ts

https://coveord.atlassian.net/browse/KIT-481

docs: extract InteractiveResult controller documentation

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/controllers/tab/headless-tab.ts

https://coveord.atlassian.net/browse/KIT-487

docs: extract tab controller documentation

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ts
packages/headless/src/features/search-parameters/search-parameter-actions.ts

https://coveord.atlassian.net/browse/KIT-484

docs: extract search parameter manager documentation

---

Jenkinsfile
package.json
packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/src/interface-resolver.ts
packages/headless/package.json

Adding a documentation generation step to CI to help ensure that changes to the parser of interfaces do not introduce a regression.
https://coveord.atlassian.net/browse/KIT-490

docs: build documentation on CI

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/src/api-finder.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet-options.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.test.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/interfaces/response.ts

https://coveord.atlassian.net/browse/KIT-489

docs(headless): adjust NumericFacet interfaces to extract documentation

---

packages/atomic/cypress.json
packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-485
User& password access to Cypress dashboard I have shared through Lastpass

test(atomic): Link test run with live Cypress Dashboard

---

packages/atomic/cypress.json
packages/atomic/cypress/integration/facet-selectors.ts
packages/atomic/cypress/integration/facet-standard.cypress.ts
packages/atomic/cypress/integration/facet-utils.ts
packages/atomic/cypress/utils/componentUtils.ts
packages/atomic/src/components/facets/facet-value/facet-value.tsx

https://coveord.atlassian.net/browse/KIT-460
Add cypress test for Standard Facet
- 27 test runs + 
- 2 pending test (just description)
- 1 test  related to the issue that Facet should be hidden when returns no result
-  Test for DelimitingCharacter

test(atomic): cypress test for standard facet

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box-options.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.ts

https://coveord.atlassian.net/browse/KIT-493

docs: extract standalone search box documentation

---

packages/atomic/src/index.html

https://coveord.atlassian.net/browse/KIT-500

chore(atomic): add custom result templates examples

---

packages/headless/doc-parser/doc-parser.ts
packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/category-facet/category-facet-search.tsx
packages/samples/headless-react/src/components/category-facet/category-facet.class.tsx
packages/samples/headless-react/src/components/category-facet/category-facet.fn.tsx
packages/samples/headless-react/src/components/search-parameter-manager/search-parameter-manager.ts

https://coveord.atlassian.net/browse/KIT-435

docs(headless): add React sample for category facet

---

packages/samples/headless-react/src/components/result-list/result-link.tsx

https://coveord.atlassian.net/browse/KIT-506

docs(headless): filter protocols in result list for react sample

---

packages/atomic/src/components/atomic-component-error/readme.md
packages/atomic/src/components/atomic-sort-criteria/atomic-sort-criteria.tsx
packages/atomic/src/components/atomic-sort-criteria/readme.md
packages/atomic/src/components/result-template-components/result-template-decorators.ts

https://coveord.atlassian.net/browse/KIT-515

fix(atomic): display error when atomic-sort-criteria has no parent atomic-sort-dropdown

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/locales.json
packages/atomic/src/utils/initialization-utils.tsx

Adds formatting for both the facets and the breadcrumbs
KIT-528
https://coveord.atlassian.net/browse/KIT-528

feat(atomic): date and numeric facet formatting

---

packages/headless/doc-parser/doc-parser.ts
packages/samples/headless-react/src/components/breadcrumb-manager/breadcrumb-manager.class.tsx
packages/samples/headless-react/src/components/breadcrumb-manager/breadcrumb-manager.fn.tsx
packages/samples/headless-react/src/pages/SearchPage.tsx

https://coveord.atlassian.net/browse/KIT-417

docs(headless): add React sample for breadcrumb manager

---

packages/headless/doc-parser/doc-parser.ts
packages/samples/headless-react/src/components/standalone-search-box/standalone-search-box.class.tsx
packages/samples/headless-react/src/components/standalone-search-box/standalone-search-box.fn.tsx
packages/samples/headless-react/src/pages/SearchPage.tsx

https://coveord.atlassian.net/browse/KIT-422

docs(headless): add React sample for standalone search box

---

packages/headless/doc-parser/doc-parser.ts

https://coveord.atlassian.net/browse/KIT-532

docs(headless): add history manager sample to doc

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx

KIT-529
https://coveord.atlassian.net/browse/KIT-529

feat(atomic): do not generate automatic ranges when manual ranges are provided

---

packages/quantic/force-app/custom-token/test/classes/CustomTokenProviderTest.cls-meta.xml
packages/quantic/force-app/custom-token/test/classes/MockHttpTokenResponse.cls
packages/quantic/force-app/custom-token/test/classes/MockHttpTokenResponse.cls-meta.xml
packages/quantic/force-app/main/default/classes/SampleTokenProviderTest.cls

[SFINT-3738](https://coveord.atlassian.net/browse/SFINT-3806)
Some files were missing, preventing deployment of the Quantic source files in a Salesforce organization with the following command.
sfdx force:source:push -u LWC
The missing files were recovered from [this branch](https://github.com/louis-bompart/ui-kit/tree/SFINT-3766-2).
* Deployed Quantic files with `sfdx force:source:push -u LWC`
* Executed APEX tests successfully

fix(quantic): add missing files

---

packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx

[COM-905]
[COM-905]: https://coveord.atlassian.net/browse/COM-905

feat(atomic): replace ec_image field by ec_thumbnails field

---

packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx

https://coveord.atlassian.net/browse/KIT-538

fix(atomic): remove double space in atomic-query-summary

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/facets/atomic-date-range/atomic-date-range.tsx

https://coveord.atlassian.net/browse/KIT-547

fix(atomic): remove end-inclusive option on date range

---

packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx

KIT-536
https://coveord.atlassian.net/browse/KIT-536

feat(atomic): add number of values to last parent in category facet

---

packages/atomic/src/components/facets/facet-search/facet-search.tsx

KIT-546
https://coveord.atlassian.net/browse/KIT-546

fix(atomic): show facet search results on consecutive searches

---

packages/atomic/cypress/integration/result-list.cypress.ts
packages/atomic/cypress/integration/result-templates/field-condition.cypress.ts
packages/atomic/cypress/integration/result-templates/result-date.cypress.ts
packages/atomic/cypress/integration/result-templates/result-icon.cypress.ts
packages/atomic/cypress/integration/result-templates/result-image.cypress.ts
packages/atomic/cypress/integration/result-templates/result-link.cypress.ts
packages/atomic/cypress/integration/result-templates/result-number.cypress.ts
packages/atomic/cypress/integration/result-templates/result-price.cypress.ts
packages/atomic/cypress/integration/result-templates/result-printable-uri.cypress.ts
packages/atomic/cypress/integration/result-templates/result-template.cypress.ts
packages/atomic/cypress/integration/result-templates/result-text.cypress.ts
packages/atomic/src/components/atomic-result-template/atomic-result-template.tsx
packages/atomic/src/components/result-template-components/atomic-field-condition/atomic-field-condition.tsx

When through all the "result" components implementation & wrote test descriptions that I'll implement in upcoming PRs, wanted to make it digestible.
https://coveord.atlassian.net/browse/KIT-512

test(atomic): write tests for result-list & all result template components

---

packages/atomic/cypress/integration/component-error-selectors.ts
packages/atomic/cypress/integration/result-list-selectors.ts
packages/atomic/cypress/integration/result-list.cypress.ts
packages/atomic/cypress/integration/result-templates/field-condition.cypress.ts
packages/atomic/cypress/integration/result-templates/result-date.cypress.ts
packages/atomic/cypress/integration/result-templates/result-icon.cypress.ts
packages/atomic/cypress/integration/result-templates/result-image.cypress.ts
packages/atomic/cypress/integration/result-templates/result-link.cypress.ts
packages/atomic/cypress/integration/result-templates/result-number.cypress.ts
packages/atomic/cypress/integration/result-templates/result-price.cypress.ts
packages/atomic/cypress/integration/result-templates/result-printable-uri.cypress.ts
packages/atomic/cypress/integration/result-templates/result-template-selectors.ts
packages/atomic/cypress/integration/result-templates/result-template.cypress.ts
packages/atomic/cypress/integration/result-templates/result-text.cypress.ts
packages/atomic/cypress/utils/network.ts
packages/atomic/cypress/utils/setupComponent.ts
packages/atomic/src/components/atomic-result-template/atomic-result-template.tsx
packages/atomic/src/components/result-template-components/atomic-field-condition/atomic-field-condition.tsx
packages/atomic/src/components/result-template-components/result-template-decorators.ts
packages/atomic/src/pages/test-no-search.html

https://coveord.atlassian.net/browse/KIT-512

test(atomic): implement result-list & result-template cypress tests

---

Jenkinsfile
packages/atomic/cypress/integration/facets/date-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet.cypress.ts
packages/atomic/cypress/integration/facets/numeric-facet.cypress.ts
packages/atomic/package.json

lets see how this goes
https://coveord.atlassian.net/browse/KIT-562

fix(atomic): replace cypress server

---

packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.pcss
packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/facets/base-facet/base-facet.tsx

https://coveord.atlassian.net/browse/KIT-578

feat(atomic): add ellipsis & title to facet labels (button, breadcrumb, header)

---

packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx

https://coveord.atlassian.net/browse/KIT-580

fix(atomic): make category facet active value non clickable

---

packages/atomic/src/index.html

https://coveord.atlassian.net/browse/KIT-594

fix(atomic): cleanup index.html templates

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/atomic-search-box/readme.md

https://coveord.atlassian.net/browse/KIT-595

fix(atomic): remove id prop from search box

---

packages/atomic/src/index.html

https://coveord.atlassian.net/browse/KIT-587

fix(atomic): cleanup index.html capitalize CSS rule

---

packages/atomic/src/index.html

https://coveord.atlassian.net/browse/KIT-588

fix(atomic): cleanup end-inclusive for facet range in index.html

---

packages/atomic/src/index.html

https://coveord.atlassian.net/browse/KIT-586

fix(atomic): fix .side-by-side container alignment

---

packages/atomic/cypress/integration/sort-dropdown.cypress.ts
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx

https://coveord.atlassian.net/browse/KIT-592

fix(atomic): sort dropdown should hide on no results

---

package.json
packages/headless/src/controllers/quickview/headless-quickview.test.ts
packages/headless/src/controllers/quickview/headless-quickview.ts
packages/headless/src/features/result-preview/result-preview-analytics-actions.ts

https://coveord.atlassian.net/browse/KIT-603

feat(headless): log document quickview event

---

packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-analytics-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions-utils.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-analytics-actions.ts

Related PR, will bump library once it's merged: https://github.com/coveo/coveo.analytics.js/pull/274
https://coveord.atlassian.net/browse/KIT-589

feat(atomic): use the getFacetState method of the SearchPageClientProvider

---

packages/atomic/src/index.html
packages/atomic/src/templates/default.html

Grey badge for field values in default template + change font to gibson for default page.
https://coveord.atlassian.net/browse/KIT-612

feat(atomic): change style of field value in default template

---

packages/atomic/cypress/integration/pager.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-pager/readme.md

✅  by UX
https://coveord.atlassian.net/browse/KIT-602

feat(atomic): remove enableNavigationButtons prop for Pager

---

packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/images/arrow-down.svg
packages/atomic/src/themes/default.css
packages/atomic/tailwind.config.js

https://coveord.atlassian.net/browse/KIT-613

feat(atomic): styling changes for sort dropdown

---

packages/atomic/cypress/integration/pager.cypress.ts
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx

https://coveord.atlassian.net/browse/KIT-599

fix(atomic): make pager & result-per-page responsive with many elements

---

packages/atomic/cypress/integration/facets/facet.cypress.ts
packages/atomic/cypress/utils/setupComponent.ts

https://coveord.atlassian.net/browse/KIT-589

test(atomic): test facetState being part of the interface load event

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/index.html

Gray background for header
https://coveord.atlassian.net/browse/KIT-614

 feat(atomic): styling for search box in default page

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/facet-search/facet-search.pcss
packages/atomic/src/components/facets/facet-search/facet-search.tsx
packages/atomic/src/utils/combobox.tsx

https://coveord.atlassian.net/browse/KIT-611
I think we could go even further with the refactor 🤔 let me know if this is good enough

chore(atomic): refactor facet search

---

packages/atomic/cypress/integration/facets/category-facet.cypress.ts
packages/atomic/cypress/integration/facets/date-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet.cypress.ts
packages/atomic/cypress/integration/facets/numeric-facet.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-category-facet/readme.md
packages/atomic/src/components/facets/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/facets/atomic-date-facet/readme.md
packages/atomic/src/components/facets/atomic-facet-placeholder/atomic-facet-placeholder.pcss
packages/atomic/src/components/facets/atomic-facet-placeholder/atomic-facet-placeholder.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-facet/readme.md
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/readme.md
packages/atomic/src/themes/default.css
packages/atomic/src/utils/combobox.tsx
packages/atomic/tailwind.config.js

https://coveord.atlassian.net/browse/KIT-255

feat(atomic): add atomic-facet-placeholder for loading state

---

packages/atomic/src/templates/default.html

Just unsightly otherwise on a smaller screen
https://coveord.atlassian.net/browse/KIT-620

fix(atomic): fix default template wrap issue for field values

---

packages/atomic/cypress/integration/facets/category-facet.cypress.ts
packages/atomic/cypress/integration/facets/date-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet-selectors.ts
packages/atomic/cypress/integration/facets/facet-utils.ts
packages/atomic/cypress/integration/facets/facet.cypress.ts
packages/atomic/cypress/integration/facets/numeric-facet.cypress.ts
packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.pcss
packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/atomic-breadcrumb-manager/readme.md
packages/atomic/src/components/facets/facet-value/facet-value.tsx
packages/atomic/src/index.html

https://coveord.atlassian.net/browse/KIT-616

fix(atomic): remove max-with for breadcrumbs and ellipse the content

---

packages/atomic/cypress/integration/facets/category-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet-utils.ts

- Add check for last level item is not a button 
- Add some tests for basePath
- Add test for Category Facet search Path
** some tests for highlighted & UA, I disabled them for now, as we still have some small issues with that

test(atomic): Add cypress test for category facet search and basepath

---

packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/index.html
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-624

feat(atomic): manage display & localize show more breadcrumb

---

packages/samples/atomic/index.html
packages/samples/atomic/package-lock.json
packages/samples/atomic/package.json
packages/samples/atomic/sandbox.config.json

Added an atomic folder to samples with the codesandbox demo files.

doc(atomic): add atomic folder and codesandbox demo

---

packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-category-facet/readme.md
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-facet/readme.md
packages/atomic/src/components/facets/facet-search/facet-search.tsx
packages/atomic/src/components/result-template-components/atomic-result-printable-uri/readme.md
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-631

feat(atomic): add facet search "No values found." result

---

.deployment.config.json
Jenkinsfile
packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-564
Accompanied by https://github.com/coveo/cdn/pull/32.

ci(atomic): added atomic cdn upload to deployment pipeline

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/facet-search/facet-search.pcss
packages/atomic/src/components/facets/facet-search/facet-search.tsx

https://coveord.atlassian.net/browse/KIT-630

fix(atomic): reverse facet search highlighting and only match once

---

packages/atomic/src/index.html

https://coveord.atlassian.net/browse/KIT-650

fix(atomic): fix wrap for facet mobile

---

packages/atomic/cypress/integration/search-interface.cypress.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/headless/src/features/configuration/configuration-actions.ts

https://coveord.atlassian.net/browse/KIT-645

feat(atomic): set headless language config on atomic language change

---

packages/headless/src/app/analytics-middleware.test.ts
packages/headless/src/app/logger-middlewares.test.ts
packages/headless/src/test/mock-engine.ts

https://coveord.atlassian.net/browse/KIT-652

refactor(headless): simplify mock-engine by removing mockStore

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/configuration/configuration-actions-loader.ts
packages/headless/src/features/configuration/configuration-actions.ts
packages/headless/src/features/index.ts

feat(headless): add loadConfigurationActions function

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/debug/debug-actions-loader.ts
packages/headless/src/features/index.ts

feat(headless): add loadDebugActions function

---

CODEOWNERS

https://coveord.atlassian.net/browse/KIT-664

chore(atomic,headless):  add nbuissoncoveo to owners

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-actions-loader.ts
packages/headless/src/features/facets/facet-set/facet-set-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/facets/facet-set/interfaces/options.ts
packages/headless/src/features/index.ts

feat(headless): add loadFacetSetActions function

---

packages/atomic/src/components/facets/atomic-facet-placeholder/atomic-facet-placeholder.tsx

https://coveord.atlassian.net/browse/KIT-668

fix(atomic): fix facet placeholder in mobile mode

---

packages/atomic/package-lock.json
packages/atomic/package.json
packages/atomic/src/components/atomic-result/atomic-result.tsx
packages/atomic/src/components/result-template-components/result-template-decorators.ts
packages/atomic/src/utils/event-utils.ts
packages/atomic/src/utils/initialization-utils.tsx

The previous method updating the component directly caused weird issues, using the events (same method as for bindings) prevent those issues.
https://coveord.atlassian.net/browse/KIT-604

fix(atomic): use event to resolve parent result

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/fields/fields-actions-loader.ts
packages/headless/src/features/index.ts

feat(headless): add loadFieldActions function

---

packages/atomic/src/components/atomic-facet-manager/atomic-facet-manager.pcss
packages/atomic/src/components/atomic-pager/atomic-pager.pcss
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-result/atomic-result.pcss
packages/atomic/src/components/atomic-result/atomic-result.tsx
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.pcss
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx
packages/atomic/src/components/atomic-search-box/atomic-search-box.pcss
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/facets/base-facet/base-facet.pcss
packages/atomic/src/components/result-template-components/atomic-result-link/atomic-result-link.pcss
packages/atomic/src/components/result-template-components/atomic-result-link/atomic-result-link.tsx
packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.pcss
packages/atomic/src/index.html

https://coveord.atlassian.net/browse/KIT-662

fix(atomic): various styling issues

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/index.ts
packages/headless/src/features/pipeline/pipeline-actions-loader.ts

feat(headless): add loadPipelineActions function

---

packages/atomic/src/components/facets/base-facet/base-facet.tsx
packages/atomic/src/index.html
packages/atomic/src/themes/default.css

https://coveord.atlassian.net/browse/KIT-672

fix(atomic): allow to scroll down mobile facets

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/index.ts
packages/headless/src/features/pagination/pagination-actions-loader.ts
packages/headless/src/features/pipeline/pipeline-actions-loader.ts

feat(headless): add loadPaginationActions function

---

packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/facet-search/facet-search.tsx
packages/headless/src/api/search/facet-search/category-facet-search/category-facet-search-request.test.ts
packages/headless/src/api/search/facet-search/specific-facet-search/specific-facet-search-request.test.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/facets/facet-search/facet-search.test.ts
packages/headless/src/controllers/facets/facet-search/facet-search.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/features/facets/facet-search-set/category/category-facet-search-request-builder.ts
packages/headless/src/features/facets/facet-search-set/facet-search-reducer-helpers.test.ts
packages/headless/src/features/facets/facet-search-set/facet-search-reducer-helpers.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-request-builder.ts
packages/headless/src/test/mock-facet-search-request-options.ts

https://coveord.atlassian.net/browse/KIT-642

feat(atomic,headless): expose facetSearch query in controllers state

---

packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/facets/base-facet/base-facet.tsx

https://coveord.atlassian.net/browse/KIT-672

fix(atomic): category facet x overflow & breadcrumb x position

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/index.ts
packages/headless/src/features/query/query-actions-loader.ts
packages/headless/src/features/query/query-actions.ts

feat(headless): add loadQueryActions function

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/index.ts
packages/headless/src/features/query-suggest/query-suggest-actions-loader.ts
packages/headless/src/features/query-suggest/query-suggest-actions.ts

feat(headless): add loadQuerySuggestActions function

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/index.ts
packages/headless/src/features/redirection/redirection-actions-loader.ts
packages/headless/src/features/redirection/redirection-actions.ts

feat(headless): add loadRedirectionActions function

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/index.ts
packages/headless/src/features/sort-criteria/sort-criteria-actions-loader.ts

feat(headless): add loadSortCriteriaActions function

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/analytics/click-analytics-actions-loader.ts
packages/headless/src/features/analytics/index.ts

feat(headless): add loadClickAnalyticsActions function

---

packages/headless/src/features/analytics/index.ts
packages/headless/src/features/index.ts

https://coveord.atlassian.net/browse/KIT-680

chore(headless): deprecate action namespaces

---

packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/api/search/search-api-params.ts
packages/headless/src/api/search/search/search-request.test.ts
packages/headless/src/api/search/search/search-request.ts
packages/headless/src/controllers/tab/headless-tab.test.ts
packages/headless/src/controllers/tab/headless-tab.ts
packages/headless/src/features/configuration/configuration-state.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/test/mock-analytics-configuration.ts

https://coveord.atlassian.net/browse/KIT-407

feat(headless): add #id option to tab controller; send originLevel2 as #tab parameter

---

packages/headless/src/features/pagination/pagination-slice.test.ts
packages/headless/src/features/pagination/pagination-slice.ts

https://coveord.atlassian.net/browse/KIT-669

fix(headless): modifying filters (facets) should reset the pagination

---

CHANGELOG.md
packages/atomic/CHANGELOG.md
packages/atomic/README.md
packages/bueno/CHANGELOG.md
packages/bueno/README.md
packages/headless/CHANGELOG.md
packages/headless/README.md
packages/quantic/CHANGELOG.md
packages/quantic/package.json

fix: Change all references of bitbucket to github for all remaining files
**Please repo owner review carefully. This PR has been generated by a script and it has not been tested.**
JIRA CA-97

Change all references of bitbucket to github

---

packages/headless/package.json
packages/headless/recommendation/package.json
packages/headless/rollup.config.js
packages/headless/src/controllers/index.ts
packages/headless/src/features/index.ts
packages/headless/src/recommendation.index.ts

https://coveord.atlassian.net/browse/KIT-685

chore(headless): expose recommendation from a dedicated sub-package.

---

Jenkinsfile

https://coveord.atlassian.net/browse/KIT-703

ci: prevented CI from removing node_modules and husky

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/components/atomic-result-list-placeholder/atomic-result-list-placeholder.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.pcss
packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets-v1/facet-container/facet-container.tsx
packages/atomic/src/components/facets-v1/facet-header/facet-header.tsx
packages/atomic/src/components/facets-v1/facet-search-input/facet-search-input.tsx
packages/atomic/src/components/facets-v1/facet-show-less/facet-show-less.tsx
packages/atomic/src/components/facets-v1/facet-show-more/facet-show-more.tsx
packages/atomic/src/components/facets-v1/facet-value-box/facet-value-box.tsx
packages/atomic/src/components/facets-v1/facet-value-checkbox/facet-value-checkbox.tsx
packages/atomic/src/components/facets-v1/facet-value-link/facet-value-link.tsx
packages/atomic/src/components/facets-v1/facet-wrapper/facet-wrapper.tsx
packages/atomic/src/components/facets/atomic-facet-placeholder/atomic-facet-placeholder.tsx
packages/atomic/src/pages/v1.html

I create the new specific facet for v1 with only its building blocks, don't pay attention to the styling, props & interactivity in this PR. Follow PRs will build each blocks with more details.
https://coveord.atlassian.net/browse/KIT-698

feat(atomic): add facet v1 building blocks

---

packages/headless/package.json
packages/headless/product-recommendation/package.json
packages/headless/rollup.config.js
packages/headless/src/controllers/index.ts
packages/headless/src/features/index.ts
packages/headless/src/product-recommendation.index.ts

https://coveord.atlassian.net/browse/KIT-707

chore(headless): add product-recommendation sub-package

---

packages/atomic/src/components/atomic-facet-manager/atomic-facet-manager.tsx
packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/utils/initialization-utils.tsx

https://coveord.atlassian.net/browse/KIT-712
Also found a better way of updating the UI when the language changes

fix(atomic): re-render FacetManager's content when language changes

---

packages/atomic/stencil.config.ts
packages/headless/rollup.config.js

Quick fix for the dev build
https://coveord.atlassian.net/browse/KIT-731

fix(atomic,headless): add new packages to dev files being copied

---

packages/headless/src/app/product-recommendation-engine/product-recommendation-engine-configuration.ts
packages/headless/src/app/product-recommendation-engine/product-recommendation-engine.ts
packages/headless/src/app/recommendation-engine/recommendation-engine-configuration.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.ts
packages/headless/src/app/search-engine/search-engine-configuration.ts
packages/headless/src/app/search-engine/search-engine.ts

https://coveord.atlassian.net/browse/KIT-727

docs(headless): add missing tsdoc for new engine exports

---

.deployment.config.json

https://coveord.atlassian.net/browse/KIT-736
I made a mistake and the variable names in the Jenkinsfile aren't the same as those in the deployment config.

ci: changed MINOR and MAJOR variable names in deployment config

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-actions.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-assertions.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-selectors.ts
packages/atomic/cypress/integration/facets-v1/facet/facet.cypress.ts
packages/atomic/cypress/integration/search-box.cypress.ts
packages/atomic/cypress/utils/componentUtils.ts

https://coveord.atlassian.net/browse/KIT-725

test(atomic): second phase of cypress tests for facet v1 

---

packages/headless/contributors/migration-guide.md
packages/headless/src/api/platform-client.test.ts
packages/headless/src/api/platform-client.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-client.ts
packages/headless/src/api/service/case-assist/case-assist-api-client.ts
packages/headless/src/app/engine.test.ts
packages/headless/src/app/engine.ts
packages/headless/src/app/product-recommendation-engine/product-recommendation-engine.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.ts
packages/headless/src/app/search-engine/search-engine.ts
packages/headless/src/features/configuration/configuration-actions-loader.ts
packages/headless/src/features/configuration/configuration-actions.ts
packages/headless/src/features/configuration/configuration-slice.test.ts
packages/headless/src/features/configuration/configuration-slice.ts
packages/headless/src/test/mock-case-assist-api-client.ts
packages/headless/src/test/mock-engine.ts
packages/headless/src/test/mock-search-api-client.ts

https://coveord.atlassian.net/browse/KIT-735

chore(headless): remove renewAccessToken from public api

---

packages/headless/src/controllers/index.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.test.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.ts

https://coveord.atlassian.net/browse/KIT-740

chore: remove deprecated relevance inspector logic

---

packages/headless/src/api/platform-client.test.ts
packages/headless/src/api/platform-client.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-client.ts
packages/headless/src/api/service/case-assist/case-assist-api-client.ts
packages/headless/src/app/product-recommendation-engine/product-recommendation-engine.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.ts
packages/headless/src/app/search-engine/search-engine-configuration.ts
packages/headless/src/app/search-engine/search-engine.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.test.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.ts
packages/headless/src/test/mock-search-api-client.ts

https://coveord.atlassian.net/browse/KIT-741

chore: remove deprecated preprocess request middleware

---

packages/headless/contributors/migration-guide.md
packages/headless/src/api/platform-client.test.ts
packages/headless/src/api/platform-client.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-client.ts
packages/headless/src/api/service/case-assist/case-assist-api-client.ts
packages/headless/src/app/product-recommendation-engine/product-recommendation-engine.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.ts
packages/headless/src/app/search-engine/search-engine-configuration.ts
packages/headless/src/app/search-engine/search-engine.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.test.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.ts
packages/headless/src/controllers/search-box/headless-search-box.test.ts
packages/headless/src/controllers/search-box/headless-search-box.ts
packages/headless/src/features/query-suggest/query-suggest-actions.ts
packages/headless/src/features/query-suggest/query-suggest-slice.test.ts
packages/headless/src/features/query-suggest/query-suggest-slice.ts
packages/headless/src/test/mock-search-api-client.ts

https://coveord.atlassian.net/browse/KIT-739

chore: remove hideSuggestions from SearchBox controller

---

packages/atomic/cypress.json
packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-actions.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-assertions.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-selectors.ts
packages/atomic/cypress/integration/facets-v1/facet/facet.cypress.ts
packages/atomic/cypress/utils/setupComponent.ts
packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets-v1/facet-search/facet-search-matches.tsx

https://coveord.atlassian.net/browse/KIT-725

test(atomic): third phase of cypress tests for facet v1 

---

packages/headless/src/api/search/search/question-answering.ts
packages/headless/src/api/search/search/search-response.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/smart-snippet-questions-list/headless-smart-snippet-questions-list.ts
packages/headless/src/controllers/smart-snippet-suggestions/headless-smart-snippet-suggestions.ts
packages/headless/src/controllers/smart-snippet/headless-smart-snippet.ts
packages/headless/src/features/analytics/search-analytics-actions-loader.ts
packages/headless/src/features/question-answering/question-answering-analytics-actions.ts
packages/headless/src/features/search/search-state.ts
packages/headless/src/test/mock-search-response.ts

Essentially some boiler plate.
I've left TODOS everywhere, and I'll be filling in the blank in the next few days.
Follows the design doc I've shared with you all.
https://coveord.atlassian.net/browse/KIT-750

feat(headless): initial support for question answering

---

packages/headless/src/controllers/folded-result-list/headless.folded-result-list.test.ts
packages/headless/src/features/folding/folding-slice.test.ts
packages/headless/src/features/folding/folding-slice.ts

https://coveord.atlassian.net/browse/KIT-715

fix(headless): prevented folding loop & added tests

---

packages/atomic/cypress/integration/facets/category-facet/category-facet-search.cypress.ts
packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/headless/src/controllers/facets/facet-search/category/headless-category-facet-search.test.ts
packages/headless/src/controllers/facets/facet-search/specific/headless-facet-search.test.ts
packages/headless/src/controllers/facets/facet-search/specific/headless-facet-search.ts
packages/headless/src/controllers/facets/facet/headless-facet.test.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.test.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.ts
packages/headless/src/controllers/facets/range-facet/headless-range-facet.test.ts
packages/headless/src/controllers/facets/range-facet/headless-range-facet.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.test.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.test.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/facets/generic/facet-reducer-helpers.test.ts
packages/headless/src/features/facets/generic/facet-reducer-helpers.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-set-slice.test.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-set-slice.test.ts

Reworked the previous PR https://github.com/coveo/ui-kit/pull/895, this time, we don't have new actions, only new controller methods.
https://coveord.atlassian.net/browse/KIT-729

feat(headless): add single selection feature for facets

---

packages/headless/src/controllers/index.ts
packages/headless/src/features/analytics/search-analytics-actions-loader.ts

https://coveord.atlassian.net/browse/KIT-773

chore(headless): temp remove global exports for question answering

---

packages/headless/package-lock.json
packages/headless/package.json
packages/headless/rollup.config.js

https://coveord.atlassian.net/browse/KIT-775

chore: bundle correct coveo.analytics with headless for node

---

packages/headless/src/api/search/search/product-recommendation.ts
packages/headless/src/controllers/breadcrumb-manager/headless-breadcrumb-manager.ts
packages/headless/src/controllers/context/headless-context.ts
packages/headless/src/controllers/controller/headless-controller.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet-options.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.ts
packages/headless/src/controllers/product-recommendations/headless-cart-recommendations-options.ts
packages/headless/src/controllers/product-recommendations/headless-cart-recommendations.ts
packages/headless/src/features/facets/category-facet-set/interfaces/response.ts
packages/headless/src/features/facets/range-facets/date-facet-set/interfaces/response.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/interfaces/response.ts

Reviewed and updated the following controller strings:
- BreadcrumbManager
- CartRecommendationsList
- CategoryFacet
- Context
- DateFacet

docs(headless): updated jsdoc

---

.deployment.config.json
Jenkinsfile
lerna.json

https://coveord.atlassian.net/browse/KIT-787

ci: adjust release process for independent mode

---

packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-filter.test.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-filter.test.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-set-slice.test.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-reducers.test.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-set-slice.test.ts
packages/headless/src/features/pagination/pagination-slice.test.ts

https://coveord.atlassian.net/browse/KIT-780

test(headless): add tests for headless-numeric-filter/headless-date-filter

---

packages/atomic/src/components/atomic-query-error/atomic-query-error.tsx
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-794

feat(atomic): add specific error message for organization paused

---

packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets-v1/facet-header/facet-header.tsx
packages/atomic/src/components/facets-v1/facet-search/facet-search-matches.tsx
packages/atomic/src/components/facets-v1/facet-show-more-less/facet-show-more-less.tsx
packages/atomic/src/components/facets-v1/facet-value-box/facet-value-box.tsx
packages/atomic/src/components/facets-v1/facet-value-checkbox/facet-value-checkbox.tsx
packages/atomic/src/components/facets-v1/facet-value-link/facet-value-link.tsx
packages/atomic/src/global/global.pcss
packages/atomic/src/locales.json

I suggest looking at the ticket to understand wha the issues were
https://coveord.atlassian.net/browse/KIT-777

fix(atomic): various css improvements for facets v1

---

packages/atomic/src/components/atomic-modal/atomic-modal.tsx
packages/atomic/src/components/atomic-query-error/atomic-query-error.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/facets-v1/facet-header/facet-header.tsx
packages/atomic/src/components/facets-v1/facet-show-more-less/facet-show-more-less.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.pcss
packages/atomic/src/components/facets/base-facet/base-facet.pcss
packages/atomic/src/components/result-template-components/atomic-result-quickview/atomic-result-quickview.tsx
packages/atomic/src/pages/test.html
packages/atomic/src/pages/v1.html
packages/atomic/src/templates/default.html
packages/atomic/src/themes/accessible.css
packages/atomic/src/themes/coveo.css
packages/atomic/tailwind.config.js
packages/samples/atomic/index.html

Should we keep the default.css for v0 just so it doesn't return a 404 if some customers were using it previously and upgrade?
https://coveord.atlassian.net/browse/KIT-784

feat(atomic): theme changes

---

packages/headless/src/app/product-recommendation-engine/product-recommendation-engine.test.ts
packages/headless/src/app/product-recommendation-engine/product-recommendation-engine.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.test.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.ts
packages/headless/src/app/search-engine/search-engine.test.ts

https://coveord.atlassian.net/browse/KIT-801

fix(headless): update searchHub/pipeline from configuration for recommendation engines

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets-v1/facet-number-input/facet-number-input.tsx
packages/atomic/src/locales.json
packages/atomic/src/pages/v1.html
packages/atomic/src/utils/initialization-utils.spec.ts
packages/atomic/src/utils/initialization-utils.tsx
packages/atomic/tailwind.config.js
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-filter.test.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-filter.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-filter.test.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-filter.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-actions.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-actions.ts

https://coveord.atlassian.net/browse/KIT-751
When the range is not yet valid:
When the range is valid:
When the range is applied:

feat(atomic): add numeric facet custom input

---

packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.tsx

https://coveord.atlassian.net/browse/KIT-751

fix(atomic): fix atomic-numeric-facet-v1 render condition

---

packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/components/atomic-result-list-placeholder/atomic-result-list-placeholder.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/facets/atomic-facet-placeholder/atomic-facet-placeholder.tsx
packages/atomic/src/themes/accessible.css
packages/atomic/src/themes/coveo.css
packages/atomic/src/utils/utils.ts

https://coveord.atlassian.net/browse/KIT-754

feat(atomic): rework placeholders style

---

packages/atomic/cypress/integration/breadbrumb-manager.cypress.ts
packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/utils/initialization-utils.tsx
packages/headless/src/index.ts

https://coveord.atlassian.net/browse/KIT-766

feat(atomic): add facet format method to Atomic store

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets-v1/atomic-timeframe-facet/atomic-timeframe-facet.pcss
packages/atomic/src/components/facets-v1/atomic-timeframe-facet/atomic-timeframe-facet.tsx
packages/atomic/src/locales.json
packages/atomic/src/pages/v1.html

https://coveord.atlassian.net/browse/KIT-804
Can't play with it yet, only the initial setup next will be:
- The configurable ranges (refer to design doc for details)
- The custom date picker

chore(atomic): create new timespan facet component skeleton

---

packages/atomic/src/components/facets-v1/atomic-rating-facet/atomic-rating-facet.pcss
packages/atomic/src/components/facets-v1/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-812
only skeleton for now, afterwards will work on adding the stars.

feat(atomic): skeleton for Atomic-Rating-Facet

---

packages/headless/contributors/adding-a-controller.md
packages/headless/doc-parser/use-cases/search.ts

https://coveord.atlassian.net/browse/KIT-816

docs(headless): extract trigger reference documentation

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets-v1/facet-common.ts
packages/atomic/src/components/facets-v1/facet-number-input/facet-number-input.tsx
packages/atomic/src/components/facets-v1/facet-number-input/number-input-type.ts
packages/atomic/src/locales.json
packages/atomic/src/pages/v1.html
packages/atomic/tailwind.config.js

https://coveord.atlassian.net/browse/KIT-808
Issues fixed:
- remove withRange prop (numberOfValues should be set to 0 instead)
- conditionally create facet controller (when there is only an input, but no facet)
- should hide whole facet when there are no results and no selected values
- allow input of negative values directly without using arrows
- leverage input type number validation
- leverage with-input prop to allow input integer vs decimal values
- add parts
- replace onApply prop with event

fix(atomic): various numeric facet v1 fixes & improvements

---

packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.html
packages/quantic/force-app/main/default/lwc/jsconfig.json
packages/quantic/force-app/main/default/lwc/quanticDidYouMean/quanticDidYouMean.css
packages/quantic/force-app/main/default/lwc/quanticDidYouMean/quanticDidYouMean.html
packages/quantic/force-app/main/default/lwc/quanticDidYouMean/quanticDidYouMean.js
packages/quantic/force-app/main/default/lwc/quanticDidYouMean/quanticDidYouMean.js-meta.xml
packages/quantic/force-app/main/default/lwc/quanticSearchBox/quanticSearchBox.js

[SFINT-3956](https://coveord.atlassian.net/browse/SFINT-3956) Implement Quantic DidYouMean component
The `quantic-did-you-mean` component is responsible for handling query corrections.
**Corrected automatically**
**Corrected manually**

feat(quantic): SFINT-3956 Quantic didYouMean component

---

packages/headless/src/api/search/search-api-client.test.ts

I adjusted the tests in this file to no longer throw errors. This is in preparation to move the ui-kit project to node 16.
The tests were throwing either because a mock function was returning `undefined`, or because `.json` was being called multiple times on the same `Response` object.
https://coveord.atlassian.net/browse/KIT-827

chore: adjust search-api-client tests to not throw errors

---

packages/headless/doc-parser/use-cases/search.ts
packages/headless/src/features/folding/folding-actions-loader.ts
packages/headless/src/features/folding/folding-actions.ts
packages/headless/src/features/index.ts
packages/headless/src/features/question-answering/question-answering-actions-loader.ts

https://coveord.atlassian.net/browse/KIT-830

feat(headless): export action loaders

---

packages/headless/src/controllers/facets/range-facet/date-facet/date-range.test.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-filter.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-actions.test.ts
packages/headless/src/features/facets/range-facets/date-facet-set/interfaces/request.ts
packages/headless/src/features/facets/range-facets/date-facet-set/interfaces/response.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.test.ts
packages/headless/src/features/search/search-mappings.test.ts
packages/headless/src/test/mock-search-request.ts

https://coveord.atlassian.net/browse/KIT-819

feat(headless): relative date additional tests & docs

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets-v1/atomic-color-facet/atomic-color-facet.pcss
packages/atomic/src/components/facets-v1/atomic-color-facet/atomic-color-facet.tsx

https://coveord.atlassian.net/browse/KIT-838

feat(atomic): atomic Color Facet skeleton

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/facets-v1/facet/facet.cypress.ts
packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets-v1/atomic-timeframe-facet/atomic-timeframe-facet.tsx
packages/atomic/src/pages/index.html
packages/atomic/src/pages/v1.html
packages/atomic/src/utils/field-utils.ts
packages/headless/src/api/search/facet-search/category-facet-search/category-facet-search-request.test.ts
packages/headless/src/api/search/facet-search/specific-facet-search/specific-facet-search-request.test.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search/search-request.test.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/facets/facet-search/facet-search.test.ts
packages/headless/src/controllers/facets/facet-search/facet-search.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/features/facets/facet-search-set/category/category-facet-search-request-builder.ts
packages/headless/src/features/facets/facet-search-set/generic/generic-facet-search-actions.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-request-builder.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/features/search/search-mappings.ts
packages/samples/atomic/index.html

https://coveord.atlassian.net/browse/KIT-840

feat(atomic): support Facet Value Captions

---

packages/headless/doc-parser/use-cases/search.ts
packages/samples/headless-react/src/components/date-facet/date-facet.class.tsx
packages/samples/headless-react/src/components/date-facet/date-facet.fn.tsx
packages/samples/headless-react/src/components/numeric-facet/numeric-facet.class.tsx
packages/samples/headless-react/src/components/numeric-facet/numeric-facet.fn.tsx
packages/samples/headless-react/src/components/relative-date-facet/relative-date-facet.class.tsx
packages/samples/headless-react/src/components/relative-date-facet/relative-date-facet.fn.tsx
packages/samples/headless-react/src/components/relative-date-facet/relative-date-utils.ts
packages/samples/headless-react/src/pages/SearchPage.tsx

https://coveord.atlassian.net/browse/KIT-843

doc(headless): add relative date facet to samples

---

Jenkinsfile
packages/atomic/package-lock.json
packages/atomic/package.json
packages/bueno/package-lock.json
packages/bueno/package.json
packages/headless/package-lock.json
packages/headless/package.json
packages/quantic/package-lock.json
packages/quantic/package.json
packages/samples/atomic/package-lock.json
packages/samples/atomic/package.json
packages/samples/headless-react/package-lock.json
packages/samples/headless-react/package.json

https://coveord.atlassian.net/browse/KIT-863

ci: made version bump commits skip lockLernaDependencies

---

packages/bueno/package.json
packages/samples/atomic/package.json

https://coveord.atlassian.net/browse/KIT-864

ci: fixed package versions

---

packages/atomic/cypress/integration/facets-v1/facet/facet-actions.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-assertions.ts
packages/atomic/cypress/integration/facets-v1/facet/facet.cypress.ts

Clean up cypress test for facet v1
- Reuse all common shared assertions & actions _ which were created while doing cypress test for numeric facet v1
https://coveord.atlassian.net/browse/KIT-857

test(atomic): Clean up cypress test for facet v1

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets-v1/atomic-category-facet/atomic-category-facet.pcss
packages/atomic/src/components/facets-v1/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/pages/v1.html

https://coveord.atlassian.net/browse/KIT-842

feat(atomic): add category facet v1 skeleton

---

packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-858

doc(atomic): add docs folder to package.json files

---

packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.js
packages/quantic/force-app/main/default/lwc/quanticSearchInterface/quanticSearchInterface.js

Added urlManager to searchInterface component.

feat(quantic): added url manager to searchinterface

---

packages/atomic/src/components/facets-v1/atomic-category-facet/atomic-category-facet.pcss
packages/atomic/src/components/facets-v1/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets-v1/category-facet-search-result/category-facet-search-result.pcss
packages/atomic/src/components/facets-v1/category-facet-search-result/category-facet-search-result.tsx
packages/atomic/src/components/facets-v1/facet-common.ts
packages/atomic/src/components/facets-v1/facet-value-icon-rating/facet-value-icon-rating.tsx
packages/atomic/src/components/facets-v1/facet-value-label-highlight/facet-value-label-highlight.tsx

https://coveord.atlassian.net/browse/KIT-842

feat(atomic): add Category Facet Search Results

---

packages/headless/src/test/mock-engine.ts

Running unit tests was throwing errors in the console because analytics actions are being dispatched. I am not sure why I did not see the errors earlier, hmm.
```
...
customData: {
query: '',
aq: '',
cq: '',
dq: '',
errorType: 'NoAuthenticationException',
errorMessage: 'You must provide credentials to perform this operation'
},
facetState: [],
eventType: 'errors',
eventValue: 'query'
}
at AnalyticsFetchClient.<anonymous> (node_modules/coveo.analytics/dist/library.js:2046:33)
at step (node_modules/coveo.analytics/dist/library.js:172:27)
at Object.next (node_modules/coveo.analytics/dist/library.js:153:57)
at fulfilled (node_modules/coveo.analytics/dist/library.js:143:62)
```
This PR disables analytics when creating a mock engine.
https://coveord.atlassian.net/browse/KIT-869

chore: disable analytics when instantiating a mock engine

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/result-template-components/atomic-result-badge/atomic-result-badge.pcss
packages/atomic/src/components/result-template-components/atomic-result-badge/atomic-result-badge.tsx
packages/atomic/src/components/result-template-components/atomic-result-icon/atomic-result-icon.pcss
packages/atomic/src/components/result-template-components/atomic-result-icon/atomic-result-icon.tsx
packages/atomic/src/pages/v1.html

https://coveord.atlassian.net/browse/KIT-841

feat(atomic): added badges

---

packages/atomic/src/components/facets-v1/facet-date-input/facet-date-input.tsx
packages/atomic/src/components/facets-v1/facet-header/facet-header.tsx
packages/atomic/src/components/facets-v1/facet-number-input/facet-number-input.tsx
packages/atomic/src/components/facets-v1/facet-search/facet-search-input.tsx
packages/atomic/src/components/facets-v1/facet-search/facet-search.pcss
packages/atomic/src/components/facets-v1/facet-show-more-less/facet-show-more-less.tsx
packages/atomic/src/global/global.pcss
packages/atomic/src/themes/accessible.css
packages/atomic/src/themes/coveo.css
packages/atomic/tailwind.config.js
packages/headless/src/features/search/search-mappings.test.ts

https://coveord.atlassian.net/browse/KIT-880

feat(atomic): add outline color & ring color

---

packages/atomic/src/components/result-template-components-v1/atomic-result-icon/atomic-result-icon.tsx

https://coveord.atlassian.net/browse/KIT-882

fix(atomic): fixed new assets directory being created on each build

---

packages/atomic/cypress/integration/facets-v1/numeric-facet/numeric-facet.cypress.ts

https://coveord.atlassian.net/browse/KIT-889

ci(cypress): skip failing cypress test

---

packages/atomic/cypress.json
packages/atomic/cypress/integration/facets-v1/numeric-facet/numeric-facet-actions.ts
packages/atomic/cypress/integration/facets-v1/numeric-facet/numeric-facet-assertions.ts
packages/atomic/cypress/integration/facets-v1/numeric-facet/numeric-facet.cypress.ts
packages/atomic/package-lock.json
packages/atomic/package.json
packages/bueno/package-lock.json
packages/headless/package-lock.json
packages/quantic/package-lock.json
packages/samples/atomic/package-lock.json
packages/samples/headless-react/package-lock.json

https://coveord.atlassian.net/browse/KIT-834
- Test cover for atomic-format-number, atomic-format-currency and atomic-format-unit

test(atomic): Add Cypress test for atomicFormat value component

---

packages/atomic/cypress/integration/search-engine.cypress.ts
packages/atomic/package.json
packages/headless/src/app/search-engine/search-engine.ts
packages/headless/src/test/mock-engine.ts
packages/samples/headless-react/src/pages/SearchPage.tsx

https://coveord.atlassian.net/browse/KIT-870

feat(headless): add method for first search after standalone redirect

---

packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-888

fix(atomic): increase memory for building atomic

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.pcss

https://coveord.atlassian.net/browse/KIT-898

feat(atomic): added padding to table result list

---

packages/atomic/src/components/result-template-components-v1/atomic-result-fields-list/atomic-result-fields-list.tsx

Tiny string review for [DOC-9558](https://coveord.atlassian.net/browse/DOC-9568)
Sorry I didn't catch this in [the PR](https://github.com/coveo/ui-kit/pull/1073) @btaillon , slight confusion because Danny is on vacation.

doc(atomic): result field list string review

---

packages/atomic/cypress/integration/breadbrumb-manager.cypress.ts
packages/atomic/cypress/integration/no-results-v1.cypress.ts

https://coveord.atlassian.net/browse/KIT-887

test(atomic): no-results-v1 cypress test

---

packages/atomic/src/components/atomic-result-v1/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-row-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-row-mobile.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result.pcss
packages/atomic/src/global/global.pcss
packages/atomic/src/global/polyfills.pcss

https://coveord.atlassian.net/browse/KIT-897

feat(atomic): limited height of excerpt section

---

packages/atomic/tailwind.config.js

https://coveord.atlassian.net/browse/KIT-896

fix(atomic): made desktop and mobile @screen directives mutually exclusive

---

packages/atomic/src/pages/v1.html

https://coveord.atlassian.net/browse/KIT-915

fix(atomic): fix v1.html

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list-cards.pcss
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list-dividers.pcss
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.pcss
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.tsx
packages/atomic/src/components/atomic-result-placeholder-v1/atomic-result-placeholder.pcss
packages/atomic/src/components/atomic-result-placeholder-v1/atomic-result-placeholder.tsx
packages/atomic/src/components/atomic-result-v1/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-display-options.ts
packages/atomic/src/components/atomic-result-v1/atomic-result-row-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-row-mobile.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result.tsx

https://coveord.atlassian.net/browse/KIT-768
Can be tested on multiple layouts & compared with results here: https://kit-768.herokuapp.com/

feat(atomic): added placeholder for v1 list and grid results

---

packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.js
packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.js
packages/quantic/force-app/main/default/lwc/quanticDidYouMean/quanticDidYouMean.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
packages/quantic/force-app/main/default/lwc/quanticHeadlessLoader/quanticHeadlessLoader.js
packages/quantic/force-app/main/default/lwc/quanticNoResults/quanticNoResults.js
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js
packages/quantic/force-app/main/default/lwc/quanticPager/quanticPager.js
packages/quantic/force-app/main/default/lwc/quanticQueryError/quanticQueryError.js
packages/quantic/force-app/main/default/lwc/quanticResultList/quanticResultList.js
packages/quantic/force-app/main/default/lwc/quanticResultsPerPage/quanticResultsPerPage.js
packages/quantic/force-app/main/default/lwc/quanticSearchBox/quanticSearchBox.js
packages/quantic/force-app/main/default/lwc/quanticSearchInterface/quanticSearchInterface.js
packages/quantic/force-app/main/default/lwc/quanticSort/quanticSort.js
packages/quantic/force-app/main/default/lwc/quanticSummary/quanticSummary.js

Just cleanup up in a couple places.

feat(quantic): added optional chaining

---

packages/atomic/src/components/atomic-icon/atomic-icon.pcss
packages/atomic/src/components/atomic-rating/atomic-rating.tsx
packages/atomic/src/components/result-template-components/atomic-result-quickview/atomic-result-quickview.tsx
packages/atomic/src/pages/v1.html

https://coveord.atlassian.net/browse/KIT-916

fix(atomic): fixed atomic-icon for Safari

---

packages/atomic/src/components/atomic-result-v1/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-row-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-row-mobile.pcss
packages/atomic/src/themes/accessible.css
packages/atomic/src/themes/coveo.css

https://coveord.atlassian.net/browse/KIT-786

feat(atomic): made result font sizes personalize-able with CSS variables

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.pcss
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.tsx
packages/atomic/src/components/atomic-result-list-v1/atomic-result-table.pcss
packages/atomic/src/components/atomic-result-placeholder-v1/atomic-result-placeholder.tsx
packages/atomic/src/components/atomic-result-table-placeholder/atomic-result-table-placeholder.pcss
packages/atomic/src/components/atomic-result-table-placeholder/atomic-result-table-placeholder.tsx

https://coveord.atlassian.net/browse/KIT-912
Can be tested [here](http://kit-912.herokuapp.com/) by changing the values of the comboboxes at the top left corner of the screen.

feat(atomic): added placeholder for table result list

---

packages/headless/src/features/recent-queries/recent-queries-analytics-actions.ts
packages/headless/src/features/recent-queries/recent-queries-slice.test.ts
packages/headless/src/features/recent-queries/recent-queries-slice.ts

fix(headless): corrected actions mismatch and slice list

---

packages/quantic/force-app/main/default/labels/CustomLabels.labels-meta.xml
packages/quantic/force-app/main/translations/fr.translation-meta.xml

Issue: https://coveord.atlassian.net/browse/SFINT-4032
String review for [SFINT-3987](https://coveord.atlassian.net/browse/SFINT-3987)

[SFINT-4032] string review for sfint-3987

---

packages/atomic/src/utils/ripple.ts

https://coveord.atlassian.net/browse/KIT-944

fix(atomic): cleanup ripple when animation finishes

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.tsx

https://coveord.atlassian.net/browse/KIT-969

fix(atomic): add check before removing result list placeholder

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.tsx

https://coveord.atlassian.net/browse/KIT-970

fix(atomic): fixed condition to show loading animation

---

packages/headless/src/features/advanced-search-queries/advanced-search-queries-slice.test.ts
packages/headless/src/features/advanced-search-queries/advanced-search-queries-state.ts
packages/headless/src/features/search-parameters/search-parameter-schema.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.ts

The recent `lq` contribution did not run on jenkins CI. It contained lint errors which broken the build on the master branch.
This PR fixes the errors. I've also started [a thread](https://coveo.slack.com/archives/CBP3GTFTQ/p1630510105065500) with the Dev Tooling team to see how we can improve our workflow with external contributors.
https://coveord.atlassian.net/browse/KIT-978

chore(headless): lint recent files

---

packages/atomic/src/components/atomic-breadbox/atomic-breadbox.tsx

https://coveord.atlassian.net/browse/KIT-955

fix(atomic): fix breadcrumb alignment to baseline

---

packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js

Specifying the facetId seems to fix the issue caused by navigating between "pages" of a single-page community. 
- Added facetId as prop 
- Set facetId to field by default

fix(quantic): added facetid

---

packages/atomic/cypress/integration/facets-v1/facet-common-assertions.ts
packages/atomic/cypress/integration/facets-v1/timeframe-facet/timeframe-facet-action.ts
packages/atomic/cypress/integration/facets-v1/timeframe-facet/timeframe-facet-assertions.ts
packages/atomic/cypress/integration/facets-v1/timeframe-facet/timeframe-facet-selectors.ts
packages/atomic/cypress/integration/facets-v1/timeframe-facet/timeframe-facet.cypress.ts

- Add Cypress test for timeframe facet
- Add 2 TODO to enable test for accessibility & option period="next" once the issues are fixed

test(atomic): add cypress test for timeframe facet

---

packages/atomic/src/components/atomic-search-box-v1/atomic-search-box.tsx
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-851

feat(atomic): add search-box v1 interactivity + accessibility

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-box-v1/atomic-search-box.pcss
packages/atomic/src/components/atomic-search-box-v1/atomic-search-box.tsx
packages/atomic/src/global/global.pcss
packages/atomic/src/locales.json
packages/atomic/src/pages/v1.html
packages/atomic/src/themes/accessible.css
packages/atomic/src/themes/coveo.css
packages/atomic/tailwind.config.js

Combo of this PR as well https://github.com/coveo/ui-kit/pull/1186
https://coveord.atlassian.net/browse/KIT-851

feat(atomic): add search-box v1

---

.github/workflows/merge-bot.yml
.github/workflows/prbot.yml

https://coveord.atlassian.net/browse/KIT-1004

chore(all): create merge-bot.yml

---

packages/atomic/cypress/integration/no-results.cypress.ts
packages/atomic/src/components/atomic-no-results/atomic-no-results.tsx
packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/controllers/history-manager/headless-history-manager.test.ts
packages/headless/src/controllers/history-manager/headless-history-manager.ts
packages/headless/src/features/analytics/search-analytics-actions-loader.ts
packages/headless/src/features/history/history-analytics-actions.ts

https://coveord.atlassian.net/browse/KIT-904

fix(headless): fix no results back analytics event

---

packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-actions.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-badges.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-bottom-metadata.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-emphasized.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-excerpt.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-title-metadata.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-title.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-visual.tsx

Recreated PR to apply string edits to result section components.

doc(atomic):string edits for result sections

---

packages/atomic/cypress/integration/facets/rating-facet/rating-facet-actions.ts
packages/atomic/cypress/integration/facets/rating-facet/rating-facet-assertions.ts
packages/atomic/cypress/integration/facets/rating-facet/rating-facet-selectors.ts
packages/atomic/cypress/integration/facets/rating-facet/rating-facet.cypress.ts
packages/atomic/cypress/integration/facets/rating-range-facet/rating-range-facet-actions.ts
packages/atomic/cypress/integration/facets/rating-range-facet/rating-range-facet-assertions.ts
packages/atomic/cypress/integration/facets/rating-range-facet/rating-range-facet-selectors.ts
packages/atomic/cypress/integration/facets/rating-range-facet/rating-range-facet.cypress.ts

Add Cypress test for Rating & Rating Range Facet
- Issue : Accessibility issue for Rating Facet (display as checkbox) when 1 facetValue is selected, so test is commented out for now

test(atomic) Cypress test for Rating & Rating Range Facet

---

packages/atomic/src/components/atomic-no-results/atomic-no-results.tsx
packages/atomic/src/images/magnifying-glass.svg

https://coveord.atlassian.net/browse/KIT-945

fix(atomic): make magnifying glass fluid width on no results

---

packages/atomic/src/components/result-template-components/atomic-result-link/atomic-result-link.pcss

https://coveord.atlassian.net/browse/KIT-1008

fix(atomic): change hover and visited state for links

---

packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx

https://coveord.atlassian.net/browse/KIT-1009

fix(atomic): change numeric and timeframe facet to put input at the bottom

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/components/atomic-refine-toggle/atomic-refine-toggle.tsx
packages/atomic/tailwind.config.js

Shared screen recording/movie in slack.
https://coveord.atlassian.net/browse/KIT-1010

fix(atomic): add animation on refine modal

---

packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/images/sort.svg

https://coveord.atlassian.net/browse/KIT-951

fix(atomic): set width on refine modal sort icon

---

packages/atomic/src/components/facets/facet-header/facet-header.tsx

https://coveord.atlassian.net/browse/KIT-1015

fix(atomic): facet header should not be rounded

---

packages/atomic/src/components/atomic-result/atomic-result-row-desktop.pcss

https://coveord.atlassian.net/browse/KIT-1017
Before:
After:

fix(atomic): reduce result template visual section potential height

---

packages/atomic/src/global/global.pcss

https://coveord.atlassian.net/browse/KIT-1016

fix(atomic): breadbox has wrong rounded class

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/components/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx

It appears to me they have some usefulness, but it can be argued against, let me know what you think.
https://coveord.atlassian.net/browse/KIT-865

feat(atomic): add delimitingCharacter, filterFacetCount & injectionDepth options to facets

---

packages/quantic/force-app/main/default/lwc/quanticNumberButton/quanticNumberButton.js

Pretty straight forward. It now looks like the mockups

fix(quantic): inverse button color

---

packages/headless/src/utils/validate-payload.test.ts
packages/headless/src/utils/validate-payload.ts

If you look at the JIRA ticket, you should see an example of the original problem.
https://coveord.atlassian.net/browse/KIT-386

fix(headless): validate action that receives a payload that is not an object

---

Jenkinsfile

https://coveord.atlassian.net/browse/KIT-1018

ci: change version of bump stage to node 16

---

scripts/deploy/bump-version.js

https://coveord.atlassian.net/browse/KIT-1018

ci: made version bumps set their local git config

---

packages/headless/src/app/product-listing-engine/product-listing-engine-configuration.ts
packages/headless/src/app/product-listing-engine/product-listing-engine.ts
packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet-options.ts
packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet.test.ts
packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet.ts
packages/headless/src/controllers/core/facets/facet-search/category/headless-category-facet-search.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet.test.ts
packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.ts
packages/headless/src/controllers/product-listing/headless-product-listing.ts
packages/headless/src/controllers/product-listing/sort/headless-product-listing-sort.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/product-listing/product-listing-actions.ts
packages/headless/src/product-listing.index.ts
packages/headless/src/state/product-listing-app-state.ts
packages/headless/src/test/mock-product-listing-state.ts

[COM-1202]
Basically the same job that was done for facets, sorts, and pager.
[COM-1202]: https://coveord.atlassian.net/browse/COM-1202

feat(core): split category facet into core

---

packages/atomic/src/components/atomic-result-placeholder/atomic-result-placeholder.tsx

https://coveord.atlassian.net/browse/KIT-1020

fix(atomic): display result placeholders by adding with-sections

---

Jenkinsfile

https://coveord.atlassian.net/browse/KIT-1018

ci: lowered version of npm publish

---

packages/atomic/src/components/atomic-breadbox/atomic-breadbox.tsx
packages/atomic/tailwind.config.js

https://coveord.atlassian.net/browse/KIT-924

feat(atomic): automatically adapt the number of element of the breadbox

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search/search-response.ts
packages/headless/src/app/recommendation-engine/recommendation-engine-configuration.ts
packages/headless/src/app/search-engine/search-engine-configuration.ts
packages/headless/src/features/pipeline/pipeline-state.ts
packages/headless/src/features/search/search-state.ts
packages/headless/src/test/mock-search-response.ts

As explained in our daily scrum !
https://coveord.atlassian.net/browse/KIT-1033

fix(headless): rework default pipeline parameter

---

packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/components/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx
packages/atomic/src/locales.json
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-995

fix(atomic): add timeframe future locales & allow timeframes in refine modal

---

packages/headless/src/features/pagination/pagination-selectors.test.ts
packages/headless/src/features/pagination/pagination-slice.ts

https://coveord.atlassian.net/browse/KIT-1034

feat(atomic): set maximumNumberOfResultsFromIndex to 5000

---

packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-facet.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-filter.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-facet.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-filter.ts

[COM-1296]
A product-listing-wide change that was suggested.
I also noticed some bad imports, so I changed them all
[COM-1296]: https://coveord.atlassian.net/browse/COM-1296

feat(productlisting): send analytics after fetch

---

packages/headless/src/controllers/core/results-per-page/headless-core-results-per-page.test.ts
packages/headless/src/controllers/core/results-per-page/headless-core-results-per-page.ts
packages/headless/src/controllers/product-listing/results-per-page/headless-product-listing-results-per-page.test.ts
packages/headless/src/controllers/product-listing/results-per-page/headless-product-listing-results-per-page.ts
packages/headless/src/controllers/results-per-page/headless-results-per-page.ts

Similar to the other controllers

feat(core): split results-per-page into core

---

packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js
packages/quantic/force-app/main/default/lwc/quanticPager/quanticPager.js
packages/quantic/force-app/main/default/lwc/quanticResultsPerPage/quanticResultsPerPage.html
packages/quantic/force-app/main/default/lwc/quanticResultsPerPage/quanticResultsPerPage.js
packages/quantic/force-app/main/default/lwc/quanticTab/quanticTab.js
packages/quantic/force-app/main/default/lwc/quanticUtils/quanticUtils.js

Added the following options:
- QuanticPager
- numberOfPages
- QuanticResultsPerPage
- choicesDisplayed
- initialChoice
- QuanticTab
- initAsActive

feat(quantic): added some missing component options

---

packages/atomic/cypress/integration/facets/rating-facet/rating-facet.cypress.ts

Was fixed previously
https://coveord.atlassian.net/browse/KIT-1005

test(atomic): enabled skipped rating facet test

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1023

fix(atomic): add search box input default vertical padding

---

packages/headless/doc-parser/use-cases/search.ts
packages/headless/src/controllers/index.ts
packages/headless/src/features/context/context-actions-loader.ts
packages/headless/src/features/dictionary-field-context/dictionary-field-context-actions-loader.ts
packages/headless/src/features/index.ts
packages/samples/headless-react/src/components/context/context.ts
packages/samples/headless-react/src/components/dictionary-field-context/dictionary-field-context.fn.ts
packages/samples/headless-react/src/pages/SearchPage.tsx

https://coveord.atlassian.net/browse/KIT-354

feat(headless): document DictionaryFieldContext

---

packages/atomic/cypress/integration/result-list/result-components/result-link.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-number.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-text.cypress.ts
packages/atomic/src/components/result-template-components/result-template-decorators.tsx

https://coveord.atlassian.net/browse/KIT-1060

fix(atomic): result template components should be removed from DOM on error

---

packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.css
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacetStyles/quanticFacetStyles.css
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.css
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.html
packages/quantic/force-app/main/default/lwc/quanticRecentQueriesList/quanticRecentQueriesList.html
packages/quantic/force-app/main/default/lwc/quanticRecentResultsList/quanticRecentResultsList.html

fix(quantic): fixed clear filter button alignment

---

packages/headless/doc-parser/use-cases/product-recommendation.ts
packages/headless/doc-parser/use-cases/recommendation.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts
packages/headless/src/features/recommendation/recommendation-actions.ts
packages/headless/src/product-recommendation.index.ts
packages/headless/src/recommendation.index.ts
packages/headless/src/state/product-recommendations-app-state.ts
packages/headless/src/state/recommendation-app-state.ts
packages/headless/src/test/mock-product-recommendations-state.ts
packages/headless/src/test/mock-recommendation-state.ts

https://coveord.atlassian.net/browse/KIT-1065

feat(headless): support dictionaryFieldContext on recommendation and product-recommendation

---

packages/atomic/cypress/integration/result-list/result-components/result-fields-list.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-fields-list.selector.ts
packages/atomic/src/components/result-template-components/atomic-result-fields-list/atomic-result-fields-list.tsx

https://coveord.atlassian.net/browse/KIT-964

test(atomic): add cypress tests result-fields-list

---

packages/atomic/src/components/atomic-result/atomic-result-row-desktop.pcss

https://coveord.atlassian.net/browse/KIT-1041

fix(atomic): fix atomic-result-section-badges height in comfortable mode

---

packages/headless/src/features/sort-criteria/criteria-parser.test.ts
packages/headless/src/features/sort-criteria/criteria-parser.ts

https://coveord.atlassian.net/browse/KIT-1072

fix(headless): improve sort criterion error messages

---

packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx

https://coveord.atlassian.net/browse/KIT-1139

fix(atomic): register filters to store when ranges are not defined (numeric & timeframe facets)

---

packages/atomic/src/components/atomic-result-list/atomic-result-list-cards.pcss
packages/atomic/src/components/atomic-result-list/atomic-result-list-dividers.pcss
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1154

fix(atomic): re-added divider in large grid on mobile

---

packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-1100

doc(atomic): mention filters in search tips (atomic-no-results)

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/headless/src/api/search/facet-search/base/base-facet-search-request.ts
packages/headless/src/api/search/facet-search/category-facet-search/category-facet-search-request.ts
packages/headless/src/api/search/facet-search/specific-facet-search/specific-facet-search-request.test.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/controllers/core/facets/facet/headless-core-facet-options.ts
packages/headless/src/controllers/facets/facet/headless-facet-options.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-request-builder.ts
packages/headless/src/features/facets/facet-set/facet-set-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts

https://coveord.atlassian.net/browse/KIT-1095

chore(atomic,headless): remove & deprecate delimitingCharacter on specific facets

---

packages/atomic/src/components/atomic-breadbox/atomic-breadbox.tsx

https://coveord.atlassian.net/browse/KIT-1125

fix(atomic): hide breadbox "Show less" when on first row

---

packages/quantic/force-app/main/default/lwc/quanticSearchBox/quanticSearchBox.js
packages/quantic/force-app/main/default/lwc/quanticStandaloneSearchBox/quanticStandaloneSearchBox.js

Casting number props in searchboxes otherwise it crashes when set directly in markup.

fix(quantic): wrap number props

---

JenkinsfileProductionRelease
JenkinsfileQARelease
packages/atomic/package-lock.json
packages/bueno/package-lock.json
packages/headless/package-lock.json
packages/quantic/package-lock.json
packages/samples/atomic/package-lock.json
packages/samples/headless-react/package-lock.json

https://coveord.atlassian.net/browse/KIT-1170
I also ran a `npm run setup` for good measures

fix(ci): update production and qa docker containers 

---

.deployment.config.json
packages/atomic/.eslintrc.json
packages/atomic/.storybook/default-story.tsx
packages/atomic/.storybook/main.js
packages/atomic/package.json

This will be needed by @npushkarskii   to integrate into the documentation website.
https://coveord.atlassian.net/browse/KIT-1181

docs(atomic): deploy storybook static folder to s3 / CDN

---

packages/atomic/cypress/integration/result-list/result-components/result-image-selectors.ts
packages/atomic/cypress/integration/result-list/result-components/result-printable-uri-selector.ts
packages/atomic/cypress/integration/result-list/result-components/result-printable-uri.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-text-selectors.ts
packages/atomic/cypress/integration/result-list/result-components/result-text.cypress.ts
packages/atomic/src/components/result-link/result-link.tsx
packages/atomic/src/components/result-template-components/atomic-result-image/atomic-result-image.tsx
packages/atomic/src/components/result-template-components/atomic-result-link/atomic-result-link.tsx
packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.tsx
packages/atomic/src/components/result-template-components/atomic-result-text/atomic-result-text.tsx

https://coveord.atlassian.net/browse/KIT-1175

chore(atomic): remove parts from components without shadow dom

---

packages/atomic/src/components/atomic-result/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result/atomic-result-row-desktop.pcss
packages/atomic/src/components/atomic-result/atomic-result-row-mobile.pcss
packages/atomic/src/components/atomic-result/atomic-result-with-sections.pcss
packages/atomic/src/components/result-template-components/atomic-result-badge/atomic-result-badge.pcss
packages/atomic/src/components/result-template-components/atomic-result-badge/atomic-result-badge.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-actions.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-badges.tsx
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-983
The badges section is now a flexbox.

fix(atomic): made badges wrap on small screens

---

packages/atomic/.storybook/default-result-component-story.tsx
packages/atomic/.storybook/default-story-shared.tsx
packages/atomic/.storybook/map-result-list-props-to-args.ts

Allows to select result density, display mode, layout.
https://coveord.atlassian.net/browse/KIT-1178

docs(atomic): support for result list attributes in result components

---

packages/atomic/src/components/result-template-components/atomic-result-multi-value-text/atomic-result-multi-value-text.tsx

https://coveord.atlassian.net/browse/KIT-1184

docs(atomic): improved doc for result-multi-value-text-value-* slot

---

packages/atomic/cypress/integration/facets/manager/facet-manager-actions.ts
packages/atomic/cypress/integration/facets/manager/facet-manager-assertions.ts
packages/atomic/cypress/integration/facets/manager/facet-manager.cypress.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet-action.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-facet-manager/atomic-facet-manager.tsx

https://coveord.atlassian.net/browse/KIT-1012

feat(atomic): dynamically collapse facets in facet manager

---

JenkinsfileProductionRelease

https://coveord.atlassian.net/browse/KIT-1171

fix(ci): change invalidate-cloudfront.js path

---

packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.html
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js

Removed the onchange handlers causing the issue by setting the value of the input. IIRC I had put those in when fiddling with the input validations. They don't appear to be necessary and removing them fixes the issue.

fix(quantic): removed onchange handlers causing error

---

packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.css
packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.html
packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.css
packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.html
packages/quantic/force-app/main/default/lwc/quanticFacetValue/quanticFacetValue.css
packages/quantic/force-app/main/default/lwc/quanticFacetValue/quanticFacetValue.html

Demo link to validate alignment: https://sandbox-ability-enterprise-8364-dev--17d05ee4b87.cs10.force.com/examples/s/full-search-example#tab=All

feat(quantic): fixed facet count alignment

---

packages/atomic/.storybook/default-story-shared.tsx
packages/atomic/package-lock.json
packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-1196

fix(atomic): fix storybook build for windows user

---

scripts/deploy/invalidate-cloudfront.js

https://coveord.atlassian.net/browse/KIT-1171

fix(ci): update invalidate-cloudfront.js path quantity

---

.github/workflows/create-quantic-package.yml
packages/quantic/README.md
packages/quantic/sfdx-project.json

Updated the readme and the sfdx-project definition file with v1 package id

chore(quantic): update readme

---

packages/atomic/.storybook/manager.js
packages/atomic/.storybook/theme.js

https://coveord.atlassian.net/browse/KIT-1217

docs(atomic): use coveo colors for storybook theme

---

packages/quantic/cypress/integration/facets/timeframe-facet/timeframe-facet-actions.ts
packages/quantic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/quantic/docs/adr/ADR-001-range-facet-validations.md
packages/quantic/docs/adr/ADR-template.md
packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.html
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.html
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.js

https://coveord.atlassian.net/browse/SFINT-4263
After some testing with UX, here is the updated validations for the Timeframe facet. You will find the ADR with details on the actual implementation, but here are the leading principles behind it:
1. Give the end user the opportunity to fill in the range before showing validation errors (i.e., wait for the Apply button to be clicked)
2. The form is optional and therefore input fields become required only when the form is filled. The errors related to required fields should disappear automatically when interacting with other components, or when erasing the field content.
3. The errors related to invalid form input (e.g., invalid format, invalid range) should persist even when interacting with other components. These error messages are still …

fix(quantic): update timeframe facet range validations

---

packages/atomic/src/components/result-template-components/atomic-result-link/atomic-result-link.pcss
packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.pcss

https://coveord.atlassian.net/browse/KIT-1227

fix(atomic): reuse result links :hover styling for :focus-visible, remove outline

---

packages/atomic/.storybook/default-init.ts

https://coveord.atlassian.net/browse/KIT-1234

docs(atomic): clear search interface content when doc is rendered

---

packages/atomic/cypress/integration/facets/manager/facet-manager.cypress.ts
packages/atomic/src/components/atomic-facet-manager/atomic-facet-manager.tsx
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1202

fix(atomic): validate collapse-facets-after property for facet manager component

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/load-more-results-actions.ts
packages/atomic/cypress/integration/load-more-results-selectors.ts
packages/atomic/cypress/integration/load-more-results.cypress.ts

https://coveord.atlassian.net/browse/KIT-1186

test(atomic): cypress tests for load-more-results component

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/refine-toggle-actions.ts
packages/atomic/cypress/integration/refine-toggle-selectors.ts
packages/atomic/cypress/integration/refine-toggle.cypress.ts

https://coveord.atlassian.net/browse/KIT-931

test(atomic): cypress tests for refine toggle

---

packages/atomic/src/components/facets/facet-value-link/facet-value-link.tsx

https://coveord.atlassian.net/browse/KIT-1250

fix(atomic): add group class to link facet values

---

packages/atomic/src/components/result-template-components/atomic-result-badge/atomic-result-badge.pcss
packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.pcss
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1157

fix(atomic): line break for badge and printable uri

---

packages/headless/jest.config.js
packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/api/platform-client.test.ts
packages/headless/src/app/case-assist-engine/case-assist-engine.test.ts
packages/headless/src/app/logger-middlewares.test.ts
packages/headless/src/app/renew-access-token-middleware.test.ts
packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.test.ts
packages/headless/src/controllers/result-list/headless-result-list.test.ts
packages/headless/src/features/redirection/redirection-slice.test.ts

https://coveord.atlassian.net/browse/KIT-1251

chore: prevent case assist id message from logging to console

---

packages/atomic/src/components/facets/atomic-rating-range-facet/atomic-rating-range-facet.stories.tsx

A component I forgot to include in Storybook !
https://coveord.atlassian.net/browse/KIT-1255

docs(atomic): add atomic-rating-range-facet story

---

packages/auth/README.md

https://coveord.atlassian.net/browse/KIT-1252

fix(auth): fix installation command in readme

---

packages/atomic/cypress/integration/result-list/result-list-selectors.ts
packages/atomic/cypress/integration/result-list/result-list-utils.ts
packages/atomic/cypress/integration/result-list/result-list.cypress.ts
packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx

https://coveord.atlassian.net/browse/KIT-1253

fix(atomic): fixed list root image classes

---

packages/atomic/README.md
packages/atomic/src/components/result-template-components/result-template-decorators.tsx
packages/atomic/src/index.ts
packages/atomic/src/utils/initialization-utils.tsx

https://coveord.atlassian.net/browse/KIT-1258

feat(atomic): expose & document Stencil decorators

---

packages/atomic/src/pages/accessibility/commerce-full.html

https://coveord.atlassian.net/browse/KIT-1261
Testable here: https://staticdev.cloud.coveo.com/atomic/pr/KIT-1261/commerce-full.html
Is there anything you believe is missing on this page?

docs(atomic): added condensed accessibility test page

---

JenkinsfileProductionRelease

prod release build failed due to missing comma in quantic publishing part of jenkins script.
https://searchuibuilds.dev.cloud.coveo.com/job/ui-kit-production-release/50/console

ci(quantic): added missing comma

---

packages/atomic/src/components/atomic-result/atomic-result.tsx
packages/atomic/src/components/result-template-components/atomic-result-fields-list/atomic-result-fields-list.tsx
packages/atomic/src/components/result-template-components/result-template-decorators.spec.tsx
packages/atomic/src/components/result-template-components/result-template-decorators.tsx
packages/atomic/src/index.ts
packages/atomic/src/pages/examples/custom.html

https://coveord.atlassian.net/browse/KIT-1259

feat(atomic): add & export resultContext method

---

packages/atomic/package-lock.json
packages/atomic/package.json
packages/atomic/stencil.config.ts

https://coveord.atlassian.net/browse/KIT-1286

chore(atomic): bump stencil/core & remove warning

---

packages/headless/esbuild.js

https://coveord.atlassian.net/browse/KIT-1291

fix: add apache license to headless bundles

---

scripts/reports/bundle-size/command.js
scripts/reports/bundle-size/report.js
scripts/reports/bundle-size/time-series.js
scripts/reports/pr-report.js

https://coveord.atlassian.net/browse/KIT-1290

ci: readd bundle size report

---

.github/actions/e2e-atomic/action.yml
.github/actions/e2e-quantic/action.yml

https://coveord.atlassian.net/browse/KIT-1294

ci: added cypress record key to masterbot.yml

---

.github/actions/e2e-atomic/action.yml
.github/actions/e2e-quantic/action.yml
.github/workflows/masterbot.yml

https://coveord.atlassian.net/browse/KIT-1295

ci: fix how secrets are passed to e2e GitHub actions

---

.github/workflows/masterbot.yml
packages/quantic/cypress.json

https://coveord.atlassian.net/browse/KIT-1296

ci(quantic): linked cypress.io project to Quantic

---

.github/workflows/masterbot.yml
scripts/deploy/bump-version.js

https://coveord.atlassian.net/browse/KIT-1297

ci: added git author identity to version bump commit

---

packages/quantic/coveo.d.ts
packages/quantic/force-app/main/default/lwc/quanticCaseAssistInterface/quanticCaseAssistInterface.html
packages/quantic/force-app/main/default/lwc/quanticCaseAssistInterface/quanticCaseAssistInterface.js
packages/quantic/force-app/main/default/lwc/quanticCaseAssistInterface/quanticCaseAssistInterface.js-meta.xml
packages/quantic/force-app/main/default/lwc/quanticHeadlessLoader/quanticHeadlessLoader.js

[SFINT-4305](https://coveord.atlassian.net/browse/SFINT-4305)

feat(quantic): quanticCaseAssistInterface component added 

---

.github/workflows/masterbot.yml
.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1299
Ultimately, I believe this is what we're trying to accomplish with tags. Conditions on tags have been pretty unreliable, I believe this approach should work more reliably.

ci: changed masterbot and publishbot condition to use commit message

---

.github/actions/create-deployment-package/action.yml
.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1301

ci: replaced ec2 runner with eks runner

---

.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1306

ci: installed build-essential before setup step in publishbot.yml

---

.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1307
Context in issue

ci: added `sudo` to CI apt-get update & install

---

packages/atomic/cypress/integration/common-assertions.ts
packages/atomic/cypress/integration/result-list/result-components/result-badge.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-date.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-fields-list.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-icon-selectors.ts
packages/atomic/cypress/integration/result-list/result-components/result-icon.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-image.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-link.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-multi-value-text-selectors.ts
packages/atomic/cypress/integration/result-list/result-components/result-multi-value-text.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-number.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-printable-uri.cypress.ts
packages/atomic/cypress/integration/result-list/result-components/result-text.cypress.ts
packages/atomic/cypress/integration/result-list/result-list-utils.ts
packages/atomic/cypress/integration/result-list/result-list.cypress.ts

https://coveord.atlassian.net/browse/KIT-971

test(atomic): added accessibility tests for all result components

---

packages/headless/doc-parser/use-cases/search.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-filter.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-filter.ts
packages/samples/headless-react/src/components/date-filter/date-filter.class.tsx
packages/samples/headless-react/src/components/date-filter/date-filter.fn.tsx
packages/samples/headless-react/src/components/numeric-filter/numeric-filter.class.tsx
packages/samples/headless-react/src/components/numeric-filter/numeric-filter.fn.tsx
packages/samples/headless-react/src/pages/SearchPage.tsx

https://coveord.atlassian.net/browse/KIT-793

doc(headless): add dateFilter & numericFilter React samples

---

packages/atomic/cypress/integration/breadbox/breadbox-actions.ts
packages/atomic/cypress/integration/breadbox/breadbox-assertions.ts
packages/atomic/cypress/integration/breadbox/breadbox-selectors.ts
packages/atomic/cypress/integration/breadbox/breadbox.cypress.ts
packages/atomic/cypress/integration/facets/category-facet/category-facet-assertions.ts
packages/atomic/cypress/integration/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/integration/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/cypress/integration/facets/manager/facet-manager-actions.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet-actions.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet.cypress.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet-action.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/atomic/cypress/integration/refine-toggle-actions.ts

KIT-930
- Add breadcrumb for each facet _ but not rating & rating range
- Add general breadcrumb tests with ShowMore, ShowLess, ClearAll

test(atomic): add cypress test for breadbox

---

packages/atomic/package-lock.json
packages/atomic/package.json
packages/quantic/package-lock.json
packages/quantic/package.json

https://coveord.atlassian.net/browse/KIT-1319
The CI seems to be failing because of a missing dependency in a file downloaded externally (cypress.zip). Since the downloaded file depends on the specified version of Cypress, I want to test whether updating Cypress will fix the issue.

fix: updated cypress version

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/result-list/result-components/result-text.cypress.ts
packages/atomic/src/components/atomic-search-interface/analytics-config.ts
packages/atomic/src/utils/local-storage-utils.spec.ts
packages/auth/src/saml/saml-flow.test.ts
packages/headless/src/api/commerce/product-listings/product-listing-api-client.test.ts
packages/headless/src/features/case-assist/case-assist-analytics-actions-loader.ts
packages/quantic/cypress/integration/facets/numeric-facet/numeric-facet-expectations.ts
packages/quantic/cypress/reporters/detailed-collector.ts

https://coveord.atlassian.net/browse/KIT-1309

style(atomic,headless,quantic): fixed all linter warnings

---

packages/atomic/src/components/result-template-components/result-template-decorators.tsx
packages/atomic/src/pages/examples/custom.html

https://coveord.atlassian.net/browse/KIT-1277

fix(atomic): specify use of connectedCallback for resultContext method

---

packages/atomic/cypress/integration/search-box-assertions.ts
packages/atomic/cypress/integration/search-box.cypress.ts
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-query-suggestions/atomic-search-box-query-suggestions.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx
packages/atomic/src/components/search-box-suggestions/suggestions-common.ts

https://coveord.atlassian.net/browse/KIT-1079

fix(atomic): improved keyboard focus on search box

---

.github/actions/create-deployment-package/action.yml
.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1323

ci(atomic,headless): replaced EKS GHA runner with EC2 runner

---

packages/headless/src/controllers/search-box/headless-search-box.test.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-actions-loader.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.test.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.ts
packages/headless/src/features/facets/facet-set/facet-set-actions-loader.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/facets/generic/facet-actions.ts
packages/headless/src/features/search/search-actions.ts

https://coveord.atlassian.net/browse/KIT-1333

fix(headless): add updateFacetAutoSelection & stop preventing auto select on new searches

---

packages/atomic-react/package.json
packages/atomic/package.json
packages/auth/package.json
packages/bueno/package.json
packages/headless/package.json

https://coveord.atlassian.net/browse/KIT-1352

chore(atomic-react): adjust clean script to use rimraf

---

Jenkinsfile

https://coveord.atlassian.net/browse/KIT-1354
In the first commit, I re-added the Jenkinsfile without any modifications.
In the second commit, I adapted it to only run on version bumps.
There's [an ongoing conversation with dev tooling](https://coveo.slack.com/archives/CBP3GTFTQ/p1642527281085400) about the current issue with the deployment. If [this](https://github.com/coveo/ui-kit/runs/4857248936?check_suite_focus=true) run passes, then I will close this PR.

ci(atomic,headless): re-added Jenkinsfile

---

JenkinsfileProductionRelease
JenkinsfileQARelease

https://coveord.atlassian.net/browse/KIT-1361
[Conversation](https://coveo.slack.com/archives/CBP3GTFTQ/p1642612929113300)

ci: updated NPM token for QA and prod

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx

https://coveord.atlassian.net/browse/KIT-1327

fix(atomic): made search-box maintain focus effect after selecting suggestions

---

packages/atomic/cypress/integration/pager-selectors.ts
packages/atomic/cypress/integration/pager.cypress.ts
packages/atomic/src/components/atomic-pager/atomic-pager.pcss
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.pcss
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx
packages/atomic/src/components/common/button-style.tsx
packages/atomic/src/components/common/button.tsx
packages/atomic/src/components/common/radio-button.tsx
packages/atomic/src/global/global.pcss
packages/atomic/src/utils/accessibility-utils.tsx

https://coveord.atlassian.net/browse/KIT-1328
* I transformed the buttons in the pager into radio buttons
* Since selecting a page moves the focus, I made sure that the page waits for the focus to be changed before scrolling up
* I extracted the radio button logic into a component similar to `<Button>`
* I removed the ul/li in favor of a `radiogroup`.

fix(atomic): improved accessibility for pager

---

packages/atomic/cypress/integration/breadbox/breadbox-actions.ts
packages/atomic/cypress/integration/breadbox/breadbox-assertions.ts
packages/atomic/cypress/integration/breadbox/breadbox.cypress.ts
packages/atomic/cypress/integration/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/integration/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet.cypress.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/atomic/cypress/support/commands.ts
packages/atomic/cypress/utils/analyticsUtils.ts

https://coveord.atlassian.net/browse/KIT-1347

test(atomic): removed necessity for cy.wait after clearing a breadcrumb

---

packages/atomic/cypress/integration/search-box-assertions.ts
packages/atomic/cypress/integration/standalone-search-box.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx
packages/atomic/src/components/search-box-suggestions/suggestions-common.ts
packages/atomic/src/pages/examples/standalone.html
packages/atomic/src/utils/local-storage-utils.tsx
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.test.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.ts

https://coveord.atlassian.net/browse/KIT-937
Follows this guide https://docs.coveo.com/en/headless/latest/usage/standalone-search-box-usage/

feat(atomic): allow atomic-search-box to be standalone

---

packages/atomic/src/components/search-box-suggestions/atomic-search-box-query-suggestions/atomic-search-box-query-suggestions.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx

https://coveord.atlassian.net/browse/KIT-1245

fix(atomic): improved contrast ratio on search suggestion icons

---

.github/actions/setup/action.yml
.github/workflows/masterbot.yml
.github/workflows/prbot.yml

https://coveord.atlassian.net/browse/KIT-1367

fix(headless): added doc to NPM package and deployment package

---

packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx

https://coveord.atlassian.net/browse/KIT-1212
When focusing on the "Sort" heading with TalkBack, it would read out "Sort, InIn". You can see a video of it in the JIRA above.

fix(atomic): gave main role to refine modal's content

---

packages/atomic-react/package.json
scripts/deploy/update-npm-tag.js

https://coveord.atlassian.net/browse/KIT-1374

chore(atomic): add publish official script

---

JenkinsfileProductionRelease
JenkinsfileQARelease

https://coveord.atlassian.net/browse/KIT-1372
I'm gonna try to discuss with CSEC, IT and/or DT about updating this token for one that isn't a personal access token.

ci: changed NPM token for updating tags

---

packages/headless/src/test/index.ts
packages/headless/src/test/mock-engine.ts
packages/headless/src/test/mock-raw.ts
packages/headless/src/test/mock-result.ts
packages/headless/src/test/mock-state.ts

https://coveord.atlassian.net/browse/KIT-1410

chore(headless): document each specific "TestUtils"

---

packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/api/analytics/product-recommendations-analytics.ts
packages/headless/src/app/engine-configuration.ts
packages/headless/src/features/configuration/configuration-actions.ts
packages/headless/src/features/configuration/configuration-slice.test.ts
packages/headless/src/features/configuration/configuration-slice.ts
packages/headless/src/features/configuration/configuration-state.ts
packages/headless/src/test/mock-analytics-state.ts

https://coveord.atlassian.net/browse/KIT-1409
Goes along with https://github.com/coveo/coveo.analytics.js/pull/321

feat(headless): add originContext to analytics' state & configuration

---

packages/quantic/cypress/integration/breadcrumb-manager/breadcrumb-manager.cypress.ts
packages/quantic/cypress/integration/facets/numeric-facet/numeric-facet.cypress.ts
packages/quantic/cypress/integration/result-quickview/result-quickview.cypress.ts
packages/quantic/cypress/page-objects/example-search.ts

https://coveord.atlassian.net/browse/SVCC-453
https://coveord.atlassian.net/browse/SVCC-454

fix(quantic): fix flaky tests

---

packages/atomic/package-lock.json
packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-1424
If you installed Atomic, it tried to run patch-package in the postinstall script. Since it was a dev dependency, it wasn't added

fix(atomic): move patch-package to dependency

---

packages/quantic/force-app/main/default/lwc/quanticDocumentSuggestion/quanticDocumentSuggestion.html

SFINT-4376 no suggestions slot added

---

JenkinsfileProductionRelease
JenkinsfileQARelease

https://coveord.atlassian.net/browse/KIT-1426
https://coveo.slack.com/archives/CBP3GTFTQ/p1645461054512029
https://coveo.slack.com/archives/C6VB0J866/p1644608404422889

fix: update Jenkinsfile docker args

---

packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1429
one liner in the sample page so I'll just merge that instantly

fix(atomic): update index.html example layout y gap

---

.github/workflows/manual-package.yml

https://coveord.atlassian.net/browse/KIT-1432

ci(ci): add manual workflow for package creation

---

packages/headless/src/controllers/case-field/headless-case-field.ts

JS Doc description added for autoSelect parameter.

fix(headless): JS Doc description added

---

.github/actions/setup/action.yml

https://coveord.atlassian.net/browse/KIT-1434

ci(atomic-angular): add angular dist to build cache

---

scripts/deploy/update-npm-tag.js

https://coveord.atlassian.net/browse/KIT-1441

ci(atomic-angular): temp revert bump tag script

---

packages/atomic-react/package-lock.json
packages/atomic/package-lock.json
packages/bueno/package-lock.json
packages/headless/package-lock.json

https://coveord.atlassian.net/browse/KIT-1440

ci(headless): regenerate package lock

---

.dcignore
.deployment.config.json
.eslintrc.json
.gitignore
.vscode/extensions.json
Jenkinsfile
packages/atomic/src/components/atomic-did-you-mean/atomic-did-you-mean.tsx
packages/atomic/src/components/atomic-icon/atomic-icon.tsx
packages/atomic/src/components/atomic-load-more-results/atomic-load-more-results.tsx
packages/atomic/src/components/atomic-no-results/atomic-no-results.tsx
packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/components/atomic-result/atomic-result.tsx
packages/atomic/src/components/facets/facet-search/facet-search-matches.tsx
packages/atomic/src/components/facets/facet-value-label-highlight/facet-value-label-highlight.tsx
packages/atomic/src/components/result-template-components/atomic-result-text/atomic-result-text.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-query-suggestions/atomic-search-box-query-suggestions.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx
packages/headless/src/app/engine-configuration.ts

https://coveord.atlassian.net/browse/KIT-1443

ci(ci): move from veracode to snyk code 

---

packages/atomic-angular/README.md

Fixes for minor Readme issues I found while working on the [corresponding PR for the docs site](https://github.com/coveo/doc_jekyll-public-site/pull/6647)

docs: minor readme corrections

---

packages/atomic-angular/README.md

https://coveord.atlassian.net/browse/KIT-1455

docs(atomic-angular): add explanation on initialization process

---

packages/atomic/src/components/atomic-layout-section/sections.ts

it's a follow-up update to this PR: https://github.com/coveo/doc_jekyll-public-site/pull/6634

feat(headless): updates the possible values for the Section property

---

.deployment.config.json

https://coveord.atlassian.net/browse/KIT-1457

ci: fixed snyk code configuration

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx

https://coveord.atlassian.net/browse/KIT-1437

fix(atomic): remove unnecessary border from search box

---

packages/atomic/src/components/facets/facet-header/facet-header.tsx

https://coveord.atlassian.net/browse/KIT-1276

fix(atomic): invert collapsible facet icon

---

packages/samples/angular/package-lock.json
packages/samples/angular/package.json
packages/samples/angular/src/app/app.module.ts

https://coveord.atlassian.net/browse/KIT-1466

docs(angular-sample): fix angular sample startup script

---

.github/actions/e2e-atomic-angular/action.yml
.github/actions/e2e-atomic-react/action.yml
.github/workflows/manual-package.yml
.github/workflows/masterbot.yml

Recording cypress tests for these smoke tests is not really needed.
https://coveord.atlassian.net/browse/KIT-1475

ci(cypress): remove cypress record for smoke tests

---

packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/features/search-and-folding/search-and-folding-request.test.ts
packages/headless/src/features/search-and-folding/search-and-folding-request.ts

https://coveord.atlassian.net/browse/KIT-1483

fix(headless): add actionsHistory to search request

---

packages/atomic/src/global/global.pcss

The real fix will be upgrading Tailwind with this change https://github.com/tailwindlabs/tailwindcss/commit/c245d94e41b9ce9797de93474eff69330a1932ed
https://coveord.atlassian.net/browse/KIT-1470
They don't make release super often, so I want the temp in order to fix it now on our side

fix(atomic): temp fix for outline rings

---

package-lock.json
package.json

https://coveord.atlassian.net/browse/KIT-1494

chore: added commitizen to dev dependencies

---

packages/samples/headless-react/src/components/dependent-facet/multi-level-dependent-facet.tsx
packages/samples/headless-react/src/components/dependent-facet/single-parent-multiple-dependent.fn.tsx
packages/samples/headless-react/src/components/dependent-facet/single-parent-single-dependent.fn.tsx
packages/samples/headless-react/src/components/dependent-facet/single-value-dependent.fn.tsx
packages/samples/headless-react/src/pages/DependentFacetPage.tsx

https://coveord.atlassian.net/browse/KIT-1484

docs(headless): added FacetConditionsManager headless-react doc

---

Jenkinsfile

https://coveord.atlassian.net/browse/KIT-1501
Team slack thread: https://coveo.slack.com/archives/G7HD9P48H/p1647272092635179

fix: generate doc before pushing to NPM with Jenkins

---

packages/atomic/src/components/atomic-result-template/atomic-result-template.tsx
packages/atomic/src/components/result-template-components/atomic-field-condition/atomic-field-condition.tsx
packages/headless/src/controllers/search-box/headless-search-box.ts

https://coveord.atlassian.net/browse/KIT-1510
Copied the doc from the result template over here

doc(atomic): add documentation for mustMatch/mustNotMatch of AtomicFieldCondition

---

packages/headless/src/api/search/search/search-request.ts
packages/headless/src/features/fields/fields-state.ts
packages/headless/src/index.ts

https://coveord.atlassian.net/browse/KIT-1518

feat(headless): export SearchDefaultFieldsToInclude

---

packages/atomic/src/components/result-template-components/atomic-result-icon/atomic-result-icon.pcss

https://coveord.atlassian.net/browse/KIT-1534

fix(atomic): atomic-result-icon styling typo

---

packages/samples/headless-react/src/components/smart-snippet/smart-snippet.class.tsx
packages/samples/headless-react/src/components/smart-snippet/smart-snippet.fn.tsx

https://coveord.atlassian.net/browse/KIT-1486
Split from: https://github.com/coveo/ui-kit/pull/1843
Let's experiment: can I put two commits on `master` with the same JIRA? 🤔

docs(headless): added react sample for feedback modal

---

packages/atomic/src/components/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1433

feat(atomic): add default part for color facet values 

---

packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx

My first tentative did not work correctly when I tested a full loop.
I was able to test this one locally, but I might also need to do some manual deploy shenanigans
https://coveord.atlassian.net/browse/KIT-1559

fix(atomic): fix set renderingFunction for atomic-react

---

packages/atomic/src/pages/examples/folding.html

https://coveord.atlassian.net/browse/KIT-1566

docs(atomic): move folded list to separate example page

---

packages/atomic-react/package-lock.json
packages/atomic-react/package.json
packages/atomic-react/src/components/SearchInterfaceWrapper.tsx
packages/samples/atomic-react/package-lock.json
packages/samples/atomic-react/package.json

https://coveord.atlassian.net/browse/KIT-1554

feat(atomic-react): support react18 as peer dependency

---

packages/atomic/src/pages/examples/custom.html
packages/atomic/src/pages/examples/external.html
packages/atomic/src/pages/examples/folding.html
packages/atomic/src/pages/examples/headless.html
packages/atomic/src/pages/examples/standalone.html
packages/atomic/src/pages/header.js
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1571

docs(atomic): add header navigation to sample page

---

packages/headless/src/controllers/folded-result-list/headless-folded-result-list.test.ts
packages/headless/src/controllers/folded-result-list/headless-folded-result-list.ts

https://coveord.atlassian.net/browse/KIT-1572

feat(headless): add methods for finding results by id and by collection

---

packages/atomic/cypress/integration/result-list/result-components/result-icon.cypress.ts
packages/atomic/src/components/result-template-components/atomic-result-icon/atomic-result-icon.pcss
packages/atomic/src/components/result-template-components/atomic-result-icon/atomic-result-icon.tsx

https://coveord.atlassian.net/browse/KIT-1585

fix(atomic): change default icon for atomic-result-icon & make it full-width

---

packages/atomic/src/components/atomic-load-more-children-results/atomic-load-more-children-results.tsx
packages/atomic/src/components/result-lists/atomic-result-children/atomic-result-children.tsx
packages/atomic/src/components/result-lists/result-list-decorators.tsx
packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/controllers/folded-result-list/headless-folded-result-list.test.ts
packages/headless/src/controllers/folded-result-list/headless-folded-result-list.ts
packages/headless/src/features/folding/folding-actions.ts

https://coveord.atlassian.net/browse/KIT-1576?atlOrigin=eyJpIjoiZmQxZDZmNjMwOTQwNGUzNWE1NzJmMjM3Y2ZjNTk1MTQiLCJwIjoiaiJ9

feat(atomic,headless): add analytics to the show more/show less button

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx

https://coveord.atlassian.net/browse/KIT-1594
I accidentally merged https://github.com/coveo/ui-kit/pull/1949#discussion_r860874886 without looking at this review! #shame

docs(atomic): improve search box timeout description

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/common-assertions.ts
packages/atomic/cypress/integration/search-interface.cypress.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx

https://coveord.atlassian.net/browse/KIT-1605

fix(atomic): graciously handle prop changes before initialization and log warning

---

packages/headless/src/features/analytics/search-analytics-actions-loader.ts
packages/headless/src/features/question-answering/question-answering-actions-loader.ts
packages/headless/src/features/question-answering/question-answering-document-id.ts
packages/headless/src/features/question-answering/question-answering-slice.ts
packages/headless/src/features/question-answering/question-answering-state.ts

https://coveord.atlassian.net/browse/KIT-1615
Extracted from https://github.com/coveo/ui-kit/pull/1965

fix(headless): added missing actions to actions loaders

---

packages/atomic/cypress/integration/smart-snippet-assertions.ts
packages/atomic/cypress/integration/smart-snippet-suggestions-assertions.ts
packages/atomic/cypress/integration/smart-snippet-suggestions.cypress.ts
packages/atomic/cypress/integration/smart-snippet.cypress.ts

https://coveord.atlassian.net/browse/KIT-1619

test(atomic): improved answerTopMargin and answerBottomMargin snippet tests

---

packages/atomic/src/components/atomic-external/atomic-external.tsx

https://coveord.atlassian.net/browse/KIT-1599
Added an event listener in the atomic-external component that handles and then dispatches the scrollToTop event to the element encapsulated by the atomic-external tags.

feat(atomic): atomic-external handles scrollToTop event

---

packages/atomic/src/components/result-lists/result-list-common.pcss

https://coveord.atlassian.net/browse/KIT-1644

fix(atomic): fix grid columns when image is not large

---

.github/actions/e2e-atomic-screenshots/action.yml
.github/workflows/masterbot.yml
.github/workflows/prbot.yml
packages/atomic/cypress-screenshots.json
packages/atomic/cypress/integration-screenshots/result-list-screenshots.cypress.ts
packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-1654

test(atomic): add cypress screenshots testing

---

packages/atomic/src/components/atomic-no-results/atomic-no-results.tsx
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx

https://discuss.coveo.com/t/missing-shadow-parts-custom-properties/7355/11?u=jfthibodeau
https://coveord.atlassian.net/browse/KIT-1428

feat(atomic): add missing parts for atomic-search-box/atomic-no-results

---

packages/atomic/cypress/integration/facets/color-facet/color-facet-assertions.ts
packages/atomic/cypress/integration/facets/color-facet/color-facet-selectors.ts
packages/atomic/cypress/integration/facets/color-facet/color-facet.cypress.ts
packages/atomic/package-lock.json
packages/atomic/src/components/facets/atomic-color-facet/atomic-color-facet.tsx
packages/quantic/package-lock.json

https://coveord.atlassian.net/browse/KIT-1264

fix(atomic): sanitize facet value to use them as parts

---

packages/atomic/src/components/common/fieldset-group.tsx
packages/atomic/src/components/common/group.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/components/facets/atomic-segmented-facet/atomic-segmented-facet.tsx
packages/atomic/src/components/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx
packages/atomic/src/components/facets/facet-values-group/facet-values-group.tsx
packages/atomic/src/global/global.pcss
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-1673
Details in issue.
I'll wait for two dev reviews on this PR instead of one review.

fix(atomic): added fieldset and legend around facet values

---

packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/atomic/src/components/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx

https://coveord.atlassian.net/browse/KIT-1681

fix(atomic): handle timeframe-facet with no date picker and no timeframe configured

---

packages/atomic/cypress/integration/search-box.cypress.ts

https://coveord.atlassian.net/browse/KIT-1691

test(atomic): increase timeout for suggestion promises

---

packages/headless/src/utils/highlight.test.ts
packages/headless/src/utils/highlight.ts

https://coveord.atlassian.net/browse/KIT-1679

fix(headless): fix highlighting to escape last part of the value

---

packages/atomic/cypress/integration/result-list/folded-result-list.cypress.ts
packages/atomic/cypress/integration/result-list/result-list-actions.ts
packages/atomic/src/components/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx
packages/headless/src/features/folding/folding-actions.ts

https://coveord.atlassian.net/browse/KIT-1655

fix(atomic,headless): fix schema definition for foldedResultList controller

---

packages/atomic-angular/projects/atomic-angular/package-lock.json
packages/atomic-react/package-lock.json
packages/atomic/package-lock.json
packages/auth/package-lock.json
packages/bueno/package-lock.json
packages/headless/package-lock.json
packages/quantic/package-lock.json
packages/samples/atomic-react/package-lock.json
packages/samples/atomic-react/package.json
packages/samples/headless-react/package-lock.json

https://coveord.atlassian.net/browse/KIT-1694

test(atomic-react): allow local changes for atomic component in samples

---

packages/atomic/src/pages/examples/instantResults.html
packages/atomic/src/pages/examples/suggestions.html
packages/atomic/src/pages/header.js

https://coveord.atlassian.net/browse/KIT-855

docs(atomic): add page for instant results and clean up suggestions page

---

scripts/deploy/bump-version.js

as promised, this reverts commit 5d64d67bb94e6123f8394354b91b256a22fb2de8.

Revert "fix: temporarily force git tags (#2088)"

---

.github/actions/e2e-atomic-angular/action.yml
.github/actions/e2e-atomic-react/action.yml
.github/actions/e2e-atomic-screenshots/action.yml
.github/actions/e2e-atomic-visual-tests/action.yml
.github/actions/e2e-atomic/action.yml
.github/actions/e2e-quantic/action.yml
.github/actions/e2e-stencil/action.yml
.github/actions/e2e-vuejs/action.yml
.github/actions/setup/action.yml
.github/workflows/manual-package.yml
.github/workflows/masterbot.yml
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1719

fix: reinstall cypress locally in subpackages without running "npm ci", remove cypress keys

---

packages/atomic/src/locales.json

[QA-979](https://coveord.atlassian.net/browse/QA-979)

chore(atomic): add a few chinese localization strings

---

.github/actions/e2e-atomic/action.yml
.github/actions/e2e-quantic/action.yml

https://coveord.atlassian.net/browse/KIT-1740

fix: set record false on master branches

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx
packages/atomic/src/components/result-lists/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/result-lists/result-list-common.tsx
packages/atomic/src/components/result-template-components/atomic-result-multi-value-text/atomic-result-multi-value-text.tsx
packages/atomic/src/components/result-template-components/atomic-result-number/atomic-result-number.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.tsx
packages/atomic/src/pages/examples/instantResults.html
packages/atomic/src/pages/examples/suggestions.html
packages/atomic/src/utils/store.ts

https://coveord.atlassian.net/browse/KIT-1733

feat(atomic): handle fields to include in instant results

---

.github/workflows/manual-package.yml
.github/workflows/masterbot.yml

https://coveord.atlassian.net/browse/KIT-1719

fix: ci git add end of line

---

.github/workflows/manual-package.yml
.github/workflows/masterbot.yml
.github/workflows/prbot.yml

https://coveord.atlassian.net/browse/KIT-1719

fix: git add use single quotes

---

packages/atomic/src/pages/accessibility/commerce-full.html

https://coveord.atlassian.net/browse/KIT-1739

docs(atomic): include instant results in commerce-full page

---

packages/headless/src/controllers/core/result-list/headless-core-result-list.ts

https://coveord.atlassian.net/browse/KIT-1754
Let's clear this up once and for all 😂

fix(headless): disable linter error for fetchMoreResultsActionCreator

---

LICENSE.md

So that it shows on the deets of the repo

docs: create root LICENSE.md

---

packages/atomic/src/pages/accessibility/commerce-full.html
packages/atomic/src/pages/header.js

https://coveord.atlassian.net/browse/KIT-1776

docs(atomic): add commerce-full page to header

---

packages/atomic/cypress/integration/facets/manager/facet-manager-assertions.ts
packages/atomic/src/components/search/atomic-facet-manager/atomic-facet-manager.tsx
packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/components/search/facets/facet-common.ts

https://coveord.atlassian.net/browse/KIT-1737

fix(atomic): make isCollapsed prop's value consistent

---

packages/atomic/cypress/integration/result-list/folded-result-list-assertions.ts
packages/atomic/cypress/integration/result-list/folded-result-list.cypress.ts

https://coveord.atlassian.net/browse/KIT-1781

test(atomic): fixed e2e folded result list tests

---

.github/actions/commit-generated-files/action.yml
.github/workflows/masterbot.yml
.github/workflows/prbot.yml
packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/cypress/integration/query-summary-assertions.ts
packages/atomic/cypress/integration/query-summary.cypress.ts
packages/atomic/cypress/integration/search-box/search-box.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/global/global.pcss
packages/atomic/src/themes/accessible.css
packages/atomic/src/themes/coveo.css
packages/atomic/tailwind.config.js

https://coveord.atlassian.net/browse/KIT-1765
We're not changing anything to the OOT behaviour. This is just to allow developers to externally prevent users from triggering searches for X condition

feat(atomic): disableSearch prop for search box

---

packages/atomic/cypress/integration/search-box/search-box-assertions.ts
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx

https://coveord.atlassian.net/browse/KIT-1784
oopsie

fix(atomic): actually include fieldsToInclude in search from interface

---

packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx

https://coveord.atlassian.net/browse/KIT-1785
vid with instant results:
https://user-images.githubusercontent.com/30511433/175350032-4cfee06b-ea85-43c5-9936-a0a4ab8f40e6.mp4
vid without instant results:
https://user-images.githubusercontent.com/30511433/175350118-501b5ace-ae79-4aef-9340-66cd08a46b22.mp4

fix(atomic): fix arrow navigation on input

---

packages/atomic/src/components/search/atomic-segmented-facet-scrollable/atomic-segmented-facet-scrollable.tsx
packages/atomic/tailwind.config.js

Demo:
https://user-images.githubusercontent.com/97299176/176762820-f1ca9ef7-29d4-4758-b1e1-1f73ca958910.mov

feat(atomic): Hide arrow animation

---

packages/atomic-angular/projects/atomic-angular/package-lock.json
packages/atomic-react/package-lock.json
packages/atomic/package-lock.json
packages/auth/package-lock.json
packages/bueno/package-lock.json
packages/headless/package-lock.json
packages/headless/package.json
packages/quantic/package-lock.json

https://coveord.atlassian.net/browse/KIT-1814

fix(atomic): add insight and case assist to headless files

---

packages/atomic-angular/projects/atomic-angular/package-lock.json
packages/atomic-react/package-lock.json
packages/atomic/cypress/integration/common-assertions.ts
packages/atomic/cypress/integration/facets/facet-common-actions.ts
packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/package-lock.json
packages/auth/package-lock.json
packages/bueno/package-lock.json
packages/headless/package-lock.json
packages/quantic/package-lock.json

https://coveord.atlassian.net/browse/KIT-1815

fix(atomic): amoreau was being selected & searched in tests

---

Jenkinsfile
package.json
packages/samples/headless-react/package.json

https://coveord.atlassian.net/browse/KIT-1832

ci: update npm publish version

---

packages/atomic/.storybook/default-story-shared.tsx
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.stories.tsx
packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-query-suggestions/atomic-search-box-query-suggestions.stories.tsx
packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.stories.tsx

Stories for: 
* atomic-query-suggestions
* atomic-recent-queries
* atomic-instant-results
https://coveord.atlassian.net/browse/KIT-1830

docs(atomic): storybook for searchbox suggestions providers

---

packages/headless/src/features/analytics/analytics-actions.ts
packages/headless/src/features/analytics/generic-analytics-actions-loader.ts

https://coveord.atlassian.net/browse/KIT-1838

fix(headless): wrong payload interface for logClickEvent

---

Jenkinsfile
JenkinsfileProductionRelease

https://coveord.atlassian.net/browse/KIT-1852
Context https://coveo.slack.com/archives/CBP3GTFTQ/p1657632333195469

fix: add heavy to node Jenkins config

---

packages/headless/doc-parser/use-cases/search.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/instant-results/instant-results.ts
packages/samples/headless-react/src/components/instant-results/instant-results.class.tsx
packages/samples/headless-react/src/components/instant-results/instant-results.fn.tsx
packages/samples/headless-react/src/pages/SearchPage.tsx

https://coveord.atlassian.net/browse/KIT-1803

docs(headless): add samples for instant-results controller

---

packages/atomic/src/components/search/facets/atomic-segmented-facet/atomic-segmented-facet.tsx
packages/headless/src/controllers/core/facets/_common/facet-option-definitions.ts
packages/headless/src/controllers/facets/facet/headless-facet-options.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-request-builder.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/facets/facet-set/interfaces/request.ts
packages/headless/src/features/search/search-mappings.test.ts
packages/headless/src/features/search/search-mappings.ts
packages/headless/src/features/search/search-request.test.ts
packages/headless/src/test/mock-facet-request.ts

https://coveord.atlassian.net/browse/KIT-1819

feat(headless): clearAllBreadcrumbs only affects regular facets

---

packages/atomic/src/components/search/result-lists/table-display-results.tsx
packages/samples/atomic-react/src/App.tsx
packages/samples/atomic-react/src/pages/TableResultListPage.tsx

https://coveord.atlassian.net/browse/KIT-1842

feat(atomic-react): add support for result list table

---

.github/workflows/snyk.yml

https://coveord.atlassian.net/browse/KIT-1827

fix: prevent running snyk on bump commits

---

packages/atomic/src/components/facets/atomic-segmented-facet-scrollable/atomic-segmented-facet-scrollable.tsx

https://coveord.atlassian.net/browse/KIT-1848

feat(atomic): fix bug where arrows appear when field is invalid

---

package-lock.json
packages/headless/package.json
packages/headless/src/api/analytics/recommendations-analytics.test.ts
packages/headless/src/api/analytics/recommendations-analytics.ts
packages/headless/src/api/analytics/search-analytics.test.ts
packages/headless/src/api/analytics/search-analytics.ts
packages/headless/src/api/search/search/search-response.ts
packages/headless/src/features/recommendation/recommendation-actions.ts
packages/headless/src/features/recommendation/recommendation-slice.ts
packages/headless/src/features/recommendation/recommendation-state.ts
packages/headless/src/features/search/search-state.ts
packages/headless/src/test/mock-recommendation.ts
packages/headless/src/test/mock-search-response.ts

Goes with: https://github.com/coveo/coveo.analytics.js/pull/358
https://coveord.atlassian.net/browse/KIT-1807

feat(atomic): add support for search API A/B test feature

---

packages/quantic/force-app/main/default/classes/HeadlessControllerTest.cls
packages/quantic/force-app/main/default/classes/HeadlessControllerTest.cls-meta.xml
packages/quantic/force-app/main/default/classes/InsightControllerTest.cls
packages/quantic/force-app/main/default/classes/InsightControllerTest.cls-meta.xml

Need to meet minimum coverage to promote an unlocked package. Behold these tests in all their glory.

fix(quantic): added apex tests to meet min coverage

---

packages/atomic/src/components/facets/atomic-segmented-facet-scrollable/atomic-segmented-facet-scrollable.tsx
packages/atomic/src/components/search/facets/atomic-segmented-facet/atomic-segmented-facet.tsx

https://coveord.atlassian.net/browse/KIT-185
https://user-images.githubusercontent.com/97299176/178804722-5a88670f-d398-494e-a366-abc23ed260f6.mov

feat(atomic): loading animation for segmented facets

---

packages/atomic/src/components/search/atomic-breadbox/atomic-breadbox.tsx
packages/atomic/src/components/search/atomic-sort-dropdown/atomic-sort-dropdown.tsx

https://coveord.atlassian.net/browse/KIT-1853
Requested here https://discuss.coveo.com/t/missing-shadow-parts-custom-properties/7355/23?u=jfthibodeau

feat(atomic): add parts to breadbox & sort dropdown elements

---

package-lock.json
packages/headless/package.json
packages/headless/src/controllers/core/did-you-mean/headless-core-did-you-mean.test.ts
packages/headless/src/controllers/core/did-you-mean/headless-core-did-you-mean.ts
packages/headless/src/controllers/did-you-mean/headless-did-you-mean.test.ts
packages/headless/src/controllers/insight/did-you-mean/headless-insight-did-you-mean.test.ts
packages/headless/src/controllers/insight/did-you-mean/headless-insight-did-you-mean.ts
packages/headless/src/features/did-you-mean/did-you-mean-insight-analytics-actions.ts
packages/headless/src/features/insight-search/insight-search-actions.ts
packages/headless/src/insight.index.ts
packages/headless/src/state/insight-app-state.ts
packages/headless/src/test/mock-insight-state.ts

https://coveord.atlassian.net/browse/SVCC-2210

feat(headless): Add IP DidYouMean controller

---

packages/atomic/cypress/integration/facets/category-facet/category-facet-selectors.ts
packages/atomic/cypress/integration/facets/color-facet/color-facet-selectors.ts
packages/atomic/cypress/integration/facets/facet/facet-selectors.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet-selectors.ts
packages/atomic/cypress/integration/facets/rating-facet/rating-facet-selectors.ts
packages/atomic/cypress/integration/facets/rating-range-facet/rating-range-facet-selectors.ts
packages/atomic/cypress/integration/facets/segmented-facet/segmented-facet-selectors.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet-selectors.ts
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/search/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/components/search/facets/atomic-segmented-facet/atomic-segmented-facet.tsx
packages/atomic/src/components/search/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx
packages/atomic/src/components/search/facets/facet-segmented-value/facet-segmented-value.tsx
packages/atomic/src/components/search/facets/facet-value-box/facet-value-box.tsx
packages/atomic/src/components/search/facets/facet-value-link/facet-value-link.tsx

https://coveord.atlassian.net/browse/KIT-1823

feat(atomic): added "-selected" parts for link and box facet values

---

packages/atomic/src/components/search/atomic-load-more-results/atomic-load-more-results.tsx
packages/atomic/src/components/search/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/search/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/components/search/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx

https://coveord.atlassian.net/browse/KIT-1869

chore(atomic): remove "ripple" part JS Doc

---

packages/atomic/src/components/search/result-template-components/result-template-decorators.spec.tsx
packages/atomic/src/components/search/result-template-components/result-template-decorators.tsx
packages/atomic/src/pages/examples/custom.html
packages/atomic/src/utils/initialization-utils.spec.ts
packages/atomic/src/utils/initialization-utils.tsx

https://coveord.atlassian.net/browse/KIT-1873

fix(atomic): use custom "closest" method for initializeBindings, resultContext

---

packages/atomic/src/components/search/atomic-results-per-page/atomic-results-per-page.tsx

https://coveord.atlassian.net/browse/KIT-1877

fix(atomic): added accessible group for results per page options

---

packages/atomic/src/pages/accessibility/commerce-full.html

https://coveord.atlassian.net/browse/KIT-1672

docs(atomic): removed grid from accessible demo
