packages/headless/src/controllers/search-box/headless-search-box.test.ts
packages/headless/src/controllers/search-box/headless-search-box.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.test.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.ts
packages/headless/src/features/analytics/analytics-actions.ts
packages/headless/src/features/query-suggest/query-suggest-analytics-actions.ts
packages/headless/src/test/mock-engine.ts

This PR makes the search-box log analytics just like in JSUI.
1. When selecting a suggestion from a search-box, only the suggestion click is logged, with no searchboxSubmit event.
2. When selecting a suggestion from a standalone search-box, only the redirect event is logged. The suggestion click is no longer logged, since this should happen when the redirect target page loads. There is no mechanism in place atm to do this. Will explore this in a dedicated PR,
I also added a `findAsyncAction` utility method on the mock-engine to make it easier to find these actions when writing unit tests.

fix(headless): prevent logging search box sumbit when clicking a query suggestion.

---

packages/atomic/package-lock.json
packages/atomic/package.json
packages/atomic/stencil.config.ts

I could not start atomic after updating `@stencil/sass` to `1.4.0` because rollup could not resolve global sass module imports (e.g. `@module-name`). Good news is the ionic team [published a fix](https://github.com/ionic-team/stencil-sass/commits/master) yesterday!
https://coveord.atlassian.net/browse/KIT-287

chore: update @stencil/sass to latest

---

packages/atomic/src/components/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/atomic-facet/atomic-facet.tsx
packages/headless/src/controllers/facets/category-facet/headless-category-facet.test.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/facets/facet/headless-facet.test.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/features/facets/facet-search-set/generic/generic-facet-search-actions.ts

With the previous way the destructuring was done, we'd get a copy of the original empty state for facet search.
Also fixed a problem with `isSpecificFacetSearchState`, because it would always evaluate to true if you had a CategoryFacet + Specific facet in the same page.
I also reworked how the facet search state was exposed on each controller:
```javascript
const facet = buildFacet(...)
// or select(),showMore() etc. All methods are still available
facet.search.search() 
// this was previously how you would reach the state for facet search
// this cause problem in your UI layer, since normally you subscribe to facet.state changes 
// and not facet.search.state changes
facet.search.state.values 
// I've changed it so the facet search state is included in the normal state object for …
```

fix(headless): fix facet search for headless controllers facet controllers

---

packages/atomic/src/components/atomic-category-facet/atomic-category-facet.spec.tsx
packages/atomic/src/components/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/atomic-category-facet/readme.md
packages/atomic/src/components/atomic-date-facet/atomic-date-facet.spec.tsx
packages/atomic/src/components/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/atomic-date-facet/readme.md
packages/atomic/src/components/atomic-facet/atomic-facet.spec.tsx
packages/atomic/src/components/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/atomic-facet/readme.md
packages/atomic/src/components/atomic-numeric-facet/atomic-numeric-facet.spec.tsx
packages/atomic/src/components/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/atomic-numeric-facet/readme.md
packages/headless/src/controllers/facets/_common/facet-id-determinor.test.ts
packages/headless/src/controllers/facets/_common/facet-id-determinor.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.test.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
packages/headless/src/controllers/facets/facet/headless-facet.test.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/controllers/facets/range-facet/headless-range-facet.test.ts
packages/headless/src/controllers/facets/range-facet/headless-range-facet.ts

Facet ids were being generated randomly in the atomic facets.
By deferring id generation to the controller, and exposing the facetId from the controller, the atomic facets no longer need to handle this. The facet id prop is updated after initializing the controller so that the facet manager can continue to access the ids to sort the facets.

feat(atomic,headless): set atomic facet's facetId to deterministic value from controller.

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/atomic-search-box/readme.md
packages/atomic/src/components/atomic-search-interface/readme.md
packages/headless/src/app/logger-middlewares.test.ts
packages/headless/src/app/logger-middlewares.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-actions.ts
packages/headless/src/utils/validate-payload.test.ts
packages/headless/src/utils/validate-payload.ts

https://coveord.atlassian.net/browse/KIT-309
I also serialized the SchemaValidationError, since that's what redux toolkit does for errors thrown inside thunks (consistency). It also prevents the serializability check middleware from warning us in the console.
Basically, we don't want an action with a validation error to dispatch, but we want to let other types of errors dispatch, such as API errors.
Jira had a query syntax example, hence why I added the enableQuerySyntax prop on the Atomic component.

fix(headless): logActionErrorMiddleware should only stop on SchemaValidationError

---

packages/headless/src/api/search/product-recommendations/product-recommendations-request.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts

[COM-696]
The Search API and ML teams looked into it and it is properly working now. No idea if this was just a mis-manipulation on my part or if something really changed in prod :shrug: 
[COM-696]: https://coveord.atlassian.net/browse/COM-696

fix(recommendations): remove maximum age from product recommendations

---

packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/features/facets/category-facet-set/category-facet-utils.ts
packages/headless/src/features/facets/facet-api/request.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-action-utils.test.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions-utils.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts
packages/headless/src/features/facets/generic/interfaces/generic-facet-response.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-selectors.test.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-selectors.ts

Goes hand in hand with https://github.com/coveo/coveo.analytics.js/pull/235
As for the problem with facet `title`, `position`, `displayValue` that we send to analytics possibly not being what is actually displayed in the app built on top of headless (because that's ultimately out of the control of headless), I asked in DNE slack channel, and got this answer: 
> displayValue and title are not essential, but they are used for debugging and understanding the date. I'd prefer that they'd be there if possible, and it's not the end of the world if they're not "perfect".
> As for facetPosition it's not used right now but I'd say that search impressions will have precedence over UA, so again, it's not the end of the world if it's not there.
> For position, we can send what we guess it will be …

fix(headless): fix facet state analytics

---

packages/headless/src/controllers/result-list/headless-result-list.ts

I moved the options annotations onto the type instead of the schema, similar to what we did with facets, and intellisense seems to work with it.

docs(headless): resultlist controller annotations

---

packages/atomic/src/components/atomic-did-you-mean/atomic-did-you-mean.tsx
packages/headless/src/features/search/search-actions.ts
packages/headless/src/features/search/search-slice.test.ts

https://coveord.atlassian.net/browse/KIT-312

fix(headless): get queryCorrections from fetched response instead of retried response

---

packages/headless/src/controllers/search-box/headless-search-box-options.ts
packages/headless/src/features/analytics/analytics-actions.ts
packages/headless/src/features/context/context-actions.ts
packages/headless/src/features/did-you-mean/did-you-mean-actions.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-actions.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-controller-actions.ts
packages/headless/src/features/facets/category-facet-set/category-facet-validate-payload.ts
packages/headless/src/features/facets/facet-search-set/category/category-facet-search-actions.ts
packages/headless/src/features/facets/facet-search-set/generic/generic-facet-search-actions.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-validate-payload.ts
packages/headless/src/features/facets/generic/facet-actions-validation.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-actions.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-validate-payload.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-actions.ts
packages/headless/src/features/fields/fields-actions.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts
packages/headless/src/features/query-set/query-set-actions.ts
packages/headless/src/features/query-suggest/query-suggest-actions.ts
packages/headless/src/features/recommendation/recommendation-actions.ts
packages/headless/src/utils/validate-payload.ts

`requiredEmptyString` for used only in `/facet` folder. Refactoring it so that all of `/features` have access to it to be more consistent. 
Also, I realized I didn't set the correct value initially. It had `emptyAllowed: true`. So I changed that 
Also created `requiredEmptyAllowedString` as well and used it in a few places to make it more consistent as well. 
The next thing would be the controllers, but I figured that could be done at the same time as the synchronization between `features` and `controller` validation to have only one source of truth as we mentioned a while ago.

refactor(headless): requiredNonEmptyString refactor

---

packages/atomic/src/templates/default.html
packages/headless/src/features/analytics/analytics-utils.ts

lots of thunks failed because the author was missing or the url wasn't a uri (e.g. file://)
https://coveord.atlassian.net/browse/KIT-340

fix(headless):  make validateResultPayload less strict 

---

packages/headless/src/controllers/facets/range-facet/date-facet/date-range.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.ts
packages/headless/src/controllers/facets/range-facet/headless-range-facet.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.ts

In this PR, I tried out not including any types for params and returns, and intellisense is still working correctly. Let me know if that approach makes sense.
However, I can't find where to document options so that they appear with intellisense- it doesn't seem to work the same way as the basic and category facets.

docs(headless): range facets documentation

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.spec.tsx
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/atomic-search-interface/readme.md
packages/atomic/src/global.css
packages/atomic/src/index.html
packages/atomic/src/utils/initialization-utils.spec.ts
packages/atomic/src/utils/initialization-utils.tsx
packages/atomic/stencil.config.ts

Regarding initialization
- Hide the interface content until Stencil initializes
- Adds a rudimentary loading state when Stencil is initialized but the interface is not "ready"
- When both the headless engine has been created & the strings have been loaded, it propagates the context to the sub-components, removing their loading states
Others
- Add language prop
https://coveord.atlassian.net/browse/KIT-243

feat(atomic): rework initialization process

---

.deployment.config.json

Variable is needed by the production release jenkins job, but is currently not passed through.
https://coveord.atlassian.net/browse/KIT-359

ci(headless): pass COMMIT_HASH to deployment pipeline prod release step

---

packages/headless/src/features/index.ts

This PR is in response to a [Discuss post](https://discuss.coveo.com/t/cant-find-facetactions-or-genericfacetactions/5028/4) asking if we could export the `DeselectAllFacets` action. I used the opportunity to also expose the Facet actions.
https://coveord.atlassian.net/browse/KIT-347

feat(headless): export deselectAllFacets action and Facet Actions

---

packages/headless/README.md

searchPageReducers and SearchPageState were renamed to searchAppReducers and SearchAppState. 
But the examples in the README were not updated.

feat(headless): rename searchPageReducers in README

---

packages/atomic/src/components/atomic-category-facet/atomic-category-facet.pcss
packages/atomic/src/components/atomic-component-error/atomic-component-error.pcss
packages/atomic/src/components/atomic-date-facet/atomic-date-facet.pcss
packages/atomic/src/components/atomic-did-you-mean/atomic-did-you-mean.pcss
packages/atomic/src/components/atomic-facet-manager/atomic-facet-manager.pcss
packages/atomic/src/components/atomic-numeric-facet/atomic-numeric-facet.pcss
packages/atomic/src/components/atomic-pager/atomic-pager.pcss
packages/atomic/src/components/atomic-query-error/atomic-query-error.pcss
packages/atomic/src/components/atomic-query-summary/atomic-query-summary.pcss
packages/atomic/src/components/atomic-result-list/atomic-result-list.pcss
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.pcss
packages/atomic/src/components/atomic-search-box/atomic-search-box.pcss
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.pcss
packages/atomic/src/components/atomic-tab/atomic-tab.pcss
packages/atomic/src/globals/global.pcss
packages/atomic/tailwind.config.js

KIT-378
https://coveord.atlassian.net/browse/KIT-378
We don't need the individual imports of Tailwind with shadow DOM disabled because all the components now have access to the global import of Tailwind. This speeds up the initial build quite a bit and prevents the DOM structure of `index.html` from getting too large in dev mode.

refactor(atomic): remove tailwind from each individual pcss file

---

packages/atomic/tailwind.config.js

KIT-377
https://coveord.atlassian.net/browse/KIT-377
Right now purge isn't running because process.NODE_ENV isn't by Stencil. I used is dev watch to enable/disable purge instead.

fix(atomic): fix purge css in prod

---

packages/headless/docs.config.json
packages/headless/docs/actions-parser.ts
packages/headless/docs/doc-json-parser.ts

I know actions are lower priority than controllers, but the logic was already almost complete in the old version of the parser, so I added it in here. We'll need to add the rest of the actions to the config as well.

docs(headless): implement actions parser

---

packages/headless/jest.config.js
packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/features/product-recommendations/product-recommendations-slice.test.ts
packages/headless/src/features/recommendation/recommendation-slice.test.ts
packages/headless/src/features/search/search-slice.test.ts

I had to modify some tests because the `.rejected` function to create a rejected async action is apparently an internal concern of RTK/not part of their API.
https://stackoverflow.com/a/65429810
https://coveord.atlassian.net/browse/KIT-401

feat(headless): bump rtk to 1.5.0

---

packages/headless/src/controllers/facets/facet/headless-facet.ts

I added the [state attribute](https://github.com/coveo/ui-kit/pull/482/files#diff-96f9b3bc380442a8d8022d8ca46d327f0b84e4407d328642b9d11a3cd7b4f6d4L102) to solve a tsc error when converting the facetSearch interfaces and forgot to remove it after finishing the conversion.
https://coveord.atlassian.net/browse/KIT-413

fix(headless): remove #state attribute from FacetSearch interface

---

packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-results-per-page/atomic-results-per-page.tsx
packages/atomic/src/components/atomic-sort-criteria/atomic-sort-criteria.tsx
packages/bueno/src/values/number-value.test.ts
packages/bueno/src/values/number-value.ts

We don't really need to reflect most props, I only kept facets ids and some search interface props such as pipeline, searchhub
https://coveord.atlassian.net/browse/KIT-404
also opened this issue on the stencil side https://github.com/ionic-team/stencil/issues/2828

fix(atomic,bueno): validate isNaN for NumberValue (bueno) and remove some reflected props (atomic)

---

packages/atomic/src/components/atomic-history/atomic-history.tsx
packages/headless/src/app/search-app-reducers.ts
packages/headless/src/app/undoable.test.ts
packages/headless/src/app/undoable.ts
packages/headless/src/controllers/history/headless-history.test.ts
packages/headless/src/controllers/history/headless-history.ts
packages/headless/src/features/advanced-search-queries/advanced-search-queries-slice.ts
packages/headless/src/features/context/context-slice.ts
packages/headless/src/features/facet-options/facet-options-slice.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.ts
packages/headless/src/features/facets/facet-order/facet-order-slice.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-set-slice.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-set-slice.ts
packages/headless/src/features/history/history-actions.ts
packages/headless/src/features/history/history-slice.test.ts
packages/headless/src/features/history/history-slice.ts
packages/headless/src/features/history/history-state.ts
packages/headless/src/features/pagination/pagination-slice.ts
packages/headless/src/features/pipeline/pipeline-slice.ts
packages/headless/src/features/query-set/query-set-slice.ts
packages/headless/src/features/query/query-slice.ts
packages/headless/src/features/search-hub/search-hub-slice.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/features/sort-criteria/sort-criteria-slice.ts

https://coveord.atlassian.net/browse/KIT-432
I basically removed the initial state inside undoable. The current history state is then “undefined” until a first “snapshot” is dispatched. Before it was calling “updateHistory” on every dispatch, now it only calls it on “snapshot”.
I scoped the action creators and types, passing them as options, this make the undoable plugin reusable and won’t trigger snapshot, undos, redos on other reducers.
I had to update the slices using history, preventing them to “change” is there is no history, realistically we would never even call “change” unless there is past/future.
Many tests will fail here, I'll have to refactor them in a separate branch, the current ones touches enough files 😅

fix(headless): refactored undoable to remove initial state and update only on snapshots

---

packages/headless/src/features/history/history-state.ts

Used the original history state design previous to the https://github.com/coveo/ui-kit/pull/498 PR. Removes the warnings, deconstructing the whole state on every search was a bit too intense performance-wise
https://coveord.atlassian.net/browse/KIT-442

fix(headless): remove history initial state deconstruction

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/mocks/mock-api-doc-comment.ts
packages/headless/doc-parser/src/controller-resolver.ts
packages/headless/doc-parser/src/entity-builder.ts
packages/headless/doc-parser/src/function-resolver.test.ts
packages/headless/doc-parser/src/interface-resolver.test.ts
packages/headless/src/controllers/context/headless-context.ts

This PR adjusts the Context controller to be able to retrieve it's documentation.

docs(headless): place documentation on Context controller interfaces

---

packages/headless/doc-parser/mocks/mock-obj-entity.ts
packages/headless/doc-parser/src/controller-resolver.ts
packages/headless/doc-parser/src/entity-builder.ts
packages/headless/doc-parser/src/entity.ts
packages/headless/doc-parser/src/extractor.test.ts
packages/headless/doc-parser/src/extractor.ts
packages/headless/doc-parser/src/function-param-resolver.ts
packages/headless/doc-parser/src/function-resolver.test.ts
packages/headless/doc-parser/src/function-resolver.ts
packages/headless/doc-parser/src/interface-resolver.test.ts
packages/headless/doc-parser/src/interface-resolver.ts

There is a practical limit on displaying a deeply nested interface containing members that have interface types and so on.
The general layout of a page is `Section | Heading | key | type` where `key` and `type` are displayed inside a table.
```
Section | Heading | key | type
Initialize | buildFacet | props | FacetProps
Facet | state | canShowMoreValues | boolean
Facet | state | values | FacetValue[]
```
In this case, displaying `canShowMoreValues` is no problem, but displaying `FacetProps` and `FacetValue` would not be easy. To follow the pattern, they would need to be extracted to start a new chain.
This PR pulls out complex types on Interfaces and places them in an `extractedTypes` array. These will be displayed at the bottom of the reference under a dedicated section. e.g.
```
Types | …
```

docs(headless): extract complex types into dedicated array

---

packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/api/analytics/product-recommendations-analytics.ts
packages/headless/src/api/analytics/shared-analytics.ts
packages/headless/src/api/search/plan/plan-request.ts
packages/headless/src/api/search/product-recommendations/product-recommendations-request.ts
packages/headless/src/api/search/query-suggest/query-suggest-request.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-params.ts
packages/headless/src/api/search/search/search-request.ts
packages/headless/src/app/headless-engine.ts
packages/headless/src/features/configuration/configuration-actions.ts
packages/headless/src/features/configuration/configuration-slice.test.ts
packages/headless/src/features/configuration/configuration-slice.ts
packages/headless/src/features/configuration/configuration-state.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts
packages/headless/src/features/query-suggest/query-suggest-actions.ts
packages/headless/src/features/redirection/redirection-actions.ts
packages/headless/src/features/search-parameters/search-parameter-actions.ts
packages/headless/src/features/search-parameters/search-parameter-schema.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/test/mock-search-request.ts

I've added support for a new query parameter called "locale".
https://docs.coveo.com/en/1461/build-a-search-ui/query-parameters#RestQueryParameters-locale
At the same time, I used that same parameter for the `analytics` parameter, by extracting the first part of the `locale`.
So: 
locale = search API parameter.
language = Analytics parameter
if locale == "en-US", then language = "en".
if locale == "fr-CA", then language = "fr".
And so on.
This can be configured with the global configuration option, under the `search` section.
https://coveord.atlassian.net/browse/KIT-447

feat(headless): add support for locale parameter + analytics language

---

packages/headless/src/controllers/facet-manager/headless-facet-manager.test.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/utils/facet-utils.ts

https://coveord.atlassian.net/browse/KIT-476
For instance, say you sorted `[facetA, facetB, facetC]` and only `facetB` was part of the last search response, then only `[facetB]` would be returned. With this change, `[facetB, facetA, facetC]` would be returned.

feat(headless): made facet manager's sort results include every payload

---

packages/headless/doc-parser/doc-parser.ts
packages/samples/headless-react/src/App.tsx
packages/samples/headless-react/src/components/facet-manager/facet-manager.class.tsx
packages/samples/headless-react/src/components/facet-manager/facet-manager.fn.tsx
packages/samples/headless-react/src/components/facet/facet.class.tsx
packages/samples/headless-react/src/components/facet/facet.fn.tsx

[https://coveord.atlassian.net/browse/KIT-420](https://en.wikipedia.org/wiki/420_(cannabis_culture))
Functional and class components are implemented differently, in those samples. The class component requires its child facets to include a facetId, while the functional component can read the facetId from the controllers of its children.
If you intend to test this PR locally, it may not work without https://github.com/coveo/ui-kit/pull/548.

docs(headless): add React sample for facet manager

---

packages/atomic/src/components/atomic-query-summary/atomic-query-summary.pcss
packages/atomic/src/components/atomic-query-summary/readme.md
packages/atomic/src/components/atomic-result/atomic-result.tsx
packages/atomic/src/components/result-template-components/atomic-result-excerpt/atomic-result-excerpt.tsx
packages/atomic/src/components/result-template-components/atomic-result-value/atomic-result-value.tsx
packages/atomic/src/templates/default.html
packages/atomic/src/utils/result-utils.ts

Was already the case for other components like field condition & result value... not sure if it's necessary for result link
https://coveord.atlassian.net/browse/KIT-474

feat(atomic): remove atomic-result-excerpt component from DOM when empty

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/src/extractor.test.ts
packages/headless/doc-parser/src/extractor.ts
packages/headless/doc-parser/src/interface-resolver.ts

Two fixes here. First, functions within objects weren't having their types extracted; that's fixed in extractor.ts. Then, I realized that the typeName being extracted didn't include the generics. Turns out you _can't_ include them when using the `findApi` method, but we do still need to display them on the docs site, so I adjusted interface-resolver.ts so that both type names (with and without generics) are extracted.
If you run the parser, you should notice that `SpecificFacetSearchResult` is extracted from the `facetSearch.select` method and that `FacetManagerPayload<T>` now includes the `<T>`, neither of which happened before.

docs(headless): bug fix in doc parser

---

packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet-options.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/interfaces/request.ts

https://coveord.atlassian.net/browse/KIT-495
I missed [this comment](https://github.com/coveo/ui-kit/pull/575#discussion_r586704075) in a previous PR.

docs(headless): removed redundant NumericFacetValueOption interface

---

packages/headless/doc-parser/src/interface-resolver.ts

This is a quick, _temporary_ fix to the parser that prevents it from trying to resolve the first object in a union type.
Properly resolving union types is going to be a much bigger refactor, so Sami and I decided to hold off on that for now. But, the parser was already attempting to resolve (and then extract) the first type in a union if it was an object, and it wasn't working properly. It's better to have missing docs than incorrect docs, so this fix just makes the parser resolve union types on properties as primitives.
(As discussed with Sami, I didn't make the same temporary fix for methods because there were no instances of union types occurring there. If we run into one before the bigger refactor, we'll make another temporary fix then.)

docs(headless): resolve union types in properties as primitives

---

packages/headless/src/controllers/facet-manager/headless-facet-manager.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.ts
packages/headless/src/features/facets/range-facets/generic/interfaces/request.ts

Just a quick PR to fix some small issues I found while generating the documentation. I fixed a typo in FacetManager and made some last adjustments to NumericFacet that were missed during the initial flattening.
All Headless unit tests passed after my changes, and the documentation now parses correctly; let me know if there's any other check I need to do.

docs(headless): source code fixes for documentation extraction

---

packages/atomic/cypress/integration/facet-standard.cypress.ts
packages/atomic/cypress/integration/facet-utils.ts
packages/atomic/cypress/integration/pager.cypress.ts
packages/atomic/cypress/integration/sort-dropdown.cypress.ts

https://coveord.atlassian.net/browse/KIT-507
Sort
- Add check for URL
- Add check for sort with field QRE generated correctly
- Add more check for invalid sort-criteria field
Pager
- Add check for 'disable-navigation' button when go to page 2
Facet
- Remove async when function is not async/await

test(atomic): Add more cypress tests for sort & pager components

---

packages/headless/doc-parser/src/tsdoc-emitter.test.ts
packages/headless/doc-parser/src/tsdoc-emitter.ts

Previously, descriptions were stripped of all their leading/trailing whitespace, which included removing newlines between paragraphs. The code I've added re-inserts newlines between paragraphs, allowing for proper display on the docs site.

docs(headless): handle multi-paragraph descriptions

---

packages/headless/doc-parser/mocks/mock-entity-with-type-alias.ts
packages/headless/doc-parser/src/entity.ts
packages/headless/doc-parser/src/interface-resolver.test.ts
packages/headless/doc-parser/src/interface-resolver.ts

The intent behind the change is to help the doc-generation scripts render attributes when their type is a resolved type alias.
@kaitlynkatz, I will wait for your confirmation before merging.
https://coveord.atlassian.net/browse/KIT-526

docs: label primitive entities holding a type alias

---

packages/headless/src/api/search/search/product-recommendation.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/product-recommendations/headless-base-product-recommendations.ts
packages/headless/src/controllers/product-recommendations/headless-cart-recommendations.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts
packages/headless/src/features/product-recommendations/product-recommendations-slice.test.ts
packages/headless/src/features/product-recommendations/product-recommendations-state.ts
packages/headless/src/test/mock-product-recommendation.ts

I changed the type from an alias to an interface to allow the tool to pick it up and resolve it. I used the opportunity to export the longer `ProductRecommendation` since I felt `Product` was too vague.
https://coveord.atlassian.net/browse/KIT-527

docs: export as ProductRecommendation interface instead of Product type

---

packages/headless/doc-parser/src/interface-resolver.test.ts
packages/headless/doc-parser/src/interface-resolver.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.ts

The parser was only filtering members that already existed at the top-level interface. This PR adjusts the logic to filter duplicates among inherited interfaces.
Example:
```
interface A extends B, C {}
```
If `B` and `C` both have the member `bar`, it will now only be included once as a member of A.
Once this PR is merged, I will start a ui-kit release and we will publish docs shortly afterward.

docs: filter duplicate inherited members

---

packages/atomic/src/components/atomic-frequently-bought-together/atomic-frequently-bought-together.tsx
packages/headless/src/api/search/product-recommendations/product-recommendations-request.ts
packages/headless/src/api/search/search/product-recommendation.ts
packages/headless/src/controllers/product-recommendations/headless-base-product-recommendations.test.ts
packages/headless/src/controllers/product-recommendations/headless-base-product-recommendations.ts
packages/headless/src/controllers/product-recommendations/headless-cart-recommendations-options.ts
packages/headless/src/controllers/product-recommendations/headless-frequently-bought-together.ts
packages/headless/src/controllers/product-recommendations/headless-popular-bought-recommendations.ts
packages/headless/src/controllers/product-recommendations/headless-popular-viewed-recommendations.ts
packages/headless/src/controllers/product-recommendations/headless-user-interest-recommendations.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts
packages/headless/src/features/product-recommendations/product-recommendations-slice.test.ts
packages/headless/src/features/product-recommendations/product-recommendations-slice.ts
packages/headless/src/features/product-recommendations/product-recommendations-state.ts
packages/headless/src/test/mock-product-recommendation.ts

And rename the product recommendations fields
The core of the discussion is here: https://discuss.coveo.com/t/product-recommendations-mapping-filtering-out-fields/5400
Basically, we want to allow retrieving other fields than the Commerce Standard Fields, but also make it clear that they are not from the standard.
So you can now request "additionalFields" which will be returned in the "additionalFields" object.
We also renamed the properties so that they match what fields they come from. It was more confusing than helping, really.
[COM-918]
[COM-918]: https://coveord.atlassian.net/browse/COM-918

feat(productrecommendations): allow adding additional fields

---

packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx

Without this the text was overflowing outside the button
KIT-545
https://coveord.atlassian.net/browse/KIT-545

fix(atomic): fixed overflow on breadcrumbs

---

packages/headless/src/controllers/result-list/headless-result-list.test.ts

https://coveord.atlassian.net/browse/KIT-557
Tests were occasionally throwing this error, so I used jest timers instead.

test(headless): improved fetchMoreResults tests

---

packages/headless/doc-parser/src/entity-builder.test.ts
packages/headless/doc-parser/src/entity-builder.ts
packages/headless/doc-parser/src/entity.ts
packages/headless/src/api/search/facet-search/base/base-facet-search-request.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet-options.ts
packages/headless/src/controllers/facets/facet/headless-facet-options.ts
packages/headless/src/controllers/facets/range-facet/date-facet/date-range.ts
packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet-options.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet-options.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/numeric-range.ts
packages/headless/src/controllers/pager/headless-pager.ts
packages/headless/src/controllers/product-recommendations/headless-cart-recommendations-options.ts
packages/headless/src/controllers/recommendation/headless-recommendation.ts
packages/headless/src/controllers/result-list/headless-interactive-result.ts
packages/headless/src/controllers/search-box/headless-search-box-options.ts
packages/headless/src/features/facets/category-facet-set/interfaces/request.ts
packages/headless/src/features/facets/facet-api/request.ts
packages/headless/src/features/facets/facet-set/interfaces/request.ts
packages/headless/src/features/facets/range-facets/generic/interfaces/request.ts
packages/headless/src/features/recommendation/recommendation-state.ts

The goal was to extract default values for controller options but also minimums/maximums. As it turns out, the API extractor tool doesn't handle custom tags like `@default` and `@minimum`. Fortunately, it does properly parse the `@defaultValue` tag.
So, I switched all `@default` tags to `@defaultValue` and added code backticks around the values so that the parser can parse them. I also removed the `@minimum` tags (there were no maximums) and incorporated them into the summary. If custom tags are implemented in the API extractor tool at a later date (it seems to be in progress now), we can move min/max back into a tagged annotation and extract them then.

docs(headless): extract default values for controller options

---

package-lock.json
package.json
packages/headless/package-lock.json
packages/headless/package.json

Running `npm start` was not correctly starting the headless project due to the `npx` invokation. The PR fixes the issue by placing `concurrently` in the headless package.json.
I also add a new `dev` command in the root that just starts the atomic/headless projects.

chore: improve dev workflow

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx

Other possible solution, with no `pre` tag: 
```
suggestion.highlightedValue.replace(/\s/g, '&nbsp;')
```
https://coveord.atlassian.net/browse/KIT-593

fix(atomic): fix query suggestions whitespace

---

packages/headless/src/api/platform-service-params.ts
packages/headless/src/api/search/facet-search/base/base-facet-search-request.ts
packages/headless/src/api/search/facet-search/facet-search-request.ts
packages/headless/src/api/search/html/html-request.ts
packages/headless/src/api/search/plan/plan-request.ts
packages/headless/src/api/search/product-recommendations/product-recommendations-request.ts
packages/headless/src/api/search/query-suggest/query-suggest-request.ts
packages/headless/src/api/search/recommendation/recommendation-request.ts
packages/headless/src/api/search/search-api-client.ts
packages/headless/src/api/search/search-api-params.ts
packages/headless/src/api/search/search/search-request.ts

https://coveord.atlassian.net/browse/SFINT-3836
For the Case Assist, we'll need to add a CaseAssistAPIClient. In order to invoke this client, we'll need to pass some request parameters that are already defined for the SearchAPIClient.
In order to better share request parameters between the different API clients, this PR moves the common request parameters into the `platform-service-params.ts` file.

chore(headless): share request parameters

---

packages/atomic/src/index.html

Did some tweaks to the grid to get the search box correctly aligned with search results + gray header (previously added)
https://coveord.atlassian.net/browse/KIT-619

feat(atomic): styling default page search box alignment with results

---

packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.pcss
packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.tsx
packages/atomic/src/images/arrow-right.svg
packages/atomic/src/themes/default.css

* Smaller text for printable uri
* Use svg icon for separator
* Remove css var atomic-separator (used only for this component from what I can see)
https://coveord.atlassian.net/browse/KIT-615

feat(atomic): styling changes for printable uri

---

packages/headless/src/app/headless-engine.test.ts
packages/headless/src/app/headless-engine.ts
packages/headless/src/app/reducer-manager.test.ts
packages/headless/src/app/reducer-manager.ts
packages/headless/src/app/reducers.ts
packages/headless/src/app/store.ts
packages/headless/src/controllers/facets/facet/headless-facet.test.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/controllers/pager/headless-pager.test.ts
packages/headless/src/controllers/pager/headless-pager.ts
packages/headless/src/test/mock-engine.ts
packages/headless/src/utils/errors.ts

The goal of this PR is to simplify Headless configuration. Rather than asking a developer to specify reducers, they would be added dynamically when instantiating a controller. Some benefits of the approach are:
- Less configuration for Typescript users. The `reducers` option when instantiating an engine would eventually become optional.
- Reduces the chance of errors for javascript users. The state of the engine argument on controllers can be empty.
- Smaller bundles. Only the instantiated controllers and their corresponding reducers will be included in the bundle. At the moment, all the reducers in `searchAppReducers` are included, whether or not the feature set is being used.
Inspiration: https://redux.js.org/recipes/code-splitting#using-a-reducer-manager

chore(headless): dynamically load reducers

---

packages/headless/src/features/facets/facet-search-set/facet-search-reducer-helpers.test.ts
packages/headless/src/features/facets/facet-search-set/facet-search-reducer-helpers.ts

Consistent behaviour because updating a text with an empty string would set the query to `**`.
The issue was that for a hierarchical facet search, an empty string without wildcards returned no values, meanwhile it did for a specific facet search. I mentioned this bug to the API for v4.
https://coveord.atlassian.net/browse/KIT-601

fix(headless): add wildcards in facet search initially query

---

packages/headless/src/app/frequently-bought-together-app-reducers.ts
packages/headless/src/app/recommendation-app-reducers.ts
packages/headless/src/app/reducers.ts
packages/headless/src/app/search-app-reducers.ts
packages/headless/src/controllers/breadcrumb-manager/headless-breadcrumb-manager.test.ts
packages/headless/src/controllers/breadcrumb-manager/headless-breadcrumb-manager.ts
packages/headless/src/controllers/context/headless-context.test.ts
packages/headless/src/controllers/context/headless-context.ts
packages/headless/src/controllers/did-you-mean/headless-did-you-mean.test.ts
packages/headless/src/controllers/did-you-mean/headless-did-you-mean.ts
packages/headless/src/controllers/facet-manager/headless-facet-manager.test.ts
packages/headless/src/controllers/facet-manager/headless-facet-manager.ts

Since this PR was getting large, I will split the changes across a few PRs.
This one converts: `breadcrumbManager`, `context`, `didYouMean` and `facetManager`.

chore: load reducers dynamically

---

packages/atomic/src/components/atomic-query-summary/atomic-query-summary.tsx
packages/atomic/src/components/facets/base-facet/base-facet.tsx
packages/atomic/src/index.html
packages/atomic/src/templates/default.html
packages/atomic/src/themes/default.css
packages/atomic/tailwind.config.js

+ Change printable uri font-size for default template to 0.8rem;
+ Change result link font-size for default template to 1.25rem;
+ Change excerpt line-height for default template to 1.5rem;
+ Change default font-weight bold for index.html to 600;
https://coveord.atlassian.net/browse/KIT-636

fix(atomic): add support for bold font weight variable

---

packages/atomic/cypress/integration/facets/category-facet-assertions.ts
packages/atomic/cypress/integration/facets/category-facet-selectors.ts
packages/atomic/cypress/integration/facets/category-facet.cypress.ts
packages/atomic/cypress/utils/componentUtils.ts
packages/atomic/cypress/utils/setupComponent.ts
packages/atomic/src/components/atomic-breadcrumb-manager/atomic-breadcrumb-manager.tsx
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-category-facet/readme.md
packages/atomic/src/components/facets/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/facets/atomic-date-facet/readme.md
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-facet/readme.md
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/readme.md
packages/atomic/src/components/facets/base-facet/base-facet.tsx
packages/atomic/src/components/facets/facet-search/facet-search.pcss
packages/atomic/src/components/facets/facet-search/facet-search.tsx
packages/atomic/src/utils/combobox.tsx
packages/atomic/src/utils/initialization-utils.spec.ts

https://coveord.atlassian.net/browse/KIT-629
(When I mean search & search box here, it's for the facet, not the atomic-search-box search)
**To recap:**
- Removed "show more button" in the facet search results
- We show more depending on the scroll position, the more we go down in the list, the more we fetch (like JSUI)
- The selected element is now always shown in scroll view when using the keyboard
- The selected element is reset when changing the query
- The query is now cleared when leaving the search box (like JSUI)
- We don't trigger a new search when selecting an element
- We hide the result when it's querying (loading) I'M NOT A SUPER FAN OF THIS ONE, [see my other comment](https://github.com/coveo/ui-kit/pull/730/files#r617012250)

fix(atomic): fix facet search scrolling & focus issues

---

packages/headless/case-assist/package.json
packages/headless/contributors/adding-a-sub-package.md

Lerna version bump throws an error when it detects a package.json with no version field that is not private.
```
lerna ERR! ENOVERSION A version field is required in case-assist's package.json file.
lerna ERR! ENOVERSION If you wish to keep the package unversioned, it must be made private.
```
https://coveord.atlassian.net/browse/KIT-639

chore: mark case-assist package private to resolve lerna version bump error

---

packages/atomic/src/index.html
packages/atomic/src/templates/default.html

Very incomplete, but for v0 it should be "good enough" I guess.
I did all of that only in index.html/default.html, but for v1 we will obviously need to revisit how we want to do responsiveness, especially if we want to move components around/reorder them completely when the screen size changes.
It's not like the mockups on figma, because this would have required much more important changes for all facets + facet manager + a way to move re-order components in the page with JS.
https://coveord.atlassian.net/browse/KIT-644

feat(atomic): v0 reponsive style

---

packages/headless/src/app/headless-engine.test.ts
packages/headless/src/app/headless-engine.ts

`this.logger` is called inside `this.validateConfiguration` when there's an error in the config.
Net result before fix: Engine creation fails (that's ok, it's invalid) but you can't see a nice log message that explains why.
https://coveord.atlassian.net/browse/KIT-646

fix(headless): fix create engine logger before validation

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/src/headless-export-resolvers/action-loader-resolver.ts
packages/headless/doc-parser/src/headless-export-resolvers/controller-resolver.ts
packages/headless/doc-parser/src/headless-export-resolvers/initializer-resolver.ts
packages/headless/doc-parser/src/interface-resolver.test.ts
packages/headless/doc-parser/src/interface-resolver.ts
packages/headless/src/features/index.ts
packages/headless/src/features/search/search-actions-loader.ts

This PR is a PoC show-casing a way to retrieve actions in headless v1.
Rather than exporting namespaces, headless would provide a series of `load<featureName>Actions` functions that take one parameter: the engine. The function would attach the necessary reducers, and return an object containing the actions relevant to the feature.
Usage:
```
const {interfaceLoad} = loadAnalyticsSearchActions(engine);
const {executeSearch} = loadSearchActions(engine);
engine.dispatch(executeSearch(interfaceLoad()));
```
The PoC also documents the `load` function. Since it is similar to a controller function, it was possible to reuse the existing code with only minor tweaks.
<details>
<summary>JSON output  for <code>loadSearchActions</code></summary>
```json
"actionLoaders": [
{
"initializer": {
"kind": …
```

feat: add loadSearchActions

---

packages/headless/src/api/search/search/product-recommendation.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions.ts

According to the data standard, `ec_thumbnails` should be an array and not a string.
[COM-1014]
[COM-1014]: https://coveord.atlassian.net/browse/COM-1014

fix(headless): make ec_thumbnails array

---

packages/headless/src/features/facet-options/facet-options-actions-loader.ts
packages/headless/src/features/facet-options/facet-options-actions.ts

Keeping `loadFacetOptions` internal, since the action was never exposed. I will refactor to use the load functions inside the controllers in a future PR. 

chore: add loadFacetOptions function

---

packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.pcss
packages/atomic/src/templates/default.html

https://coveord.atlassian.net/browse/KIT-649

fix(atomic): prevent result template  text elements from overflowing

---

packages/quantic/README.md

@tedre191 I noticed just a few lines below that there was already a command to supposedly export to a SF org, but it did not mention the copy:staticresources, so it was likely wrong. So I removed it and created a new section as we had discussed.
Also, I thought I could reuse some paragraphs I had written elsewhere (https://github.com/coveo/ui-kit/compare/DOC-8874) about what is Quantic and when to use it, but I realized that it really depends on it being available as an unmanaged package, so I can't really use it here, and I think it's best that I just wait until it is indeed available as an unmanaged package.
Let me know if that all makes sense, and thank you :D

doc(quantic): explain how to push in readme

---

.github/dependabot.yml

The intent behind this change is to be able to merge dependabot PRs directly, without needing to adjust the commit message [Ref](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#commit-message).
https://coveord.atlassian.net/browse/KIT-675

chore: configure dependabot commit-message prefix

---

.github/dependabot.yml

Reverting my change because there is a 15 character limit on the prefix:
https://github.com/coveo/ui-kit/runs/2555975457

chore: shorten dependabot prefix to below 15 character limit

---

packages/headless/src/features/facets/facet-search-set/category/category-facet-search-set-slice.ts
packages/headless/src/features/facets/facet-search-set/facet-search-reducer-helpers.test.ts
packages/headless/src/features/facets/facet-search-set/facet-search-reducer-helpers.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-set-slice.ts
packages/headless/src/test/mock-category-facet-search.ts
packages/headless/src/test/mock-facet-search.ts

https://coveord.atlassian.net/browse/KIT-655
We have potential race condition problems for all Search API requests except the /search endpoint, which is the only one with an abort mechanism.
I’m focusing here on an issue with the /facetSearch & /querySuggest endpoints. Both are used in set slices and usually called often (on keypress). This means that technically multiple requests could be happening simultaneously and resolving different results for different slices, that’s good. The problems are:
- Both those slices also have “clear” actions, which empty the results. If a request fulfills after the clear has been dispatched, it will fill up the results again.
- If the API happens to be slower on a first request but not a second, we could see the wrong results appear.
The solution is to …

fix(headless): prevent facet search race conditions

---

lerna.json
packages/samples/atomic/package.json
packages/samples/headless-react/package.json
scripts/deploy/bump-version.js

https://coveord.atlassian.net/browse/KIT-686
It looks like the CI is trying and failing to graduate every package due to some packages not having a version. It looks like previously it was only graduating packages with `-alpha`.

ci: added package names to conventional-graduate parameter

---

Jenkinsfile

https://coveord.atlassian.net/browse/KIT-700
Lerna was trying to bump the version of atomic-loader because it doesn't have `"private": true`. However, we can't add `"private": true` to it because it's generated by Stencil.
Instead of trying to exclude it manually, I made the CI clean untracked changes before bumping the version, which should delete atomic-loader.
Before:

ci: cleaned untracked changes before bumping version

---

packages/samples/atomic/package.json
packages/samples/headless-react/package.json

https://coveord.atlassian.net/browse/KIT-705
Packages with `"private": true` don't get a version bump, which was intended. However, when their versions aren't bumped, their dependencies neither.
`--no-private` is still necessary to exclude sub-packages with no dependencies like `case-assist`.

ci: removed `private` from samples `package.json`

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/configuration/configuration-actions.ts
packages/headless/src/features/configuration/search-configuration-actions-loader.ts
packages/headless/src/features/index.ts

I did not want to group this action with `loadConfigurationActions`, because it is specific to the search app use-case. It loads reducers that may not be relevant to other cases (e.g. product recommendations do not use `pipeline`).
This PR exposes the action using a dedicated loader function.
https://coveord.atlassian.net/browse/KIT-663

feat(headless): expose updateSearchConfiguration via dedicated loader function

---

packages/headless/src/features/analytics/analytics-utils.test.ts
packages/headless/src/features/analytics/analytics-utils.ts

First I thought we had an issue with the default fields to include that we request to the API, but I realized that in JSUI, we use the `source` field to map it to `sourceName` for click event payload in UA.
And `source` is correctly included in the default list of fields to include.
`sourceName` is also a mandatory parameter for UA, otherwise the event gets rejected.
https://coveord.atlassian.net/browse/KIT-713

fix(headless): fix invalid field usage for sourceName click event

---

packages/headless/doc-parser/doc-parser.ts
packages/headless/src/features/analytics/analytics-actions.ts
packages/headless/src/features/analytics/custom-analytics-actions-loader.ts
packages/headless/src/features/analytics/generic-analytics-actions-loader.ts
packages/headless/src/features/analytics/index.ts

While refactoring to expose analytics actions via loader functions, I left out certain lower level actions like `logClickEvent` and `logSearchEvent` since there are higher level actions that can be used instead (if there is a need to expose the low-level action, please let me know).
On the other hand, `logCustomEvent` would be useful to a dev wanting to send additional information, This PR exposes the action using the new loader function approach.

feat(headless): expose logCustomEvent via loader function

---

packages/quantic/coveo.d.ts
packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
packages/quantic/force-app/main/default/lwc/quanticHeadlessLoader/__tests__/headlessLoader.test.js
packages/quantic/force-app/main/default/lwc/quanticHeadlessLoader/quanticHeadlessLoader.js
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js
packages/quantic/force-app/main/default/lwc/quanticPager/quanticPager.js
packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.js
packages/quantic/force-app/main/default/lwc/quanticResultList/quanticResultList.js
packages/quantic/force-app/main/default/lwc/quanticResultsPerPage/quanticResultsPerPage.js
packages/quantic/force-app/main/default/lwc/quanticSearchBox/quanticSearchBox.js
packages/quantic/force-app/main/default/lwc/quanticSort/quanticSort.js
packages/quantic/force-app/main/default/lwc/quanticSummary/quanticSummary.js
packages/quantic/force-app/main/default/lwc/testUtils/coveoHeadlessStub.js

The `HeadlessEngine` class is deprecated, in favor of engines dedicated to each use-case. This PR refactors to use `buildSearchEngine`.
https://coveord.atlassian.net/browse/KIT-726

chore(quantic): migrate quantic to search engine

---

.deployment.config.json
Jenkinsfile

https://coveord.atlassian.net/browse/KIT-724
With this PR, the CDN would no longer contain every patch version, it would only contain major and minor versions.
E.g.:
https://staticdev.cloud.coveo.com/atomic/latest/atomic.esm.js
https://staticdev.cloud.coveo.com/atomic/v0/atomic.esm.js
https://staticdev.cloud.coveo.com/atomic/v0.23/atomic.esm.js
https://staticdev.cloud.coveo.com/atomic/v0.22/atomic.esm.js
https://staticdev.cloud.coveo.com/atomic/v0.21/atomic.esm.js
Yay or nay?

ci: update ci to only upload major and minor versions

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-actions.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-assertions.ts
packages/atomic/cypress/integration/facets-v1/facet/facet-selectors.ts
packages/atomic/cypress/integration/facets-v1/facet/facet.cypress.ts
packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/atomic/src/themes/default.css

Heavily inspired and copied from the "legacy" facets tests, like the components, they will be removed for Atomic v1.
That's the first of a few PR covering tests, you can still see empty describe blocks
https://coveord.atlassian.net/browse/KIT-725

test(atomic): first cypress tests for facet v1

---

.deployment.config.json
Jenkinsfile

https://coveord.atlassian.net/browse/KIT-714
~~Also removed the now unnecessary `PRERELEASE` variable.~~

ci: added version to deployment package name

---

packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/utils/initialization-utils.spec.ts
packages/atomic/src/utils/initialization-utils.tsx

https://coveord.atlassian.net/browse/KIT-732
😩    That one was a bit of a pain to find.
Basically an intermittent race condition problem:
- The facet manager reorders facets from the DOM
- That causes them to disconnect & reconnect from the DOM from a web component's perspective
- I previously implemented an `unsubscribe` on `disconnectedCallback` and a  _re_`subscribe` on `connectedCallback`
- Sometimes it did not appear to resubscribe correctly and the facet remained frozen as it was not getting Headless updates anymore
- What I've done instead is remove that implementation and on `disconnectedCallback` I added a delay that checks if the component still exists and only unsubcribes then, moving components in the DOM won't cause any issues.

fix(atomic): unsubscribe controllers after delay, if element is still removed from the DOM

---

packages/headless/src/api/search/recommendation/recommendation-request.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-params.ts
packages/headless/src/api/search/search/search-request.test.ts
packages/headless/src/api/search/search/search-request.ts
packages/headless/src/features/folding/folding-actions.ts
packages/headless/src/features/recommendation/recommendation-actions.ts
packages/headless/src/features/search/search-actions.ts

I made the change for both the search and recommendation requests. I also sent the originLevel2 (tab) in the recommendation request.

fix(headless): send originLevel3 to searchapi using referrer parameter

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/formats/atomic-format-currency.tsx
packages/atomic/src/components/formats/atomic-format-number.tsx
packages/atomic/src/components/formats/atomic-format-unit.tsx
packages/atomic/src/components/formats/format-common.ts
packages/atomic/tsconfig.json

https://coveord.atlassian.net/browse/KIT-751
Upcoming work:
- add custom inputs
https://www.figma.com/file/BWSlnVeORhILh79Z2gSf1U/Atomic-v1?node-id=0%3A1
https://docs.google.com/document/d/1Mg-5Iuh88trrulUUYzfQh2npSboMhzvWkXzaMQDsUEs/edit#heading=h.soxpq1m179g6

feat(atomic): add formats for new numeric facet

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx

I believe using an event here is a clean solution, since the "scrollContainer" (the element to which you want to scroll back to) has only to be defined on the atomic-search-interface. Then many component can emit that same event and make the page scroll. The pagination is a no brainer, but for other element such as clicking facet values, or changing result per page.
Another solution is to emit the event when the page change (looking at the pagination state)
https://coveord.atlassian.net/browse/KIT-747

feat(atomic): scroll to top of the "scrollContainer" when interacting with Pager

---

packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.pcss
packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.pcss
packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets-v1/facet-common.pcss
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-date-facet/atomic-date-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/base-facet/base-facet.pcss
packages/atomic/src/pages/index.html

OOTB sets display:none on facets when they have no values.
This will allow implementation to hide a section of their UI when no facets are visible.
A downside is the class name, I did prepend atomic so it's not affect by a customer's css
https://coveord.atlassian.net/browse/KIT-746

feat(atomic): add "state" classes on facet for display management

---

packages/atomic/cypress/integration/facets/date-facet/date-facet.cypress.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet.cypress.ts

> I'm seeing a specific kind of cypress test is intermittently failing on Jenkins. The test is checking that the correct UA event is sent after deselecting all facet values. Sometimes it's the numeric, sometimes it's the date facet. Any thoughts as to what might be causing these tests to error?
The structure and a missing wait was probably causing the intermittent test failure. Now it's similar to the facet/category-facet which don't appear as flaky
https://coveord.atlassian.net/browse/KIT-792

test(atomic): improve date/numeric facet cypress flakiness

---

packages/atomic/cypress/integration/facets/date-facet/date-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet/facet-assertions.ts
packages/atomic/cypress/integration/facets/facet/facet-selectors.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet.cypress.ts

We have to be careful with tests with hardcoded value that rely on new data not being added, such as this new document, which bumped the position to 2
https://coveord.atlassian.net/browse/KIT-792

test(atomic): fix date/numeric facet cypress url test

---

packages/headless/src/controllers/triggers/headless-redirection-trigger.test.ts
packages/headless/src/controllers/triggers/headless-redirection-trigger.ts
packages/headless/src/features/redirection/redirection-actions.ts
packages/headless/src/features/redirection/redirection-analytics-actions.ts
packages/headless/src/features/redirection/redirection-slice.test.ts
packages/headless/src/features/triggers/trigger-analytics-actions.ts
packages/headless/src/features/triggers/triggers-state.ts

https://coveord.atlassian.net/browse/KIT-802
List of fixes:
- Changed `triggers.state.redirectTo: string | null` to `triggers.state.redirectTo: string`
- Added empty string test case
- Reformatted Controller test
- Question about logTriggerRedirect Action

fix(headless): fix Redirect Triggers

---

packages/quantic/package-lock.json
packages/quantic/package.json
packages/quantic/sfdx-project.json

https://coveord.atlassian.net/browse/SFINT-3951
This PR fixes 2 issues I got while doing the project setup to develop in Quantic.
1. The Salesforce API version had to be updated as scratch orgs are now using version 52.0.
2. The Jest unit tests are failing with the error below. Updating `sfdx-lwc-jest` fixed it.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object

fix(quantic): jest unit tests

---

packages/headless/config/api-extractor/base.json
packages/headless/config/api-extractor/recommendation.json
packages/headless/config/api-extractor/search.json
packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/use-cases/recommendation.ts
packages/headless/doc-parser/use-cases/use-case-configuration.ts
packages/headless/package.json
packages/headless/rollup.config.js
packages/headless/scripts/extract-documentation.js
packages/headless/src/features/recommendation/recommendation-click-analytics-actions-loader.ts
packages/headless/src/recommendation.index.ts

This PR adjusts the doc extraction and parsing to support `n` use-cases and extracts the recommendation use-case.
I will open a sister branch for product-recommendation,
https://coveord.atlassian.net/browse/KIT-809

docs(headless): extract recommendation use-case reference

---

packages/headless/doc-parser/doc-parser.ts

@dlutzCoveo is saying that it would be simpler for the doc scripts if the action loaders where stored under a key called `actions`, so I made the adjustment.
https://coveord.atlassian.net/browse/KIT-813

docs: store actionloaders under #actions key

---

packages/atomic/cypress/integration/search-engine.cypress.ts
packages/headless/package-lock.json
packages/headless/package.json
packages/headless/src/app/search-engine/search-engine.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.test.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.ts
packages/headless/src/features/analytics/analytics-actions.ts
packages/headless/src/features/analytics/search-analytics-actions-loader.ts
packages/headless/src/features/query-suggest/query-suggest-analytics-actions.ts

This PR tries to make it easier to implement the standalone search box use-case using headless:
1. The `logSearchFromLink` and `logOmniboxFromLink` actions are now available.
2. The `executeFirstSearch` accepts a search action, allowing a developer specify the analytics event associated with the first search.
3. The standalone search box controller provides the analytics cause and metadata.
I will create a doc article too, since developers will still need to manage the plumbing between the standalone page and the actual search page. Once available, we can link to it inside the reference,

feat(headless): improve standalone search box experience

---

packages/atomic/package.json
packages/bueno/package.json
packages/headless/package.json

Added a link to the repos in each package.json files to make it nicer for NPM users.
One choice I took was to link to the leaf package instead of the root one, but both are valid IMO.
Having `homepage` filled out will provide a link to the repo, as shown for example in `@coveo/cra-template`

docs: ✏️ add homepage links to packages

---

.deployment.config.json
Jenkinsfile
JenkinsfileProductionRelease
JenkinsfileQARelease

~I initially was looking to speed up the pipeline with this jira by removing the build step in qa. After understanding the deployment config though, I realized it was needed to upload files to the CDN.~
I noticeed that the prd directory override path was equal to the default path though, so I removed it to tidy up the config.
I also removed the setup and build steps from QA and Prod because they do not seem to be needed. I crossed out my earlier observations because the s3 upload happens before the Jenkins job runs. This should speed up the pipeline by ~15-20 min.
Ref: https://tools-docs.dep.cloud.coveo.com/deployment-package/_static/schema_doc.html#phases_s3_prd
https://coveord.atlassian.net/browse/KIT-818

chore: improve release pipeline speed

---

packages/atomic/src/components/facets-v1/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets-v1/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets-v1/atomic-rating-facet/atomic-rating-facet.tsx

Stencil will accept any string, it won't automatically constrain the values. For props that aren't validated by headless controllers, we have to be careful and validate the string literals.
https://coveord.atlassian.net/browse/KIT-835

fix(atomic): add prop validation for Facets string literals

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/result-template-components/atomic-size-condition/atomic-size-condition.pcss
packages/atomic/src/components/result-template-components/atomic-size-condition/atomic-size-condition.tsx
packages/atomic/src/pages/v1.html

https://coveord.atlassian.net/browse/KIT-839
* [Design doc](https://docs.google.com/document/d/1NkSlX-w8p6BlrXICPWD-oM5Z7sMjgD9XOES-ldObrzY/view#heading=h.xbn6j3r37uiw)
Usage example:
```html
<atomic-size-condition maximum-width-inclusive="3rem">
<atomic-result-icon></atomic-result-icon>
</atomic-size-condition>
<atomic-size-condition minimum-width-exclusive="3rem">
</atomic-size-condition>
```
If you prefer, I can rebase this towards `master`.

feat(atomic): added atomic-size-condition component

---

packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.test.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ts
packages/headless/src/controllers/url-manager/headless-url-manager.test.ts
packages/headless/src/controllers/url-manager/headless-url-manager.ts

This PR refactors the `synchronize` parameter to the SearchParameterManager to make it available to devs creating custom url formats.

feat(headless): expose synchronize method on search parameter manager

---

packages/headless/src/controllers/search-status/headless-search-status.test.ts
packages/headless/src/controllers/search-status/headless-search-status.ts

https://coveord.atlassian.net/browse/KIT-833
https://discuss.coveo.com/t/pager-is-still-visible-when-error-raised/6191
A few things:
- I don't think changing the `handleRejectedSearch` of the search-slice method to always reset the response is the way to go. Sometimes it might reject because of an aborted request and in that case, we don't want our results to disappear.
- Modifying the search state controller only should fix the issue, I could go a step further and add a condition in the render method of the 2 components but I think it's a bit overkill here 😄

fix(headless): set hasResults to false when hasError is true

---

packages/atomic/src/components/result-template-components/atomic-result-text/atomic-result-text.tsx

https://coveord.atlassian.net/browse/KIT-862
Since this isn't substantially breaking and doesn't depend on v1 templates, I'm merging this towards `master`. If you prefer, I can always rebase to [KIT-749](https://coveord.atlassian.net/browse/KIT-749).

feat(atomic): added localization to atomic-result-text

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/facets-v1/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/facets-v1/atomic-rating-range-facet/atomic-rating-range-facet.tsx

https://coveord.atlassian.net/browse/KIT-859
made `endInclusive: false` for the rating facet and updated the display of the number of icons to match the start of the interval instead of the end
rating range facet now starts from 0 instead of 1:

fix(atomic): rating and rating range facet ranges end not inclusive

---

packages/headless/src/controllers/search-status/headless-search-status.test.ts
packages/headless/src/controllers/search-status/headless-search-status.ts
packages/headless/src/features/search/search-slice.test.ts
packages/headless/src/features/search/search-slice.ts

Moved from the controller's level to the slice's level
https://coveord.atlassian.net/browse/KIT-833

fix(headless): clear response/results when search contains an error

---

packages/headless/src/controllers/search-box/headless-search-box.test.ts
packages/headless/src/controllers/search-box/headless-search-box.ts
packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.test.ts
packages/headless/src/features/query-suggest/query-suggest-actions.ts
packages/headless/src/features/query-suggest/query-suggest-slice.test.ts
packages/headless/src/features/query-suggest/query-suggest-slice.ts
packages/headless/src/features/query-suggest/query-suggest-state.ts
packages/headless/src/test/mock-query-suggest.ts
packages/headless/src/test/mock-search-api-error-with-state-code.ts
packages/headless/src/test/mock-search-api-error-with-status-code.ts

This PR adds an `isLoadingSuggestions` property to the search box controller.
I also added defense in the query suggest slice against unregistered ids.

feat(headless): add isLoadingSuggestions to search box

---

JenkinsfileProductionRelease

I removed certain stages [as part of this PR](https://github.com/coveo/ui-kit/commit/6cde8a706ef18802539246bdfa99490b035f8df6#diff-29ea4805c4f5fd924d77d3fa0966f6c9d70d8c95cb8c4d66300150269e0f7354L9-L11) to speed up the pipeline. However, the `setup` stage is needed in prod since the publish script imports certain dependencies. 
https://coveord.atlassian.net/browse/KIT-879

ci: readd setup stage to prod release

---

packages/atomic/src/components/atomic-result-list/atomic-result-list.pcss
packages/atomic/src/components/atomic-result/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result/atomic-result.pcss
packages/atomic/src/components/result-template-components/atomic-result-icon/atomic-result-icon.pcss

https://coveord.atlassian.net/browse/KIT-876
Results with a large image on mobile will show the same style as list results with a large image on mobile.
Other changes in this PR include:
* Fixing some minor margin issues on the desktop grid layout
* Making icons keep a 1:1 aspect ratio
Previews with normal density:
<details>
<summary>Image size: small</summary>
</details>
<details>
<summary>Image size: icon</summary>
</details>
<details>
<summary>Image size: none</summary>
</details>

feat(atomic): added support for grid results on mobile

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-result-v1/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-row-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-row-mobile.pcss
packages/atomic/src/components/result-template-components-v1/atomic-result-fields-list/atomic-result-fields-list.pcss
packages/atomic/src/components/result-template-components-v1/atomic-result-fields-list/atomic-result-fields-list.tsx
packages/atomic/src/pages/v1.html

https://coveord.atlassian.net/browse/KIT-884
* [Design](https://www.figma.com/file/BWSlnVeORhILh79Z2gSf1U/Atomic-v1?node-id=430%3A80)
* [Live test](http://kit-884.herokuapp.com/)
The purpose of this component is to display as many fields as possible without exceeding its parent's boundaries. Additionally, this component adds a divider between each field.
In the future, a `display-show-more` option could be added that adds a "Show more" button.
<details>
<summary>Image</summary>
</details>
You can test it [here](http://kit-884.herokuapp.com/).

feat(atomic): added atomic-result-fields-list component

---

packages/atomic/src/components/facets-v1/category-facet-search-result/category-facet-search-result.tsx

https://coveord.atlassian.net/browse/KIT-895
Just had to set a width to the parent element to fix the overflow.

fix(atomic): fix text overflow on Category Facet

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.tsx

https://coveord.atlassian.net/browse/KIT-899
For some reason, I didn't think stencil supported or needed `key` :facepalm:

fix(atomic): made table refresh when sort or filters are changed

---

packages/atomic/src/components/atomic-result-v1/atomic-result-common.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-row-mobile.pcss
packages/atomic/src/themes/accessible.css
packages/atomic/src/themes/coveo.css

https://coveord.atlassian.net/browse/KIT-798
* The visual section is now always a 1:1 aspect ratio
* The visual section now has a light gray background color (same as the default badge background color), in case the image is transparent.
* The visual section now has a border radius

feat(atomic): gave opinionated style to visual section

---

packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts

I * think * this should be the desired behaviour: 
* Allow auto selection for all facets which are in an "inactive" mode (no selection) on initial search parameters restore.
* Prevent auto selection for all facets which are in an "active" mode (has selection) on initial search parameters restore.
The original discuss related to this problem: https://discuss.coveo.com/t/disable-preventautoselect-for-facets-with-headless/6017/6
https://coveord.atlassian.net/browse/KIT-774

fix(headless): fix prevent auto select when restoring facet search parameters

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/result-template-components-v1/atomic-result-number/atomic-result-number.tsx
packages/atomic/src/pages/v1.html

https://coveord.atlassian.net/browse/KIT-900
Removed old formatting props from the v1 result number and added support for formatting components.
E.g.:
```html
<atomic-result-number field="sncost">
<atomic-format-currency currency="CAD"></atomic-format-currency>
</atomic-result-number>
```

feat(atomic): added atomic-format-* support to atomic-result-number

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.tsx
packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx
packages/headless/src/controllers/folded-result-list/headless-folded-result-list.ts
packages/headless/src/controllers/result-list/headless-result-list.ts
packages/headless/src/features/search/search-slice.ts
packages/headless/src/features/search/search-state.ts
packages/headless/src/test/mock-search-state.ts

An alternative, perhaps less controversial, solution to https://github.com/coveo/ui-kit/pull/1103 
https://coveord.atlassian.net/browse/KIT-906

fix(atomic,headless): fix result rendering by adding searchResponseId

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list-dividers.pcss
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.pcss
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.tsx
packages/atomic/src/components/result-template-components-v1/atomic-result-fields-list/atomic-result-fields-list.tsx

https://coveord.atlassian.net/browse/KIT-948
* [list demo](https://ftohe.csb.app/)
* [table demo](https://htz09.csb.app/)
This change ensures that placeholders for results stay while results aren't done rendering. This causes a bit of movement in the rest of the UI though.

feat(atomic): keep placeholders while results are rendering

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.pcss

https://coveord.atlassian.net/browse/KIT-936
Once results reach the maximum width, they are centered like this:
<details>
<summary>List view</summary>
</details>
<details>
<summary>Grid view (767px)</summary>
</details>
<details>
<summary>Grid view (1023px)</summary>
</details>

feat(atomic): added maximum width for mobile list & grid results with large images

---

packages/headless/src/controllers/core/interactive-result/headless-core-interactive-result.ts
packages/headless/src/controllers/recent-results-list/headless-interactive-recent-result.test.ts
packages/headless/src/controllers/recent-results-list/headless-interactive-recent-result.ts
packages/headless/src/controllers/result-list/headless-interactive-result.test.ts
packages/headless/src/controllers/result-list/headless-interactive-result.ts
packages/headless/src/features/recent-results/recent-results-slice.ts

I misunderstood how the `wasOpened` was used before so the recentResults actions were being dispatched several times on each click as we have the event running on 3 handlers.
Unlike the regular result action, we want these to run when a result is clicked (once), regardless of if they've been clicked before, so I added a debounce to catch the extra dispatches instead.

fix(headless): added some debounce to click actions

---

packages/quantic/force-app/main/default/lwc/jsconfig.json
packages/quantic/force-app/main/default/lwc/quanticUtils/__tests__/quanticUtils.test.js
packages/quantic/force-app/main/default/lwc/quanticUtils/quanticUtils.js
packages/quantic/jest.config.js
packages/quantic/tsconfig.json

https://coveord.atlassian.net/browse/SFINT-4050
Opening the `exampleSearch` component using the `en-CA` locale raised this error.
Uncaught (in promise) TypeError: a.isPluralInLocale[i.default] is not a function
at Function.getLabelNameWithCount (quanticUtils.js:formatted:43)
at Q.get summaryLabel [as summaryLabel] (quanticSummary.js:4)
...
The reason is that the `I18nUtils` class was only handling `en-US` and `fr-CA` locales.
This PR fixes the issue by leveraging [Intl.PluralRules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules) to find out which plural rule applies in the current locale.

fix(quantic): pluralization with en-CA locale

---

packages/headless/package.json

Screenshot available in the jira for the webpack error this change solves.
https://coveord.atlassian.net/browse/KIT-952

fix(headless): specify dymanically required node bundle dependencies as peer dependencies

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result-v1/atomic-result-cell-mobile.pcss

https://coveord.atlassian.net/browse/KIT-925
<details>
<summary>Minimum width per result (mobile)</summary>
</details>
<details>
<summary>Maximum width per result (mobile)</summary>
</details>
<details>
<summary>Minimum width per result (desktop)</summary>
</details>
<details>
<summary>Maximum width per result (desktop)</summary>
</details>
<details>
<summary>Minimum width per result (desktop)</summary>
</details>
<details>
<summary>Maximum width per result (desktop)</summary>
</details>

feat(atomic): made grid results fill remaining screen width

---

packages/headless/src/controllers/pager/headless-product-listing-pager.ts
packages/headless/src/controllers/product-listing/pager/headless-product-listing-pager.test.ts
packages/headless/src/controllers/product-listing/pager/headless-product-listing-pager.ts
packages/headless/src/features/pagination/pagination-slice.test.ts
packages/headless/src/features/pagination/pagination-slice.ts
packages/headless/src/features/product-listing/product-listing-actions.ts
packages/headless/src/product-listing.index.ts

[COM-1185]
I tried to plug in the `pager` in my demo using Product Listing. I noticed a small change: page is 1 based in our API instead of 0 based, and I had to create a new pager from the core one that executes the right search.
That's pretty much it!
[COM-1185]: https://coveord.atlassian.net/browse/COM-1185

feat(commerce): support pagination in product listing engine

---

packages/headless/src/features/analytics/analytics-actions.ts
packages/headless/src/features/analytics/analytics-utils.ts

https://coveord.atlassian.net/browse/KIT-938

fix(headless): use origin level 2 for interface change analytics event

---

packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.pcss
packages/atomic/src/components/atomic-result-list-v1/atomic-result-list.tsx

https://coveord.atlassian.net/browse/KIT-980
When writing cypress tests for the new result list, I noticed that tests were very flaky; every ~60 tests, a `insertBefore` error would cause the entire result list to stop loading and fail tests.
I wasn't able to pinpoint the exact cause of the error, and experimenting with different ways to display placeholders & results under the same parent didn't lead anywhere.
Given that, in addition to this error, there [was another error when removing placeholders](https://coveord.atlassian.net/browse/KIT-969), I'm thinking this behaviour may not be very well supported by Stencil and I prefer to go for a CSS-only approach.
This change is simply reverting [some changes](https://github.com/coveo/ui-kit/pull/1137/commits/6fa4a14c0534b04413c72bbcab6cf56adefd …

fix(atomic): made result list not dynamically remove placeholders

---

packages/atomic/src/components/result-template-components-v1/atomic-result-multi-value-text/atomic-result-multi-value-text.pcss

**What's causing the issue?**
The `global.pcss` file contains a style that overrides the `font-size` set by the template section. This makes the font-size of multi-value text larger than `atomic-result-text`.
The `multi-value-text` component imports this file presumably for the base tailwind style overrides. The component uses `ul` and `li` tags, so without the overrides, the default bullet list styles show.
**Solution**
This PR scopes the import to only the base styles instead of the global styles.
https://coveord.atlassian.net/browse/KIT-982

fix(atomic): import only base styles to prevent font-size override

---

packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/pages/v1.html

For this fix, this depends on the layout of the page (different section in v1.html that are not part of Atomic itself).
I've added a toggle class on the host search interface element, so that different layout can leverage that class to determine how each section should react (in this case, display: none)
https://coveord.atlassian.net/browse/KIT-968

fix(atomic): add toggle on search interface host element on no results

---

packages/quantic/force-app/main/default/lwc/quanticRecentResultsList/quanticRecentResultsList.js

https://coveord.atlassian.net/browse/SFINT-4067
There was a typo in some localized label names breaking the Quantic components deployment.

fix(quantic): typo in label names

---

packages/atomic/cypress/integration/result-list/result-list-selectors.ts
packages/atomic/cypress/integration/result-list/result-list-utils.ts
packages/atomic/cypress/integration/result-list/result-list.cypress.ts
packages/atomic/src/components/atomic-result-list/atomic-result-list.pcss
packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/atomic-result-placeholder/atomic-result-placeholder.pcss

https://coveord.atlassian.net/browse/KIT-997
As far as I recall, the reason not to do this was that this results in a shadowDOM (results) in another shadowDOM (result list) and introduces too many parts for styling.
However, given that we can insert styling directly into result templates, I don't think this is too much of an issue, and I prefer that as opposed to leaking CSS classes. The `index.html` file (formerly v1.html) didn't need any change, all its styles still work with this change.

feat(atomic): made result list use shadowDOM

---

packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.js
packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.js
packages/quantic/force-app/main/default/lwc/quanticDidYouMean/quanticDidYouMean.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js
packages/quantic/force-app/main/default/lwc/quanticNoResults/quanticNoResults.js
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js
packages/quantic/force-app/main/default/lwc/quanticPager/quanticPager.js
packages/quantic/force-app/main/default/lwc/quanticQueryError/quanticQueryError.js
packages/quantic/force-app/main/default/lwc/quanticRecentQueriesList/quanticRecentQueriesList.js
packages/quantic/force-app/main/default/lwc/quanticRecentResultLink/quanticRecentResultLink.js
packages/quantic/force-app/main/default/lwc/quanticRecentResultsList/quanticRecentResultsList.js
packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.js
packages/quantic/force-app/main/default/lwc/quanticResultList/quanticResultList.js
packages/quantic/force-app/main/default/lwc/quanticResultsPerPage/quanticResultsPerPage.js
packages/quantic/force-app/main/default/lwc/quanticSearchBox/quanticSearchBox.js
packages/quantic/force-app/main/default/lwc/quanticSort/quanticSort.js
packages/quantic/force-app/main/default/lwc/quanticStandaloneSearchBox/quanticStandaloneSearchBox.js
packages/quantic/force-app/main/default/lwc/quanticSummary/quanticSummary.js
packages/quantic/force-app/main/default/lwc/quanticTab/quanticTab.js

- The @api decorator on the initialization function isn't necessary for us and AFAIK shouldn't be used by quantic users wrapping these components.
- (Personal preference alert) Arrow functions > binding. Can't remember why we were binding in the first place.

feat(quantic): refactoring of initalize functions

---

packages/atomic/src/components/facets/facet-value-box/facet-value-box.pcss

Since a 2px border is always going to change/affect the size of elements around it on selection,, there's a couple solution.
1- Change selected border to 1px. It makes it pretty "subtle" to see that a value is selected, however. 
2- Use an outline instead of a border. Outline cannot be rounded/cannot have border radius.
3- Box shadow, which is not * exactly * looking like a border, but I think it's "close enough".
https://coveord.atlassian.net/browse/KIT-1006

fix(atomic): change selected facet box from border to box-shadow

---

CODEOWNERS
README.md

[Codeowners documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
The current status of access to this repo:
Along with this, something to investigate: https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team
> By using code review assignments, any time your team has been requested to review a pull request, the team is removed as a reviewer and a specified subset of team members are assigned in the team's place. Code review assignments allow you to decide whether the whole team or just a subset of team members are notified when a team is requested for review.
https://coveord.atlassian.net/browse/KIT-1004

chore(all): update codeowner & readme

---

README.md
packages/headless/package.json
packages/headless/rollup.config.js

[COM-1202]
This is just an experiment I did, and it seemed to work pretty well, so let me know what you think!
Usage:  `npm run build -- --filter product-listing` would only build the `product-listing` package.
[COM-1202]: https://coveord.atlassian.net/browse/COM-1202

feat(core): allow building headless with a filter

---

packages/headless/src/features/recent-queries/recent-queries-slice.test.ts
packages/headless/src/features/recent-queries/recent-queries-slice.ts

trimming query string to avoid this:

fix(headless): trim query string before saving it in recent queries

---

packages/headless/src/app/product-listing-engine/product-listing-engine.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet-manager.ts
packages/headless/src/controllers/product-listing/headless-product-listing.test.ts
packages/headless/src/controllers/product-listing/headless-product-listing.ts
packages/headless/src/features/product-listing/product-listing-actions.ts
packages/headless/src/features/product-listing/product-listing-slice.test.ts
packages/headless/src/features/product-listing/product-listing-slice.ts
packages/headless/src/product-listing.index.ts

[COM-1202]
We were trying out the product listing in our demo environment and we needed all of this to properly render our result templates, so here we go :)
Should be simple enough, there are two commits with simple changes.
[COM-1202]: https://coveord.atlassian.net/browse/COM-1202

feat(productlisting): allow setting the additional fields + add facet manager and missing interfaces

---

packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.test.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.ts

Two changes to the `toggleCategoryFacetValue` action with this PR:
- It's now possible to deep select a category facet value if starting from a pristine state.
- If a category facet has an active path, it now gets overwritten by the new path instead of being a no-op.
Next step: support a string array as an argument.

fix(headless): support selecting deep category facet values

---

packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js

The bug happend when we insert text in the iput search of the facet, then we click collapse button and expand button => we got this error message 
I also add some other verification to avoid problem like we had this morning when the search results are null

fix(quantic): fix the facet when click on collapse/expand button

---

packages/atomic/.snyk

https://coveord.atlassian.net/browse/KIT-1022
Snyk issue: https://app.snyk.io/org/coveo-jsui/project/c9e8d9ee-3d2d-473c-91b3-4c38b42f2f50#issue-snyk:lic:npm:salesforce-ux:design-system:Unknown
Slack thread: https://coveo.slack.com/archives/GDGFC1C2W/p1632254742000800
The dependency seems to follow correct option https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license
```
{
"license" : "SEE LICENSE IN <filename>"
}
```
Other than ignoring the error, which is in some sense a false flag, I don't see a way to say "@salesforce-ux/design-system" is using X license. Open to other ideas...

fix(atomic): add .snyk file to ignore unknown @salesforce-ux/design-system license

---

packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.ts
packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-controller-actions.test.ts
packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-controller-actions.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-controller-actions.test.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-controller-actions.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-controller-actions.test.ts
packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-controller-actions.ts

[COM-1202]
After doing the category facet, I decided to split the date and numeric one even more. So here, I am simply removing `executeSearch` from the actions. 
I double-checked that they were not exposed to clients.
Next step is to create the "core" implementation of those components
[COM-1202]: https://coveord.atlassian.net/browse/COM-1202

feat(core): remove executeSearch from date and numeric facets actions

---

packages/headless/src/app/engine.test.ts
packages/headless/src/app/engine.ts
packages/headless/src/app/reducer-manager.test.ts
packages/headless/src/app/reducer-manager.ts

React logs a warning when a state change occurs while the `render` function is executing.
The state change happens because controllers call `addReducer`, which calls `replaceReducer`, which triggers a state update.
Since `addReducers` never supported overrides, it was possible to add an early return to avoid calling `replaceReducer` when all keys exist.
The approach is the same as the initial attempt to [solving the HMR bug](https://github.com/coveo/ui-kit/pull/1146#discussion_r698780946). One concern I had is it closes the door to overriding reducers. If overriding does becomes a requirement, we would need a dedicated `overrideReducers` method.
https://coveord.atlassian.net/browse/KIT-761

fix(headless): prevent state update when all reducer keys already exist

---

packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-facet.test.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-facet.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-filter.test.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-filter.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-facet.test.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-facet.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-filter.test.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-filter.ts
packages/headless/src/product-listing.index.ts

[COM-1285]
Pretty much a copy of the base headless ones, but using `fetchProductListing`
[COM-1285]: https://coveord.atlassian.net/browse/COM-1285

feat(productlisting): create product listing date and numeric ranges

---

packages/quantic/cypress/integration/example-search.cypress.ts
packages/quantic/cypress/integration/facets/facet-common-expectations.ts
packages/quantic/cypress/integration/facets/facet/facet-selectors.ts
packages/quantic/cypress/integration/facets/facet/facet.cypress.ts
packages/quantic/cypress/page-objects/example-search.ts
packages/quantic/cypress/page-objects/search.ts
packages/quantic/cypress/plugins/index.ts
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js

https://coveord.atlassian.net/browse/SFINT-4116
Some tests were missing for the quantic facet. This PR adds them along with some other improvements.
Added tests:
* load selected value from URL hash
* show more/less buttons
* facet with invalid field/no values
* invalid sorting
Other improvements:
* use specific selectors for expand and collapse
* moved facet search tests one level up (they were previously in the "selecting a value" block)
* added some new facet expectations

fix(quantic): improve/add missing quantic facet tests

---

.github/workflows/create-quantic-package.yml

https://coveord.atlassian.net/browse/SFINT-4104
The `SFDX_AUTH_CLIENT_ID` and `SFDX_AUTH_JWT_KEY` have been updated to use an organization better suited to create scratch orgs. However, the packaging workflow must use the same organization as before.
The packaging workflow now relies on `SFDX_AUTH_PACKAGE_CLIENT_ID` and `SFDX_AUTH_PACKAGE_JWT_KEY` secrets.
And it [works again](https://github.com/coveo/ui-kit/actions/runs/1288306902).

fix(quantic): fixed packaging credentials

---

packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.html
packages/quantic/force-app/main/default/lwc/quanticTab/quanticTab.js

set expression to default to empty string so we don't have to pass an empty string in props

feat(quantic): tab expression default

---

packages/quantic/force-app/main/default/lwc/jsconfig.json
packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.css
packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.html
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacetStyles/quanticFacetStyles.css
packages/quantic/force-app/main/default/lwc/quanticFacetValue/quanticFacetValue.css
packages/quantic/force-app/main/default/lwc/quanticFacetValue/quanticFacetValue.html
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.html
packages/quantic/force-app/main/default/lwc/quanticPill/quanticPill.css
packages/quantic/force-app/main/default/lwc/quanticPill/quanticPill.html
packages/quantic/force-app/main/default/lwc/quanticPill/quanticPill.js
packages/quantic/force-app/main/default/lwc/quanticPill/quanticPill.js-meta.xml
packages/quantic/force-app/main/default/lwc/quanticRecentQueriesList/quanticRecentQueriesList.html
packages/quantic/force-app/main/default/lwc/quanticRecentResultsList/quanticRecentResultsList.html
packages/quantic/tsconfig.json

Updated breadcrumb component to fix long string truncating behaviour and swap the "X" for an icon.
To do this we added a `quanticPill` component to avoid duplicated markup for each breadcrumb.
Named it "Pill" over breadcrumb because it could be used in different contexts as well.

fix(quantic): update to breadcrumb style

---

packages/headless/src/api/platform-client.test.ts
packages/headless/src/api/platform-client.ts
packages/headless/src/features/configuration/configuration-slice.test.ts

Luckily, we currently only use that function internally with "no parameter", which did return the correct default platform URL.
However, the function is exported globally in Headless (not 100% sure why, but 🤷 ), which means someone could have stumbled upon that bug.
I validated the correct endpoint and region available using https://platform.cloud.coveo.com/rest/global/regions (switching per environment).
The only valid external facing URL as far as Headless is concerned are the "main endpoint".
https://coveord.atlassian.net/browse/KIT-1064

fix(headless): fix platformURL exported function

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-query-suggestions/atomic-search-box-query-suggestions.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx
packages/atomic/src/components/search-box-suggestions/suggestions-common.ts
packages/atomic/src/images/clock.svg
packages/atomic/src/locales.json
packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.ts

**Part 1:** https://github.com/coveo/ui-kit/pull/1261
**Final Result:**

PART 2 - configurable query suggestions & recent queries

---

packages/headless/config/api-extractor/product-listing.json
packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/use-cases/product-listing.ts
packages/headless/src/api/commerce/product-listings/product-listing-api-client.ts
packages/headless/src/app/product-listing-engine/product-listing-engine-configuration.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet-manager.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.ts
packages/headless/src/controllers/product-listing/headless-product-listing.test.ts
packages/headless/src/controllers/product-listing/headless-product-listing.ts
packages/headless/src/controllers/product-listing/pager/headless-product-listing-pager.ts
packages/headless/src/controllers/product-listing/range-facet/date-facet/headless-product-listing-date-facet.ts
packages/headless/src/controllers/product-listing/range-facet/numeric-facet/headless-product-listing-numeric-facet.ts
packages/headless/src/controllers/product-listing/results-per-page/headless-product-listing-results-per-page.ts
packages/headless/src/controllers/product-listing/sort/headless-product-listing-sort.ts
packages/headless/src/features/product-listing/product-listing-actions.ts
packages/headless/src/features/product-listing/product-listing-state.ts
packages/headless/src/features/sort/sort-actions-loader.ts
packages/headless/src/product-listing.index.ts
packages/samples/headless-react/src/components/product-listing/product-listing.fn.tsx
packages/samples/headless-react/src/context/engine.ts

I think this is all :thinking: 
There were a lot of jsdoc that was carried over from the split into core controllers. I went through pretty much all of the changes from [this commit](https://github.com/coveo/ui-kit/pull/1260) to ensure that they all were documented.
Then I ran the script to generate the doc a couple of times until it stopped complaining about missing interfaces :hehehehehe:
The Sort one was missing a lot of them, so it would be important to review it

feat(productlisting): Create documentation definitions

---

packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.html

fix(quantic): fix alignement for sort when query is too long

---

Jenkinsfile

**Context**
Tagged builds are failing often due to flaky cypress tests.
It's important that tagged builds are stable. Failure means packages are not deployed to npm, creating errors for others. Missing npm packages, in combination with bad symlinks, can cause:
- Other people's branches to fail if they pull in the version bump commit from `master` branch.
- Failed installation when running `npm run setup` after pulling the latest `master` branch.
**Proposed solution**
On tagged builds, e2e tests are skipped.
This should not change the risk of deploying regressions. Prior to creating the tag, cypress tests would have run successfully at least twice; on PR and on merge into `master`.

ci: skip cypress tests on tagged builds

---

packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.pcss

https://coveord.atlassian.net/browse/KIT-1039
Prior to this PR, it was black.

fix(atomic): changed color of arrow in printable uri

---

packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.test.ts
packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ts
packages/headless/src/features/search-parameters/search-parameter-actions.ts
packages/headless/src/features/search-parameters/search-parameter-schema.ts
packages/headless/src/features/search-parameters/search-parameter-selectors.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.test.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.ts
packages/headless/src/features/static-filter-set/static-filter-set-slice.test.ts
packages/headless/src/features/static-filter-set/static-filter-set-slice.ts
packages/headless/src/test/mock-search-parameters.ts

This PR adds active static filter captions to the url, using a similar form to facets and category facets:
```
sf[id]=caption1,caption2
```
Next step: Documentation and samples

feat(headless): support static filter in url

---

packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.test.ts
packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.ts
packages/headless/src/controllers/search-box/headless-search-box.ts
packages/headless/src/features/search/search-actions-loader.ts
packages/headless/src/features/search/search-actions.ts

Clicking on a recent query would not recent facet selection and pager. The behaviour should be consistent with executing the query in the searchbox which would clear facets and reset pager.
The action for recent-queries-list item selection now dispatches those actions.

feat(headless): match recentquery select with searchbox behaviour

---

packages/atomic/src/components/atomic-result/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result/atomic-result-row-desktop.pcss
packages/atomic/src/components/atomic-result/atomic-result-row-mobile.pcss

https://coveord.atlassian.net/browse/KIT-1121
I tried to match the gap seen in the updated design.
Density no longer affects the gap.

fix(atomic): reduced margin above title metadata section

---

packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.tsx

https://coveord.atlassian.net/browse/KIT-1163
Expanding the printable uri on a grid result was redirecting to the clickUri of the result, since the grid result is wrapped in a `<a>` tag.

fix(atomic): allowed printable uri to be expanded on grid results

---

packages/atomic/src/components/atomic-result/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result/atomic-result-mixin.pcss
packages/atomic/src/components/atomic-result/atomic-result-row-desktop.pcss
packages/atomic/src/components/atomic-result/atomic-result-row-mobile.pcss
packages/atomic/src/components/atomic-result/atomic-result.pcss
packages/atomic/src/components/atomic-table-result/atomic-result-cell.pcss
packages/atomic/src/themes/accessible.css
packages/atomic/src/themes/coveo.css

https://coveord.atlassian.net/browse/KIT-1070
To make the line height relative to the font size, instead of adding a variable for each sizes, I created the `--atomic-line-height-ratio` variable. In most cases it should not need to be updated, but for some fonts the current ratio could be better.

fix(atomic): make result template line-height relative to font-size

---

packages/headless/src/utils/query-expression/common/part.ts
packages/headless/src/utils/query-expression/date-field/date-field.test.ts
packages/headless/src/utils/query-expression/date-field/date-field.ts
packages/headless/src/utils/query-expression/date-range-field/date-range-field.test.ts
packages/headless/src/utils/query-expression/date-range-field/date-range-field.ts
packages/headless/src/utils/query-expression/exact-match/exact-match.test.ts
packages/headless/src/utils/query-expression/exact-match/exact-match.ts
packages/headless/src/utils/query-expression/field-exists/field-exists.test.ts
packages/headless/src/utils/query-expression/field-exists/field-exists.ts
packages/headless/src/utils/query-expression/keyword/keyword.test.ts
packages/headless/src/utils/query-expression/keyword/keyword.ts
packages/headless/src/utils/query-expression/near/near.test.ts
packages/headless/src/utils/query-expression/near/near.ts
packages/headless/src/utils/query-expression/numeric-field/numeric-field.test.ts
packages/headless/src/utils/query-expression/numeric-field/numeric-field.ts
packages/headless/src/utils/query-expression/numeric-range-field/numeric-range-field.test.ts
packages/headless/src/utils/query-expression/numeric-range-field/numeric-range-field.ts
packages/headless/src/utils/query-expression/query-expression.test.ts
packages/headless/src/utils/query-expression/query-expression.ts
packages/headless/src/utils/query-expression/query-extension/query-extension.test.ts
packages/headless/src/utils/query-expression/query-extension/query-extension.ts
packages/headless/src/utils/query-expression/string-facet-field/string-facet-field.test.ts
packages/headless/src/utils/query-expression/string-facet-field/string-facet-field.ts
packages/headless/src/utils/query-expression/string-field/string-field.test.ts
packages/headless/src/utils/query-expression/string-field/string-field.ts

Good suggestion by @acote-coveo, to ensure the `Part` interface is correctly implemented and prevent unxpected behaviours that might be associated with overriding `toString`.

refactor: rename toString to toQuerySyntax

---

packages/headless/src/controllers/core/facets/range-facet/date-facet/date-range.ts
packages/headless/src/features/facets/range-facets/date-facet-set/interfaces/request.ts

Links were originally added manually on docs site and source annotations were not updated.

docs(headless): apply Relative Date links in annotations

---

packages/atomic/src/components/atomic-result/atomic-result-cell-desktop.pcss
packages/atomic/src/components/atomic-result/atomic-result-cell-mobile.pcss
packages/atomic/src/components/atomic-result/atomic-result-with-sections.pcss
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-actions.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-badges.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-bottom-metadata.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-emphasized.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-excerpt.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-title-metadata.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-title.tsx
packages/atomic/src/components/result-template-components/atomic-result-sections/atomic-result-section-visual.tsx
packages/atomic/src/utils/result-section-utils.ts

https://coveord.atlassian.net/browse/KIT-1153
The "empty" class was being overriden by other styles, mainly the line-clamp mixin. Setting it inline will ensure it's not overriden

fix(atomic): add util to hide sections using inline styling

---

packages/atomic/src/components/result-template-components/atomic-result-link/atomic-result-link.pcss
packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.pcss

https://coveord.atlassian.net/browse/KIT-1152
Printable uri can display a list of links or a single link, depending on the data.

fix(atomic): assign color to printable uri links

---

packages/quantic/force-app/main/default/lwc/exampleSearch/resultTemplates/caseResultTemplate.html
packages/quantic/force-app/main/default/lwc/exampleSearch/resultTemplates/chatterResultTemplate.html
packages/quantic/force-app/main/default/lwc/exampleSearch/resultTemplates/youtubeResultTemplate.html
packages/quantic/force-app/main/default/lwc/quanticResult/quanticResult.css
packages/quantic/force-app/main/default/lwc/quanticResult/quanticResult.html
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.css
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html

- Fixed a bug when clicking above or below the modal to close it.
- Updated style to this based on lengthy deliberation and democratic action.

fix(quantic): changed quickview style and placement

---

packages/atomic/src/components/atomic-query-error/atomic-query-error.tsx

https://coveord.atlassian.net/browse/KIT-1174
Safe from XSS here, since we aren't using innerHTML, but putting the description directly in the JSX

fix(atomic): stop escaping platform URL for query error

---

packages/atomic/src/components/atomic-result-list/atomic-result-table.pcss
packages/atomic/src/components/atomic-result-table-placeholder/atomic-result-table-placeholder.tsx

https://coveord.atlassian.net/browse/KIT-960
I added a minimum width to the first column in a table and I removed one column from the placeholder to make their sizes more consistent on smaller screen sizes.

fix(atomic): made table results more responsive

---

packages/atomic/cypress/integration/result-list/result-components/result-multi-value-text.cypress.ts
packages/atomic/cypress/integration/result-list/result-list-actions.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/result-template-components/atomic-result-multi-value-text/atomic-result-multi-value-text.tsx

https://coveord.atlassian.net/browse/KIT-985
I made it possible for field values to be split and trimmed in `atomic-result-multi-value-text`.

feat(atomic): added preprocessing for field values in atomic-result-multi-value-text

---

packages/atomic/package.json

Needed in order for the static website uploaded on s3 to have the necessary JS/CSS resources for Atomic without too much URL rewrite with cryptic Webpack config.
https://coveord.atlassian.net/browse/KIT-1190

docs(atomic): copy atomic resources to storybook static on build

---

packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.css
packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.html
packages/quantic/force-app/main/default/lwc/quanticCardContainer/quanticCardContainer.html
packages/quantic/force-app/main/default/lwc/quanticPlaceholder/quanticPlaceholder.css

fixed an issue where our card headers were getting clipped. Given the flexible nature of our components and their labels, this is the optimal solution and this truncating behaviour matches the SLDS `lightning-card` component when in narrow containers.
Also removed the fixed min-width from the placeholder component. In narrow containers it overflowed rather nastily. Since adding the `flex-grow` property in another PR it was no longer necessary but stayed behind by mistake.
It's important to note that this does make the placeholders render bizarrely initially in the local dev server though they render as they should in lightning experience. 
The bug is due to the localdevserver's container element and the issue has been reported several times to the team responsible. 
1. …

fix(quantic): added truncate and removed placeholder min-width

---

packages/quantic/cypress/integration/facets/timeframe-facet/timeframe-facet-expectations.ts
packages/quantic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.html
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.js
packages/quantic/force-app/main/default/lwc/quanticUtils/quanticUtils.js

https://coveord.atlassian.net/browse/SFINT-4253
This PR fixes some issues for the timeframe facet.
* Display a single validation message when custom date range is invalid
* Hide validation messages when clicking outside the custom range section
* Hide the facet when no results are returned (unless a timeframe or a custom range is active for the facet)
The end to end tests have been updated accordingly.

fix(quantic): various timeframe facet issues

---

packages/headless/src/features/facets/category-facet-set/category-facet-set-analytics-actions.ts
packages/headless/src/features/facets/range-facets/generic/range-facet-analytics-actions.ts

We're importing source files in TypeScript from `coveo.analytics` and that makes webpack cough a little when someone tries to use headless.
When possible we should not import stuff that is not exported as we do, but if we do it regardless, we should import declaration files.
This causes issues for example with `@coveo/angular`.
I reckon this changeset ain't a big deal, because they actually look more like a typo than something that was done on purpose, given that there are already other occurrences of `import ... from 'coveo.analytics/dist/definitions'` in the codebase.

fix(headless): remove ca.js/src import

---

packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js

The option was no-oped in headless and remove in atomic here https://coveord.atlassian.net/browse/KIT-1095

feat(quantic): removed delimitingCharacter

---

.vscode/tasks.json

https://coveord.atlassian.net/browse/KIT-1201
@dlutzCoveo I'm not sure why, but they were removed in your PR (https://github.com/coveo/ui-kit/pull/1430). I'm guessing this wasn't on purpose, but I'm curious what removed it, especially since `tasks.json` is ignored by git.

chore(headless,atomic): re-added vscode tasks

---

packages/atomic/README.md

The link was leading to a 404. So I replaced it with a relative path to be on the safe side. (will be easier if we revamp several readme in a single branch too)

doc(atomic): fix broken link

---

packages/headless/package-lock.json
packages/headless/package.json
packages/headless/rollup.config.js

**Context**
Source maps are not working on CDN because the source files are not being uploaded. This PR copies the `src` directory inside `dist/browser` which is uploaded to the CDN, ad adjusts the paths in the source map files to point to the new location.
**Demo**
Check it out in action using [this CSB](https://codesandbox.io/s/naughty-perlman-6e6ff?file=/index.html).
Place a breakpoint on the `const configuration` line (chrome dev tools > sources > (index)), and jump in once triggered.
Source maps should work with `v1.31`. Changing the CDN version in Code Sandbox to `1.30` should not work.

fix(headless): load sourcemaps from CDN

---

packages/headless/src/api/search/facet-search/base/base-facet-search-request.ts
packages/headless/src/features/facets/facet-search-set/category/category-facet-search-request-builder.test.ts
packages/headless/src/features/facets/facet-search-set/category/category-facet-search-request-builder.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-request-builder.test.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-request-builder.ts

**Context**
Bass Pro reported seeing incorrect facet search counts when using folding. This PR sends the `filterFacetCount` param with the search request. The value of the property is `true` by default.
**Next steps**
If there is no use-case for having `filterFacetCount` set to `false`, we can deprecate and eventually remove the option. Will follow up with @acote-coveo and @francistb based on this [comment](https://coveo.slack.com/archives/C02ABMU1HPC/p1636570145014800?thread_ts=1636569017.011500&cid=C02ABMU1HPC).
https://coveord.atlassian.net/browse/KIT-1207

fix(headless): send filterFacetCount param with facet search request

---

packages/quantic/copy-static-resources.js

So that's kind of an "low change" fix, since it does not touch any source file in Quantic.
The problem is that the dist folder in Headless contains quite a bit of stuff, which exceed the 5mb static resource limit in Salesforce:
* Commerce, Service, Search use case related packages
* Different module type output (umd, esm), both for Node and Browser environments
* Source maps
* Original TypeScript source code for source maps to function properly.
* Definitions file
* Documentation output
* etc..
With the change in this PR, it's bundling just the strict minimum for stuff to work in Quantic, but it means that some feature won't be included today (you'd have to manually include them over time if they are needed).
Possibly, this also means a more sophisticated mechanism to "load" the resources …

fix(quantic): copy only main headless browser file

---

packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx

This is just a quick follow-up to the recent PR #1473 as it was merged without my approval and fixes.

docs(atomic): atomic-result-list: adds minor fixes to shadow parts' descriptions

---

packages/atomic/.storybook/code-sample-addon/code-sample-panel.tsx
packages/atomic/.storybook/default-result-component-story.tsx

There are 3 result components with Shadow Dom that needs this support: 
* ResultRating
* MultiValueText
* ResultBadge
https://coveord.atlassian.net/browse/KIT-1204

docs(atomic): support shadow parts for results components

---

packages/atomic/.storybook/code-sample-addon/code-sample-panel.tsx

When focusing on the code editor, we switch to read only mode, so that users don't try to modify the code sample and expect it to be reflected in the live example.
However, this means that any new code added in the sample after that point (ie: you go back and modify new props on the component) would not be formatted correctly.
The `format this document` action in Monaco editor does not work when the editor is in read only mode.
So, we switch to read-only=true when focusing in, and back to read-only=false when focusing out.
https://coveord.atlassian.net/browse/KIT-1211

docs(atomic): fix code sample issue stuck in read only mode

---

packages/atomic/.storybook/default-result-component-story.tsx
packages/atomic/src/components/result-template-components/atomic-field-condition/atomic-field-condition.stories.tsx

Various visual improvements for the Result components:
* Force a max width on the search interface by creating/merging a default config with `additionalMarkup`
* Query only one result on the API by creating/merging a default config with  `preprocessRequest`
* Add a container around result list with dashed border, to convey the information about result template acting as container for your result.
https://coveord.atlassian.net/browse/KIT-1213

docs(atomic): visual improvements for result components documentation 

---

packages/atomic/.storybook/default-result-component-story.tsx
packages/atomic/.storybook/default-story-shared.tsx
packages/atomic/.storybook/default-story.tsx
packages/atomic/package.json
packages/atomic/scripts/list-assets.js
packages/atomic/src/components/atomic-did-you-mean/atomic-did-you-mean.mdx
packages/atomic/src/components/atomic-did-you-mean/atomic-did-you-mean.stories.tsx
packages/atomic/src/components/atomic-icon/atomic-icon.mdx
packages/atomic/src/components/atomic-icon/atomic-icon.stories.tsx

* Add a new script to list assets on build, and output to doc folder `assets.json`.
* Display all assets in the `atomic-icon` story in a grid.
* Bonus: Added Did you mean story config (was missing)
https://coveord.atlassian.net/browse/KIT-1224

docs(atomic): add storybook support for atomic-icon

---

packages/headless/config/api-extractor/product-listing.json
packages/headless/config/api-extractor/product-recommendation.json
packages/headless/config/api-extractor/recommendation.json
packages/headless/config/api-extractor/search.json
packages/headless/package-lock.json
packages/headless/package.json
packages/headless/rollup.config.js
packages/headless/src/index.ts

The api-extractor team fixed the import limitation. The work-around of bundling definitions into a single file is no longer needed 🎉 
There is still a smaller limitation though, where it does not understand `export * as NamedExport from ...` syntax.
The work-around is to do it in two steps, first importing as a named export, then exporting the named export.

docs: simplify doc extraction

---

package.json
packages/atomic/.storybook/atomic-search-interface-storybook-helper.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.mdx
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.stories.tsx

As explained, the canvas view for Search interface did not work very well, after a couple of trials and errors.
So instead, I made it so the canvas is hidden for the Search interface, and instead we only have a doc page (.mdx), where we render a table dynamically with all the props, and some code sample to showcase an example of each option.
We will still need to have an actual article about the component itself, though ! 
https://coveord.atlassian.net/browse/KIT-1226

docs(atomic): storybook for search interface

---

packages/atomic/src/components/atomic-search-interface/atomic-search-interface.mdx
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.stories.css

Fixing some overflow problem for the props table in search interface, as well as using the `Source` component available from storybook for the small code sample.
https://coveord.atlassian.net/browse/KIT-1232

docs(atomic): fix props table visual glitch for search interface story

---

packages/atomic/.storybook/default-init.ts
packages/atomic/.storybook/main.js
packages/atomic/.storybook/preview.js
packages/atomic/.storybook/register.js
packages/atomic/package-lock.json
packages/atomic/package.json

We need to tweak the base addon a bit to put it in "manual" mode, that re-run accessibility test only after the query has been executed.
But otherwise seems to be working great !
https://coveord.atlassian.net/browse/KIT-1233

docs(atomic): add support for accessibility addon

---

packages/atomic/src/components/common/atomic-focus-trap.tsx

`originalTarget` is not recommended by MDN, for being non-standard.
https://developer.mozilla.org/en-US/docs/Web/API/Event/Comparison_of_Event_Targets
https://coveord.atlassian.net/browse/KIT-1235

fix(atomic): fix focus trap event target

---

package-lock.json
packages/atomic/package-lock.json
packages/bueno/package-lock.json
packages/headless/package-lock.json
packages/quantic/.npmignore
packages/quantic/copy-static-resources.js
packages/quantic/package-lock.json
packages/quantic/package.json
packages/quantic/scripts/build/create-package.ts
packages/quantic/scripts/build/deploy-community.ts
packages/quantic/scripts/build/util/github.ts
packages/quantic/scripts/build/util/sfdx.ts
packages/samples/atomic/package-lock.json
packages/samples/headless-react/package-lock.json

fix a bunch of eslint-ignore.
engine in package.json is to fix the node/no-unsupported-features/node-builtins (i.e. specify which version of node to use for dev. I defaulted on maintenance LTS and above)
.npmignore is to fix the no-unpublished-import/require. Because you're not specifying which file you're publishing ('cause you ain't a npm package), you need to either add a file field in the package.json to specify the 'true sources', or do a npmignore to remove the non-source file. (think allow/ban list).
I did a npmignore here because 'twas easier for me, but the file approach is good as well.

for @nlafrance, fix eslint-disable

---

packages/quantic/force-app/main/default/lwc/quanticHeadlessLoader/__tests__/quanticHeadlessLoader.test.js
packages/quantic/force-app/main/default/lwc/quanticSearchBox/__tests__/quanticSearchBox.test.js
packages/quantic/force-app/main/default/lwc/quanticSearchInterface/__tests__/quanticSearchInterface.test.js
packages/quantic/force-app/main/default/lwc/testUtils/coveoHeadlessStub.js
packages/quantic/force-app/main/default/lwc/testUtils/testUtils.js

https://coveord.atlassian.net/browse/SFINT-4302
This PR fixes the deployment issue that prevents the `sfdx-cli` upgrade to 7.127.0. Also it seems the sfdx issue that was preventing us from upgrading is now fixed (test file being deleted from the working copy after deployment).
The root cause is that the `testUtils` folder is not a component and it appears that `sfdx-cli` now validates that.

fix(quantic): fix main package deployment

---

packages/atomic/tsconfig.json

Built with --stats didn't see any significant changes, the dist/atomic folder is 5.7mb for both
https://coveord.atlassian.net/browse/KIT-1240

chore(atomic): set target to es2019

---

packages/headless/src/features/case-field/case-field-actions.ts
packages/headless/src/state/state-sections.ts

The reducer names didn't match the interfaces after a renaming effort left them out in the cold.

feat(headless): renamed interface to match state

---

scripts/deploy/publish.js

When a package does not exist on npm (e.g. when a package is being published for the first time), `npm view` throws an error.
https://coveord.atlassian.net/browse/KIT-1246

ci: publish package if first publish

---

packages/atomic/src/components/atomic-result/atomic-result-cell-desktop.pcss

Original problem was about title being cutoff when it could not wrap (ie: a title contains underscore), so I've added a `word-break: break-word` rule.
The text would start to wrap properly, however the bottom of the title text is cutoff when it wraps on two line, because there's max height applied.
@btaillon I'm not a 100% sure about this one, since your last changes on this file were about switching from a `min-height` to a `max-height` for sections.
I don't think it's necessary ? Don't we want sections to stretch "as much as needed" depending on their content ?
https://coveord.atlassian.net/browse/KIT-1155

fix(atomic): fix line clamp max height & break word in title section

---

packages/atomic/src/components/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx

Started seeing an error in the console because of this, `retrieveLocalStorage` calls an undefined `this.storage`
https://coveord.atlassian.net/browse/KIT-1256

fix(atomic): init SafeStorage before calling it

---

README.md
packages/headless/rollup.config.js

https://coveord.atlassian.net/browse/KIT-1262
The problem was running (from root)
```
npm run setup
npm run build
```
did not create the external-builds that Atomic needs, I changed the config so it runs locally for both dev/prod configs

fix(headless): always build external builds locally

---

Jenkinsfile

This option will remove the cypress logging, but keep the mocha `spec` reporter logs.
Default logging:
With `--quiet` option:

ci: specify cypress --quiet option

---

packages/atomic/src/index.ts

https://coveord.atlassian.net/browse/KIT-1271
Importing `@coveo/atomic` in another Stencil project, it tries looking for an index.js in collection/component/, which doesn't exist

fix(atomic): explicitly define exports

---

packages/headless/src/controllers/controller/headless-controller.test.ts
packages/headless/src/controllers/controller/headless-controller.ts

Since `prevState` is a local function variable to each controller, the comparison would work only once for the first subscriber function, since it would get "reset" after the first comparison.
In practice:  
```
const myController = buildController()
myController.subscribe(()=> console.log('hello')); // print 'hello' properly on each state change
myController.subscribe(()=> console.log('world')); // print 'world' only once, only on the initial execution.
```
https://coveord.atlassian.net/browse/KIT-1270

fix(headless): rework previous state comparison for controllers to allow multiple subscribers

---

Jenkinsfile

I think that changed when I did the versions bump with renovate last week. 
That step is no longer necessary it seems 🤷
https://coveord.atlassian.net/browse/KIT-1272

ci: fix chown issue in Jenkins

---

packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/tailwind.config.js

The closing animation was kind of wacky looking, with the timing function leaving a "shadow" of the modal for a split second at the end as it was getting scaled down.
Changed it to a simpler linear slide down with no scaling effect.
https://coveord.atlassian.net/browse/KIT-1265

fix(atomic): change refine toggle closing animation to a simple slide down

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/search-interface.cypress.ts
packages/atomic/src/components/atomic-search-interface/analytics-config.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/global/environment.ts
packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts

This is a request from M.Petitclerc.
This helps the UA team track different version of what our commerce clients are using.
https://coveord.atlassian.net/browse/KIT-1269

feat(atomic,headless): add analytics metadata about headless and atomic version number

---

packages/samples/headless-react/src/components/static-filter/static-filter.fn.tsx
packages/samples/headless-react/src/components/tab/tab.fn.tsx
packages/samples/headless-react/src/pages/SearchPage.tsx

I changed the method to generate the string expression in response to a PR comment, but did not adjust the samples.
Caught this while clicking around to test the ESM bundle generated by esbuild,
https://coveord.atlassian.net/browse/KIT-1274

docs(headless-react): fix query syntax builder samples

---

packages/quantic/copy-static-resources.js

At one point while testing different bundles with quantic, I hit this cryptic error:
This PR adjusts to catch and log a hopefully clearer error.
https://coveord.atlassian.net/browse/KIT-1275

chore: improve copy static resources error message

---

packages/headless/esbuild.js
packages/headless/package-lock.json
packages/headless/package.json
packages/headless/rollup.config.js

Build time (my machine): ~1 second (esbuild only)
Build time (Jenkins): 109 seconds (esbuild-rollup hybrid) vs. 234 seconds (rollup only)
Esbuild minified bundle size: ~3% larger
Percentage comparisons are versus rollup.
|Use Case | Rollup (kb) | Esbuild (kb) | Diff (%) | Terser minification | Diff (%)
|---|---|---|---|---|---
|search|243|260| 7 | 255 | 5
|recommendation|176|182| 3 | 178 | 1
|product recommendation|177|183| 3
|product listing|193|199 | 3
|case-assist|179|181 | 1
Terser provides smaller bundles at the cost of additional time and configuration complexity due to using two tools (not included in this PR). Rollup still outperforms. I only ran the terser benchmark for two use-cases.
**Summary**
Salesforce needs a UMD bundle, so using esbuild OOTB is not possible. It might be …

ci: generate headless bundles using esbuild

---

packages/atomic/.storybook/default-story-shared.tsx
packages/atomic/src/components/atomic-no-results/atomic-no-results.stories.tsx

Force the storybook ID (what generates permalink to a specific story) to the component tag instead of "the name of the story", as it makes it harder to have dead links in doc website.
https://coveord.atlassian.net/browse/KIT-1285

docs(atomic): normalize storybook id

---

packages/samples/headless-react/package.json

Jenkins build time: 102s -> 12s
Since the headless-react project is not deployed anywhere, we can save the compute involved in generating a production bundle. The build step now only checks for typescript errors.
https://coveord.atlassian.net/browse/KIT-1282

ci(headless-react): only validate types; skip bundle

---

packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.css
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.js

- ### The button to open the Quick view is now customizable using the following properties  `previewButtonLabel`, `previewButtonIcon` and `previewButtonVariant`.
- ### The ability to have a footer in the quick view where the end user can plug other components using the  slot `footer`.
https://user-images.githubusercontent.com/86681870/145244465-1e7764c8-c7c8-404e-b712-88c87f3e4bc9.mov
- ### Default:
- ### Default when there is no preview
- ### Brand variant with custom label and custom icon
- ### Brand variant with custom label and custom icon when there is no preview
- ### Outline variant with custom label and custom icon
- ### Brand variant with custom label and custom icon when there is no preview

feat(quantic): slots added in quick view

---

packages/quantic/scripts/build/deploy-community.ts
packages/quantic/scripts/build/util/sfdx-commands.ts

https://coveord.atlassian.net/browse/SFINT-4259
This PR updates the `deploy-community` to delete the scratch organizations (for a given branch) that are more than 2 hours old. With concurrent builds, a scratch organization could be deleted by job-2 while job-1 was still executing tests.

feat(quantic): remove old scratch organizations

---

packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.js

Before: 
- Tooltip appearing only when hovering on the icon.
- When `preview-button-icon` is set to `''` an additional right padding was appearing in the preview button.
After:
- Tooltip appearing only when hovering on the whole button.
- When `preview-button-icon` is set to `''` the preview button is now appearing correctly.

fix(quantic): Fix the appearance of the preview button of the quick view

---

.github/workflows/create-quantic-package.yml
packages/quantic/force-app/main/default/lwc/quanticSearchInterface/quanticSearchInterface.js

Removed pipeline default value because it would overwrite searchub configured pipeline when searchhub is specified and pipeline isn't.
[Related discuss post](https://discuss.coveo.com/t/searchhub-and-pipeline-wrong-behavior/6961/9)

fix(quantic): removed default pipeline value

---

.github/workflows/masterbot.yml
.github/workflows/prbot.yml
.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1298
Without authenticating as an admin user in our repo, it's impossible to update a protected branch (`master`, in our case). I created a personal access token and added it to our org (see discussion in `#support-dev_tooling`).
If you look at previous runs, you may notice that it did push *something* though. While only an admin can update the *branch*, any member can push tags or commits.
As for the fetch depth, I happened upon the doc for it (which I should've read earlier), and a fetch depth of 0 fetches the whole git history, which we don't need in most jobs, so I decided to remove it. The default fetch depth is 1 (HEAD only).

ci: added admin token for version bump and reduced fetch depth

---

packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-selectors.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions-utils.ts
packages/headless/src/features/facets/facet-set/facet-set-selectors.ts

A bad request (400) error occurred when sending usage analytics requests from a Product Listing controllers.
After investigation there are 2 problems identified:
1. No SearchUID from product listing response was set.
2. Facet state form Search was queried but should be from Product Listing.
https://coveord.atlassian.net/browse/COM-1341
To validate:
Prerequisite: a page with Product Listing controllers like https://github.com/coveo/saqdemo. 
Open the network tab in chrome dev tools and filter on `search?visitor`.
Do facet related actions.
Previously you would get a 400 response.
Now you get a 200 response when these changes are applied.

fix: (headless): Send correct analytics events from Product Listing controllers

---

packages/headless/src/controllers/core/facets/facet/headless-core-facet-options.ts
packages/headless/src/controllers/facets/facet/headless-facet-options.ts
packages/headless/src/features/facets/facet-set/facet-set-actions.ts

Updated sortCriteria annotation for facets in Headless to explain the default behaviour of `automatic`. Prompted by [this discussion](https://coveord.atlassian.net/browse/DOC-10113).

docs(headless): update sortCriteria to describe 'automatic' default

---

.github/workflows/masterbot.yml
.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1299
According to [this](https://stackoverflow.com/a/63646054), the build condition may have failed because the tags already existed, due to a previous issue with the build.

ci: changed tag condition for workflows to match every tag

---

JenkinsfileProductionRelease
packages/quantic/package-lock.json
packages/quantic/package.json

The production jenkins script had a missing bracket, which prevented it from running. The file [now builds](https://searchuibuilds.dev.cloud.coveo.com/job/ui-kit-production-release/58/) on jenkins.
Also tweaked the github credentials (old `credentialId` did not exist), and adjusted to build all packages, since quantic needs headless files.
https://coveord.atlassian.net/browse/KIT-1302

ci: add missing bracket to production Jenkinsfile

---

packages/atomic/cypress/integration/result-list/result-components/result-badge-selectors.ts
packages/atomic/cypress/integration/result-list/result-components/result-badge.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/result-template-components/atomic-result-badge/atomic-result-badge.tsx
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1092
Allows for the following kind of syntax:
```html
<atomic-result-badge
icon="https://raw.githubusercontent.com/Rush/Font-Awesome-SVG-PNG/master/black/svg/language.svg"
>
<atomic-result-multi-value-text field="language"></atomic-result-multi-value-text>
</atomic-result-badge>
```
Badge with the language field:
Badge with a `atomic-result-multi-value-text` slotted element:

feat(atomic): added slot inside of atomic-result-badge

---

.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1303
It should already be verbose since it was given the `--verbose` parameter, but I guess it's not since it's failing without any details.

ci: added verbose logging to npm publish in GHA

---

.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1304
The build [here](https://github.com/coveo/ui-kit/runs/4587320178?check_suite_focus=true) was failing because make and GCC were missing. I asked dev tooling, they told me `apt` should be available within the runner.

ci: installed build-essential in self-hosted GHA runner

---

packages/quantic/.gitignore
packages/quantic/scripts/build/create-package.ts

The quantic publishing script is failing due to a poor ordering of steps. SFDX authentication is required to get the next package version but an attempt at retrieving the version number is done before authentication is done. This PR puts things back in order and has been tested in jenkins.

ci(quantic): put package version retrieval after auth

---

.github/actions/setup/action.yml
.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1303
I think the publish step may be silently failing because the registry is missing. In the [official documentation](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages), the registry is added. In the old Jenkinsfile, the registry was also added.

ci: added registry to npm publish GHA step

---

packages/atomic/cypress/integration/common-assertions.ts
packages/atomic/cypress/integration/facets/category-facet/category-facet-actions.ts
packages/atomic/cypress/integration/facets/category-facet/category-facet-assertions.ts
packages/atomic/cypress/integration/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/integration/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet-common-actions.ts
packages/atomic/cypress/integration/facets/facet-common-assertions.ts
packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet.cypress.ts
packages/atomic/cypress/integration/facets/rating-facet/rating-facet.cypress.ts
packages/atomic/cypress/integration/facets/rating-range-facet/rating-range-facet.cypress.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.pcss
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/components/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx
packages/atomic/src/components/facets/facet-common.ts
packages/atomic/src/components/facets/facet-header/facet-header.tsx
packages/atomic/src/components/facets/facet-show-more-less/facet-show-more-less.tsx
packages/atomic/src/components/facets/facet-value-link/facet-value-link.tsx
packages/atomic/src/utils/accessibility-utils.tsx

https://coveord.atlassian.net/browse/KIT-1075
In addition to E2E test that test focus, I added some other missing E2E tests.
I added a `FocusTarget` decorator, which allows us to define upcoming focus targets that may or may not exist yet. This utility should easily be reusable to improve accessibility in other components such as the pager. I recommend looking at [its usage](https://github.com/coveo/ui-kit/pull/1618/files#r774742155) before looking at its definition.
New behaviours:
* When pressing the "show less" button in any facet, the "show more" button is focused.
* When pressing the "show more" button in any facet, if there's no more "show more" button, the "show less" button is focused.
* When pressing the "clear filters" button in any facets, the header is focused.
* In a category …

fix(atomic): maintained keyboard focus on facets for accessibility

---

packages/quantic/force-app/main/default/lwc/quanticCaseAssistInterface/quanticCaseAssistInterface.js
packages/quantic/force-app/main/default/lwc/quanticSearchInterface/quanticSearchInterface.js

A brave SE tried to instantiate a quantic-search-interface without any quantic components in it. It crashed due to an unsafe evaluation.
Optional chaining to the rescue.

fix(quantic): added missing optional chaining

---

packages/headless/src/controllers/core/facets/range-facet/date-facet/date-range.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.ts
packages/headless/src/features/facets/range-facets/date-facet-set/interfaces/request.ts
packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.js
packages/quantic/force-app/main/default/lwc/quanticFacetValue/quanticFacetValue.js
packages/quantic/force-app/main/default/lwc/quanticResult/quanticResult.js
packages/quantic/force-app/main/default/lwc/quanticResultBadge/quanticResultBadge.js
packages/quantic/force-app/main/default/lwc/quanticResultLabel/quanticResultLabel.js
packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.js
packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/quanticResultPrintableUri.js

Since the Headless documentation section was recently restructured, I had to update a few links here.

doc(headless): update headless doc links

---

packages/atomic/src/components/facets/facet-date-input/facet-date-input.tsx

https://coveord.atlassian.net/browse/KIT-1112
Tested with BrowserStacks 
valueAsDate isn't supported, and I added a placeholder to inform the user of the correct date input format

fix(atomic): allow date input for Safari versions under 14

---

packages/headless/esbuild.js

~~Shot in the dark to try to fix [this issue](https://github.com/coveo/ui-kit/issues/1616). This is a work-around though because it seems like the issue is caused by webpack. TBD~~
**Problem**
In node esm bundles, esbuild replaces `require` statements import node built-ins with a custom `__require` function. When webpack encounters these statements, it does not know how to resolve the node built-ins and throws an error.
Here's the code for the custom `__require` function:
```js
var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
}) : x)(function(x) {
if (typeof require !== "undefined")
return require.apply(this, arguments);
throw new Error('Dynamic …
```

fix(headless): adjust __require statements in node esm bundles

---

.github/actions/create-deployment-package/action.yml

https://coveord.atlassian.net/browse/KIT-1320
Because of the cache option, `setup-python` expected a `requirements.txt` file to use as its hash.

ci: removed python cache

---

packages/atomic/src/components/facets/facet-date-input/facet-date-input.tsx

https://coveord.atlassian.net/browse/KIT-1112
Forgot to put back the `2\\d{3})` part

fix(atomic): bring safari date regexp into the new millenium

---

packages/atomic/src/components/atomic-breadbox/atomic-breadbox.tsx
packages/atomic/src/components/result-template-components/atomic-result-fields-list/atomic-result-fields-list.tsx

https://coveord.atlassian.net/browse/KIT-1317
Prevent's crashing component and displaying an error to the console. It's quite an old version for the web 2018. The downside will be not adapting the breadcrumb/field list to be on one line.
Side note: css parts selectors don't work in Safari 12 😱

fix(atomic): prevent ResizeObserver from crashing Safari 12

---

packages/atomic/src/components/facets/facet-value-box/facet-value-box.pcss
packages/atomic/src/components/facets/facet-value-box/facet-value-box.tsx

https://coveord.atlassian.net/browse/KIT-1316
Before
After

fix(atomic): fix color facet values in Safari 13

---

packages/atomic/cypress/integration/breadbox/breadbox-assertions.ts
packages/atomic/cypress/integration/breadbox/breadbox.cypress.ts
packages/atomic/src/components/atomic-breadbox/atomic-breadbox.tsx

https://coveord.atlassian.net/browse/KIT-1084
Removing a breadcrumb selects the next breadcrumb, or the "clear all" button.
Focus is still lost when removing the last breadcrumb or pressing "clear all". Maintaining focus when that happens would require adding a lot of logic to find what's the next focusable element in the DOM (or adding a package such as [tabbable](https://www.npmjs.com/package/tabbable)). We'll see if Deque deems it important.

fix(atomic): fixed focus when clearing a breadcrumb

---

packages/atomic/cypress/integration/pager-assertions.ts
packages/atomic/cypress/integration/pager-selectors.ts
packages/atomic/cypress/integration/pager.cypress.ts
packages/atomic/cypress/integration/result-list/result-list.cypress.ts
packages/atomic/src/components/atomic-pager/atomic-pager.tsx

https://coveord.atlassian.net/browse/KIT-1078
If pages "1, 2, 3, 4, 5" are displayed, pressing page 5 shifts the displayed pages to "3, 4, 5, 6, 7", but the focus would stay on the last button (page 7), which is confusing when using a screen reader. With this change, the focus would be moved to page 5, so it stays on the same page they just pressed.

fix(atomic): fixed focus when pressing a pager page button

---

.github/actions/create-deployment-package/action.yml
.github/workflows/publishbot.yml

https://coveord.atlassian.net/browse/KIT-1338
Fixes [this error](https://github.com/coveo/ui-kit/runs/4791438447?check_suite_focus=true), based on [this](https://coveo.slack.com/archives/CBP3GTFTQ/p1639765347363300) discussion.
When reverting the EKS change, I copied the example action and forgot about the issue caused by running in a docker container.

fix(atomic,headless): removed docker container from deployment package action

---

packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/features/query-suggest/query-suggest-actions.ts
packages/headless/src/features/query-suggest/query-suggest-slice.test.ts
packages/headless/src/features/query-suggest/query-suggest-slice.ts
packages/headless/src/features/query-suggest/query-suggest-state.ts

There's some code that's needed to ensure the `q` property in the query suggest slice stays in sync with the `q` in the query set. The duplication is not needed though and can be stream-lined.
This PR takes the first step. It removes the dependency on the `q` property and deprecates it. It does not remove the duplicate reducer code and unit tests though to not change the behavior in case anyone is reading the `q` property. We would do this just before headless v2 is released.
https://coveord.atlassian.net/browse/KIT-674

refactor(headless): remove dependency on #q property in querysuggest slice

---

packages/atomic/cypress/integration/breadbox/breadbox.cypress.ts

The test checking the rendering of a large number of breadcrumbs sometimes times out. Here is the relevant part of the error (link to build and screenshot in jira):
```
1) Breadbox Test Suites
when selecting 12 facet values
verify rendering
should display 12 number of values in breadcrumb:
Timed out retrying after 4000ms
+ expected - actual
-10
+12
```
This PR adjusts to select all values at once via the url instead of making multiple requests.
A side benefit of this is the test suite time drops from 30s to 15s.
https://coveord.atlassian.net/browse/KIT-1337

test(atomic): select multiple facet values using url

---

packages/quantic/docs/jsdoc-guidelines.md
packages/quantic/force-app/main/default/lwc/quanticTimeframe/quanticTimeframe.js

The `label` property of the QuanticTimeframe was marked as required by our jsdoc parser because no `@defaultValue` tag was specified.

doc(quantic): set default value text on label prop

---

packages/atomic/src/components/atomic-external/atomic-external.tsx

Added a doc string for the external component selector option.
Seems to generate correctly, but let me know if I made some kind of syntax mistake, it's been a while since I played in this project.

doc(atomic): external component selector option

---

packages/atomic/cypress/integration/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet/facet.cypress.ts

When "show more" is pressed, the number of displayed values increases by the initially configured number. The default value is 8, so if a facet has a lot of values, it will take several presses, increasing the chance of timing out.
The field used for the facet test had about ~130 values, so ~17 clicks are needed to fully expand.
```
1) Facet v1 Test Suites
when selecting the "Show more" button
repeatedly until there's no more "Show more" button
verify rendering
should focus on the show less button:
AssertionError: Timed out retrying after 4000ms: expected '<button.btn-text-primary.flex.items-baseline.text-left.p-2.text-sm.max-w-full>' to be 'focused'
```
This PR adjusts the initial number of values so that the facet is fully expanded after one "show more" click.
One draw-back to point out …

test(atomic): decrease number of show more needed to fully expand facet

---

packages/atomic/cypress/integration/search-box.cypress.ts
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx

https://coveord.atlassian.net/browse/KIT-1342
I originally added this because I expected it to improve the experience with screen readers a bit, but now I don't see why I thought this was a good idea. Focusing on the search box causes the search suggestions to open.

fix(atomic): removed search box focus when pressing search button

---

packages/atomic-react/package.json
packages/samples/headless-react/.gitignore
packages/samples/headless-react/package.json

For all external assets (things that may not be loaded ahead of times by our components), project using Atomic-react (and all other output target we will support- Angular, Vue, etc), the embedding project has to make available `lang` (translation) and `assets` (bunch of SVG)  in whatever represent their "public" web server folder.
For example, in our sample headless-react package built with create react app, this means making all files available in the `public` folder.
This is a gotcha that we will need to document clearly for our users ! 
If they don't copy `node_modules/@coveo/atomic-react/dist/lang` to some publicly available folder on their server, it means that the language dictionary will be empty by default (english won't even load) and for all strings you would only see the "key", …

feat(atomic): make assets and language available for atomic-react

---

packages/quantic/force-app/main/default/lwc/quanticDidYouMean/quanticDidYouMean.js
packages/quantic/force-app/main/default/lwc/quanticNoResults/quanticNoResults.js
packages/quantic/force-app/main/default/lwc/quanticSummary/quanticSummary.js
packages/quantic/force-app/main/default/lwc/quanticUtils/__tests__/quanticUtils.test.js
packages/quantic/force-app/main/default/lwc/quanticUtils/quanticUtils.js

`lightning-formatted-rich-text` which we use for bolding renders html in a query. I added a util that uses html <textarea> escaping in a clever way so the queries are displayed properly.
Before
After

fix(quantic): added escape util for showing query in rich-text

---

packages/atomic/cypress/integration/result-list/result-components/result-printable-uri.cypress.ts
packages/atomic/src/components/result-link/result-link.tsx
packages/atomic/src/components/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.tsx
packages/atomic/src/locales.json
packages/atomic/src/utils/accessibility-utils.tsx

https://coveord.atlassian.net/browse/KIT-1076
* Added a label to the printable URI as a whole
* Made the expand button focus on the first newly revealed value
* Added a role to separators

fix(atomic): improved accessibility for printable uri

---

packages/atomic/cypress/integration/facets/category-facet/category-facet-assertions.ts
packages/atomic/cypress/integration/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet/facet-assertions.ts
packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/cypress/utils/componentUtils.ts
packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet-options.ts
packages/headless/src/features/facets/category-facet-set/category-facet-set-actions.ts
packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.js
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.js

`occurrences` is spelled with 2 Rs

fix(headless,atomic,quantic): typos for occurrences

---

packages/atomic/cypress/integration/search-box.cypress.ts

I think I turned all the stones ...
I commented out all code that is clearing suggestions. Still, I saw suggestions being cleared in cypress. So, I think the test code is at fault.
One way to make it work™️ is to slow down the typing. At 200ms, I did not see any failing attempts locally. At 150ms, they still occasionally happened.
Since this solution relies on delays, it is not as stable as the initial PR, so I put the changes in a separate branch,

test(atomic): make test stable using the old setup 

---

packages/atomic-react/README.md
packages/atomic-react/src/components/ResultListWrapper.tsx
packages/atomic-react/src/components/SearchInterfaceWrapper.tsx

@jpmarceau : This is essentially what will need to be documented for Atomic React (everything that appears in the README), and resurfaced on our doc website.
As of this moment, there is not other difference from the basic Atomic library.
https://coveord.atlassian.net/browse/KIT-1360

docs(atomic): documentation for wrapper component + README for result templates

---

packages/atomic/cypress/integration/breadbox/breadbox-assertions.ts
packages/atomic/cypress/integration/no-results.cypress.ts
packages/atomic/cypress/utils/componentUtils.ts
packages/atomic/src/components/atomic-breadbox/atomic-breadbox.tsx
packages/atomic/src/components/atomic-no-results/atomic-no-results.tsx
packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/components/atomic-sort-dropdown/atomic-sort-dropdown.tsx
packages/atomic/src/components/facets/category-facet-search-result/category-facet-search-result.tsx
packages/atomic/src/components/facets/color-facet-checkbox/color-facet-checkbox.tsx
packages/atomic/src/components/facets/facet-common.pcss
packages/atomic/src/components/facets/facet-value-box/facet-value-box.tsx
packages/atomic/src/components/facets/facet-value-checkbox/facet-value-checkbox.tsx
packages/atomic/src/components/facets/facet-value-link/facet-value-link.tsx
packages/atomic/src/global/global.pcss
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-1087
In the case of "filter:" at-least, the colon (`:`) symbol being inside a `::after` caused screen readers to select it individually. In the first commit, I extracted the colon symbol out of `::after` blocks.
In the second commit (so I can revert it if you guys think it's too out-of-scope), I did the same thing for parentheses (which are notably used in every facet) and quotation marks. I didn't spot accessibility issues with those, these changes are mostly preventive. As a bonus, those are all localized, now.

fix(atomic): made screen readers skip colon in "filters" and "sort by"

---

packages/auth/README.md
packages/auth/src/saml/saml-flow.test.ts
packages/auth/src/saml/saml-flow.ts

In collaboration with the searchapi team, we wanted to remove the need to send an organizationId during the SAML handshake.
The goal was to make the handshake token necessary and sufficient.
However, [it turns out](https://coveord.atlassian.net/browse/SEARCHAPI-6571) that this is complex to change in the service.
This PR adjusts to send the org id during handshake.
https://coveord.atlassian.net/browse/KIT-1382

fix(auth): send organizationId as query string param during handshake

---

packages/samples/headless-react/cypress/integration/atomic-react/smoke-test.cypress.ts
packages/samples/headless-react/package.json

* Add a script to `npm link` local react instance when running the samples in dev
* Add a larger viewport for the smoke tests, I can't be bothered with making the sample responsive on all devices :D 
* The regex check on the resize observer, from the google search I've done, seems to be what many people recommend, as it is apparently a benign error that is reported by Chrome. And cypress will automatically fail on any console error being thrown.
Now, I'm not sure what actually causes this error to happen. I suspect a deeper performance issue in Atomic as a whole (nothing to do with Atomic React), that simply (sometimes) gets triggered in the "full commerce page sample" because it uses many components. But I don't think the performance issue is critical. Just not as good as it could be in …

test(atomic-react): improve stability of atomic-react smoke tests

---

packages/atomic/src/pages/examples/headless.html
packages/headless/src/features/facets/facet-set/facet-set-actions-loader.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
packages/headless/src/features/facets/facet-set/facet-set-slice.ts

https://coveord.atlassian.net/browse/KIT-1388
To try it out with Atomic:
```html
<script type="module">
import {loadFacetSetActions} from '/build/headless/headless.esm.js';
async function main() {
await customElements.whenDefined('atomic-search-interface');
const searchInterface = document.querySelector(
'atomic-search-interface'
);
await searchInterface.initialize({
accessToken: 'xx564559b1-0045-48e1-953c-3addd1ee4457',
organizationId: 'searchuisamples',
});
const engine = searchInterface.engine;
const action = loadFacetSetActions(engine).toggleSelectFacetValue({
facetId: 'author',
selection: {state: 'selected', value: 'helloooo'},
});
engine.dispatch(action);
searchInterface.executeFirstSearch();
}
main();
</script>
```

feat(headless): allow toggleSelectFacetValue to add new values

---

packages/atomic/cypress/integration/facets/facet-common-actions.ts
packages/atomic/cypress/integration/facets/facet-common-assertions.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet-assertions.ts
packages/atomic/cypress/integration/facets/rating-facet/rating-facet-assertions.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet-assertions.ts
packages/quantic/cypress/integration/result-quickview/result-quickview.cypress.ts
packages/quantic/cypress/integration/result-template/result-template-actions.ts

Fixed some warnings related to unused imports, and using the `any` type.
https://coveord.atlassian.net/browse/KIT-1400

chore: fix eslint warnings

---

packages/atomic/src/components/facets/atomic-facet-placeholder/atomic-facet-placeholder.tsx

https://coveord.atlassian.net/browse/KIT-1395
Remnant from v0 where facets where on top inline when on a mobile display, the placeholder only had the title.

fix(atomic): remove facet placeholder mobile specific styling

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/atomic-angular.module.ts
packages/atomic/stencil-plugin/atomic-angular-module/index.ts
packages/samples/angular/src/app/atomic-angular-page/atomic-angular-page.component.html

So, I struggled quite a bit on this one, going far down the rabbit hole of reading a lot about Angular `Content projection` , `ng-template`, `@ViewChild`, `@ContentChildren` etc. trying to understand how angular deals with the native `<template>` tag, and how I could workaround it.
Turns out it's due to a plain bug in angular, linked in the comment I added in `AtomicAngularModule`.
After this change, all the rest of the logic of result templates can stay exactly the same as the core Atomic library.
https://coveord.atlassian.net/browse/KIT-1404

fix(atomic-angular): fix custom result templates for atomic angular

---

packages/atomic-angular/projects/atomic-angular/package-lock.json
packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/standalone-search-box.cypress.ts
packages/atomic/package-lock.json
packages/atomic/package.json
packages/atomic/src/components/atomic-breadbox/atomic-breadbox.tsx
packages/atomic/src/components/atomic-pager/atomic-pager.tsx
packages/atomic/src/components/atomic-rating/atomic-rating.tsx
packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/facets/facet-header/facet-header.tsx
packages/atomic/stencil.config.ts
packages/atomic/tailwind.config.js

https://coveord.atlassian.net/browse/KIT-1397
Followed https://tailwindcss.com/docs/upgrade-guide

chore(atomic): migrate to Tailwindcss v3

---

packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.test.ts
packages/headless/src/controllers/relevance-inspector/headless-relevance-inspector.ts
packages/samples/headless-react/src/components/relevance-inspector/relevance-inspector.class.tsx
packages/samples/headless-react/src/components/relevance-inspector/relevance-inspector.fn.tsx

https://coveord.atlassian.net/browse/KIT-1416
fieldsDescription or fieldDescriptions, since it's an array of fields I went for the former.
Currently it's a bit confusing. parts of the code have either naming. Now for the relevance inspector everything is fieldsDescription and the rest has been deprecated.

fix(headless): relevance inspector fetchFieldsDescription rename interface & enable by default

---

packages/quantic/force-app/main/default/lwc/quanticSearchBox/quanticSearchBox.html
packages/quantic/force-app/main/default/lwc/quanticStandaloneSearchBox/quanticStandaloneSearchBox.html
packages/quantic/force-app/main/default/lwc/searchBoxStyle/searchBoxStyle.css
packages/quantic/scripts/build/util/sfdx.ts

Before
After
Changed to make custom button as custom css doesn't collaborate well with SLDS LWC. This should keep us from getting messed up from changes introduced by salesforce.
Also added a CSS instruction to keep the styling on iOS, preventing the search input from getting the extra-rounded style.

fix(quantic): fix searchbox button style

---

packages/headless/src/controllers/case-field/headless-case-field.test.ts
packages/headless/src/controllers/case-field/headless-case-field.ts
packages/headless/src/controllers/case-input/headless-case-input.test.ts
packages/headless/src/controllers/case-input/headless-case-input.ts

- Calling the **buildCaseField** function of a field that was already registered  will reset its value to an empty string and its suggestions to an empty array.
- Calling the **buildCaseInput** function of a field that was already registered  will reset its value to an empty string.
- Conditions added to check if the field is registered or not before registering it again.

Fix(Headless): prevent caseField and caseInput from reseting when being already registered 

---

packages/atomic-angular/README.md
packages/atomic-angular/modify-package-json.js
packages/atomic-angular/package.json
scripts/deploy/update-npm-tag.js

Angular is a bit special, since the `ng cli` tool generates a "project distribution" folder (`packages/atomic-angular/projects/atomic-angular/dist/**`) , which is what needs to be published (not the "root" package.json file at `packages/atomic-angular`)
So I've added a small script to build then modify the generated `package.json` with the needed script to `npm:publish:alpha` like other packages.
https://coveord.atlassian.net/browse/KIT-1427

ci(atomic-angular): add deploy alpha script

---

packages/headless/src/features/analytics/analytics-utils.test.ts
packages/headless/src/features/analytics/analytics-utils.ts

Original discussion: https://discuss.coveo.com/t/log-click-events-default-contentidkey-values-permanentid-vs-permanentid-vs-urihash/7356/6
https://coveord.atlassian.net/browse/KIT-1430

fix(headless): add warning on missing permanentid

---

.github/workflows/create-quantic-package.yml

The github actions workflow that creates an **UNPUBLISHED** package has been broken since 1746. This workflow runs daily and is only to test that the current state of quantic in master can successfully be packaged so we can catch errors before real releases.
Anyway, this is an attempt to fix the issue. From what I can read [here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) it seems manual or scheduled workflows can only be run when in the default branch so I don't think I can test this before merge. If i'm wrong please let me know.

chore(quantic): fixing github actions quantic package test workflow

---

.github/workflows/create-quantic-package.yml
packages/quantic/scripts/build/create-package.ts

https://github.com/coveo/ui-kit/runs/5321152179?check_suite_focus=true
We got farther but this should fix it.. for real this time.
The GITHUB_TOKEN env variable is not necessary for creating unpublished packages.
It's only to create Discussion posts after a successful publish so I deem it non-critical.
If the env variable is missing the final step will fail but the release won't be cancelled outright.

chore(quantic): remove unnecessary check for github token

---

packages/headless/src/case-assist.index.ts
packages/headless/src/controllers/core/interactive-result/headless-core-interactive-result.ts
packages/headless/src/controllers/document-suggestion-list/case-assist-headless-interactive-result.test.ts
packages/headless/src/controllers/document-suggestion-list/case-assist-headless-interactive-result.ts
packages/headless/src/features/case-assist/case-assist-analytics-actions.ts
packages/headless/src/features/case-assist/case-assist-analytics-selectors.test.ts
packages/headless/src/features/case-assist/case-assist-analytics-selectors.ts
packages/quantic/force-app/main/default/lwc/quanticDocumentSuggestion/quanticDocumentSuggestion.html
packages/quantic/force-app/main/default/lwc/quanticDocumentSuggestion/quanticDocumentSuggestion.js
packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.js
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.js

- New controller `buildCaseAssistInteractiveResult` created. this controller will take care of sending the correct analytics events when the user clicks on the title of a document suggestion in a quickview.
- New analytic action created `logDocumentSuggestionOpen`, this action dispatch a `suggestion_click` event with metadata indicating that the click was made to open the document suggestion after clicking on its title from the quickview.
- The QuanticResultLink calls the  buildCaseAssistInteractiveResult controller when being used in a Case Assist use case.
- The value of target in the QuanticResultLink  when used in the QuanticResultQuickview updated to be "_blank" instead of "_self", to open the link in a new tab instead of opening it in the same tab. …

Fix(Headless, Quantic): Sending the correct analytics event when clicking on the title of the Quickview of a document suggestion

---

packages/headless/config/api-extractor/case-assist.json
packages/headless/doc-parser/doc-parser.ts
packages/headless/doc-parser/use-cases/case-assist.ts
packages/headless/src/api/service/case-assist/get-document-suggestions/get-document-suggestions-response.ts
packages/headless/src/app/case-assist-engine/case-assist-engine-configuration.ts
packages/headless/src/case-assist.index.ts
packages/headless/src/controllers/document-suggestion-list/headless-document-suggestion-list.ts
packages/headless/src/features/case-assist/case-assist-analytics-actions-loader.ts
packages/headless/src/features/document-suggestion/document-suggestion-slice.test.ts
packages/headless/src/features/document-suggestion/document-suggestion-state.ts
packages/quantic/force-app/main/default/lwc/quanticDocumentSuggestion/quanticDocumentSuggestion.js

https://coveord.atlassian.net/browse/SVCC-470
This PR makes the JSDoc available for the case assist use case in Headless.
The end result was tested by generating both the Headless and Quantic documentation in the online documentation repository.

feat(case-assist): add JSDoc support

---

packages/headless/src/controllers/case-field/headless-case-field.test.ts
packages/headless/src/controllers/case-field/headless-case-field.ts
packages/headless/src/features/case-assist/case-assist-analytics-actions.ts
packages/headless/src/features/case-assist/case-assist-analytics-selectors.test.ts
packages/headless/src/features/case-assist/case-assist-analytics-selectors.ts
packages/quantic/cypress/integration/case-classification/case-classification-expectations.ts
packages/quantic/cypress/integration/case-classification/case-classification.cypress.ts
packages/quantic/force-app/main/default/lwc/quanticCaseClassification/quanticCaseClassification.js

[SVCC-456](https://coveord.atlassian.net/browse/SVCC-456)
On the first time loading the case classification component (no interaction by user yet), this component already send 2 UA events : `svc_action: "ticket_classification_click"`  & `svc_action: "ticket_field_update"`.
This is happening because from the Quantic side we automatically select the classification with highest confidence when fetching classifications. .
When a value is auto-selected because it has the highest confidence, we should send a "ticket_classification_click" with metadata identifying it as an automatic selection.
https://user-images.githubusercontent.com/86681870/154517620-3da46c16-fb86-4606-9ee9-f951a9c6e330.mov

fix(headless, quantic):  Update analytics events sent when auto selecting the classification with the highest confidence

---

packages/quantic/scripts/build/util/github.ts

The typing for these params was either changed or is newly enforced. Either way, this fixes it so the quantic release discussion post can be done automatically again.

chore(quantic): updated graphql typing

---

packages/quantic/cypress/integration/case-classification/case-classification-expectations.ts
packages/quantic/cypress/integration/case-classification/case-classification.cypress.ts
packages/quantic/cypress/integration/console-expectations.ts
packages/quantic/cypress/integration/document-suggestion/document.suggestion.expectations.ts
packages/quantic/force-app/main/default/lwc/quanticCaseClassification/quanticCaseClassification.js

[SVCC-466](https://coveord.atlassian.net/browse/SVCC-466)
Currently we always display the suggestions returned by our ML models even if the returned suggestions are not among all the available options retrieved from Salesforce. 
If a user for Example introduces `Priority` as the SF field name and `sfreason` as the Coveo field name, like that we having non corresponding SF field name and Coveo field name. in this case we dont want to display the suggestions cause they are not corresponding to the right field and to inform the user of this problem we want to log warnings to inform him.
Ignore suggestions that aren't part of the possible values retrieved from Salesforce and raise a warning when it happens.

fix(quantic): not displaying suggestions when they are not among all the available options

---

packages/atomic/stencil.config.ts
packages/headless/esbuild.js

When running `npm run dev`, and trying to do changes in Headless and testing them in Atomic, source maps where completely broken.
I added a plugin to `replaceHeadlessMap` which fiddle with the rollup output to fix the map file to the "external builds" folder.
Next up, I want to fix the problem where there's like 3 or 4 reload in Atomic whenever you you do a change in Headless 😮‍💨 
https://coveord.atlassian.net/browse/KIT-1460

chore(headless): fix sourcemap when working in dev with atomic

---

.deployment.config.json

Otherwise the `.dcignore` file at the root of the repo gets, well, ignored.
https://coveord.atlassian.net/browse/KIT-1463

ci(snyk): fix snyk code config to use one path

---

packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx

Was missing the proper template content selection in result list table display, which is ultimately used by AtomicReact.
https://coveord.atlassian.net/browse/KIT-1462

fix(atomic-react): fix result list table layout

---

packages/atomic-react/README.md
packages/atomic-react/src/components/SearchInterfaceWrapper.tsx
packages/atomic/src/index.ts

Was originally reported from Coveo discuss.
Getting a reference to the 18n instance on the search interface is kind of awkward to do in React otherwise.
https://coveord.atlassian.net/browse/KIT-1461

feat(atomic-react): improve localization configuration for atomic-react

---

packages/quantic/cypress/integration/case-classification/case-classification.cypress.ts
packages/quantic/force-app/main/default/lwc/quanticCaseClassification/quanticCaseClassification.js

[SFINT-4428](https://coveord.atlassian.net/browse/SFINT-4428)
Steps to reproduce:
1. The user types the subject/description of his case.
2. Some suggestions appears and the user selects one of the suggestions.
3. The user updates the subject/description triggering new suggestions that do not include the value selected by the user.
4. The suggestions are not displayed and the value selected by the user is persisted and displayed in the select dropdown.
5. The user updates the subject/description triggering new suggestions that do include the value selected by the user.
6. The value suggestions are still not displayed and the the value selected by the user is still displayed in the select input which is not the behaviour we want.
https://user-images.githubusercontent.com/86681870/158168302-3 …

fix(quantic): improvement of the display behaviour of the suggestions

---

packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx

For whatever reason, it looks like `100vh` on Android includes the navigation bar.
| Pixel 4 Emulator — Chrome | OnePlus 9 Pro — Chrome | OnePlus 9 Pro — Firefox |
| --- | --- | --- |
|  ![Screenshot_1647266709](https://user-images.githubusercontent.com/54454747/158192324-aef119f1-00ed-4cdd-bc6a-9757dd994ca8.png) | ![Screenshot_2022-03-14-10-03-45-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/54454747/158192597-19aa5f23-24d7-4353-a019-c5cff23eb40c.jpg) | ![Screenshot_2022-03-14-10-03-20-55_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/54454747/158192628-d6f48009-016a-4d12-9f0a-0288cda9ac15.jpg)  |
After fixing the issue, I tested on iOS as well to make sure I didn't break anything.
https://coveord.atlassian.net/browse/KIT-1366

fix(atomic): moved "view results" button on Android above the navigation bar

---

scripts/deploy/update-npm-tag.js

This is something I had reverted last time I tried to do a release since the path was incorrect. Angular is "special" in how component library are packaged, with a projects subfolder.
I did a test run of the script locally and it should work next release 🤞  
https://coveord.atlassian.net/browse/KIT-1442

ci: add atomic-angular package tag

---

package-lock.json
package.json
packages/bueno/esbuild.js
packages/headless/esbuild.js
scripts/bundle/umd.js

Last time I tried to update esbuild, this broke the integration with Quantic, since there was some changes in how esbuild generates the common js module.
I've modified the "umd" output (which is itself not supported by esbuild) to use an IIFE + global name (CoveoHeadless) + a footer to mimic what UMD would do.
I also had to specify es6 for the esm module, otherwise this would break in Atomic storybook integration.
https://coveord.atlassian.net/browse/KIT-1450

chore(headless): update esbuild

---

packages/headless/src/controllers/search-box/headless-search-box.ts

it's a follow-up to this PR: https://github.com/coveo/doc_jekyll-public-site/pull/6709

feat(headless): adds a link to the usage article about highlighting

---

packages/atomic/src/components/facets/facet-value-box/facet-value-box.tsx

Display count for "box" facets as compact (or short) notation.
ie: 123,999,888-> 124M
Otherwise it gets silly pretty quickly since there's not a lot of horizontal space for each individual value.
https://coveord.atlassian.net/browse/KIT-1037

feat(atomic): display count as compact number for facet values box

---

packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx

https://coveord.atlassian.net/browse/KIT-1513
Follow-up to https://github.com/coveo/ui-kit/pull/1867
Example:
```css
atomic-result-list::part(result-table-row-even) {
background-color: var(--atomic-neutral-light);
}
```

feat(atomic): added table odd and even row parts

---

scripts/deploy/bump-version.js

https://coveord.atlassian.net/browse/KIT-1515
[**See this related PR for samples**](https://github.com/ThibodeauJF/atomic-cli-v1.25/pull/1/files)
When installing @coveo/atomic, @coveo/headless is both a “subpackage” (@coveo/atomic/headless) and a dependency (@coveo/headless).
1. Both versions can have a possible mismatch
2. The typescript of Atomic’s Headless points to @coveo/headless instead of @coveo/atomic/headless. <img width="566" alt="Screen Shot 2022-03-30 at 8 58 15 AM" src="https://user-images.githubusercontent.com/4923043/160917982-d60866c9-d602-416f-84a8-039e6eee9318.png">
3. You start getting completions for both packages in VS code, because of the dependency. Not a big deal, but can be a bit annoying. <img width="808" alt="Screen Shot 2022-03-30 at 8 30 06 AM" …

fix(atomic): possible @coveo/headless version mismatch

---

.deployment.config.json
Jenkinsfile

To allow [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) capabilities to our clients, we need to deploy patch versions to our CDN.
That way a link on a specific patch version can be "fixed", have its SHA-512 computed, and will not change over time.
As opposed to minor version, which could contain hotfix in the future.
@npushkarskii & @jpmarceau : Eventually (really not needed short term/not urgent), we should arrange for CDN links to be auto generated in our doc website for each release we do, similar to JSUI. 
For example with last release:
https://docs.coveo.com/en/m16b2503/javascript-search-framework/march-2022-release
https://coveord.atlassian.net/browse/KIT-1512

ci(cdn): deploy patch version to CDN

---

packages/atomic/src/components/atomic-result-children/atomic-result-children.tsx

https://coveord.atlassian.net/browse/KIT-1535
so we could add something like
only when there are children

feat(atomic): allow to add children inside atomic-result-children

---

packages/atomic-react/README.md

- Replace `jsx` by `tsx`, we are using type annotations.
- Add imports. This is the meat, it'll help understand that you have access to `headless` through `@coveo/atomic-react` and that you should not install it directly.
- Fixed the example involving the `AtomicResultBadge`, the callback was not returning an Element.

docs(atomic-react): add imports, fix example

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/cypress/integration/smart-snippet.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-answer.tsx
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-expandable-answer.tsx
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet.tsx
packages/atomic/src/utils/utils.ts

https://coveord.atlassian.net/browse/KIT-1499
Follow-up to https://github.com/coveo/ui-kit/pull/1854/files, but improved.
This adds custom styling to smart snippet answers by doing the following:
```html
<atomic-smart-snippet>
<template>
<style>
b { color: red; }
</style>
</template>
</atomic-smart-snippet>
```
This also adds a prop which can be used as an alternative in frameworks like React, Angular or Vue.

feat(atomic): added custom styling to smart snippet answer

---

packages/atomic-react/package-lock.json
packages/atomic/src/components/atomic-result-list/atomic-result-list.tsx
packages/samples/headless-react/jest.setup.js
packages/samples/headless-react/package-lock.json
packages/samples/headless-react/package.json

Couple seems to have went wrong:
* With the bump to atomic-react@1.0, I also bumped some `cra` dependencies. This caused subtle changes to jest setup in headless-react samples, which means we now have to add extra config for Jest
* `setRenderingFunction` in AtomicResultList could be undefined if called before `initialize`. I modified it so that `ResultListCommon` is always created first, no matter the entry point.
🤞 
https://coveord.atlassian.net/browse/KIT-1557

fix(atomic): fix atomic react rendering function

---

packages/headless/src/api/commerce/product-listings/product-listing-params.ts
packages/headless/src/controllers/context/headless-context.test.ts
packages/headless/src/controllers/context/headless-context.ts
packages/headless/src/controllers/core/context/headless-core-context.test.ts
packages/headless/src/controllers/core/context/headless-core-context.ts
packages/headless/src/controllers/product-listing/context/headless-product-listing-context.test.ts
packages/headless/src/controllers/product-listing/context/headless-product-listing-context.ts
packages/headless/src/features/product-listing/product-listing-actions.ts
packages/headless/src/product-listing.index.ts
packages/headless/src/state/product-listing-app-state.ts
packages/headless/src/test/mock-product-listing-state.ts

Add a context controller to give custom context information through the product listings engine.
[COM-1459](https://coveord.atlassian.net/browse/COM-1459)

feat(commerce): add a context controller for the product listings engine

---

packages/quantic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/quantic/cypress/integration/search-expectations.ts
packages/quantic/cypress/page-objects/search.ts
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.js

Clearing the filters on the Quantic Timeframe Facet would trigger two search requests due to the filter.clear action dispatching a search as well as the facet.deselectAll.
Now we only execute one or the other depending on if the filter is set using the filter or a selected timeframe.
[SVCC-550](https://coveord.atlassian.net/browse/SVCC-550)

fix(quantic): fixed double search on timeframe facet clear

---

packages/quantic/force-app/main/default/lwc/quanticSearchBox/quanticSearchBox.js
packages/quantic/force-app/main/default/lwc/quanticStandaloneSearchBox/quanticStandaloneSearchBox.js

Clicking the search boxes before the engine is initialized causes an error that breaks the components.
Simple optional chaining fixes it.

fix(quantic): added optional chaining to searchbox

---

packages/headless/src/api/analytics/analytics.test.ts
packages/headless/src/api/analytics/analytics.ts
packages/headless/src/controllers/pager/headless-pager.test.ts
packages/headless/src/controllers/pager/headless-pager.ts
packages/headless/src/features/search/search-actions-loader.ts
packages/headless/src/features/search/search-actions.ts
packages/headless/src/features/search/search-slice.test.ts
packages/headless/src/features/search/search-slice.ts

Problem was:
1. Execute a search, get search response ID, log an analytics search event.
2. Click on a result, analytics click event is linked to search response ID generated at step # 1, everything is good so far.
3. Use the pager to go to next page, execute a new query, get a new search response ID, update the results set/response/search ID. Log a custom event (not a search, since from the end user perspective, it's not a new search, it's just a continuation of the same query performed on step # 1)
4. Click on a new result, analytics click event is linked to search response ID generated at step # 3. Since at step # 3 we never log a search event, but a custom event, this means that click is flagged as incoherent by Usage Analytics, since there is no accompanying search event.
Now, this …

fix(headless): rework pagination logic to reuse existing searchResponseId

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-load-more-children-results/atomic-load-more-children-results.pcss
packages/atomic/src/components/atomic-load-more-children-results/atomic-load-more-children-results.tsx
packages/atomic/src/components/atomic-result-placeholder/atomic-result-placeholder.tsx
packages/atomic/src/components/atomic-result/atomic-result-row-desktop.pcss
packages/atomic/src/components/atomic-result/atomic-result-row-mobile.pcss
packages/atomic/src/components/atomic-result/atomic-result.tsx
packages/atomic/src/components/result-lists/atomic-folded-result-list/atomic-folded-result-list.stories.tsx
packages/atomic/src/components/result-lists/atomic-result-children/atomic-result-children.pcss
packages/atomic/src/components/result-lists/atomic-result-children/atomic-result-children.tsx
packages/atomic/src/components/result-lists/list-display-results-placeholder.tsx
packages/atomic/src/components/result-lists/result-list-common.tsx
packages/atomic/src/components/result-template-components/result-template-decorators.tsx
packages/atomic/src/locales.json
packages/atomic/src/pages/examples/folding.html

Couple pics:
Vid: (I changed the copy from show/hide all to collapse/expand, but it needed a server restart)
https://user-images.githubusercontent.com/30511433/164505605-ab8fb516-d22a-45f7-b626-1cc0efea45cc.mov

feat(atomic): add styling and states for children results and loading

---

packages/headless/doc-parser/src/entity-builder.ts

https://coveord.atlassian.net/browse/KIT-1577
instead of 
```
/Users/liviarett/coveo/ui-kit/packages/headless/doc-parser/src/entity-builder.ts:144
throw new Error(`No description found for param: ${param.name}`);
^
Error: No description found for param: collection
at getParamDescription (/Users/liviarett/coveo/ui-kit/packages/headless/doc-parser/src/entity-builder.ts:144:11)
at buildParamEntity (/Users/liviarett/coveo/ui-kit/packages/headless/doc-parser/src/entity-builder.ts:57:16)
at buildObjEntityFromParam (/Users/liviarett/coveo/ui-kit/packages/headless/doc-parser/src/interface-resolver.ts:308:34)
at resolveParameter (/Users/liviarett/coveo/ui-kit/packages/headless/doc-parser/src/interface-resolver.ts:263:12)
at /Users/liviarett/coveo/ui-kit/packages/headless/doc-parser/src/interface-re …
```

docs: add function name to doc parser error message

---

packages/quantic/force-app/main/default/lwc/quanticSearchInterface/quanticSearchInterface.js

[SFINT-4494](https://coveord.atlassian.net/browse/SFINT-4494)
Adding a new Quantic component to the page after the first initialization of the search interface is triggering the execution of the the initialization loop for a second time causing by this a weird behaviour by the Quantic Facets: the facet values are deleted after selecting one value.
The initialization loop should run only once and the facets should work as expected after adding them after the first execution of the the initialization loop.
`buildUrlManager` headless controller is called in each initialization loop, building this controller is triggering the dispatch of the following action [restoreSearchParameters](https://github.com/coveo/ui-kit/blob/7640744168e5c46d5b2e5bd578e9ac899d975602/packages/headless/src/features/fa …

fix(quantic): initialized callback executing more than once fixed

---

packages/atomic/src/components/atomic-result/atomic-result.pcss
packages/atomic/src/components/result-lists/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/result-lists/grid-display-results.tsx
packages/atomic/src/components/result-lists/result-list-common.pcss

https://coveord.atlassian.net/browse/KIT-1574
Why? https://html.spec.whatwg.org/#the-a-element
> [Transparent](https://html.spec.whatwg.org/#transparent), but there must be no [interactive content](https://html.spec.whatwg.org/#interactive-content-2) descend[a](https://html.spec.whatwg.org/#the-a-element)nt, a element descendant, or descendant with the [tabindex](https://html.spec.whatwg.org/#attr-tabindex) attribute specified.
Inspired by https://css-tricks.com/nested-links/ & https://inclusive-components.design/cards/

feat(atomic): make grid result <a> a sibling instead of parent

---

packages/headless/src/controllers/results-per-page/headless-results-per-page.test.ts
packages/headless/src/controllers/results-per-page/headless-results-per-page.ts

Similar to: https://github.com/coveo/ui-kit/pull/1938
Forgot to change the dispatched action for results-per-page.
https://coveord.atlassian.net/browse/KIT-1597

fix(headless): fix search ID generation for results-per-page controller

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-modal/atomic-modal.pcss
packages/atomic/src/components/atomic-modal/atomic-modal.tsx
packages/atomic/src/components/atomic-refine-modal/atomic-refine-modal.tsx
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-feedback-modal.pcss
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-feedback-modal.tsx
packages/atomic/src/global/global.pcss
packages/atomic/src/pages/examples/modal.html

https://coveord.atlassian.net/browse/KIT-1587
Prior to this PR, the `atomic-modal` had a "desktop" look (which is what we generally saw for the `atomic-smart-snippet-feedback-modal` component), and it had a mobile look (which is what we always saw for the `atomic-refine-modal` component).
In this PR, a boolean `fullscreen` prop was added to `atomic-modal`. The desktop look was mapped to the value `false` and the mobile look was mapped to the value `true`.
Uses `<atomic-modal fullscreen={false} ...>...</atomic-modal>`
Uses `<atomic-modal fullscreen={true} ...>...</atomic-modal>`

feat(atomic): refactored atomic-modal mobile/desktop look to fullscreen true/false prop

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-answer.tsx
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-expandable-answer.tsx

https://coveord.atlassian.net/browse/KIT-1604
The "show more" button in smart snippet only appears when there's not enough room vertically to display the snippet. 
Prior to this PR, the height of the content of the snippet was only evaluated when the snippet was initially rendered. However, the height varies when the size of the screen changes, such as when a mobile device's orientation is changed.

fix(atomic): fixed smart snippet show more/show less issue when rotating screen

---

packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-expandable-answer.pcss
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-expandable-answer.tsx

https://coveord.atlassian.net/browse/KIT-1603
Already showed it to Johnny
<table>
<tr>
<td>
<td>
</table>
<table>
<tr>
<td>
<td>
</table>

fix(atomic): improved alignment of the "show more"/"show less" smart snippet caret

---

packages/atomic/src/global/ripple.pcss
packages/atomic/src/utils/ripple.ts

https://coveord.atlassian.net/browse/KIT-1596
Live demo: https://r1kvvq.csb.app/#q=atlas%20data%20lake
I changed the ripple animation duration of each component so they are based off the radius of the ripple.

feat(atomic): improved ripple animation speed

---

packages/atomic/src/components/atomic-search-interface/analytics-config.spec.ts
packages/atomic/src/components/atomic-search-interface/analytics-config.ts
packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/utils/store.ts
packages/headless/src/api/search/search-api-params.ts
packages/headless/src/app/engine-configuration.ts
packages/headless/src/features/configuration/configuration-actions.ts
packages/headless/src/features/configuration/configuration-slice.test.ts
packages/headless/src/features/configuration/configuration-slice.ts
packages/headless/src/features/configuration/configuration-state.ts
packages/headless/src/test/mock-analytics-state.ts

Most notably `documentLocation`, `documentReferrer`, which Headless cannot determine itself (needs to be in a browser context).
Added auto resolving of Facet title (Headless does not contain the notion of facet label: it's purely a UI option).
Some minor changes in Headless for analytics parameters: Instead of sending an empty string when a value is un-available, simply don't send anything.
https://coveord.atlassian.net/browse/KIT-1623

feat(atomic,headless): add more out of the box analytics configuration for atomic

---

packages/atomic/src/components/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/result-lists/result-list-common.tsx
packages/atomic/src/components/result-template-components/atomic-result-image/atomic-result-image.tsx
packages/atomic/src/pages/examples/folding.html
packages/atomic/src/pages/index.html
packages/atomic/src/utils/props-utils.ts
packages/quantic/force-app/main/default/lwc/exampleSearch/resultTemplates/youtubeResultTemplate.html

https://coveord.atlassian.net/browse/KIT-1620
First set of performance improvements
1. Start loading i18n configured language sooner, before `initialize` is called
2. Only load configured language for i18n, don't load fallback language (e.g. if "fr", "en.json" was still loaded)
3. Remove lodash imports (should only be used as a dev dep), saves ~97kb
4. Use loading="lazy" on `img` tags

feat(atomic): network improvements

---

packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-1602
Altered the locales.json file "between-parentheses" attribute which would add unnecessary spacing inside facet counts when switching to French.

fix(atomic): fix extra facet count spacing when switching to French language

---

packages/samples/angular/package-lock.json
packages/samples/angular/package.json

https://coveord.atlassian.net/browse/KIT-1635
Ideally, we should remove `"private": "true"` and make this auto-update, but lerna seems to try to build the angular sample before the atomic-angular package, so I think this can be done later if/when we replace lerna with something else like `nx`.
This PR isn't particularly useful because the only difference it makes is that we can test newer features like depends-on, I can close it if you prefer.

chore(atomic): updated angular sample

---

packages/atomic/cypress/integration/result-list/folded-result-list-actions.ts
packages/atomic/cypress/integration/result-list/folded-result-list.cypress.ts
packages/atomic/cypress/integration/result-list/result-list-selectors.ts
packages/atomic/src/components/result-lists/atomic-result-children/atomic-result-children.tsx
packages/atomic/src/pages/examples/folding.html

https://coveord.atlassian.net/browse/KIT-1645
When using sections, grandchildren weren't actually rendering anything because when I cloned the children for inherited templates, I only got the top level stuff, meaning that we would render the `*-section` component, but nothing that was inside it

fix(atomic): clone child nodes for inherited templates in children

---

packages/atomic/cypress/integration/smart-snippet-suggestions-assertions.ts
packages/atomic/cypress/integration/smart-snippet-suggestions.cypress.ts
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-source.tsx
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-suggestions.tsx
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet.pcss
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet.tsx

https://coveord.atlassian.net/browse/KIT-1636
For some reason, VoiceOver for Mac OS announced the source of the smart snippet as a footer, but announced the source of the smart snippet suggestions as content information. Both are valid IMO.
Thanks to @mbenkirane-coveo for the highlighting!

feat(atomic): added analytics & highlighting to smart snippet suggestions

---

packages/atomic/src/components/result-lists/atomic-folded-result-list/atomic-folded-result-list.tsx
packages/atomic/src/components/result-lists/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/result-lists/grid-display-results.tsx
packages/atomic/src/components/result-lists/list-display-results.tsx
packages/atomic/src/components/result-lists/result-list-common.pcss

https://coveord.atlassian.net/browse/KIT-1646
While writing documentation, I realized that customizing the outline and the divider of the result list was complicated and unintuitive, and could easily be broken by our own changes.
I decided to work on this PR before finishing documentation because I wanted to establish how the outline and the divider are going to be customizable.
With this PR, the outline can now be customized like this:
```css
atomic-result-list::part(outline) {
border-color: red;
}
```
And the divider like this:
```css
atomic-result-list::part(outline)::before {
background-color: blue;
}
```
Alternately, I could also add a separate `divider` part just in case we end up with a weird DOM structure in the future.

feat(atomic): made result list outline and divider easily customizable

---

packages/atomic/cypress/integration/result-list/result-list-actions.ts
packages/atomic/cypress/integration/result-list/result-list.cypress.ts
packages/atomic/package-lock.json
packages/atomic/src/components.d.ts
packages/atomic/src/components/result-lists/atomic-result-list/atomic-result-list.tsx
packages/atomic/src/components/result-lists/result-list-common.tsx
packages/quantic/package-lock.json

The deprecated `image` prop (but not yet removed) stopped working since it was not passed down to `resultListCommon`.
I also did changes so that `imageSize` is not `undefined` by default, and then internally resolved to `icon` in resultListCommon, as a fallback when not provided.
This helps documentation and various tool. We should pay special attention to not reproduce this pattern in new components/refactor: 
When we hide the default value of a prop from the `@Prop()` Stencil decorator, it means users have to guess what ends up happening internally, VS just being able to read it (or be informed by their IDE).
https://coveord.atlassian.net/browse/KIT-1642

fix(atomic): fix regression on deprecated image prop for result list

---

packages/atomic/src/components/atomic-breadbox/atomic-breadbox.tsx

https://coveord.atlassian.net/browse/KIT-1662
Each screen reader I tested already ignored the icon. This fix corresponds with recommendations I saw from multiple articles online.
Screen readers I tested:
* VoiceOver for Mac OS
* VoiceOver for iOS
* TalkBack for Android
* JAWS for Windows
* NVDA for Windows

fix(atomic): hid breadcrumb icon from screen readers

---

packages/atomic/src/components/common/atomic-focus-trap.tsx
packages/atomic/src/utils/utils.ts

https://coveord.atlassian.net/browse/KIT-1665
I spent 4 miserable hours trying to write cypress tests for this, but Cypress is extremely flaky with focus tests and the ShadowDOM.
The issue this PR fixes is that the event target and `document.activeElement` return a parent of the focused element instead of the focused element itself. Chrome and Firefox both expose different properties in the event that contain the correct element, but not the same as each-other, and I couldn't find one in Safari for iOS.
I found out that `activeElement` tends to reference an element with a ShadowDOM, and the ShadowDOM itself has another `activeElement` in its root.

fix(atomic): improved focus trap detection

---

packages/atomic/src/pages/accessibility/commerce-full.html

https://coveord.atlassian.net/browse/KIT-1675
After I'm done with all accessibility issues, I will update the accessibility doc and look at the list of commits that modified `commerce-full.html`

docs(atomic): removed heading from table description column

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet-suggestions.tsx
packages/atomic/src/components/atomic-smart-snippet/atomic-smart-snippet.tsx
packages/atomic/src/components/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/components/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx
packages/atomic/src/components/facets/facet-common.ts
packages/atomic/src/components/facets/facet-header/facet-header.tsx
packages/atomic/src/pages/accessibility/commerce-full.html

https://coveord.atlassian.net/browse/KIT-1676
The alternative was to recommend implementers to add a heading before each facet, but that would cause screen readers to repeat the same heading twice, so I prefer to do this. This also follows the same pattern as for the smart snippet.
When no heading level is set, the only side-effect of this change is that the `span` in headings is now a `div`.

feat(atomic): added heading-level prop to facets

---

packages/atomic/src/components/facets/atomic-segmented-facet/atomic-segmented-facet.pcss
packages/atomic/src/components/facets/atomic-segmented-facet/atomic-segmented-facet.tsx

- Completed the basic styling for the segmented facets. 
- Count is displayed by default and can be hidden using parts
- Created subtasks for the remaining styling to be done.
Segmented facets look like this for now: 
Update:
- First and last facets have rounded edges
- Increased padding between count and facet value
- Different shades of blue on border between hover/selected facet state
https://coveord.atlassian.net/browse/KIT-1667

feat(atomic): Segmented facets styled partially

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-query-suggestions/atomic-search-box-query-suggestions.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx
packages/atomic/src/components/search-box-suggestions/suggestions-common.ts
packages/atomic/src/utils/string-utils.ts

https://coveord.atlassian.net/browse/KIT-1689
Here is a video of the navigation:
https://user-images.githubusercontent.com/30511433/171474146-ae9f7c88-a972-4d83-bdd6-3c57445f0f19.mov
A few screenshots of the aria stuff for ease of review:
`combobox` input
`listbox` div
`option` list item when there is a query, default value (listitem?) when there isn't one, which includes dividers (`query === undefined`) and instant results (`query === ''`)

feat(atomic): Implement keyboard navigation between panels in search box suggestions

---

packages/samples/headless-react/src/components/triggers/redirection-trigger.class.tsx
packages/samples/headless-react/src/components/triggers/redirection-trigger.fn.tsx

https://coveord.atlassian.net/browse/KIT-1702
When testing in both Atomic and the headless-react sample, I noticed that using `location.href =` (equivalent of `location.assign()` caused a redirection to happen after the query was added to the URL, causing the back button to redirect us forward again whenever we press it.
I checked, and JSUI uses `location.assign`.

docs(headless): used location.replace instead of assign in redirect trigger doc

---

scripts/deploy/bump-version.js

https://coveord.atlassian.net/browse/KIT-1719
Because of previous failures of last week, the tags were updated but the package not published, we need to temporarily override these tags https://github.com/coveo/ui-kit/runs/6865381088?check_suite_focus=true
I'll revert this right after

fix: temporarily force git tags

---

packages/atomic/src/components/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.tsx

https://coveord.atlassian.net/browse/KIT-1750
This is what happens when you start already on mobile (because I don't update the suggested query when on mobile, no results ever show)
https://user-images.githubusercontent.com/30511433/174060378-fb951f15-910a-427f-be0e-0da3475fe297.mov
However when you resize to mobile, we currently don't update the suggested query, which means that the render function in instant results still shows results for it.
https://user-images.githubusercontent.com/30511433/174060458-05678805-f3cc-495a-862b-2acc92c10762.mov
So I did two things here: update the state of the search box for mobile (clearing the suggested query), but also make sure that the render function doesn't return anything for mobile

fix(atomic): hide instant results on mobile on page resize

---

packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet.test.ts
packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet.ts
packages/headless/src/controllers/core/facets/facet/headless-core-facet.test.ts
packages/headless/src/controllers/core/facets/facet/headless-core-facet.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet.test.ts
packages/headless/src/controllers/facets/facet/headless-facet.test.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.test.ts
packages/headless/src/utils/utils.ts

https://coveord.atlassian.net/browse/KIT-1753
I noticed that when investigating a maintenance case. IMO we shouldn't send parameters that aren't supposed to be there... What if one day facetSearch is an actual param? Would all the headless request instantly fail? Anyways that was my reasoning for this change 😄

fix(headless): prevent facetSearch from being sent in the search request

---

.deployment.config.json

https://coveord.atlassian.net/browse/KIT-1768
It fails often cause npm versions aren't available yet

ci: move snyk certifiers to staging

---

packages/atomic/.storybook/preview.js

Kind of a hack-ish fix for the problem we've had with storybook and atomic-smart-snippet, discussed internally on slack.
Essentially, when loading a story from the documentation website with `?path=/story/atomic-smart-snippet`, we end up loading `?path=/story/atomic-smart-snippet-suggestions--default-smart-snippet-suggestions` instead.
The root cause is that the full story identifier in Storybook is the component name (`atomic-smart-snippet`) + the story name itself (`default-smart-snippet`). Full ID to exactly load this story then becomes `atomic-smart-snippet--default-smart-snippet`. 
I first tried to make it so that the full ID is only the component name (ie: `atomic-smart-snippet`). I was not able to achieve this, and did not find anything in Storybook API that will allow that. …

docs(atomic): order stories by ID length

---

packages/headless/src/features/recent-queries/recent-queries-slice.test.ts
packages/headless/src/features/recent-queries/recent-queries-slice.ts
packages/quantic/cypress/integration/recent-queries-list/recent-queries-list.cypress.ts
packages/quantic/cypress/page-objects/search.ts

https://coveord.atlassian.net/browse/KIT-1751

fix(headless): update recent queries only when query has results

---

packages/atomic/src/components/search/atomic-modal/atomic-modal.tsx
packages/atomic/src/global/global.pcss

https://coveord.atlassian.net/browse/KIT-1778
There was a glitch when opening the dev tools and closing them which showed the top of the refine modal at the bottom of the screen.

fix(atomic): hid modals when they were never opened

---

packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
packages/atomic/src/locales.json

https://coveord.atlassian.net/browse/KIT-1793
For every facet value where "Only" is displayed, I added "only" in the aria label.
<table>
<tr>
<td>
<td>
Rating facet labels:
* Inclusion filter on only 5 stars out of 5; 205 results
* Inclusion filter on 4 stars out of 5; 1163 results
* Inclusion filter on 3 stars out of 5; 146 results
* Inclusion filter on 2 stars out of 5; 25 results
* Inclusion filter on one star out of 5; 16 results
<tr>
<td>
<td>
Rating range facet labels:
* Inclusion filter on only 5 stars out of 5; 205 results
* Inclusion filter on 4 to 5 stars; 1361 results
* Inclusion filter on 3 to 5 stars; 1503 results
* Inclusion filter on 2 to 5 stars; 1528 results
* Inclusion filter on 1 to 5 stars; 1544 results
</table>

fix(atomic): improved aria label for rating facet values

---

packages/quantic/cypress/integration/tab-bar/tab-bar.cypress.ts
packages/quantic/force-app/examples/main/lwc/exampleQuanticTabBar/exampleQuanticTabBar.html
packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.html
packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.js

https://coveord.atlassian.net/browse/SFINT-4546
When a tab containing the same expression as another tab is selected from the drop-down list:
In the following the Tab2 has the same expression as Tab4
https://user-images.githubusercontent.com/86681870/176433899-6a06798b-2550-4830-98bb-ea693a1a1b7f.mov
https://user-images.githubusercontent.com/86681870/176433923-c3767569-c8de-477f-b3d4-2d7717b14fc4.mov

fix(quantic): corner case addressed in the QuanticTabBar component

---

packages/atomic-angular/projects/atomic-angular/package-lock.json
packages/atomic-react/package-lock.json
packages/atomic/package-lock.json
packages/atomic/src/components.d.ts
packages/atomic/src/components/common/interface/store.ts
packages/atomic/src/components/insight/atomic-insight-interface/atomic-insight-interface.tsx
packages/atomic/src/components/insight/atomic-insight-interface/store.ts
packages/atomic/src/components/recommendations/atomic-recs-interface/atomic-recs-interface.tsx
packages/atomic/src/components/recommendations/atomic-recs-interface/store.ts
packages/atomic/src/components/search/atomic-result/atomic-result.tsx
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/components/search/atomic-search-interface/store.ts
packages/atomic/src/utils/initialization-utils.tsx
packages/auth/package-lock.json
packages/bueno/package-lock.json
packages/headless/package-lock.json
packages/quantic/package-lock.json

https://coveord.atlassian.net/browse/KIT-1824

fix(atomic): add explicit types for different types of store

---

packages/quantic/cypress/integration/facets/facet/facet.cypress.ts
packages/quantic/cypress/page-objects/search.ts

A couple facet tests were failing as they expected 'account' facet search to yield only one result.
Instead of relying on a changing index I decided to intercept the facetSearch request and mock the response.
To mock the facet search request response to have only one value:
- Added mock function
- Added mock test setup function
- Moved the concerned tests into their on `it` blocks as, unfortunately cypress doesn't allow you to restore intercepts and overwriting them is messy and doesn't work great either.

chore(quantic): fixed flaky facet search tests

---

packages/atomic/cypress/integration/search-box/search-box.cypress.ts
packages/atomic/src/components/common/search-box/clear-button.tsx
packages/atomic/src/components/common/search-box/search-input.tsx
packages/atomic/src/components/common/search-box/submit-button.tsx
packages/atomic/src/components/insight/atomic-insight-search-box/atomic-insight-search-box.tsx
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/pages/examples/insights.html
packages/atomic/src/pages/index.html

https://coveord.atlassian.net/browse/KIT-1867
I'm aware the insight feature/refactor isn't fully done yet, but because of this early bug I basically made the functional components agnostic of the headless search box type & we're not passing down the controller which will sometimes be of type insight, sometimes commerce, etc...

fix(atomic): prevent search box "enter" from submitting twice

---

packages/quantic/scripts/build/util/sfdx.ts

[SVCC-2349](https://coveord.atlassian.net/browse/SVCC-2349)
Apparently a recent version of sfdx-cli introduced a change in the way errors are returned. Before, the error JSON response would be returned through stderr. It is now returned through stdout.
It prevented our deploy-community script from deploying on an existing scratch org.

chore(quantic): read sfdx error JSON output from stdout instead of stderr

---

packages/atomic/cypress/integration/facets/facet/facet-selectors.ts
packages/atomic/cypress/integration/facets/numeric-facet/numeric-facet-selectors.ts
packages/atomic/cypress/integration/facets/rating-facet/rating-facet-selectors.ts
packages/atomic/src/components/common/checkbox.tsx
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx
packages/atomic/src/components/search/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
packages/atomic/src/components/search/facets/color-facet-checkbox/color-facet-checkbox.tsx
packages/atomic/src/components/search/facets/facet-value-checkbox/facet-value-checkbox.pcss
packages/atomic/src/components/search/facets/facet-value-checkbox/facet-value-checkbox.tsx

I extracted the facet value's checkbox into an accessible Checkbox functional component. `:checked` doesn't work since this is not a real checkbox.
I also changed the background color of checkboxes when hovered, so that they are accessible even when standalone. It doesn't look any worse than before in a facet value IMO.
When the checkbox is checked, the part `PART-checked` is added.
Checked:
Checked & hovered:
Checked:
Checked & hovered:
https://coveord.atlassian.net/browse/KIT-1868

feat(atomic): added -checked part to checkbox facets

---

packages/atomic/src/components/search/atomic-breadbox/atomic-breadbox.tsx

https://coveord.atlassian.net/browse/KIT-1874
Without this, screen readers only describe breadcrumbs as "Button, FacetName Colon FacetValue".

fix(atomic): improved aria label for breadcrumbs

---

packages/atomic/cypress/integration/facets/category-facet/category-facet-assertions.ts
packages/atomic/cypress/integration/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/integration/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/integration/facets/facet-common-assertions.ts
packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx
packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx

https://coveord.atlassian.net/browse/KIT-1879
In this PR, after a user presses "show more" under any facet's values, either:
* If the sort criteria is "automatic", the very first value is focused.
* If the sort criteria is anything other than "automatic", the first new value is focused.
Last time, I didn't do this because pressing "show more" would load some facet values in-between existing ones.
However, this time, I realized that setting a sort criteria ensures this never happens. I also noticed that the category facet never uses the "automatic" sort order. Woops...

fix(atomic): focus first new value in facets when pressing show more

---

packages/atomic/src/pages/accessibility/commerce-full.html

https://coveord.atlassian.net/browse/KIT-1881
A lack of contrast between the search box's outline and the header-bg was reported.

docs(atomic): removed header-bg in commerce-full.html

---

packages/quantic/cypress/integration/breadcrumb-manager/breadcrumb-manager-expectations.ts
packages/quantic/cypress/integration/breadcrumb-manager/breadcrumb-manager-selectors.ts
packages/quantic/cypress/integration/breadcrumb-manager/breadcrumb-manager.cypress.ts
packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.css
packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.html
packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.js
packages/quantic/force-app/main/default/lwc/quanticPill/quanticPill.css
packages/quantic/force-app/main/default/lwc/quanticPill/quanticPill.html
packages/quantic/force-app/main/default/lwc/quanticPill/quanticPill.js

https://coveord.atlassian.net/browse/SVCC-2354
Before:
After:
And for the voiceover for each values in the breadcrumb:
Example with Type = Space
Before: 
🔊: "Space Type Clear, button"
After:
🔊: "Type Space Clear Filter, button"

fix(quantic): Fix voiceover breadcrumb and style

---

packages/headless/src/features/insight-search/insight-search-analytics-actions.test.ts
packages/headless/src/insight.index.ts

- caseContextActionsLoader is now correctly exported.
- InsightSearchAnalyticsActionsLoader is now correctly exported.
- buildResultTemplatesManager is now correctly exported.
- buildTab is now correctly exported.
- Typos fixed.

fix(headless): exporting the missing pieces

---

packages/headless/src/api/service/insight/insight-api-client.test.ts
packages/headless/src/api/service/insight/query/query-request.ts
packages/headless/src/features/insight-search/insight-search-actions.ts

The active tab information was missing in the insight query request sent to the customer service API.
The active tab information is now sent in the constant query parameter of the  insight query request.

fix(headless): Active tab added to the insight query request

---

packages/quantic/cypress/integration/facets/category-facet/category-facet-selectors.ts
packages/quantic/cypress/integration/facets/facet/facet-selectors.ts
packages/quantic/cypress/integration/facets/numeric-facet/numeric-facet-selectors.ts
packages/quantic/cypress/integration/facets/timeframe-facet/timeframe-facet-selectors.ts
packages/quantic/cypress/integration/recent-results-list/recent-results-list-selectors.ts
packages/quantic/force-app/main/default/lwc/exampleSearch/resultTemplates/caseResultTemplate.html
packages/quantic/force-app/main/default/lwc/exampleSearch/resultTemplates/chatterResultTemplate.html
packages/quantic/force-app/main/default/lwc/exampleSearch/resultTemplates/youtubeResultTemplate.html
packages/quantic/force-app/main/default/lwc/quanticCardContainer/quanticCardContainer.html
packages/quantic/force-app/main/default/lwc/quanticNoResults/quanticNoResults.html
packages/quantic/force-app/main/default/lwc/quanticQueryError/quanticQueryError.html
packages/quantic/force-app/main/default/lwc/quanticResult/quanticResult.html
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html

https://coveord.atlassian.net/browse/SVCC-2286
Using headers is probably a bad idea for two reasons.
1. right now, for a screen reader that reads the ui, it normally ties `<h3>` elements with the previous `<h2>` element. The problem is that in quantic, facet titles are using `<h2>` and the quantic result link of the templates are using `<h3>`. So semantically it looks like the last facet title, is the title of all the result links.
2. It is very possible that customers already use a hierarchy of headers in their page, we can't assume we are the only ones using `<h2>` and `<h3>`.
Before:
After:
* So I removed all the h2, h3 and replaced by div, and the styling has not changed. 
* I also fixed the cypress selectors.

feat(quantic): Remove usage of header elements

---

packages/atomic/cypress/integration/common-assertions.ts
packages/atomic/cypress/integration/smart-snippet.cypress.ts
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet-feedback-banner.tsx
packages/atomic/src/locales.json
packages/atomic/src/utils/accessibility-utils.tsx

https://coveord.atlassian.net/browse/KIT-1882
I added e2e tests to verify this along with every accessibility test.
I also added e2e accessibility tests to `atomic-smart-snippet` and fixed its minor accessibility issues.

fix(atomic): ensured aria labels contain innerText

---

.github/workflows/snyk.yml

Our Snyk gate run by comparing the report stored in GH Security Advisory for the head and base refs. Because we skip all CI for the commit created for the release, we have no report for a bit.
This fix that by running the workflow for Snyk on the master branch right after we completed the workflow for the release
Yolo should work ™️ (it's a CI thing, hard to test 😅)
-----
KIT-1897

chore(snyk): update Snyk report after v bump

---

packages/atomic/src/components/search/atomic-pager/atomic-pager.pcss
packages/atomic/src/components/search/atomic-pager/atomic-pager.tsx
packages/headless/src/features/pagination/pagination-slice.test.ts
packages/headless/src/features/pagination/pagination-slice.ts

Couple different problems fixed in this PR:
* Headless would return fraction of pages when manually changing `firstResult` in the URL
* Atomic would incorrectly display very big pager number in `atomic-pager` (would overflow)
* Fix some alignment issue with next and previous pager button
https://coveord.atlassian.net/browse/KIT-1906

fix(atomic,headless): fix atomic pager size overflow + headless page fraction

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/search/atomic-search-box/search-suggestion.tsx
packages/atomic/src/components/search/atomic-search-interface/atomic-aria-live.tsx
packages/atomic/src/locales.json
packages/atomic/src/utils/accessibility-utils.tsx
packages/atomic/src/utils/device-utils.ts

https://coveord.atlassian.net/browse/KIT-1908
Follow-up to https://github.com/coveo/ui-kit/pull/2286
In this PR, I changed the instructions for screen readers so they reflect the correct controls for macOS.
Also, I updated an [assertive aria-live](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-live#values) whenever a suggestion is selected, since VoiceOver on macOS doesn't notify of those by default.

fix(atomic): improved search box accessibility for macOS VoiceOver

---

packages/atomic/cypress/integration/segmented-facet-scrollable.cypress.ts

Instead of changing the viewport mid test using cy.viewport(), I changed it directly on the test configuration which should make the scrollable screen size test more stable.
https://coveord.atlassian.net/browse/KIT-1904

test(atomic): fixed flaky screen size increase/decrease flaky tests

---

packages/atomic/package.json
packages/atomic/src/components.d.ts
packages/atomic/src/components/insight/atomic-insight-result/atomic-insight-result.tsx

Generated definition file was referencing an internal type, thus resulting in an invalid `d.ts` file.
Since its also pretty easy to get such errors (and we've had the same kind of problem in the past), I've added a small task to try and validate the components definition file.
https://coveord.atlassian.net/browse/KIT-1926

fix(atomic): fix components definition file

---

packages/atomic/cypress/integration/aria-live-selectors.ts
packages/atomic/cypress/integration/common-assertions.ts
packages/atomic/cypress/integration/no-results-selectors.ts
packages/atomic/cypress/integration/no-results.cypress.ts
packages/atomic/cypress/integration/query-error-selectors.ts
packages/atomic/cypress/integration/query-error.cypress.ts
packages/atomic/cypress/integration/query-summary-selectors.ts
packages/atomic/cypress/integration/query-summary.cypress.ts
packages/atomic/cypress/integration/search-box/instant-results/search-box-instant-results.cypress.ts
packages/atomic/cypress/integration/search-box/search-box-selectors.ts
packages/atomic/cypress/integration/search-box/search-box.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/atomic-search-interface/atomic-aria-live.tsx
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/pages/accessibility/commerce-full.html
packages/atomic/src/pages/examples/folding.html
packages/atomic/src/pages/index.html
packages/atomic/src/pages/visualTests.html
packages/atomic/src/utils/accessibility-utils.tsx
packages/atomic/src/utils/debounce-utils.spec.ts
packages/atomic/src/utils/debounce-utils.tsx

https://coveord.atlassian.net/browse/KIT-1927
With the upcoming `atomic-notification` component, I noticed that screen readers weren't reading all aria-live updates, so I did a bit of investigation.
I made [a test page in codesandbox](https://zpwdgl.csb.app/) with React to test how different screen readers interpret changes to aria-live elements. Here are the results of my tests:
<table>
<tr>
<th></th>
<th>JAWS</th>
<th>NVDA</th>
<th>macOS VoiceOver</th>
<th>iOS VoiceOver</th>
<th>TalkBack</th>
<tr>
<th>1 aria-live and no delay
<td>Says the last message.
<td>Says the last message.
<td>Says the last message.
<td>Says the last message.
<td>Says the last message.
<tr>
<th>1 aria-live and a delay
<td>Flaky, needs a delay of at-least 5ms.
<td>Flaky, needs a delay of at-least 15ms. …

fix(atomic): improved atomic-aria-live for simultaneous messages

---

packages/atomic/package.json

https://coveord.atlassian.net/browse/KIT-1961
Previous steps (should) already have emitted the types, so we just need to check the files exists and that it's valid.
This tsc command will do it.
@lvu285, if you can confirm that it addresses your problem, it'd be nice ;)

chore(atomic): os-agnostic filecheck

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/common/atomic-focus-detector.tsx
packages/atomic/src/components/common/atomic-focus-trap.tsx
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/utils/utils.ts

https://coveord.atlassian.net/browse/KIT-1941
iOS VoiceOver was calling the input's `onBlur`, which cleared suggestions.
Instead of detecting `blur` on the search input, I'm detecting when the entire search box component is blurred, and closing suggestions when `tab` is pressed to maintain the normal behaviour on desktop.

fix(atomic): made search box suggestions usable on iOS VoiceOver

---

packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/quanticResultPrintableUri.css
packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/quanticResultPrintableUri.html

[SVCC-2277](https://coveord.atlassian.net/browse/SVCC-2277)
Changed the clickable object from an A tag to a button as it does not redirect to another page. The mac screenreader now detects it as a expandable object

fix(quantic): changed ... to expand from a A tag to a button

---

packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacetStyles/quanticFacetStyles.css
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.html
packages/quantic/force-app/main/default/lwc/quanticSearchBox/quanticSearchBox.html
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.html

[SVCC-2302](https://coveord.atlassian.net/browse/SVCC-2302)
Removed `outline : 0` in order to display borders when `focus-visible` is active
After the changes:
[SVCC-2381](https://coveord.atlassian.net/browse/SVCC-2381)
Removed `outline : 0` in order to display borders when `focus-visible` is active
[SVCC-2309](https://coveord.atlassian.net/browse/SVCC-2309)

feat(quantic): added focus indicator for facet addMore addLess buttons.

---

packages/quantic/force-app/main/default/lwc/quanticNumberButton/quanticNumberButton.html
packages/quantic/force-app/main/default/lwc/quanticNumberButton/quanticNumberButton.js

[2306](https://coveord.atlassian.net/browse/SVCC-2306)
Facet Values’ aria-pressed is implemented along with `SVCC-2272`
Both QuanticPager and QuanticResultsPerPage render quanticNumberButton, so changes are applied to quanticNumberButton. `<lightning-button>` is replaced by `<button>`, since it does not support "aria-pressed".

feat(quantic): added aria-pressed for pager

---

packages/quantic/force-app/main/default/lwc/quanticNoResults/quanticNoResults.js

[SFINT-4605](https://coveord.atlassian.net/browse/SFINT-4605)
Making the `QuanticNoResullt` component use the right headless bundle to make it usable in multiple use cases.
Note that the HistoryManager controller is not adapted to the insight use case yet. For this reason this component will be use in the new Coveo Quantic Insight Panel only with the property `disableCancelLastAction` set to `true`.

fix(quantic): making the QuanticNoResult use the correct headless bundle

---

packages/quantic/force-app/main/default/lwc/quanticColoredResultBadge/__tests__/quanticColoredResultBadge.test.js
packages/quantic/force-app/main/default/lwc/quanticColoredResultBadge/colorsUtils.js
packages/quantic/force-app/main/default/lwc/quanticColoredResultBadge/quanticColoredResultBadge.css
packages/quantic/force-app/main/default/lwc/quanticColoredResultBadge/quanticColoredResultBadge.html
packages/quantic/force-app/main/default/lwc/quanticColoredResultBadge/quanticColoredResultBadge.js
packages/quantic/force-app/main/default/lwc/quanticColoredResultBadge/quanticColoredResultBadge.js-meta.xml

- This component will be used inside the result template of the Insight Panel to display the result badges.
- In the Insight Panel configuration we receive the following information about the badge to display for each result template: 
```
badge: {
label: "Document",
color: "#DABFE9"
}
```
- This component will create a badge with the correct label and the correct color.
- This component contains the logic to create a secondary color from the given primary color.
- The given primary color will be used as the background color of the badge and the secondary color will be used as the text color as well as the border color.
- This component will first convert the given Hex color to RGB, then will convert the RGB color to [HSL](https://www.w3schools.com/colors/colors_hsl.asp)(Hue, Saturation, …

feat(quantic): new QuanticColoredResultBadge component created

---

packages/atomic/src/components/search/result-template-components/atomic-field-condition/atomic-field-condition.tsx
packages/atomic/src/components/search/result-templates/atomic-result-children-template/atomic-result-children-template.tsx
packages/atomic/src/components/search/result-templates/atomic-result-template/atomic-result-template.tsx

Moving the annotations because MapProp annotations must be written with tags in the main component annotation.

docs(atomic): move mustMatch and mustNotMatch annotations

---

packages/atomic/src/components/search/facets/atomic-popover/atomic-popover.tsx

https://coveord.atlassian.net/browse/KIT-1974
After showing the popover to UX we came to the conclusion it was better this way.

feat(atomic): make atomic-popover backdrop transparent & make it clickable

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/did-you-mean-actions.ts
packages/atomic/cypress/integration/did-you-mean-assertions.ts
packages/atomic/cypress/integration/did-you-mean-selectors.ts
packages/atomic/cypress/integration/did-you-mean.cypress.ts
packages/atomic/cypress/integration/query-summary-assertions.ts
packages/atomic/cypress/integration/query-summary-selectors.ts
packages/atomic/src/components/search/atomic-did-you-mean/atomic-did-you-mean.tsx
packages/atomic/src/locales.json
packages/atomic/src/utils/jsx-utils.tsx

https://coveord.atlassian.net/browse/KIT-1932
Hovered:
I also changed the manual did you mean appearance (based on Johnny's feedback).
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>

feat(atomic): added query trigger to `atomic-did-you-mean` component

---

packages/samples/atomic-react/src/pages/FoldedResultListPage.tsx

https://coveord.atlassian.net/browse/KIT-1973
Unfortunately, that fix makes it almost identical to the "custom children" page, since this is the only way to display folded children right now.

docs(atomic): fixed folded result list atomic-react sample

---

packages/atomic/cypress/integration/facets/facet/facet.cypress.ts
packages/atomic/src/components/common/refine-modal/refine-modal-common.tsx
packages/atomic/src/components/insight/atomic-insight-refine-modal/atomic-insight-refine-modal.tsx
packages/atomic/src/components/insight/atomic-insight-refine-toggle/atomic-insight-refine-toggle.tsx
packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx

The original story was a relatively small fix: add a tooltip to insight-refine-toggle + change the title of the modal from `Sort and filter` to only `Sort`.
I however took the opportunity to also refactor the code for `RefineModalCommon`. It was kind of a weird class with a bunch of stateful option.
I've changed it to a (hopefully) simpler standard functional component.
https://coveord.atlassian.net/browse/KIT-1975

fix(atomic): fix insight-refine-toggle title and tooltip 

---

packages/atomic/src/components/common/pager/pager-common.tsx
packages/atomic/src/components/insight/atomic-insight-layout/insight-layout.ts
packages/atomic/src/components/insight/atomic-insight-pager/atomic-insight-pager.pcss
packages/atomic/src/components/insight/atomic-insight-pager/atomic-insight-pager.tsx
packages/atomic/src/components/search/atomic-pager/atomic-pager.tsx
packages/atomic/src/pages/examples/insights.html

Original bug was a relatively small fix to the local "widget" mode, which forced the width and height of the panel to look like a small window (in `insights.html`).
While working on that I also found some rendering problems with the pagination section when there are no results or there is a query error.
I moved styling from the layouts to the atomic-insight-pager component itself, so we can better control when it is hidden or shown.
Also refactored PagerCommon from a class to a function component.
https://coveord.atlassian.net/browse/KIT-1957

fix(atomic): fix insight panel widget mode + refactor pager

---

packages/quantic/force-app/main/default/lwc/quanticInsightInterface/quanticInsightInterface.js

In the Builder of the Salesforce Service Console, updating the Configuration ID is not reflected right away on the InsightRenderer component. The  Configuration ID is only reflected after leaving the Builder and coming back to the Service Console.
https://user-images.githubusercontent.com/86681870/186428634-1daec529-b25d-425c-a4fe-6d71b1ad92c0.mov
Destroying the Headless engine in the disconnected callback of the InsightRendrer component.
I agree that this solution sounds a bit extreme but I figured out that we gonna need to do it anyway to solve this issue and other issues like this one: [SFINT-4591](https://coveord.atlassian.net/browse/SFINT-4591), which basically is that when closing and re-opening a case record, the `interface load` analytics event  is not sent again, the reason is …

fix(quantic): destroy Engine performed when the QuanticInsightInterface is disconnected

---

packages/atomic/cypress/integration/no-results.cypress.ts
packages/atomic/src/components/common/no-results/no-results-common.tsx

Regression introduced with the extraction of no-results-common.
Reworked the component to make use of `<LocalizedString />` to quote and highlight the query.
Added a Cypress tests that verify that special characters are not double encoded.
https://coveord.atlassian.net/browse/KIT-2001

fix(atomic): fix no results message when it contains special characters

---

packages/quantic/force-app/main/default/lwc/quanticNoResults/quanticNoResults.js

Insight Panel category added to the JS doc of the QuanticNoResults component. this change will make this component appear under the Quantic Insight Panel components section in our documentation.

fix(quantic): JS doc comment fixed to generate the correct documentation for the QuanticNoResults component

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/insight/atomic-insight-interface/atomic-insight-interface.tsx
packages/atomic/src/components/insight/index.ts

https://coveord.atlassian.net/browse/KIT-2012
Added a prop and set the default to 5 in the `atomic-insight-interface`.

feat(atomic): set default insight panel results per page

---

packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.js
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.js

[2295](https://coveord.atlassian.net/browse/SVCC-2295)
Added focus control to modal;
Preview now set focus to modal's title (element `<a>`) after modal is rendered
Preview now set focus to the first focusable element when tab is pressed on the last element.

feat(quantic): add focus control to modal

---

packages/quantic/cypress/integration/refine-toggle/refine-toggle-expectations.ts
packages/quantic/cypress/integration/refine-toggle/refine-toggle.cypress.ts
packages/quantic/force-app/examples/main/lwc/exampleQuanticRefineToggle/exampleQuanticRefineToggle.js
packages/quantic/force-app/examples/main/lwc/exampleQuanticRefineToggle/templateWithFacets.html
packages/quantic/force-app/examples/main/lwc/exampleQuanticRefineToggle/templateWithFacetsWithoutInputs.html
packages/quantic/force-app/examples/main/lwc/exampleQuanticRefineToggle/templateWithoutFacets.html
packages/quantic/force-app/main/default/lwc/quanticRefineToggle/quanticRefineToggle.html
packages/quantic/force-app/main/default/lwc/quanticRefineToggle/quanticRefineToggle.js

[SFINT-4592](https://coveord.atlassian.net/browse/SFINT-4592)
The tooltip of the refine toggle button was missing.
https://user-images.githubusercontent.com/86681870/187979598-c8549f84-5827-4f01-9695-b4f5fc94da82.mov

fix(quantic): added the missing title of the refine toggle button

---

packages/quantic/cypress/integration/refine-toggle/refine-toggle.cypress.ts
packages/quantic/force-app/main/default/labels/CustomLabels.labels-meta.xml
packages/quantic/force-app/main/default/lwc/quanticRefineToggle/quanticRefineToggle.html
packages/quantic/force-app/main/default/lwc/quanticRefineToggle/quanticRefineToggle.js
packages/quantic/force-app/main/translations/fr.translation-meta.xml

[SVCC-2437](https://coveord.atlassian.net/browse/SVCC-2437)
Following a discussion with the UX team, we decided to update the title of the refine toggle button when this button is disabled.
When the facets are ON but the query returns no results:
Always keep filter button, we don’t want the layout to change all the time. Two situations here:
- The query is empty but there are filters selected: keep the filter panel accessible. So users can modify the filters as they might be the reason the query is not returning results.
- The query is empty but there are NO filters selected. Disable the button, it doesn’t help much to see an empty filter panel. Add a tooltip to explain the behaviour. example: No filters available for this query
https://user-images.githubusercontent.com/86681870/189116268- …

fix(quantic): new title for the refine toggle when it's disabled

---

packages/quantic/force-app/main/default/lwc/quanticResultTemplate/quanticResultTemplate.html
packages/quantic/force-app/main/default/lwc/quanticResultTemplate/quanticResultTemplate.js

The results templates slots were taking some space even when the slots are completely empty.
Note: Changes in this PR do not have any impact when the slots are provided.
Quantic standard result templates still look absolutely  the same:

fix(quantic): removed unnecessary margins from result template slots

---

packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.html
packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.js

[SVCC-2438](https://coveord.atlassian.net/browse/SVCC-2438)
When the title is not present, the QuanticResultLink is now displaying the click URI instead of displaying nothing.

fix(quantic): Display the click URI in the QuanticResultLink when the title is not present

---

packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.js

[SVCC-2436](https://coveord.atlassian.net/browse/SVCC-2436)
An error is thrown when trying to call the `getAbsoluteWidth` method with null as the parameter,  this situation happens when there is no Tab passed to the QuanticTabBar:

fix(quantic): issue fixed when QuanticTabBar doesn't contain any tab

---

packages/atomic/src/components/insight/atomic-insight-refine-toggle/atomic-insight-refine-toggle.tsx

Small adjustment on yesterday PR: Need to handle when there is an active facet that causes no results to return.
https://coveord.atlassian.net/browse/KIT-2019

fix(atomic): handle active breadcrumb corner case for insight-refine-toggle disable

---

packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet-assertions.ts
packages/atomic/cypress/integration/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/atomic/src/components/common/facets/facet-date-input/facet-date-input.tsx

https://coveord.atlassian.net/browse/KIT-1989
When using the input to type a date in the timespan facet, the user's timezone was assumed, which caused the values to change when when the search is resolved.
The timezone in the facet is now assumed to be UTC.

fix(atomic): removed timespan offset input timezone offset

---

packages/atomic/cypress/fixtures/test-fixture.ts
packages/atomic/cypress/integration/smart-snippet-actions.ts
packages/atomic/cypress/integration/smart-snippet-assertions.ts
packages/atomic/cypress/integration/smart-snippet-suggestions-actions.ts
packages/atomic/cypress/integration/smart-snippet-suggestions-assertions.ts
packages/atomic/cypress/integration/smart-snippet-suggestions.cypress.ts
packages/atomic/cypress/integration/smart-snippet.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet-answer.tsx
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet-expandable-answer.tsx
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet-suggestions.stories.tsx
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet-suggestions.tsx
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet.stories.tsx
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet.tsx
packages/atomic/src/components/search/result-link/result-link.tsx

https://coveord.atlassian.net/browse/KIT-2014
Copies https://github.com/coveo/search-ui/pull/1901
Depends on https://github.com/coveo/ui-kit/pull/2416
Analytics logged when clicking this:
Other changes in this PR:
* Added `times?: number` parameter to `TestFixture`'s `withCustomResponse`.
* Extracted `bindAnalyticsToLink(element: HTMLAnchorElement, options: ...)` from `LinkWithResultAnalytics`.
* Added links to example & test snippets (copied from Wikipedia).

fix(atomic): added smart snippet inline link analytics

---

packages/atomic/cypress/integration-insights-panel/insights-panel.cypress.ts
packages/atomic/cypress/integration/common-assertions.ts

https://coveord.atlassian.net/browse/KIT-2013
I want to test accessibility for the insight search box, since it's the only one which uses the `SearchInput` functional component without a popup, which has different accessibility properties.

test(atomic): change insight e2e accessibility test to only test search box

---

packages/headless/src/features/case-context/case-context-actions-loader.ts
packages/headless/src/features/case-context/case-context-actions.ts
packages/headless/src/features/case-context/case-context-slice.spec.ts
packages/headless/src/features/case-context/case-context-slice.ts
packages/headless/src/features/case-context/case-context-state.ts
packages/headless/src/features/insight-search/insight-search-analytics-actions.test.ts

`Case Id` and `Case Number` need to be sent in each insight analytics events, example:
Thus the need to add this piece of information to the case context  state and allow the user to set it with the new actions: `setCaseId` and `setCaseNumber`.
In a future PR coming soon, I'll add case number and case id to the payload sent in all the insight analytics events.

feat(headless): Case Id and Case Number added to the case context state

---

packages/atomic/src/components/common/atomic-modal/atomic-modal.tsx

https://coveord.atlassian.net/browse/KIT-1943
The strategy I went for is to add an event listener which completely disables scrolling and then prevent propagation where we do want scrolling to work.
This should affect all modals, including the feedback modal for smart snippet.
I tested to make sure this doesn't break scrolling on other browsers either. I tested the following:
* iOS Safari
* Android Chrome
* Android Firefox

fix(atomic): prevent scrolling behind refine modal on iOS

---

packages/atomic/cypress/integration/result-list/result-template-assertions.ts
packages/atomic/src/components/search/result-lists/result-list-common.tsx

https://coveord.atlassian.net/browse/KIT-2005
If the result list had `image-size="icon"` and the visual section had `image-size="small"`, results would have both the `image-icon` and `image-small` class.
What we actually want is for the list to have the class that matches its own config, and individual results to have classes that match theirs.
The result list may be due for a small refactor 🤔

fix(atomic): removed wrong section class from results

---

packages/atomic/cypress/integration/did-you-mean-assertions.ts
packages/atomic/cypress/integration/did-you-mean-selectors.ts
packages/atomic/cypress/integration/did-you-mean.cypress.ts
packages/headless/src/features/search/search-actions-thunk-processor.ts

https://coveord.atlassian.net/browse/KIT-2042
The new query was present instead of the original query.

fix(headless): fixed didYoumean auto correction originalQuery

---

packages/headless/src/api/commerce/product-listings/product-listing-api-client.test.ts
packages/headless/src/api/commerce/product-listings/product-listing-params.ts
packages/headless/src/api/platform-client.test.ts
packages/headless/src/api/platform-client.ts
packages/headless/src/api/preprocess-request.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/api/search/search-api-params.ts
packages/headless/src/api/service/case-assist/case-assist-api-client.test.ts
packages/headless/src/api/service/case-assist/case-assist-params.test.ts
packages/headless/src/api/service/case-assist/case-assist-params.ts
packages/headless/src/api/service/insight/insight-api-client.test.ts
packages/headless/src/api/service/insight/insight-params.test.ts
packages/headless/src/api/service/insight/insight-params.ts

https://coveord.atlassian.net/browse/KIT-2017
* The `clientOrigin` parameter of `preprocessRequest` for some search requests was changed.
* Product listing requests now have the `clientOrigin` `commerceApiFetch`
* Case assist requests now have the `clientOrigin` `caseAssistApiFetch`
* Insight requests now have the `clientOrigin` `insightApiFetch`

feat(headless): added platform-specific origins to requests

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/cypress/e2e/result-list/result-components/result-localized-test.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/result-template-components/atomic-result-localized-text/atomic-result-localized-text.ts

`key` is a reserved keyword. Stencil recommends not using that.
https://coveord.atlassian.net/browse/KIT-2086

fix(atomic): modify result-localized-text key property

---

packages/headless/src/integration-tests/search-app.test.ts

https://coveord.atlassian.net/browse/KIT-2099
The configuration for the test wasn't actually getting used, so this test wasn't testing anything.

test(headless): fixed renewAccessToken functional test

---

packages/headless/src/api/search/facet-search/base/base-facet-search-request.ts
packages/headless/src/api/search/search-api-client.test.ts
packages/headless/src/controllers/core/facets/facet-search/category/headless-category-facet-search.ts
packages/headless/src/controllers/core/facets/facet-search/facet-search.test.ts
packages/headless/src/controllers/core/facets/facet-search/facet-search.ts
packages/headless/src/controllers/core/facets/facet-search/specific/headless-facet-search.test.ts
packages/headless/src/controllers/core/facets/facet-search/specific/headless-facet-search.ts
packages/headless/src/controllers/facets/category-facet/headless-category-facet-search.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/controllers/field-suggestions/facet/headless-field-suggestions.test.ts
packages/headless/src/controllers/field-suggestions/facet/headless-field-suggestions.ts
packages/headless/src/controllers/index.ts
packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet-search.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.ts
packages/headless/src/features/facets/facet-search-set/generic/generic-facet-search-actions.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-request-builder.test.ts
packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-request-builder.ts
packages/headless/src/integration-tests/field-suggestions.test.ts

https://coveord.atlassian.net/browse/KIT-2073
In this PR, I made the following changes:
* Extracted facet and facet search interfaces into field suggestions interfaces
* Replaced `buildFacet` in field suggestions with `buildFacetSearch` (so that non-public options can be passed to it)
* Added "includeSearchContext` option to facet search
* Added executeFacetSearchWithoutSearchContext` action
I chose to continue using the generic facet search to avoid the changes being breaking, and because I thought it would save me some time making this change. Unfortunately, this had many drawbacks, and I'm not sure if I like this approach anymore. I will leave comments in this PR for discussion.

fix(headless): made field suggestions not inherit the search context 

---

packages/headless/src/api/service/insight/get-interface/get-interface-config-request.ts
packages/headless/src/api/service/insight/get-interface/get-interface-config-response.ts
packages/headless/src/api/service/insight/insight-api-client.test.ts

The insight interface fetch call will now return facet type info if the `detailed=true` query param is set. We want this info returned so the insight panel can render the right type of facet.

feat(headless): updated insight interface with facet type

---

packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.html
packages/quantic/force-app/main/default/lwc/quanticCategoryFacet/quanticCategoryFacet.html
packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.css
packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.html
packages/quantic/force-app/main/default/lwc/quanticCategoryFacetValue/quanticCategoryFacetValue.js
packages/quantic/force-app/main/default/lwc/quanticDateFacet/quanticDateFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.html
packages/quantic/force-app/main/default/lwc/quanticFacetStyles/quanticFacetStyles.css
packages/quantic/force-app/main/default/lwc/quanticFacetValue/quanticFacetValue.html
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.html
packages/quantic/force-app/main/default/lwc/quanticRecentQueriesList/quanticRecentQueriesList.html
packages/quantic/force-app/main/default/lwc/quanticRecentResultsList/quanticRecentResultsList.html
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.css
packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.html

Fixed the facet value overflow behaviour. It worked correctly before but we seem to have lost it in some more recent modifications. Pretty much every type of facet had the same issue.
Also added some title attributes so a user can hover over a facet value and see the whole string if it's truncated.
Also removed some `nowrap` classes which don't exist. `slds-nowrap` would be valid but clearly we don't need them.

fix(quantic): fixed facet value overflow

---

packages/quantic/force-app/main/default/lwc/quanticQueryError/quanticQueryError.js

[SFINT-4674](https://coveord.atlassian.net/browse/SFINT-4674)
- `QunticQueryError` component updated to be able to work correctly with both the Headless search bundle and the Headless insight bundle.

feat(quantic): QuanticQueryError updated to support the insight use case

---

packages/quantic/cypress/page-objects/example-search.ts
packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.css
packages/quantic/force-app/main/default/lwc/exampleSearch/exampleSearch.html
packages/quantic/force-app/main/default/lwc/quanticNumberButton/quanticNumberButton.js
packages/quantic/force-app/main/default/lwc/quanticQueryError/quanticQueryError.js

[SFINT-4565](https://coveord.atlassian.net/browse/SFINT-4565)
-  display of QuerySummary adjusted in the example search page.
Additionally I fixed a margin issue in the QuanticNumberButton:
PS: The same exact fix will be applied to the insightFullSearch in SFIINT

fix(quantic): display of QuerySummary adjusted in the example search page

---

packages/quantic/force-app/main/default/lwc/quanticSort/quanticSort.css
packages/quantic/force-app/main/default/lwc/quanticSort/quanticSort.html

[SFINT-4537](https://coveord.atlassian.net/browse/SFINT-4537)
- #### padding of the QuanticSort component fixed

fix(quantic): padding of the QuanticSort component fixed

---

packages/headless/src/api/service/insight/insight-api-client.test.ts
packages/headless/src/api/service/insight/insight-api-client.ts
packages/headless/src/api/service/insight/query-suggest/query-suggest-request.ts
packages/headless/src/api/service/insight/query/query-request.ts
packages/headless/src/features/insight-search/insight-query-set-actions-loader.ts
packages/headless/src/features/insight-search/insight-query-suggest-request.ts
packages/headless/src/features/insight-search/insight-search-actions-loader.ts
packages/headless/src/features/insight-search/insight-search-actions.ts
packages/headless/src/features/insight-search/insight-search-request.ts
packages/headless/src/insight.index.ts

Added support for query suggestions in the `insight` use case. The client targets the querySuggest proxy on the customer-service-api.
Prior to this change the query suggestion fetch was no-op.

feat(headless): added insight query suggest support

---

packages/atomic/cypress/e2e/breadbox.cypress.ts
packages/atomic/cypress/e2e/facets/category-facet/category-facet-assertions.ts
packages/atomic/cypress/e2e/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/e2e/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/e2e/facets/facet-depends-on/facet-depends-on.cypress.ts
packages/atomic/cypress/e2e/facets/facet/facet.cypress.ts
packages/atomic/cypress/e2e/facets/numeric-facet/numeric-facet-assertions.ts
packages/atomic/cypress/e2e/facets/numeric-facet/numeric-facet.cypress.ts
packages/atomic/cypress/e2e/facets/rating-facet/rating-facet.cypress.ts
packages/atomic/cypress/e2e/facets/rating-range-facet/rating-range-facet.cypress.ts
packages/atomic/cypress/e2e/facets/segmented-facet/segmented-facet.cypress.ts
packages/atomic/cypress/e2e/facets/timeframe-facet/timeframe-facet-assertions.ts
packages/atomic/cypress/e2e/facets/timeframe-facet/timeframe-facet.cypress.ts
packages/headless/src/controllers/url-manager/headless-url-manager.test.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.test.ts
packages/headless/src/features/search-parameters/search-parameter-serializer.ts
packages/quantic/cypress/e2e/facets-1/category-facet/category-facet-expectations.ts
packages/quantic/cypress/e2e/facets-1/category-facet/category-facet.cypress.ts
packages/quantic/cypress/e2e/facets-1/facet/facet.cypress.ts
packages/quantic/cypress/e2e/facets-2/breadcrumb-manager/breadcrumb-manager.cypress.ts
packages/quantic/cypress/e2e/facets-2/numeric-facet/numeric-facet-expectations.ts
packages/quantic/cypress/e2e/facets-2/numeric-facet/numeric-facet.cypress.ts
packages/quantic/cypress/e2e/facets-2/timeframe-facet/timeframe-facet-expectations.ts
packages/quantic/cypress/e2e/facets-2/timeframe-facet/timeframe-facet.cypress.ts

As discussed in Slack.
New format for facets in `search-parameter-manager` will be `f-facetid=facetvalue1,facetvalue2` as opposed to `f[facetid]=facetvalue1,facetvalue2` before.
https://coveord.atlassian.net/browse/KIT-2119
* The [UrlManager](https://docs.coveo.com/en/headless/latest/reference/search/controllers/url-manager/) now serializes facets with a dash instead of brackets.
* For instance, `f[my-facet]=valueA,valueB` would become `f-my-facet=valueA,valueB`
* This is because brackets are [reserved characters in RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2), which get serialized by certain applications resulting in broken search page URLs.
* The hash in the URL representing the state of the search page now serializes facets with a dash instead of brackets.
* For …

fix(headless): modify delimiting character for facet in url manager

---

.deployment.config.json
.github/workflows/masterbot.yml
Jenkinsfile
scripts/deploy/bump-version.js
scripts/git.js
scripts/packages.js

https://coveord.atlassian.net/browse/KIT-2114
In theory, this PR should cause the following to happen:
* Any commit on a branch titled `prerelease/**` should execute the same CI as the `master` branch
* Commit bumps on this branch will instead bump packages with Lerna's default `-pre.#` suffix (see [conventional-prerelease](https://github.com/lerna/lerna/tree/main/commands/version#--conventional-prerelease)).
* Jenkins will skip updating the `alpha` NPM tag for any commit that isn't on the `master` branch.
* The deployment pipeline will disable `package_rollout` for any commit that isn't on the `master` branch, which will prevent it from ever reaching `stg` and `prd` (which are responsible for publishing to the staging CDN, publishing to the prod CDN, updating the NPM `beta` tag and …

ci: publish prerelease versions

---

packages/quantic/cypress/e2e/default-1/tab-bar/tab-bar-expectations.ts
packages/quantic/cypress/e2e/default-1/tab-bar/tab-bar-selectors.ts
packages/quantic/force-app/main/default/lwc/quanticTab/quanticTab.css
packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.css
packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.html

Overflow is now shown so we can see the dropdown.
Also added an arbitrary max width of 150px so long tab names get truncated.

fix(quantic): fixed tab dropdown visibility

---

scripts/deploy/invalidate-cloudfront.mjs

https://coveord.atlassian.net/browse/KIT-2150
Should be the last fix necessary due to converting from CJS to ESM.

ci: fix invalidate-cloudfront.mjs import

---

packages/atomic/cypress/e2e/search-interface.cypress.ts
packages/atomic/cypress/fixtures/test-fixture.ts
packages/headless/src/app/engine.ts
packages/headless/src/features/configuration/configuration-actions.ts
packages/headless/src/utils/utils.ts

https://coveord.atlassian.net/browse/KIT-2151
In v1, this isn't strictly needed, since `coveo.analytics` already disables analytics requests on its own, and Headless doesn't happen to include any identifiable information in the `analytics` object of search requests (it includes a clientId, but it's reset after each request).
In v2, this is now needed because search requests include the `actionCause` and `customData` of analytics events in their `analytics` object.
This PR removes the `analytics` object from search requests when doNotTrack is on, which is the same behaviour as when analytics are disabled.
An alternative could be to try to detect which client `coveo.analytics` initialized and disable analytics based on that.
I'm merging this in `v1` since this is non-breaking.

fix(headless): disabled analytics when doNotTrack is on

---

JenkinsfileStagingRelease
scripts/deploy/publish.mjs
scripts/exec.mjs
scripts/packages.mjs
scripts/prerelease.mjs

https://coveord.atlassian.net/browse/KIT-2155
Will merge with the following name to force a version bump (although it will generate a changelog entry):
> fix(headless): fixed issues when publishing package and updating tags
This time, I tested `publish.mjs` locally, which I should've done the first time.

fix(headless): fixed issues when publishing package and updating tags

---

scripts/git.mjs

https://coveord.atlassian.net/browse/KIT-2156
Will merge as `fix(headless): fix branch name detection in CI`
I updated the `getBranchName` command to use an older command which gives the same output. However, in Jenkins, it returns "HEAD" instead of the branch name since Jenkins is in a detached HEAD state.
I tested the following in Jenkins to confirm that node is able to read the environment variable:
```groovy
sh 'echo "console.log(process.env.BRANCH_NAME);" | node'
```

fix(headless): fix branch name detection in CI

---

package.json
scripts/deploy/manual-major-prerelease.mjs
scripts/packages.mjs
scripts/prerelease.mjs

https://coveord.atlassian.net/browse/KIT-2158
1. I tried to run `npm run bump:version:major-prerelease -- @coveo/headless @coveo/quantic @coveo/atomic @coveo/atomic-react @coveo/atomic-angular` (this is meant to bump the specified packages to `2.0.0-pre.0`). `npm install --no-package-lock` failed with the following error:
```
npm ERR! code
ETARGET
npm
ERR! 
notarget No matching version found for @coveo/headless@2.0.0-pre.0.
npm
ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! 
notarget a package version that doesn't exist.
npm 
ERR! A complete log of this run can be found in:
npm ERR!     /Users/btaillon/.npm/_logs/2022-12-05T20_34_36_681Z-debug-0.log
```
2. I tried removing `package-lock.json` and generating a new one with `npm install …

ci: fix manual version bump "npm install"

---

packages/atomic/src/components/insight/atomic-insight-layout/insight-layout.ts

The grid behaviour was yielding some weird looks with certain combinations of tabs, toggles, searchbox.
- The toggles would wrap to the next row when no tabs were present to take an entire row.
- The number of columns would not adjust to the number of elements present and empty rows still take up space so the right spacing wouldn't be correct.
FYI I can't say i'm a `display: grid` expert so let me know if you see a better way that doesn't involve as much javascript
Before
After

fix(atomic): fixed insight search section grid behaviour

---

packages/headless/src/controllers/field-suggestions/category-facet/headless-category-field-suggestions.test.ts
packages/headless/src/controllers/field-suggestions/category-facet/headless-category-field-suggestions.ts
packages/headless/src/controllers/field-suggestions/facet/headless-field-suggestions.test.ts
packages/headless/src/controllers/field-suggestions/facet/headless-field-suggestions.ts
packages/headless/src/controllers/index.ts
packages/headless/src/integration-tests/category-field-suggestions.test.ts
packages/headless/src/integration-tests/field-suggestions.test.ts
packages/samples/headless-react/package.json
packages/samples/headless-react/src/components/field-suggestions/category-field/category-suggestions.class.tsx
packages/samples/headless-react/src/components/field-suggestions/specific-field/field-suggestions.class.tsx
packages/samples/headless-react/src/pages/SearchPage.tsx

https://coveord.atlassian.net/browse/KIT-2101
The purpose of this Jira was to remove deprecated options, however, I noticed there was also issues with the documentation for field suggestions; field suggestions are tightly tied with facets, and their options are used to register a facet, which is important to know for users if they want to understand the behaviour of field suggestions (especially when field suggestions and a facet share the same facet id).
In this PR, I tested one possible solution to this problem in my opinion:
1. Adding documentation to field suggestions themselves that clarify that they actually initialize a facet.
2. Moving all field suggestions options under "facet" sub-options, since they are all used to register a facet. I think this really clarifies the purpose of …

feat(headless): refactored field suggestion options

---

packages/headless/src/api/service/insight/insight-api-client.test.ts
packages/headless/src/api/service/insight/query/query-request.ts
packages/headless/src/features/insight-search/insight-search-request.ts

[SFINT-4580](https://coveord.atlassian.net/browse/SFINT-4580)
- ### Tab query parameter added to the insight search query.

feat(headless):  tab query parameter added to the insight search query

---

.eslintrc.json
README.md
packages/headless/package.json
packages/headless/src/api/search/html/html-api-client.ts
packages/headless/src/api/service/insight/insight-params.ts
packages/headless/src/controllers/core/quickview/headless-core-quickview.test.ts
packages/headless/src/controllers/core/quickview/headless-core-quickview.ts
packages/headless/src/controllers/insight/quickview/headless-insight-quickview.ts
packages/headless/src/controllers/quickview/case-assist-headless-quickview.ts
packages/headless/src/controllers/quickview/headless-quickview.ts
packages/headless/src/features/result-preview/result-preview-actions.ts
packages/headless/src/features/result-preview/result-preview-slice.test.ts
packages/headless/src/features/result-preview/result-preview-slice.ts
packages/headless/src/features/result-preview/result-preview-state.ts
packages/headless/src/test/mock-result-preview-request-builder.ts
packages/headless/src/utils/url-utils.test.ts
packages/headless/src/utils/url-utils.ts
packages/quantic/cypress/page-objects/search.ts
packages/quantic/force-app/main/default/cspTrustedSites/QuanticCoveoPlatform.cspTrustedSite-meta.xml
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.css
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html
packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.js

Added `srcPath` to the quickview state to be used optionally if the implementation requires usage of the GET endpoint rather than the POST.
Quantic was also updated to leverage the change.
Misc changes:
- Fixed a typo in the readme. It formatted the whole file on save... is my linting setup wrong? I'm using `Prettier ESLint`
- Added the `engines` config to headless because, while attempting to use `URL` I got an error saying we needed to be compatible with Node v8. Looks like the root config doesn't get inherited by the packages.
- Speaking of `URL` apparently it looks like React Native has [some differences](https://www.npmjs.com/package/react-native-url-polyfill#user-content-why-do-we-need-this) with its URL implementation to I created a util to replace it for my purposes.

feat(headless): add src to use quickview in iframe

---

packages/atomic-angular/package.json
packages/atomic-angular/projects/atomic-angular/CHANGELOG.md
packages/atomic-angular/projects/atomic-angular/package.json
packages/atomic-react/CHANGELOG.md
packages/atomic-react/package.json
packages/atomic/CHANGELOG.md
packages/atomic/package.json
packages/headless/CHANGELOG.md
packages/quantic/CHANGELOG.md
packages/samples/angular/package.json
packages/samples/atomic-next/package.json
packages/samples/atomic-react/package.json
packages/samples/headless-react/package.json
packages/samples/stencil/package.json
packages/samples/vuejs/package.json

https://coveord.atlassian.net/browse/KIT-2165
* Some dependencies weren't automatically bumped, so I made them use a caret version selector
* I manually removed the duplicate v2 changelog entries
* It looks like the package-lock was broken, I fixed it by running `lerna bootstrap` then `npm install`.

fix: fixed v2 dependency linking

---

.github/actions/setup/action.yml
packages/quantic/.gitignore
packages/quantic/copy-static-resources.js
packages/quantic/coveo.d.ts
packages/quantic/cypress/e2e/default-1/tab-bar/tab-bar.cypress.ts
packages/quantic/force-app/examples/main/lwc/.eslintrc.json
packages/quantic/force-app/main/default/.eslintrc.json
packages/quantic/force-app/main/default/lwc/quanticHeadlessLoader/quanticHeadlessLoader.js
packages/quantic/force-app/main/default/lwc/quanticResultBadge/quanticResultBadge.js
packages/quantic/force-app/main/default/lwc/quanticResultLabel/quanticResultLabel.js
packages/quantic/force-app/main/default/lwc/quanticResultText/__tests__/quanticResultText.test.js
packages/quantic/force-app/main/default/lwc/quanticResultText/quanticResultText.css
packages/quantic/force-app/main/default/lwc/quanticResultText/quanticResultText.html
packages/quantic/force-app/main/default/lwc/quanticResultText/quanticResultText.js
packages/quantic/force-app/main/default/lwc/quanticResultText/quanticResultText.js-meta.xml
packages/quantic/force-app/main/default/staticresources/coveobueno.resource-meta.xml
packages/quantic/package.json
packages/quantic/typings/lwc/coveoheadless.resource.d.ts

Added component for displaying a field value in a result template.
We're planning on adding components for numeric, date and multivalue fields too so ideally those could wrap this component and leverage the `formattingFunction` prop.
Also added our [Bueno](https://github.com/coveo/ui-kit/tree/master/packages/bueno) validation library as a dependency. It's the recommended way to validate inputs and especially relevant in a javascript environment like LWC. Given I wanted to have some validation on the component I added bueno which we can use going forward.

feat(quantic): added quantic-result-text component

---

packages/atomic/src/components/insight/atomic-insight-layout/insight-layout.ts

Set the tab section to full width in the insight layout.
Before
After

fix(atomic): insight tab section full width

---

packages/headless/src/utils/highlight.test.ts
packages/headless/src/utils/highlight.ts

The escape function, like the comment says, is inspired by underscore.
Problem was that the implementation was no where near what underscore does, and was buggy.
Re-implemented it properly.
https://coveord.atlassian.net/browse/KIT-2189
[KIT-2189]: https://coveord.atlassian.net/browse/KIT-2189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(headless): improve escape highlight function

---

packages/headless/src/api/service/insight/insight-params.ts
packages/headless/src/controllers/insight/quickview/headless-insight-quickview.test.ts
packages/headless/src/controllers/insight/quickview/headless-insight-quickview.ts
packages/headless/src/features/insight-search/insight-result-preview-request-builder.test.ts
packages/headless/src/features/insight-search/insight-result-preview-request-builder.ts
packages/headless/src/insight.index.ts

*WIP as the proxy endpoint is not yet in production*
Modified the insight quickview controller to use the quickview endpoint on the customer-service-api.

feat(headless): insight quickview using proper endpoint

---

packages/atomic/src/components/search/atomic-layout/atomic-search-layout.pcss

The `flex-basis` of the left suggestions panel was `--atomic-layout-search-box-left-suggestions-width`, but the left & right suggestions panels both had `flex-grow: 1`, which caused them to both grow to take the extra space.
In this PR, I made the right suggestions panel have a flex-basis equal to `100% - var(--atomic-layout-search-box-left-suggestions-width)`, so that the left suggestions respect the intended size.
This also means that the left suggestions, with the search layout, are going to have a default size of 30%. Prior to this PR, since they split 20% of the remaining space with the right suggestions, the left suggestions occupied 40%. Without the search layout, the behavior is unaffected, each side takes 50%.
https://coveord.atlassian.net/browse/KIT-2147

fix(atomic): prevented left suggestions from expanding beyond layout variable

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/search/result-template-components/atomic-result-date/atomic-result-date.tsx
packages/atomic/src/components/search/result-template-components/atomic-result-image/atomic-result-image.tsx
packages/atomic/src/components/search/result-template-components/atomic-result-text/atomic-result-text.tsx
packages/atomic/src/components/search/result-template-components/atomic-result-timespan/atomic-result-timespan.tsx

I missed some annotations that told readers to set the fields-to-include in the result list. It should now be in the search-interface.

doc(atomic): fields to include update

---

packages/headless/src/controllers/core/facets/facet/headless-core-facet.ts
packages/headless/src/controllers/facets/facet/headless-facet.ts
packages/headless/src/controllers/insight/facets/facet/headless-insight-facet-options.ts
packages/headless/src/controllers/insight/facets/facet/headless-insight-facet.ts
packages/headless/src/controllers/product-listing/facet/headless-product-listing-facet.ts
packages/headless/src/insight.index.ts

https://coveord.atlassian.net/browse/KIT-2174
The doc parser was unable to extract the doc of FacetOptions since it was passed as a generic type to FacetProps.
I tried to refactor all "Option" interfaces from `core` files, prefixing them with "Core" (e.g., "FacetSearchOptions" -> "CoreFacetSearchOptions"), but this ended up being too big of a change and causing a lot of issues, so I dropped it.
Diff of the `parsed_doc.json` file with the changes in this PR: https://gist.github.com/btaillon/8a88b39f8869b88d1f302a37077f6535/revisions

docs(headless): removed generic type of FacetProps

---

packages/headless/src/api/service/insight/get-interface/get-interface-config-response.ts

The customer-service-api now returns the field type for result template details to allow the ui to render the appropriate result-template-[text|number|date|multi-value] component.

feat(headless): updated insight result template detail type

---

packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
packages/atomic/cypress/e2e/search-box/search-box.cypress.ts
packages/atomic/cypress/e2e/standalone-search-box.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/utils/local-storage-utils.tsx
packages/headless/src/controllers/core/search-box/headless-core-search-box-options.ts
packages/headless/src/features/query/query-actions.ts
packages/headless/src/features/query/query-state.ts
packages/headless/src/features/search-parameters/search-parameter-actions.ts

https://coveord.atlassian.net/browse/KIT-2201
I also added support for the query syntax in the standalone search box, so that the query syntax can be used for the initial search. However, both the standalone search box and the normal search box must have the query syntax enabled for that to work.

feat(atomic): added query syntax support to search box

---

packages/quantic/force-app/main/default/lwc/quanticResult/quanticResult.js

[SFINT-4766](https://coveord.atlassian.net/browse/SFINT-4766)
The Quickview  modal is closing it self whenever the mouse cursor leaves the page:
https://user-images.githubusercontent.com/86681870/211880769-2778f4f2-044a-4767-bdb1-f6ef623d6196.mov
This is occurring because when the mouse leaves the page the Quantic Result component is no longer hovered, which means the result actions are removed from the page including the Quickview result action, that's why the quickview modal is closing it self strangely.
When the Quick view modal is open, the Quantic Result component is now considered still in the hovered state even when the mouse leaves the page:
https://user-images.githubusercontent.com/86681870/211881689-218540d7-0ff1-4c77-95c8-0c562e37c706.mov
[SFINT-4760]: …

fix(quantic): hover state removed from result only when the modal quickview is closed

---

packages/headless/src/features/result-preview/result-preview-slice.test.ts
packages/headless/src/features/result-preview/result-preview-slice.ts

My initial thought was to add a new action to clear the preview content from the state.
This would be used by UI's when they want to "clear" the Quickview from the page, and don't need it loaded in memory anymore.
However I realized we could also just clear it automatically for our users whenever there is a new query executed, since... that's pretty much when you would want to unload any displayed Quickview from a page anyway...
Said differently, you load a quickview from a given list of result currently displayed to users.
When a new query is performed (and a new set of results is retrieved), then keeping the Quickview content in memory seems superfluous and we can just clear it automatically.
https://coveord.atlassian.net/browse/KIT-2198

feat(headless): reset preview content on new query

---

packages/headless/src/app/recommendation-engine/recommendation-engine-configuration.ts
packages/headless/src/app/recommendation-engine/recommendation-engine.test.ts
packages/headless/src/app/search-engine/search-engine-configuration.ts
packages/headless/src/app/search-engine/search-engine.test.ts
packages/headless/src/features/configuration/configuration-actions.ts

https://coveord.atlassian.net/browse/KIT-2225
I'm not sure of the exact reason why, but changing the page in Storybook or changing any option caused the whole search interface to crash with an error that said `search: value is an empty string.`.
My guess is that my recent changes to the `atomic-search-interface` (specifically adding `mutable: true` to `pipeline` and setting `this.pipeline = this.engine!.state.pipeline;` after initialization) caused Stencil to add `pipeline=""` to the search interface, and a piece of logic in Storybook that's responsible for cloning the interface and replacing it with the clone, caused the search interface to try to initialize the engine with an empty string as a pipeline.
When I added a check that excludes the pipeline from the engine's initial …

fix(headless): allowed empty string for query pipeline

---

packages/atomic/.storybook/default-result-component-story.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview/atomic-quickview.stories.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview/atomic-quickview.tsx
packages/headless/src/controllers/quickview/case-assist-headless-quickview.ts
packages/headless/src/controllers/quickview/headless-quickview.ts

Had to fix some stuff for storybook related to "preprocess" request.
Quickviews are using `application/x-www-form-urlencoded` , which you can't JSON.parse, JSON.stringify.
Adding @jpmarceau for some doc review as well.
https://coveord.atlassian.net/browse/KIT-2224

docs(atomic): add storybook for quickview

---

packages/quantic/force-app/main/default/lwc/quanticNoResults/quanticNoResults.html
packages/quantic/force-app/main/default/lwc/quanticSummary/quanticSummary.html
packages/quantic/force-app/main/default/lwc/quanticTabBar/quanticTabBar.html

`disable-linkify` property added to the Lightning Formatted Rich Text component used in the Quantic Summary and the Quantic No Results:
Removed unnecessary scroll bar from the Quantic Tab Bar component:
https://user-images.githubusercontent.com/86681870/214635566-49d5170e-dd11-46f0-b530-a5f36e6b24bc.mov
[SVCC-2784]: https://coveord.atlassian.net/browse/SVCC-2784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SFINT-4781]: https://coveord.atlassian.net/browse/SFINT-4781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(quantic): linkify property disabled in Quantic Summary and Quantic No Results

---

packages/atomic/src/components/search/result-template-components/atomic-quickview-modal/atomic-quickview-modal.pcss
packages/atomic/src/components/search/result-template-components/atomic-quickview-modal/atomic-quickview-modal.tsx

So that's a big "scope down" of my initial idea, which was to make everything in the header configurable in result templates. 
So that someone could embed custom components in the header, for example, as we could see in the mockups.
I spent some time figuring out how to make it all work in the first place. The main problem is that we wanted to have arbitrary result templates components (ie: atomic-result-link, atomic-result-field, custom result template components, etc) working *outside* of their normal location (outside of the result list).
The modal is not located inside the result list/inside a result template, and we would need to do quite a bit of gymnastic to make it all work.
However, even with this working, I still had the problem of having unknown components included in the …

feat(atomic): add result link for quickview header

---

packages/atomic/cypress/integration-insight-panel/insight-panel-selectors.ts
packages/atomic/cypress/integration-insight-panel/insight-panel.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/common/atomic-modal/atomic-modal.tsx
packages/atomic/src/components/common/refine-modal/refine-modal-common.tsx
packages/atomic/src/components/insight/atomic-insight-refine-modal/atomic-insight-refine-modal.tsx

[SVCC-2776](https://coveord.atlassian.net/browse/SVCC-2776)
The Atomic insight panel is currently exclusively used in the hosted insight panel builder and the focus trap is disabling the builder form elements from being interacted with which is pretty annoying.
This PR adds an optional prop to be able to render the atomic-modal without a focus-trap component.
A future improvement could be to still allow the modal to hide its sibling elements (under the modal) which would make lots of sense in the context of an insight panel or IPX which is only a widget on the screen.
[SVCC-2776]: https://coveord.atlassian.net/browse/SVCC-2776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(atomic): added prop to omit the modal focus trap

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/common/atomic-modal/atomic-modal.pcss
packages/atomic/src/components/common/atomic-modal/atomic-modal.tsx
packages/atomic/src/components/common/refine-modal/refine-modal-common.tsx
packages/atomic/src/components/ipx/atomic-ipx-body/atomic-ipx-body.pcss
packages/atomic/src/components/ipx/atomic-ipx-body/atomic-ipx-body.tsx
packages/atomic/src/components/ipx/atomic-ipx-button/atomic-ipx-button.tsx
packages/atomic/src/components/ipx/atomic-ipx-embedded/atomic-ipx-embedded.pcss
packages/atomic/src/components/ipx/atomic-ipx-embedded/atomic-ipx-embedded.tsx
packages/atomic/src/components/ipx/atomic-ipx-modal/atomic-ipx-modal.pcss
packages/atomic/src/components/ipx/atomic-ipx-modal/atomic-ipx-modal.tsx
packages/atomic/src/components/ipx/atomic-ipx-refine-modal/atomic-ipx-refine-modal.pcss
packages/atomic/src/components/ipx/atomic-ipx-refine-modal/atomic-ipx-refine-modal.tsx
packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.pcss
packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx
packages/atomic/src/pages/examples/ipx.html
packages/atomic/tailwind.config.js

[SVCINT-1999](https://coveord.atlassian.net/browse/SVCINT-1999)
- Split the ipx components into 3: `atomic-ipx-modal`, `atomic-ipx-embedded` and `atomic-ipx-body`
- Create a new `scaleUpModalIPX` animation with a lower `translateY` value to avoid bugs
- Update a whole bunch of components to make sure `height` and `width` is inherited throughout the search interface into the `part=container` elements
- Update the `ipx.html` file to be able to toggle between the button and embedded ipx
- Probably other changes I forgot about
[SVCINT-1999]: https://coveord.atlassian.net/browse/SVCINT-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://user-images.githubusercontent.com/71142397/214706917-836e8a5c-ddad-40a0-8636-c6401d253fab.mov

SVCINT-1999 Feat: example of ipx with target selector

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/ipx/atomic-ipx-modal/atomic-ipx-modal.tsx

[SVCINT-2086](https://coveord.atlassian.net/browse/SVCINT-2086)
Added a property for the `atomic-ipx-modal` to remove the focus trap when needed. 
We are unable to interact with input texts in the IPX builder when the modal is opened.
The fix made by Nathan was for `atomic-modal`.
[SVCINT-2086]: https://coveord.atlassian.net/browse/SVCINT-2086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(atomic): add prop to remove ipx focus trap

---

packages/quantic/force-app/main/default/lwc/quanticSmartSnippetSource/__tests__/quanticSmartSnippetSource.test.js
packages/quantic/force-app/main/default/lwc/quanticSmartSnippetSource/quanticSmartSnippetSource.css
packages/quantic/force-app/main/default/lwc/quanticSmartSnippetSource/quanticSmartSnippetSource.html
packages/quantic/force-app/main/default/lwc/quanticSmartSnippetSource/quanticSmartSnippetSource.js
packages/quantic/force-app/main/default/lwc/quanticSmartSnippetSource/quanticSmartSnippetSource.js-meta.xml
packages/quantic/force-app/main/default/lwc/quanticUtils/quanticUtils.js

[SFINT-4796](https://coveord.atlassian.net/browse/SFINT-4796
)
- The Quantic Smart Snippet Source component created.
- The Quantic Smart Snippet Source displays the clickUri and the title of the smart snippet source.
- The Quantic Smart Snippet Source binds the correct actions to the events triggered  on the links within  this component in order to log analytics.
[Design-doc__Quantic-Smart-Snippet-components](https://docs.google.com/document/d/1kJswWu6qHp5ExMHQagkrCWphrjRmys8a5tQ0oAnQkJU/edit)
https://user-images.githubusercontent.com/86681870/216156849-86e1fca3-2f2c-408b-bb5e-2c9d4d0dd5f8.mov
[SFINT-4796]: https://coveord.atlassian.net/browse/SFINT-4796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(quantic):  QuanticSmartSnippetSource created

---

packages/atomic/src/components/insight/atomic-insight-layout/insight-layout.ts
packages/atomic/src/pages/examples/insights.html

Recent changes to the atomic-icon-button have clashed with the way the atomic-insight-refine-toggle component was designed. The latter expected the facet elements to be placed within its tags but this now causes this awful looking visual bug.
This PR moves the facets outside of the refine-toggle to more closely match how the rest of atomic handles it.

fix(atomic): moved insight facets outside of the refine-toggle

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/search/result-template-components/atomic-quickview-modal/atomic-quickview-modal.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview-sidebar/atomic-quickview-sidebar.tsx
packages/atomic/src/components/search/result-template-components/atomic-quickview/atomic-quickview.tsx
packages/atomic/src/utils/accessibility-utils.tsx
packages/atomic/src/utils/utils.ts

* Add support to re-focus the quickview button on the result list when the modal is closed.
* Disable tabbing through the "remove specific keywords highlighting" button when the whole "highlight keywords" feature is disabled.
* Tweak some button alignment, as reported by Lucille in KIT-2259
https://coveord.atlassian.net/browse/KIT-2259

fix(atomic): more improvements for quickview accessibility

---

packages/atomic/cypress/e2e/facets/category-facet/category-facet.cypress.ts
packages/atomic/cypress/e2e/facets/color-facet/color-facet.cypress.ts
packages/atomic/cypress/e2e/facets/facet-common-assertions.ts
packages/atomic/cypress/e2e/facets/facet/facet.cypress.ts
packages/headless/src/features/facets/facet-search-set/generic/generic-facet-search-actions.ts
packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts
packages/headless/src/integration-tests/category-field-suggestions.test.ts
packages/headless/src/integration-tests/field-suggestions.test.ts
packages/quantic/cypress/e2e/facets-1/category-facet/category-facet.cypress.ts
packages/quantic/cypress/e2e/facets-1/facet-common-expectations.ts
packages/quantic/cypress/e2e/facets-1/facet/facet.cypress.ts

KIT-2261
-----
Given that:
- the facetSearch call does not return a searchUUID,
- a search analytics log requires a searchUUID
- how the feature work (see jira)
I reckon that we shouldn't log analytics on facet search. This is further confirmed imo by the fact that the old JSUI doesn't log analytics on facet search either.
draft to run the tests

fix(headless): remove facetSearch analytics

---

packages/atomic/cypress/e2e/result-list/result-components/quickview.cypress.ts
packages/atomic/src/components/search/result-template-components/atomic-quickview-sidebar/atomic-quickview-sidebar.tsx
packages/atomic/src/components/search/result-template-components/quickview-word-highlight/quickview-word-highlight.tsx

I played with different solutions here, and this is what I think is the best.
I'll try to explain what happens for some queries:
The index will understand some queries as "a phrase", or a single term. So, in this particular JIRA, the query was `1/12`. In some documents (for example excel files), the index will do some very weird stuff at the word highlighting level.
In some documents, it might even create invalid HTML, and so we would see "empty" keywords being highlighted. Since those are just illogical, I've added a `trim` to just hide them from the end users. As for fixing it at the index level, I will open a discuss about it.
Next related problem was that it then consider pretty different keywords in the document as being part of the same group. 
By that I mean that for the query …

fix(atomic): handle invalid HTML highlights

---

packages/atomic/cypress/e2e/search-box/search-box-selectors.ts
packages/atomic/cypress/e2e/search-box/search-box.cypress.ts
packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
packages/atomic/src/utils/utils.spec.ts
packages/atomic/src/utils/utils.ts

You can check the JIRA for a link to the discuss that sparked this change.
https://coveord.atlassian.net/browse/KIT-2275

fix(atomic): ignore empty query when detecting duplicates in search box suggestions

---

packages/quantic/cypress/e2e/facets-1/facet-common-selectors.ts
packages/quantic/cypress/e2e/facets-2/numeric-facet/numeric-facet-expectations.ts
packages/quantic/cypress/e2e/facets-2/numeric-facet/numeric-facet-selectors.ts
packages/quantic/cypress/e2e/facets-2/numeric-facet/numeric-facet.cypress.ts
packages/quantic/cypress/page-objects/search.ts
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.html
packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js

[SFINT-4795](https://coveord.atlassian.net/browse/SFINT-4795)
The numeric facet was always displayed when the property `withInput` was set to `true`  even if there is no numeric facet values in this facet:
https://user-images.githubusercontent.com/86681870/220132515-a72c681e-8155-4c22-b8d8-c142ae1caf05.mov
Numeric facet displayed only when it is relevant, only when it contains numeric facet values:
https://user-images.githubusercontent.com/86681870/220132799-56313131-d3b3-4916-a030-6540635ebd34.mov
[SFINT-4795]: https://coveord.atlassian.net/browse/SFINT-4795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(quantic): numeric facet displayed only when it contains facet values

---

packages/atomic-angular/modify-package-json.js
packages/atomic-angular/package.json
packages/atomic-angular/projects/atomic-angular/project.json

https://coveord.atlassian.net/browse/KIT-2311
The `atomic-angular/dist` directory only exists when the application is built, which is required for publishing but not for updating the tag.

ci(atomic-angular): fix NPM tag bump (#2740

---

packages/headless/src/controllers/recent-results-list/headless-recent-results-list.ts

Clarifies the doc for the RecentResultList controller to mention "clicked" results.
https://coveord.atlassian.net/browse/KIT-2303

docs(headless): clarify RecentResultList doc

---

packages/headless/src/features/tab-set/tab-set-slice.test.ts
packages/headless/src/features/tab-set/tab-set-slice.ts

[SVCC-425](https://coveord.atlassian.net/browse/SVCC-425)
The tab set state was not restored properly on history change:
https://user-images.githubusercontent.com/86681870/221574786-1e62aae0-d0e3-4870-8907-f5afc9f62fc8.mov
Added a new case in the tab set reducer to properly handle the history change:
https://user-images.githubusercontent.com/86681870/221575240-1a85da46-bce1-44ea-8922-77dd5bfab0f3.mov
[SVCC-425]: https://coveord.atlassian.net/browse/SVCC-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(headless): fixed tab set restore on history change

---

packages/quantic/force-app/main/default/lwc/quanticSmartSnippetSource/quanticSmartSnippetSource.html

[SFINT-4823](https://coveord.atlassian.net/browse/SFINT-4823)
[SFINT-4823]: https://coveord.atlassian.net/browse/SFINT-4823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(quantic): overflow issue fixed in the quantic smart snippet source component

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/search/result-template-components/atomic-result-link/atomic-result-link.tsx

https://coveord.atlassian.net/browse/DOC-12292
A reader reported being confused about how to use fields in the atomic-result-link ref doc. He seems a bit confused, but to be fair we don't use the word "field". Adding a few extra words should do the trick.

docs(atomic): DOC-12292 clarify field usage in hrefTemplate

---

packages/atomic/src/utils/initialization-utils.tsx
packages/samples/stencil/cypress/integration/stencil/smoke-test.cypress.ts
packages/samples/stencil/src/components.d.ts
packages/samples/stencil/src/components/results-manager/results-manager.tsx
packages/samples/stencil/src/pages/hsp.html

https://coveord.atlassian.net/browse/KIT-2313
Some context, we used the [custom event return value](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent#return_value) as a basis for when a component has been initialized properly or not (the event’s payload is an “initialize” callback. The return value is basically:
- false if event is cancelable, and at least one of the event handlers which received event called [Event.preventDefault()](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault). We call prevent default from atomic-search-interface, for example/
- Otherwise true.
This is synchronous, if dealing with a simple DOM, like our basic search interfaces, this will always work. When we started to expose these custom events for our custom elements, …

fix(atomic): use closest for internal initialization utils

---

packages/atomic-hosted-page/cypress/integration/stencil/smoke-test.cypress.ts
packages/atomic-hosted-page/src/components.d.ts
packages/atomic-hosted-page/src/components/atomic-hosted-page/hosted-pages.ts
packages/atomic-hosted-page/src/components/atomic-simple-builder/atomic-simple-builder.tsx
packages/atomic-hosted-page/src/pages/simple-builder.html

https://coveord.atlassian.net/browse/KIT-2335
Goes along with https://github.com/coveo/search-interface-service/pull/786
This pulls the new route, which takes a page made with the builder and inserts it into a customer's page, just like the hosted pages.
It was either adding a different config, or having a conditional config, so I decided to simply share some code and make a new component. Its ownership will be more clear and future-proof.
Open to different names...
Proof:

feat(atomic-hosted-page): add new atomic-simple-builder component

---

packages/headless/src/integration-tests/field-suggestions.test.ts

Same test I had fixed (too) quickly last week.
I had a discussion about it with Jeremie on Slack.
Ultimately this should be improved a the search API level. It could cause issues for clients.
You can see the linked search API ticket in JIRA.
For the time being, we can change to an entirely different facet value for the test, linked to a specific source that is frozen in the sample org (so should not get random casing change).
https://coveord.atlassian.net/browse/KIT-2355

test(headless): fix failing test for field suggestions (again)

---

packages/atomic/src/pages/examples/ipx.html
packages/atomic/src/utils/initialization-utils.spec.ts
packages/atomic/src/utils/initialization-utils.tsx

https://coveord.atlassian.net/browse/SVCINT-2157
Little issue with some css blocking the display of the query error component, updated the rules to unhide it !
Before with errors:
https://user-images.githubusercontent.com/71142397/225121137-b84883b6-b60a-46dc-b78e-f4b6c57db34b.mov
After without errors:
https://user-images.githubusercontent.com/71142397/225121425-e498b8dc-023d-4073-a776-632034e9225a.mov
After with errors:
https://user-images.githubusercontent.com/71142397/225121491-c5213d7b-48af-4954-b6c8-eeb54818b80d.mov

fix: update css to not hide error in ipx

---

packages/quantic/copy-static-resources.js
packages/quantic/coveo.d.ts
packages/quantic/force-app/main/default/.eslintrc.json
packages/quantic/force-app/main/default/lwc/quanticHeadlessLoader/quanticHeadlessLoader.js

[SFINT-4832](https://coveord.atlassian.net/browse/SFINT-4832)
Following this [discussion](https://discuss.coveo.com/t/include-recommendations-into-quantic-resources/9196), exposed the headless recommendation engine to coveoheadless static resources in quantic.
[SFINT-4832]: https://coveord.atlassian.net/browse/SFINT-4832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(quantic): Exposed the headless recommendations scripts in coveoHeadless static resources

---

packages/atomic/cypress/e2e/smart-snippet-actions.ts
packages/atomic/cypress/e2e/smart-snippet-suggestions-actions.ts
packages/atomic/cypress/e2e/smart-snippet.cypress.ts
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet-source.tsx
packages/atomic/src/components/search/atomic-smart-snippet/atomic-smart-snippet.tsx

https://coveord.atlassian.net/browse/KIT-2237
I also refactored the default snippets test logic, and I made sure that analytics tests are contained within `beforeEach` blocks because they were flaky.

fix(atomic): made smart snippet source title re-render when changed (#2795

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/ipx/atomic-ipx-body/atomic-ipx-body.tsx
packages/atomic/src/components/ipx/atomic-ipx-embedded/atomic-ipx-embedded.tsx
packages/atomic/src/components/ipx/atomic-ipx-modal/atomic-ipx-modal.tsx

[SVCINT-2179](https://coveord.atlassian.net/browse/SVCINT-2179)
This PR adds a check inside `atomic-ipx-modal` that looks for elements mounted inside the `footer` slot. If none are found, a prop is set on the `atomic-ipx-body` which hides the footer wrapper.
I tried to find a pure CSS solution, but there doesn't seem to be one... [yet](https://github.com/WICG/webcomponents/issues/701#issuecomment-368430226) 
[SVCINT-2179]: https://coveord.atlassian.net/browse/SVCINT-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide footer when empty

---

packages/quantic/cypress/e2e/facets-2/breadcrumb-manager/breadcrumb-manager-actions.ts
packages/quantic/cypress/e2e/facets-2/breadcrumb-manager/breadcrumb-manager-selectors.ts
packages/quantic/cypress/e2e/facets-2/breadcrumb-manager/breadcrumb-manager.cypress.ts
packages/quantic/force-app/examples/main/lwc/exampleQuanticBreadcrumbManager/exampleQuanticBreadcrumbManager.html
packages/quantic/force-app/examples/main/lwc/exampleQuanticBreadcrumbManager/exampleQuanticBreadcrumbManager.js
packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.html

[SFINT-4938](https://coveord.atlassian.net/browse/SFINT-4938)
When you have two facet values in the Quantic Breadcrumb component, and you remove the first value, removing the second value will make the first value reappear like the following:
https://user-images.githubusercontent.com/86681870/227228447-2bdd4c9f-bc8d-4b45-95ed-ad22d472a0d7.mov
The facet values in the Quantic Breadcrumb component were displayed in the HTML like the following:
```
<template for:each={breadcrumb.values} for:item="breadcrumbValue">
<li key={breadcrumbValue.value}>
<c-quantic-pill ondeselect={breadcrumbValue.deselect}></c-quantic-pill>
</li>
</template>
```
The problem is that the key passed to the `li` tag is invalid.
the object `breadcrumbValue` has the following structure: 
```
{
formattedValue: 'some …
```

fix(quantic): fixed a problem when deselecting breadcrumb values 

---

packages/headless/src/app/engine.test.ts

`each` can be very powerful, but IMHO, here it's been overused a little and added unwanted complexity.

engine.test.ts

---

packages/quantic/force-app/coveo-token/main/default/classes/CoveoTokenProvider.cls

New line to provide an example of how to set a searchHub as part of the Quantic token creation through the Globals method from the Coveo for Salesforce package.
With link to the documentation page.

feat(SFINT-4880): Added default searchhub as an example

---

packages/atomic-hosted-page/cypress/integration/stencil/smoke-test.cypress.ts
packages/atomic/src/pages/examples/insights.html
packages/samples/angular/cypress/e2e/atomic-angular/smoke-test.cypress.cy.ts
packages/samples/angular/src/app/atomic-angular-page/atomic-angular-page.component.ts
packages/samples/atomic-next/cypress/e2e/smoke-test.cypress.cy.ts
packages/samples/atomic-next/pages/index.tsx
packages/samples/atomic-react/cypress/e2e/smoke-test.cypress.cy.ts
packages/samples/atomic-react/src/components/AtomicPageWrapper.tsx
packages/samples/iife/cypress/e2e/atomic-react-smoke-test.cy.ts
packages/samples/iife/www/atomic-react.html
packages/samples/vuejs/cypress/integration/atomic-angular/smoke-test.cypress.ts
packages/samples/vuejs/src/components/ResultTextFieldMultivalue.vue
packages/samples/vuejs/src/components/SearchPage.vue
packages/samples/vuejs/src/main.ts
packages/samples/vuejs/src/templates/result-template.html

Adjust some samples not using the `organizationEndpoints`. 
Samples were still working properly, but this is to silence the warnings and showcase the best practice in our own samples/documentation.
There's going to be more of those type of PR in various adjacent tooling (ie: CLI).
https://coveord.atlassian.net/browse/KIT-2388

docs(atomic,headless): fix various samples documentation to use organizationEndpoints

---

packages/atomic/src/components/ipx/atomic-ipx-modal/atomic-ipx-modal.tsx

Forgot to remove focus trap references in the IPX-modal in my other PR https://github.com/coveo/ui-kit/pull/2805/files. This removes all focus trap related props and calls from the IPX-modal
https://coveord.atlassian.net/browse/SVCINT-2161

fix(atomic): remove focus trap props in IPX modal

---

packages/headless/src/features/result-preview/result-preview-slice.test.ts
packages/headless/src/features/result-preview/result-preview-slice.ts

https://coveord.atlassian.net/browse/KIT-2389
Sames as #2657, but for `fetchMoreResults` and `fetchPage`
This fix the issue because it will make:
https://github.com/coveo/ui-kit/blob/1a358caee72aa50c0bd45a98c0760becbd39829c/packages/atomic/src/components/search/result-template-components/atomic-quickview-modal/atomic-quickview-modal.tsx#L208-L211
be/stay/return false (as it should).
-  `git checkout "@coveo/headless@2.10.1" -f ; npm run build ; npm run dev`
- Click on Quickview, close quickview, click on load more results: the quickview reopen.
- Edit `packages/atomic/www/index.html` to replace the `atomic-load-more-results` by `atomic-results-per-page`
- Click on Quickview, close quickview, click on load more results: the quickview reopen.
-  `git checkout "fix/KIT-2389" -f ; npm run …

fix(headless): reset preview content on `fetchMoreResults` and `fetchPage`

---

packages/headless/src/app/engine.test.ts
packages/headless/src/app/engine.ts
packages/headless/src/utils/url-utils.ts

This will log a warning if an implementer configure the engine like so:
```typescript
buildSearchEngine({
organizationId: 'some-org-id',
organizationEndpoints: getOrganizationEndpoints('another-org-id')
})
```
https://coveord.atlassian.net/browse/KIT-2403

fix(headless): add warning on configuration mismatch between organizationId and organizationEndpoint

---

packages/atomic/src/components/ipx/atomic-ipx-tab/atomic-ipx-tab.tsx

[SVCINT-2270](https://coveord.atlassian.net/browse/SVCINT-2270)
The tabId used was random, which is not a great experience for users, analytics, queryPipelines, etc.
We're using the tab's label now, which is way more straightforward !
[SVCINT-2270]: https://coveord.atlassian.net/browse/SVCINT-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use tab label as id

---

.github/actions/e2e-atomic-screenshots/action.yml
.github/workflows/manual-package.yml
.github/workflows/masterbot.yml
.github/workflows/prbot.yml

Related Issue
DT-5750
👋 We have come across a problem with using `if: always()` in workflows. The basic gist is that these steps become un-cancellable, possibly creating all sorts of unexpected problems. This is less frequent with GitHub hosted runners, but it can happen.
This PR introduces and workaround this problem by explicitly defining the different states the step can face.
Namely:
* `success()`
* `cancelled()`
* `failure()`
This way, you get the `always()` behaviour without it's possible caveats.
In a way, this is more of a "we really recommend this" kind of PR. That is because you may never face the problem I'm talking about, but when you do, you'll want this workaround.
If you decide against merging this, please make sure you mention this if you need support in the future to help …

chore(workflows): don't use always() in workflows

---

packages/headless/doc-parser/use-cases/case-assist.ts
packages/headless/doc-parser/use-cases/insight.ts
packages/headless/src/case-assist.index.ts
packages/headless/src/features/attached-results/attached-results-actions-loader.ts
packages/headless/src/features/recent-queries/recent-queries-actions-loader.ts
packages/headless/src/features/recent-results/recent-results-actions-loader.ts
packages/headless/src/insight.index.ts

[SFINT-4918](https://coveord.atlassian.net/browse/SFINT-4918)
I want to be able to send my own custom analytics events when using Quantic to implement my case assist flow.
- loadGenericAnalyticsActions function is currently included only in the search bundle, we need to include it in the Headless bundle of other use cases.
- we need to expose loadGenericAnalyticsActions for the insight use case as well
As you can see below, we can have access to loadGenericAnalyticsActions
CASE ASSIST: 
INSIGHT: 
ericAnalyticsActions in quantic in case assist & insight components
[SFINT-4918]: https://coveord.atlassian.net/browse/SFINT-4918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(headless): include the loadgenericanalyticsactions action loader in the case assist & insight headless bundle

---

packages/atomic-hosted-page/package.json
packages/atomic-hosted-page/src/components.d.ts
packages/atomic-hosted-page/src/components/atomic-hosted-page/atomic-hosted-page.tsx
packages/atomic-hosted-page/src/components/atomic-simple-builder/atomic-simple-builder.tsx
packages/atomic-hosted-page/src/components/utils/options-utils.ts
packages/atomic-hosted-page/src/pages/index.html
packages/atomic-hosted-page/src/pages/simple-builder.html
packages/atomic/src/components.d.ts
packages/headless/src/api/platform-client.test.ts
packages/headless/src/api/platform-client.ts

* Add `admin` endpoint in Headless > `getOrganizationEndpoints` utility function
* Leverage it to load the pages inside `<atomic-hosted-pages>` and `<atomic-simple-builder>`
https://coveord.atlassian.net/browse/KIT-2405
https://coveord.atlassian.net/browse/CDX-1410

feat(organizationendpoints): support organization endpoints for hosted-pages components

---

packages/atomic/src/components.d.ts
packages/atomic/src/components/search/result-template-components/atomic-result-badge/atomic-result-badge.tsx

https://coveord.atlassian.net/browse/DOC-12604
Multi-value field was causing errors in code sandbox when trying to be displayed within field properties of badges.
Added an example for multi-value field.

docs(atomic): Update docs for field property of atomic-result-badge

---

packages/atomic/src/components/ipx/atomic-ipx-button/atomic-ipx-button.tsx

[SVCINT-2203](https://coveord.atlassian.net/browse/SVCINT-2203)
Updated the `atomic-ipx-button` component to pre-process svg.
It will: 
- Load the provided svg in the dom
- Check if it is actually an svg
- Compute the svg's width and height if set
- Strip all the styles from the svg (including width and height) since we want the svg to adapt to the button size
- If the svg had a width and height set, set the svg's viewBox to the given width and height
[SVCINT-2203]: https://coveord.atlassian.net/browse/SVCINT-2203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: pre-process svg inside of atomic-ipx-button

---

packages/atomic/src/components/insight/atomic-insight-interface/analytics-config.ts
packages/atomic/src/components/recommendations/atomic-recs-interface/analytics-config.ts
packages/atomic/src/components/search/atomic-search-interface/analytics-config.spec.ts
packages/atomic/src/components/search/atomic-search-interface/analytics-config.ts

The spread merge was removing the augment included by default, mainly for this issue the `coveoAtomicVersion` metadata.
The handling of a custom analytisClientMiddleware is actually handled at the beginning of `getAnalyticsConfig`, e.g.:
https://github.com/coveo/ui-kit/blob/b15f42c19194152801d4435e2518a50dce8308d0/packages/atomic/src/components/insight/atomic-insight-interface/analytics-config.ts#L12-L15
For the testing, I decided to use a `.each` to reuse the existing tests that ran on the 'simple analytics config' by adding another case where there's an analytics middleware.

fix(atomic): do not overwrite analyticsClientMiddleware

---

packages/atomic/cypress/integration-insight-panel/insight-panel-selectors.ts
packages/atomic/cypress/integration-insight-panel/insight-panel.cypress.ts
packages/atomic/src/components.d.ts
packages/atomic/src/components/common/tabs/tab-bar.pcss
packages/atomic/src/components/common/tabs/tab-bar.tsx
packages/atomic/src/components/common/tabs/tab-popover.pcss
packages/atomic/src/components/common/tabs/tab-popover.tsx
packages/atomic/src/components/insight/atomic-insight-tabs/atomic-insight-tabs.pcss
packages/atomic/src/components/insight/atomic-insight-tabs/atomic-insight-tabs.tsx
packages/atomic/src/components/ipx/atomic-ipx-tabs/atomic-ipx-tabs.pcss
packages/atomic/src/components/ipx/atomic-ipx-tabs/atomic-ipx-tabs.tsx
packages/atomic/src/pages/examples/insights.html
packages/atomic/src/pages/examples/ipx.html

Some ipx and atomic tabs components were leaking global css outside of the shadow DOM. To fix I did 2 things:
1. Enabled shadow dom to `tab-popover` component
2. Removed unnecessary css from `ipx-tabs` and `insight-tabs` components which was leaking due to those components not using shadow-dom. It's necessary to the proper functioning of the `tab-bar` component they have as a child that these do not use a shadow-dom.
Added a rudimentary test to the insight test suite to check that only the expected number of script tags are added. I want to create a better test that validates script tags added by any component but currently the atomic insight use case doesn't have a good per-component test setup. That'll require more work I deem out of scope of this fix. We'll do it in the near future …

fix(atomic): fixed leaky styling from tab components

---

packages/atomic/src/components/ipx/atomic-ipx-body/atomic-ipx-body.tsx

[SVCINT-2279](https://coveord.atlassian.net/browse/SVCINT-2279)
Added some custom styling to the IPX scroll bar:
- make the scrollbar background color the atomic background color
- make the scrollbar color the atomic primary color
Changes available in all browsers except Safari
- make the scrollbar rounded
- make the scrollbar slightly thinner (0.8rem)
Here is an example:
- Chrome
[SVCINT-2279]: https://coveord.atlassian.net/browse/SVCINT-2279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(atomic): add styling to the ipx scroll bar

---

packages/headless/esbuild.mjs
packages/headless/src/app/analytics-middleware.ts
packages/headless/src/app/product-recommendation-engine/product-recommendation-engine.ts
packages/headless/src/app/product-recommendation-reducers.ts
packages/headless/src/app/reducers.ts
packages/headless/src/controllers/product-listing/headless-product-listing.ts
packages/headless/src/controllers/product-recommendations/headless-base-product-recommendations.ts
packages/headless/src/features/configuration/search-configuration-actions-loader.ts
packages/headless/src/features/product-recommendations/product-recommendations-actions-loader.ts
packages/headless/src/index.ts

So I've done quite a bit of testing around the work that will be necessary to make our bundles leaner.
One thing I've realized is everything around three shaking will require quite a lot of manual work to help bundle tools (esbuild, webpack, rollup)  identify functions/modules/classes that do not have side effects ( https://esbuild.github.io/api/#tree-shaking // https://esbuild.github.io/api/#pure ). Right now, I'd say only about 5 to 10% of Headless package is tree shakable, which is far lower that what is should be.
In the first phase, what I'd like to achieve is to simply changes the way we do imports so that we can shake off some weights from each produced bundles, notwithstanding any tree shaking capabilities.
This in itself will be a lot of work, as we need to juggle some imports …

chore(headless): initial work to cleanup headless bundles

---

package-lock.json

https://coveord.atlassian.net/browse/KIT-2467
I believe the reason for the [most recent failure](https://github.com/coveo/ui-kit/actions/runs/4951823537/jobs/8857312882) may be because of some changes from the last version bump.
I think the broken lockfile may be working for `npm ci` in the CI but not for `npm install` and reify when there's an existing `node_modules` folder.
I'm also taking a chance that Lerna may be responsible for breaking the `package-lock` files and that the new process' lock files may not have the same problem (especially since the new process seems to make far fewer changes to the lockfile).

ci: re-generated lockfiles
