coveo/ui-kit

- utils/release/bump-package.mjs
- utils/release/common/constants.mjs
- utils/release/git-lock.mjs
- utils/release/git-publish-all.mjs
- utils/release/install-npm-proxy.mjs
- utils/release/lock-master.mjs
- utils/release/reify.mjs
- utils/release/tsconfig.json
https://coveord.atlassian.net/browse/KIT-2470
I went too fast and didn't pay enough attention, I repeatedly missed some constants that referred to the CLI repo.
I decided to extract some common constants in a new file & directory (`./common/constants.mjs`) to avoid this happening again.
I was also tempted to extract secrets/env variables, but those are searchable anyway.
> ci: fixed CI repo strings and extracted common constants

- .github/workflows/release.yml
https://coveord.atlassian.net/browse/KIT-2472
I copy and pasted most things from the CLI, but somehow missed this one...
I'm taking a chance and using the `ADMIN_GITHUB_TOKEN` we already have, which was used in our old release process to checkout the repo.
> ci: added missing octokit secret

- packages/headless/src/integration-tests/search-app.test.ts
https://coveord.atlassian.net/browse/KIT-2473
Fixed this locally just to verify whether the test was flaky or whether we actually have a bug.
This test is failing every time because all 10 results happen to be from the same author as the first facet value.
Pushing the fix since I already had it locally anyway, and it fails every time.
My fix is just to select a category facet value instead, since that one's in the geographical hierarchy source, which rarely comes up in results, and should consistently change the available authors in the facet.
> test(headless): lazily fixed facet select integration test

- packages/quantic/force-app/main/default/lwc/quanticSmartSnippet/quanticSmartSnippet.html
[SFINT-5017](https://coveord.atlassian.net/browse/SFINT-5017)
Adjusted the padding around the feedback options of the smart snippet component to make this component look good inside the Quantic Insight Panel.
[SFINT-5017]: https://coveord.atlassian.net/browse/SFINT-5017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): padding of the feedback options adjusted in the quantic smart snippet component

- packages/atomic/src/components/common/checkbox.tsx
- packages/atomic/src/components/common/facets/facet-value-checkbox/facet-value-checkbox.tsx
- packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx
- packages/atomic/src/components/search/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
- packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
[KIT-2412](https://coveord.atlassian.net/browse/KIT-2412)
This PR adds a part for  the atomic-icon within facet checkboxes.
Currently, the tick icon in the SVG has a default stroke color of white and I haven't found a way to override it. If a user wanted to change the tick icon to another color, they would not be able to.
- Add custom icons to the checkbox
- Remove directly the default stroke in the tick SVG
[KIT-2412]: https://coveord.atlassian.net/browse/KIT-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(atomic): add a part on `facet-value-checkbox > atomic-icon`

- packages/atomic/src/components/search/atomic-sort-expression/atomic-sort-expression.stories.tsx
Problem originally introduced with upgrade to storybook 7. 
Deep in the storybook codebase, there's an `eval` that gets executed with the "sanitized" inline source for the story (please don't ask me why it does that, I have no idea 😂).
The sanitized string would be invalid JavaScript in that case.
Anyway, I did not go too deep on that one, I just applied a quickfix by simply rewriting the inline code a bit.
https://coveord.atlassian.net/browse/KIT-2474
> docs(atomic): fix sort-expression storybook

- CODEOWNERS
- packages/atomic/src/components.d.ts
- packages/atomic/src/components/ipx/atomic-ipx-body/atomic-ipx-body.tsx
[SVCINT-2357](https://coveord.atlassian.net/browse/SVCINT-2357)
Embedded IPX was always displayed, even when parent was hidden (since we always set the visible/invisible class)
We now only set the class if `isOpen` is set on the ipx-body, which lets us inherit visibility from the parent in the embedded case.
[SVCINT-2357]: https://coveord.atlassian.net/browse/SVCINT-2357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: hide ipx if parent is hidden SVCINT-2357

- utils/atomic-storybook/.storybook/map-props-to-args.ts
Some option description would be improperly formatted when we use markdown for the JSDoc.
https://coveord.atlassian.net/browse/KIT-2464
> docs(atomic): storybook: use performatted text block for options description

- packages/quantic/force-app/main/default/lwc/quanticResultLink/__tests__/quanticResultLink.test.js
- packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.js
[SFINT-5023](https://coveord.atlassian.net/browse/SFINT-5023)
The `target` property was not passed properly to the anchor tag used in the HTML template of the Quantic Result Link component.
The link was always opened in the same current browser tab regardless of the values passed to the property target.
[SFINT-5023]: https://coveord.atlassian.net/browse/SFINT-5023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): fixed bug with the target property of the quantic result link

- .github/workflows/release.yml
- utils/release/git-publish-all.mjs
- utils/release/lock-master.mjs
https://coveord.atlassian.net/browse/KIT-2478
Going to revert this later when we know that the release process works. I'm not 100% sure that the personal access token will work either, but I manually granted it the permissions it should need (admin and content).
> ci: temporarily use personal access token instead of github app

- .github/workflows/release.yml
- utils/release/git-publish-all.mjs
- utils/release/lock-master.mjs
https://coveord.atlassian.net/browse/KIT-2489
I accidentally missed that when copy and pasting code from the CI...
We don't need to update the root `package.json`'s version.
In this PR, I'm also bringing back the application tokens instead of the personal access tokens.
> ci: removed root package version bump

- renovate.json
- utils/atomic-storybook/.storybook/main.js
- utils/atomic-storybook/package-lock.json
- utils/atomic-storybook/package.json
https://coveord.atlassian.net/browse/KIT-2487
`@storybook/addon-a11y` has a prod dependency on `axe-core`, whose license (MPL-2.0) may be incompatible with ours due to being a weak copy-left license and us displaying addon-a11y in our docs. See https://github.com/dequelabs/axe-core/blob/develop/LICENSE for more details.
Here's a failed dependency-review-action run for reference: https://github.com/coveo/ui-kit/actions/runs/5029760617/jobs/9021704320
Discussion on Storybook's repo for reference: https://github.com/storybookjs/storybook/discussions/15777
> chore: removed @storybook/addon-a11y

- packages/atomic/cypress/e2e/facets/facet-depends-on/facet-depends-on.cypress.ts
- packages/atomic/cypress/e2e/facets/popover-facet/popover-facet.cypress.ts
- packages/atomic/cypress/e2e/facets/segmented-facet/segmented-facet.cypress.ts
- packages/atomic/cypress/e2e/result-list/folded-result-list.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/quickview.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-badge.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-date.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-fields-list.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-icon.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-image.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-link.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-multi-value-text.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-number.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-printable-uri.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-text.cypress.ts
- packages/atomic/cypress/e2e/search-box/search-box.cypress.ts
- packages/atomic/cypress/integration-insight-panel/insight-panel.cypress.ts
- packages/samples/stencil/cypress/e2e/stencil/smoke-test.cypress.ts
In prep for Cypress 12 upgrade https://github.com/coveo/ui-kit/pull/2935 apply test isolation to result-list, facet, insight-panel and stencil smoke test suites.
https://coveord.atlassian.net/browse/KIT-2432
> test: apply test isolation to e2e result-list, facet test suites

- packages/atomic/src/components/search/atomic-did-you-mean/atomic-did-you-mean.tsx
- packages/atomic/src/locales.json
https://coveord.atlassian.net/browse/CDX-1426
Adds a condition that checks if the `no-results-for-dym` key exist. If it does, it uses it for the localized string.
This avoids a breaking change by leaving the `no-results-for` key as the default value. However, this is bad code. The new key (`no-results-for-dym`) does not show in the `i18n.getResourceBundle()` function. The correct way to do this would be to have a breaking change and create an entirely new key in locales.json. 
- Merge this bandaid PR 
- Add a spike/story in the [V3 update epic ](https://coveord.atlassian.net/browse/KIT-2157) to look for other places in the code where splitting translation keys would be useful. 
- In the spike/story, add a child issue to revert this PR changes and simply add a new key in locales.json.
> feat(atomic): changed translation key in `atomic-did-you-mean`

- utils/release/git-publish-all.mjs
https://coveord.atlassian.net/browse/KIT-2509
I made a mistake. Only staged files are linted, so this was doing nothing. Woops.
> ci: lint staged files before creating version bump commits

- utils/release/git-publish-all.mjs
https://coveord.atlassian.net/browse/KIT-2510
We can't force push to `master` with a deploy key. We can, however, update the remote `master` branch using Octokit.
> ci: remove force push from version bump logic

- packages/quantic/cypress/e2e/default-1/case-classification/case-classification-expectations.ts
- packages/quantic/cypress/e2e/default-1/case-classification/case-classification.cypress.ts
- packages/quantic/force-app/examples/main/lwc/exampleQuanticCaseClassification/exampleQuanticCaseClassification.html
- packages/quantic/force-app/examples/main/lwc/exampleQuanticCaseClassification/exampleQuanticCaseClassification.js
- packages/quantic/force-app/main/default/lwc/quanticCaseClassification/quanticCaseClassification.js
[SFINT-5029](https://coveord.atlassian.net/browse/SFINT-5029)
Added a new property `fetchOnInit` to the Quantic Case Classifications  component, this property, when set to `true`, will trigger a request to fetch classifications during the initialization of the component.
https://github.com/coveo/ui-kit/assets/86681870/f55eb59b-7807-4ebf-9e1f-5c1d73e2434a
[SFINT-5029]: https://coveord.atlassian.net/browse/SFINT-5029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(quantic): new property fetchOnInit added to the Quantic Case Classification

- packages/headless/src/api/search/search-api-params.ts
- packages/headless/src/api/search/search/automatic-facets.ts
- packages/headless/src/api/search/search/search-request.ts
- packages/headless/src/api/search/search/search-response.ts
- packages/headless/src/features/facets/facet-set/interfaces/response.ts
- packages/headless/src/features/search/search-state.ts
- packages/headless/src/test/mock-search-response.ts
https://coveord.atlassian.net/browse/KIT-2523
This PR adds necessary types to support the automatic facets feature. 
I used `refactor` to not trigger semantic versioning.
> refactor(headless): add types to request and responses to support automatic facets

- .cspell.json
- packages/headless/src/app/engine.test.ts
- packages/headless/src/app/engine.ts
- packages/headless/src/app/reducer-manager.test.ts
- packages/headless/src/app/reducer-manager.ts
- packages/headless/src/utils/utils.ts
https://coveord.atlassian.net/browse/KIT-2539
One issue this causes is that, when server-side rendering a page with a facet, it's impossible to load the preloaded state on the client-side with the facet since facet-set is not a default reducer.
My fix was to add temporary "placeholder" reducers for each preloaded state value that doesn't have a reducer. These are later replaced when we load the real reducers.
Tests in this PR failed until I added the fix.
> fix(headless): allow preloading state of non-default reducers

- packages/headless/src/product-listing.index.ts
These exports were missing for https://github.com/coveo/ui-kit/pull/2964 and https://github.com/coveo/ui-kit/pull/2968
> feat: add missing exports for headless/product-listing

- packages/quantic/scripts/build/deploy-community.ts
https://coveord.atlassian.net/browse/SFINT-5074
The Quantic setup job was filling  intermittently because we were trying to deploy the content of the community while the community is still being created.
To try to solve this I increased the number of retries and added a 30 seconds delay between each try.
> chore(Quantic): fix intermittently failing Quantic setup job

- packages/quantic/force-app/main/default/lwc/quanticResultTemplate/quanticResultTemplate.js
[SFINT-5069](https://coveord.atlassian.net/browse/SFINT-5069)
-  Missing documentation for the slot "children" added to the Quantic Result Template component.
[SFINT-5069]: https://coveord.atlassian.net/browse/SFINT-5069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): missing documentation for the slot "children" added

- .eslintrc.json
* Turn spell checker plugin only in the required eslint config section and not globally for all files
* Currently eslint spell checker plugin is turned on in the global scope making it run on package-lock.json etc.
https://coveord.atlassian.net/browse/KIT-2550
> chore: fix scope of cspell plugin only to the relevant section

- .cspell.json
- package-lock.json
- packages/headless/package.json
- packages/headless/src/app/analytics-middleware.ts
- packages/headless/src/app/instantly-callable-middleware.ts
- packages/headless/src/app/logger-middlewares.ts
- packages/headless/src/app/renew-access-token-middleware.test.ts
- packages/headless/src/app/search-engine/search-engine.ts
- packages/headless/src/app/undoable.test.ts
- packages/headless/src/app/undoable.ts
- packages/headless/src/controllers/core/context/headless-core-context.test.ts
- packages/headless/src/controllers/core/facets/facet-conditions-manager/headless-facet-conditions-manager.test.ts
- packages/headless/src/controllers/product-listing/headless-product-listing.test.ts
- packages/headless/src/controllers/product-recommendations/headless-base-product-recommendations.test.ts
- packages/headless/src/controllers/recent-queries-list/headless-recent-queries-list.test.ts
- packages/headless/src/controllers/recent-results-list/headless-recent-results-list.test.ts
- packages/headless/src/controllers/recommendation/headless-recommendation.test.ts
- packages/headless/src/controllers/triggers/headless-query-trigger.test.ts
- packages/headless/src/features/facets/facet-order/facet-order-slice.test.ts
- packages/headless/src/features/folding/folding-slice.test.ts
- packages/headless/src/features/history/history-slice.test.ts
- packages/headless/src/features/search/search-actions-thunk-processor.ts
* Changing imports to go through RTK instead of redux
[Why Redux Toolkit is How To Use Redux Today | Redux](https://redux.js.org/introduction/why-rtk-is-redux-today#why-we-want-you-to-use-redux-toolkit) 
> The redux core package still works, but today we consider it to be obsolete. All of its APIs are also re-exported from @reduxjs/toolkit
> we strongly encourage you to switch over to @reduxjs/toolkit, and update your code to use the Redux Toolkit APIs instead!
https://coveord.atlassian.net/browse/KIT-2564
> chore: remove direct dependency on redux

- package-lock.json
- packages/headless/package.json
- packages/headless/src/features/analytics/insight-analytics-actions-loader.ts
- packages/headless/src/features/result-actions/result-actions-insight-analytics-actions.test.ts
- packages/headless/src/features/result-actions/result-actions-insight-analytics-actions.ts
[SFINT-5082]
logCaseSendEmail, logFeedItemTextPost 
Will have to wait until this PR has been released to bump the version of coveo.analytics.js used in ui-kit
https://github.com/coveo/coveo.analytics.js/pull/425
(These two click actionCause have also already been added to the UA valid event schema repo)
[SFINT-5082]: https://coveord.atlassian.net/browse/SFINT-5082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless): Add new insight analytics actions

- packages/quantic/scripts/build/create-package.ts
- packages/quantic/scripts/build/util/sfdx-commands.ts
- packages/quantic/scripts/build/util/sfdx.ts
Limit retrieval to last 30 days. Given we have a nightly build that creates a version this should be way enough and shortens the JSON size by a huge amount.
SFINT-5094
> chore(ci): limiting number of quantic package versions retrieved

- packages/atomic/src/components/search/atomic-generated-answer/atomic-generated-answer.pcss
- packages/atomic/src/components/search/atomic-generated-answer/atomic-generated-answer.tsx
- packages/atomic/src/components/search/atomic-generated-answer/generated-content.tsx
- packages/atomic/src/components/search/atomic-generated-answer/typing-loader.tsx
The design has been revised to no longer show a border when the component is loading so it's more subtle.
Loading
Loaded
> feat(atomic): removed border around loading state

- package.json
https://coveord.atlassian.net/browse/KIT-2573
Long talk about this problem in this eslint [issue](https://github.com/eslint/eslint/issues/15010). A proper solution never got merged in the core eslint so I used the last comment solution to directly exclude the files from the `lint-staged`.
> ci: fix `lint-staged` failures when committing generated files

- .cspell.json
- packages/atomic/cypress/support/index.d.ts
- packages/atomic/cypress/tsconfig.json
https://coveord.atlassian.net/browse/KIT-2579
This was bugging me. In kept seeing this error pop up in vs code whenever I was in the atomic/cypress folder.
`@applitools/eyes-cypress` got removed in #2463
> style: remove old traces of `@applitools/eyes-cypress`

- packages/atomic/src/components/insight/result-lists/atomic-insight-result-list/atomic-insight-result-list.pcss
[SVCC-3079](https://coveord.atlassian.net/browse/SVCC-3079)
Add the padding change made previously on `atomic-insight-folded-result-list` to `atomic-insight-result-list` to be consistent for the moment. and so that the hover works properly as we are still using `atomic-insight-result-list` instead of `atomic-insight-folded-result-list`
**BEFORE:** When using `atomic-insight-result-list `
**AFTER:**
[SVCC-3079]: https://coveord.atlassian.net/browse/SVCC-3079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(atomic): change padding in result list

- packages/headless/src/controllers/static-filter/headless-static-filter.test.ts
- packages/headless/src/controllers/static-filter/headless-static-filter.ts
- packages/headless/src/features/static-filter-set/static-filter-set-actions-loader.ts
- packages/headless/src/features/static-filter-set/static-filter-set-actions.ts
- packages/headless/src/features/static-filter-set/static-filter-set-schema.ts
- packages/headless/src/features/static-filter-set/static-filter-set-slice.ts
https://coveord.atlassian.net/browse/KIT-2587
I got part-way through implementing value exclusion for the breadcrumb manager before realizing that I hadn't accounted  for static filters, so this PR addresses that 🙂
This is all fairly derivative of my other exclusion PRs, so you'll see many similar patterns/methods/UTs throughout (`toggleExclude`,`toggleSingleExclude`, `isValueExcluded`, etc)
> feat(headless): support static filter value exclusion

- packages/atomic/src/utils/initialization-utils.tsx
This was essentially caused by a closure/scope issue. 
When you look at what happens internally in redux when the `unsubscribe` function is called, there's a closure flag (`isSubscribed`) that changes when unsubscribe is called for the first time. Any subsequent call to the same function will be a no-op that returns immediately.
We need to make sure we are referencing different instances of the unsubscribe function when a component gets removed from the page. A simple solution is to simply tack it on the component instance.
https://coveord.atlassian.net/browse/KIT-2569
> fix: unsubscribe component on disconnected callback

- packages/headless/src/api/search/search/result.ts
- packages/headless/src/test/mock-result.ts
[SFINT-5101](https://coveord.atlassian.net/browse/SFINT-5101)
The property `isUserActionView` is now added to the Result interface in Headless.
I described this property as documented in the search-ui repo: https://github.com/coveo/search-ui/blob/a39c8bec0515809812b9917917167e2751dfd0d0/src/rest/QueryResult.ts#L109-L112
In Quantic we rely on this property to display a `viewed by customer badge` component on the results viewed by a given user.
[SFINT-5101]: https://coveord.atlassian.net/browse/SFINT-5101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless): isUserActionView property added to the result interface

- packages/headless/doc-parser/use-cases/product-listing.ts
- packages/headless/src/controllers/product-listing/result-list/headless-product-listing-interactive-result.test.ts
- packages/headless/src/controllers/product-listing/result-list/headless-product-listing-interactive-result.ts
- packages/headless/src/features/product-listing/product-listing-analytics.ts
- packages/headless/src/features/product-listing/product-listing-click-analytics-actions-loader.ts
- packages/headless/src/product-listing.index.ts
Jira ticket: https://coveord.atlassian.net/browse/COMSDZ-605
The issue was with the `interactiveResult` was with the missing `loadClickAnalyticsActions` for product listing. We needed to align with Product Recommendation and not Search.
> feat: add loadClickAnalyticsActions for PLP to fix interactive result

- packages/headless/src/features/pagination/pagination-slice.test.ts
- packages/headless/src/features/pagination/pagination-slice.ts
https://coveord.atlassian.net/browse/KIT-2617
This PR adds a case in the pagination slice to reset pagination to 0 whenever an automatic facet is toggled.
> fix(headless): reset pagination when toggling automatic facet

- packages/atomic/cypress/e2e/facets/automatic-facet-builder/automatic-facet-builder-assertions.ts
- packages/atomic/cypress/e2e/facets/automatic-facet-builder/automatic-facet-builder.cypress.ts
- packages/atomic/src/components/search/facets/atomic-automatic-facet-builder/atomic-automatic-facet-builder.pcss
- packages/atomic/src/components/search/facets/atomic-automatic-facet-builder/atomic-automatic-facet-builder.tsx
https://coveord.atlassian.net/browse/KIT-2615
This PR adds placeholders for automatic facet. In other facet, the placeholder is in the actual facet component. Since the automatic facet component is only accessed after the query, the only way to have placeholders in this case is to show them depending on the `desiredCount` in the `automaticFacetBuilder`.
> feat(atomic): add placeholders for automatic facet

- packages/headless/src/api/analytics/instant-result-analytics.ts
- packages/headless/src/api/analytics/instant-results-analytics.test.ts
- packages/headless/src/api/analytics/search-analytics.ts
- packages/headless/src/features/instant-results/instant-results-actions.ts
- packages/headless/src/features/instant-results/instant-results-slice.test.ts
- packages/headless/src/features/instant-results/instant-results-slice.ts
- packages/headless/src/features/instant-results/instant-results-state.ts
- packages/headless/src/features/search/search-actions.ts
https://coveord.atlassian.net/browse/KIT-2609
In the above issue, it was identified that some analytics events had `numberOfResults: 0`, and eventually that this specifically happened for instant results on a standalone search page.
It turns out that analytics events for instant results were logging the `numberOfResults`, `results` and `responseTime` of the last submitted search request, not the instant results search request.
This PR changes the instant results analytics provider to instead use the values from the last cached instant results response.
I tried to compare this behaviour with JSUI, but it was complicated and not worth elaborating here. In a nutshell, we already decided when adding instant results to Headless that we'd send a different analytics event, so the comparison …
> fix(headless): fixed analytics metadata for instant results search

- packages/headless/src/api/platform-service-params.ts
- packages/headless/src/api/service/case-assist/case-assist-api-client.test.ts
- packages/headless/src/api/service/case-assist/get-case-classifications/get-case-classifications-request.ts
- packages/headless/src/api/service/case-assist/get-document-suggestions/get-document-suggestions-request.ts
- packages/headless/src/features/case-field/case-field-actions.ts
- packages/headless/src/features/document-suggestion/document-suggestion-actions.ts
The customer service api now accepts `clientId` or `visitorId`.
We want to favour `clientId` to phase out the other so after this PR the case assist client will send that instead.
> feat(headless): send clientId instead of visitorId in case assist

- packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx
https://coveord.atlassian.net/browse/KIT-2623
After adding this, I tested the edge cases for the atomic refine modal where there is either no automatic facets or no normal facets and I found a bug [KIT-2627](https://coveord.atlassian.net/browse/KIT-2627) whenever there was no normal facets. I reproduced the bug in the master branch so my changes have no impact on it. I will fix it in a subsequent PR.
To open the refine modal:
1. Put browser window in mobile mode when the 'sort and filter' button appears at the right.
2. Click on it to open the modal
[KIT-2627]: https://coveord.atlassian.net/browse/KIT-2627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(atomic): add automatic facets to atomic refine modal

- packages/atomic/src/pages/accessibility/commerce-full.html
- packages/atomic/src/pages/examples/external.html
- packages/samples/angular/src/app/atomic-angular-page/atomic-angular-page.component.html
- packages/samples/atomic-next/pages/index.tsx
- packages/samples/atomic-react/src/components/AtomicPageWrapper.tsx
- packages/samples/atomic-react/src/pages/FoldedResultListPage.tsx
- packages/samples/atomic-react/src/pages/InstantResultsPage.tsx
- packages/samples/atomic-react/src/pages/RecsPage.tsx
- packages/samples/atomic-react/src/pages/ResultListPage.tsx
- packages/samples/atomic-react/src/pages/TableResultListPage.tsx
- packages/samples/headless-react/src/pages/ProductRecommendationsPage.tsx
- packages/samples/iife/www/atomic-react.html
- packages/samples/vuejs/src/components/SearchPage.vue
https://coveord.atlassian.net/browse/KIT-2648
Also added a searchHub with the same name.
Note that the product recommendations engine can only be specified a search hub, it cannot be specified a pipeline.
**Warning**: auto-merge is enabled on this PR.
> ci: add e2e pipeline to electronics org samples

- packages/atomic/cypress/e2e/result-list/result-components/result-printable-uri.cypress.ts
- packages/atomic/src/components/search/result-template-components/atomic-result-printable-uri/atomic-result-printable-uri.tsx
Before, when a breadcrumb was placed inside of a grid result, clicking the ellipsis to expand the result would also click the result link. This should be fixed now though. I also added a test to confirm this.
To test:
1. Go to full commerce demo locally
2. Confirm that clicking the ellipsis on a breadcrumb doesn't also bring you to the result URL
> fix(atomic): fix grid result breadcrumbs

- package-lock.json
- package.json
- patches/@microsoft+fetch-event-source+2.0.1.patch
[SFINT-5159](https://coveord.atlassian.net/browse/SFINT-5159)
fetchEventSource library patched in order to support working in Salesforce Locker Service.
The `AbortController` used by the library can't be used in Salesforce Locker Service, that's why we are creating this patch that will update the usage of this AbortController in the library and allow the GenAi feature to work as expected in Quantic.
to patch this library I used the library: [patch-package](https://www.npmjs.com/package/patch-package?activeTab=readme
)
[SFINT-5159]: https://coveord.atlassian.net/browse/SFINT-5159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(headless): fetch event source library patched to support working in SF Locker Service

- package-lock.json
- package.json
- patches/tailwindcss+3.3.3.patch
Empirical fix, I didn't trace back exactly where it goes haywire.
Gut feeling: too much parallelism made using fs.promises, which in turn leads to Windows to :rage4: because lower limits for opened files.
Solution: Reuse the synchronous code on Windows, and let Linux be Linux.
I prefer to not invest more, will prolly be fixed when Oxide (Tailwind not-so-secret Rust sauce that should come 🔜 ™️) will land.
https://coveord.atlassian.net/browse/KIT-2691
> chore(atomic): fix build on windows

- packages/quantic/force-app/main/default/lwc/quanticSourceCitations/quanticSourceCitations.css
[SFINT-5150](https://coveord.atlassian.net/browse/SFINT-5150)
Issue:
There was a misalignment between the citations titles and the index of the citations. This was due to different font sizes (13px for the index and 14px for the citation title)
Solution: 
Set the title, label to the same font-size as index. It is now pixel perfectly aligned.
BEFORE:
AFTER:
[SFINT-5150]: https://coveord.atlassian.net/browse/SFINT-5150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): Fixed the misalignment of 1px in citations titles

- packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet.test.ts
- packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet.ts
- packages/headless/src/controllers/core/search-parameter-manager/headless-core-search-parameter-manager.ts
- packages/headless/src/controllers/insight/facets/category-facet/headless-insight-category-facet.ts
- packages/headless/src/controllers/product-listing/category-facet/headless-product-listing-category-facet.ts
- packages/headless/src/features/facets/category-facet-set/category-facet-set-selectors.ts
- packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.ts
- packages/headless/src/features/facets/category-facet-set/category-facet-utils.test.ts
- packages/headless/src/features/facets/category-facet-set/category-facet-utils.ts
- packages/headless/src/features/facets/category-facet-set/interfaces/commons.ts
- packages/headless/src/features/facets/category-facet-set/interfaces/request.ts
- packages/headless/src/features/facets/category-facet-set/interfaces/response.ts
- packages/headless/src/features/facets/facet-set/facet-set-analytics-actions-utils.test.ts
- packages/headless/src/features/history/history-slice.ts
- packages/headless/src/index.ts
- packages/headless/src/insight.index.ts
- packages/headless/src/product-listing.index.ts
Essentially, this PR replaces *both* `getActiveValueFromValueTree` and `partitionIntoParentsAndValues` (partially) with `findActiveValueAncestry`.
The first one is a method I introduced in #3105, and I could have left it there. However, in an effort to ease the deprecation of `categoryFacetState.parents`, I decided to use it in the CategoryFacetController.
However, `parents` is not entirely based on the notion of whether a value is selected or not (which IMHO is not the best because when a value is selected, it represents user intent) contrary to the new `selectedValueAncestry`, so I decided to create the latter to replace the former definitively in v3.
The second one is the historical method that doesn't work well with "multi-root-values" hierarchies, which leads to similar symptoms …
> fix(headless): consider only selected value ancestry for analytics, history and breadcrumbs 

- packages/headless/doc-parser/doc-parser.ts
- packages/headless/doc-parser/src/api-finder.ts
When adding an interface, it's confusing to know all the nooks and crannies where you should expose it.
This helps by telling you where you forgot to export it. (it is quite lazy, but it works).
------
KIT-2698
> chore(doc-tools): log failing entrypoint

- packages/quantic/force-app/main/default/lwc/quanticFeedback/__tests__/quanticFeedback.test.js
- packages/quantic/force-app/main/default/lwc/quanticFeedback/quanticFeedback.html
- packages/quantic/force-app/main/default/lwc/quanticFeedback/quanticFeedback.js
[SFINT-5142](https://coveord.atlassian.net/browse/SFINT-5142)
Added tooltips for the quantic Feedback component. I used the labels `thisAnswerWasHelpful` & `thisAnswerWasNotHelpful`
DEMO:
DISLIKE TOOLTIP:
LIKE TOOLTIP:
DEMO IN smart snippet:
If you set like-label property to something like patate, the tooltip will be the same as label
DEMO IN Generated answer:
[SFINT-5142]: https://coveord.atlassian.net/browse/SFINT-5142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): Added tooltips for quantic feedback component

- packages/atomic-angular/project.json
https://coveord.atlassian.net/browse/KIT-2718
Somehow didn't pay enough attention to my changes to the task definitions of Angular and made some bad copy-and-pastes, which are breaking the release.
> ci: fix typos in atomic-angular task definitions

- .eslintrc.json
- lint-staged.config.js
Gen files are sometimes ignored by eslint (that make sense), and this creates a eslint warning because the file is not parsed, making eslint fail, which is a bit silly 😂 
So I removed the max-warn limit and promoted the few warn rules we had to errors.
The gap we create concerns the "warn" rules that we have only through eslint extends, but I feel OK with this.
For example, this blocks React dependency update PR :finnadie: 
KIT-2731
> chore: remove eslint 0 warn, promote all manual rules to err

- CODEOWNERS
Since the commerce team works on the headless commerce sub-package, it makes sense for us to own the related files. 
[CAPI-83]
[CAPI-83]: https://coveord.atlassian.net/browse/CAPI-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(commerce): make commerce team owners of commerce sub-package

- packages/bueno/jest.config.js
- packages/bueno/tsconfig.json
- packages/bueno/tsconfig.test.json
Bueno build is more thorough while checking the libs and types.
Bueno does not depend on any `@types` packages, thus it does not need `types`.
> chore(bueno): ensure bueno types are safe-guarded

- utils/atomic-storybook/.storybook/register.js
There seems to be some regression from storybook related to selection of first story by default on load.
ref: https://github.com/storybookjs/storybook/issues/24292
https://coveord.atlassian.net/browse/KIT-2772
> docs(atomic): select first story by default with storybook when story is missing

- packages/samples/angular/cypress/e2e/atomic-angular/smoke-test.cypress.cy.ts
- packages/samples/atomic-next/cypress/e2e/smoke-test.cypress.cy.ts
- packages/samples/atomic-react/cypress/e2e/smoke-test.cypress.cy.ts
- packages/samples/iife/cypress/e2e/atomic-react-smoke-test.cy.ts
- packages/samples/stencil/cypress/e2e/stencil/smoke-test.cypress.ts
- packages/samples/vuejs/cypress/e2e/atomic-angular/smoke-test.cypress.cy.ts
https://coveord.atlassian.net/browse/KIT-2775
The regexp only checks that the first digit is 1-9. 0 would be unexpected (and usually should be a "no results" page anyway). The digit before the dash should always be 1, since we didn't press anything on the pager.
> ci: make smoke tests assert a number of results above 1 instead of exactly 10

- packages/atomic/src/components/search/atomic-generated-answer/atomic-generated-answer.pcss
Huge change to set loading icon to atomic-primary instead of the hardcoded `#1372ec`. The default color of atomic-primary is also `#1372ec`.
https://coveord.atlassian.net/browse/SVCINT-2527
> fix(genAI): set loading dots to atomic-primary

- .nvmrc
Pin NodeJS to 18.17.1:
GitHub released a new version of the ubuntu image which include a new release of NodeJS that do have a bug.
Related: https://github.com/nodejs/node/issues/49911
----
KIT-2786
> chore(ci): revert to nodejs 18.17.1

- packages/atomic/cypress/e2e/smart-snippet.cypress.ts
- packages/atomic/cypress/fixtures/test-fixture.ts
In general: Remove lots of `describe`/`beforeEach` block (perform the setup directly in the it block when possible) and perform more assertion as part of a single `it` block.
https://coveord.atlassian.net/browse/KIT-2790
> test(atomic): more simplification for smart snippet tests

- packages/headless/src/features/facets/facet-set/facet-set-slice.ts
We don't need use/need immer, and this pollute our bundles. Shoo.
> fix: import immer only as type

- packages/atomic/cypress/e2e/common-assertions.ts
- packages/atomic/cypress/e2e/search-box/instant-results/search-box-instant-results-assertions.ts
- packages/atomic/cypress/e2e/search-box/instant-results/search-box-instant-results.cypress.ts
- packages/atomic/cypress/e2e/search-box/search-box-assertions.ts
https://coveord.atlassian.net/browse/KIT-2759
I had already worked on this file 1 month ago, so this did not take a long time.
I was able to simplify these tests because the main part was looking if you were able to navigate through it using the keyboard and the mouse. These 2 do not need a reinitialization of the component. You can keep the same one and go through every use case. This way, it creates less reloading resulting in less flakiness.  
I also took the time to merge the tests in 'with a custom aria label' for the same reasons. The component did not need to be reinitialized.
> test: simplify search box instant result

- packages/atomic/cypress/fixtures/fixture-common.ts
- packages/atomic/cypress/fixtures/test-fixture.ts
- packages/atomic/cypress/fixtures/test-recs-fixture.ts
https://coveord.atlassian.net/browse/KIT-2807
Whenever a component would crash inside of cypress, it would not print in the cypress console. I think this is a feature that broke when updating cypress. I had this problem and felt like it wasn't there before. Then I remembered that @mrrajamanickam-coveo had done this change in his old PR to update to cypress 12.
> test: show console errors inside of cypress

- renovate.json
Stencil due to its patch-package is troublesome to update, let's isolate it
> chore: isolate stencil for dep updates

- utils/atomic-storybook/.storybook/map-props-to-args.ts
- utils/atomic-storybook/.storybook/map-result-list-props-to-args.ts
Fix an issue with storybook controls not appearing properly for components properties.
ie: We want a radio select for enums component options, toggle select for boolean component options, etc.
This was broken with storybook upgrade.
https://coveord.atlassian.net/browse/KIT-2811
> docs(atomic): fix storybook args 

- renovate.json
Node 18.18.0 has an issue with some webpack packages, we're waiting for Node 18.19.0 or 20 LTS. However Renovate does try to update it, let's isolate it.
(This would have been exactly the same regardless of the tool used to manage Node, like Volta :P )
KIT-282
> chore(renovate): isolate nvm

- renovate.json
#3266 didn't work because `nvm` is a packageManager for renovate, not a package.
Same same but different...
Was not able to validate locally with validator as it didn't flag the current config as ❌ 
KIT-282
> chore: isolate nvm, second attempt

- packages/atomic/src/components/common/smart-snippets/atomic-smart-snippet-collapse-wrapper/atomic-smart-snippet-collapse-wrapper.pcss
- packages/atomic/src/components/common/smart-snippets/atomic-smart-snippet-collapse-wrapper/atomic-smart-snippet-collapse-wrapper.tsx
- packages/atomic/src/pages/examples/ipx.html
Basically doing the same thing as before, except
- use `--full-height` to calculate a `max-height` instead of `height`
- set the `transition` on `max-height` instead of `height`
- set `height` to `auto`
No visual changes except making the expanded height more consistent.
TBH I think that at this point we could just not calculate `--full-height` and use a static value of like 1 Billion pixels, but I kinda want to get my feature working (it has been a while 😬)
https://github.com/coveo/ui-kit/assets/71142397/5574c9ba-2e04-4170-9214-6821785c3fda
Discussed with @btaillon-coveo and we could probably remove code that use this `--full-height` related logic in both smart-snippet components (`collapse-wrapper` and `expandable-answer`) and use `height: auto` everywhere... TBD
> fix: screw it, max-height transition !

- packages/atomic/cypress/e2e/search-box/search-box.cypress.ts
New Singhr in town is causing `q=singhr` to find two singhr. This fix the test relative to that.
KIT-2823
> test(atomic): narrow query

- packages/quantic/cypress/e2e/default-1/case-classification/case-classification.cypress.ts
[SFINT-5240](https://coveord.atlassian.net/browse/SFINT-5240)
Apparently Salesforce changed the structure of the objects returned when using the `getPicklistValuesByRecordType` wire adapter used to get a all picklist values of a field of a given object.
This change cause an issue in the mock function we used to mock this wire adapter call causing the failure of the cypress tests.
Adjusting the mock function to return exactly what's expected solved the issue.
[SFINT-5240]: https://coveord.atlassian.net/browse/SFINT-5240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): fixed case classification cypress test

- renovate.json
KIT-2787
fresh fix: https://github.com/nodejs/node/releases/tag/v18.18.1
> chore: remove nvm restriction

- packages/headless/src/features/search/search-mappings.test.ts
This makes sure the Act & Assert are both executed during the same epoch second
https://coveord.atlassian.net/browse/KIT-2825
> test: freeze time in `search-mapping.test.ts`

- packages/samples/headless-ssr/cypress/e2e/ssr-search-parameter-manager.cy.ts
https://coveord.atlassian.net/browse/KIT-2835
Could also make two separate files but I think it is fine this way. The tests are pretty fast.
> test(headless-ssr): split search parameter tests in both 'generic' and 'react' route

- packages/headless/src/controllers/search-parameter-manager/headless-search-parameter-manager.ssr.test.ts
- packages/headless/src/test/mock-engine.ts
https://coveord.atlassian.net/browse/KIT-2715
I tried to make sure only the defineSearchParameterManager function was tested and the rest was properly mocked.
> test(headless-ssr): add tests for the defineSearchParameterManager function

- packages/atomic/stencil.config.ts
fix #3310 
https://stenciljs.com/docs/react#typeerror-cannot-read-properties-of-undefined-reading-isproxied
Docs warns that this might increase bundle size. I checked and it increased by 45kb in a 55.6mb total (for atomic) 😅
> fix(atomic-react): fix for Vite by enabling import injection

- packages/quantic/cypress/e2e/default-2/recent-results-list/recent-results-list.cypress.ts
- packages/quantic/cypress/e2e/default-2/smart-snippet-suggestions/smart-snippet-suggestions-selectors.ts
- packages/quantic/cypress/e2e/default-2/smart-snippet-suggestions/smart-snippet-suggestions.cypress.ts
- packages/quantic/cypress/e2e/default-2/smart-snippet/smart-snippet-selectors.ts
- packages/quantic/cypress/e2e/default-2/smart-snippet/smart-snippet.cypress.ts
- packages/quantic/cypress/fixtures/folded-result-list/exampleResultWithMoreChildResults.json
- packages/quantic/quantic-examples-community/experiences/Quantic_Examples1/config/mainAppPage.json
[SFINT-5241](https://coveord.atlassian.net/browse/SFINT-5241)
- Locker Service enabled in the Salesforce org used to perform the cypress e2e tests.
- Few adjustments have been made to make the tests pass in  this new environment.
[SFINT-5241]: https://coveord.atlassian.net/browse/SFINT-5241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(quantic): locker service enabled in e2e environment 

- packages/headless/src/controllers/commerce/product-listing/sort/headless-product-listing-sort.ts
Instead of exporting the product listing sort types, the core sort ones were exported.
[CAPI-92]
[CAPI-92]: https://coveord.atlassian.net/browse/CAPI-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CAPI-92] Export right sort types

- packages/headless/src/controllers/generated-answer/headless-generated-answer.test.ts
- packages/headless/src/controllers/generated-answer/headless-generated-answer.ts
- packages/headless/src/features/generated-answer/generated-answer-analytics-actions.ts
[SFINT-5252](https://coveord.atlassian.net/browse/SFINT-5252)
- New `logCitationHover` method added to the generated answer controller.
- This new method will be called from the UI libraries (Atomic/Quantic) on hover over a citation of a generated answer for a given amount of time.
[SFINT-5252]: https://coveord.atlassian.net/browse/SFINT-5252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless): new logCitationHover method added to the generated answer controller

- utils/release/git-publish-all.mjs
I added a protection on release/*, but forgot to move those temp branches on an unprotected pattern.
KIT-2863
> chore: make temp-branch on an unprotected pattern

- packages/headless/src/app/logger.ts
Seems there's been some changes in Pino, and how they decide to log browser message to the console.
The symptom: By default, we set Pino level to `warn` -> We would still see `trace` or `info` level message appearing in the browser.
As soon as you use the `transmit` option, the message gets printed to the console, no matter what logging level is configured. This seems like intended behaviour from the maintainer of the library, from what I could read on their Github issues.
I've taken the editorial choice of just deprecating the `browserPostLogHook` function, which is something I'd be very surprised is used by anyone.
https://coveord.atlassian.net/browse/KIT-2858
> fix(headless): fix pino logging incorrectly

- packages/atomic/cypress/e2e/breadbox-assertions.ts
- packages/atomic/cypress/e2e/breadbox-selectors.ts
- packages/atomic/cypress/e2e/facets/automatic-facet/automatic-facet-selectors.ts
- packages/atomic/cypress/e2e/facets/facet/facet.cypress.ts
- packages/atomic/cypress/e2e/facets/rating-facet/rating-facet-selectors.ts
- packages/atomic/cypress/e2e/facets/rating-range-facet/rating-range-facet-selectors.ts
- packages/atomic/cypress/e2e/pager.cypress.ts
- packages/atomic/cypress/e2e/query-error-selectors.ts
- packages/atomic/cypress/fixtures/fixture-common.ts
https://coveord.atlassian.net/browse/KIT-2848
Couldn't recreate this issue locally. Researched many best practices for this type of problem and pretty much everywhere I looked suggested that this was a matter of sequencing (e.g., we should be checking the component at every level rather than checking most of the component, and then jumping straight to an icon that's nested a couple of levels down).
I wanted to avoid rewriting a bunch of tests, so I instead decided to instead setup an intercept for any resources requests and make cypress wait for the requests to resolve before searching for the shadow element.
Note that I have to rely on a regex for because resources are loaded through webpack as JS files with hashes appended to the file name. Unfortunately, this means we end up waiting …
> test(cypress): wait for resources in cypress tests

- package-lock.json
- package.json
- packages/atomic-hosted-page/package.json
- packages/atomic-react/package.json
- packages/atomic/package.json
- packages/auth/package.json
- packages/bueno/package.json
- packages/headless-react/package.json
- packages/headless/package.json
- packages/quantic/package.json
I think since #3399 , NPM was able to reify the package-lock way more narrowly, breaking some of our misuse/implicit dependency links.
This makes those implicit links explicit.
> chore: add release internal in each package using it

- packages/atomic-angular/package.json
- packages/atomic-angular/project.json
- packages/atomic-angular/scripts/bump.mjs
- packages/atomic-angular/scripts/publish-npm.mjs
- Remove NX quirk, it doesn't play nice with angular
- Replace with script in the same vein as later phases
- Adapt scripts to use process.env.INIT_CWD for compat.
> chore: adapt angular scripts for npm run-script

- packages/atomic/src/components/ipx/atomic-ipx-button/atomic-ipx-button.tsx
- packages/atomic/src/pages/examples/ipx.html
Sets the onClick behaviour directly in the atomic-ipx-button. This allows us to have much cleaner code in the SIS in the loader script.
> feat(IPX): make button load recs on click

- packages/headless/src/api/commerce/commerce-api-client.test.ts
- packages/headless/src/api/commerce/commerce-api-params.ts
- packages/headless/src/api/commerce/common/request.ts
- packages/headless/src/controllers/commerce/context/headless-context.test.ts
- packages/headless/src/controllers/commerce/context/headless-context.ts
- packages/headless/src/features/commerce/context/context-actions.ts
- packages/headless/src/features/commerce/context/context-slice.test.ts
- packages/headless/src/features/commerce/context/context-state.ts
- packages/headless/src/features/commerce/context/context-validation.ts
- packages/headless/src/integration-tests/commerce.test.ts
The commerce api now exposes a required `country` body parameter. This PR exposes methods to set it through the context controller, and builds commerce api requests using it.
[CAPI-348]
[CAPI-348]: https://coveord.atlassian.net/browse/CAPI-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(commerce): forward country to commerce api

- packages/headless/doc-parser/use-cases/search.ts
- packages/headless/src/controllers/generated-answer/headless-generated-answer.ts
- packages/headless/src/controllers/index.ts
Apparently the buildGeneratedAnswer function was not included in the JSON the docs team uses to generate our reference documentation.
This should do it.
> docs(headless): added RGA controller to doc-parser

- packages/quantic/force-app/main/default/lwc/quanticSearchBox/templates/expandableSearchBox.css
- packages/quantic/force-app/main/default/lwc/quanticStandaloneSearchBox/templates/expandableStandaloneSearchBox.css
- packages/quantic/force-app/main/default/lwc/quanticTooltip/quanticTooltip.css
- packages/quantic/force-app/main/default/lwc/quanticTooltip/quanticTooltip.js
[SFINT-5321](https://coveord.atlassian.net/browse/SFINT-5321)
ISSUE:
FIX: 
- Increased the z-index of the tooltip so that it is never hidden by any other elements
DEMO:
[SFINT-5321]: https://coveord.atlassian.net/browse/SFINT-5321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): Fix issue where tooltip is displayed under elements above the generated answer component

- packages/atomic/src/components/common/search-box/text-area-clear-button.tsx
- packages/atomic/src/components/common/search-box/text-area-submit-button.tsx
https://coveord.atlassian.net/browse/KIT-2938
> fix(atomic): icons in textarea search box are not centered

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.tsx
The `initializeWithSearchEngine` method of the `atomic-search-interface` component mentions that it needs a preconfigured Headless search engine, but it doesn’t link to the Headless search engine reference documentation. Adding a link will hopefully deflect some support questions.
Also added a missing period to the description of the `getOrganizationEndpoints` method.
> docs(atomic): add link to headless search engine

- packages/headless/src/controllers/commerce/search-box/headless-search-box.test.ts
- packages/headless/src/controllers/commerce/search-box/headless-search-box.ts
because we use 0-based indexing for pagination, when performing a search, we should reset the pagination to the 0th page, not the 1st page.
[CAPI-355]
[CAPI-355]: https://coveord.atlassian.net/browse/CAPI-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(commerce): use 0-based indexing for search box

- packages/headless/src/features/commerce/facets/facet-set/facet-set-selector.ts
- packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.ts
- packages/headless/src/features/commerce/facets/facet-set/interfaces/request.ts
- packages/headless/src/test/mock-commerce-facet-request.ts
The display name is required on commerce query requests. This PR attaches it to them.
🎩 tested on barca as well: 
[CAPI-355]
[CAPI-355]: https://coveord.atlassian.net/browse/CAPI-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(commerce): forward required display name

- package-lock.json
- packages/headless/package.json
- packages/headless/src/features/analytics/insight-analytics-actions.test.ts
- packages/headless/src/features/analytics/insight-analytics-actions.ts
[SFINT-5327](https://coveord.atlassian.net/browse/SFINT-5327)
**IN THIS PR:**
- Removed the triggeredBy from the insight analytics actions as it is no longer needed/ deemed useful
- updated coveo.analytics.js to 2.28.24
[SFINT-5328]: https://coveord.atlassian.net/browse/SFINT-5328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SFINT-5327]: https://coveord.atlassian.net/browse/SFINT-5327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless): removed the triggeredBy from the insight analytics actions for logCreateArticle

- packages/quantic/cypress/e2e/default-2/generatedAnswer/generated-answer.cypress.ts
SFINT-5341
Updated the e2e copy to clipboard cypress test to not check for copy to clipboard on browsers other than electron.
The problem was that the browser is requesting clipboard access through a popup which is not manageable with cypress.
So this specific test will only execute on electron.
> fix(quantic): fix genQA copy-to-clipboard e2e

- packages/headless/src/controllers/core/pager/headless-core-pager.test.ts
- packages/headless/src/test/mock-engine-v2.ts
- packages/headless/src/tsconfig.build.json
- packages/headless/src/tsconfig.test.json
This is an example PR for how I think we may want to modify our tests to try to 'fit' with some Redux good practices (and adapt some others to our specificity).
My first attempt was to try to use integration testing with our controllers, but was not able to. The main reasons are that it's cumbersome/inadequate to test all reducers using the actions triggered by a controller, and vice-versa.
So I went the opposite route, where I isolated everything
I reason that we can test everything that does consume an engine in isolation, and we mostly do actually.
The only piece that hasn't been black boxed like this is the controllers, and essentially this is what this PR do with the pager controller.
KIT-2954
> test(core-pager): rework with new practices

- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswerCopyToClipboard/quanticGeneratedAnswerCopyToClipboard.html
- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswerCopyToClipboard/quanticGeneratedAnswerCopyToClipboard.js
[SFINT-5364](https://coveord.atlassian.net/browse/SFINT-5364)
Removed the logic that was making the issue of making the copy to clipboard button not appear in the generated answer component.
`navigator.clipboard.writeText()` is not supported yet in Salesforce service console, that's what was causing the issue.
but the thing is that in Quantic, we have a fallback method that does the copy to clip board job without relying on `navigator.clipboard` so we don't really need this logic.
This condition has been initially added by the SVCC team cause they had this problem in Atomic, but in our side it's not needed cause we have a fallback method allowing us to copy to clipboard properly.
[SFINT-5364]: https://coveord.atlassian.net/browse/SFINT-5364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
> fix(quantic): fixed issue of copy to clipboard button not being  displayed

- packages/quantic/force-app/main/default/lwc/quanticCitation/quanticCitation.css
- packages/quantic/force-app/main/default/lwc/quanticStatefulButton/quanticStatefulButton.html
- packages/quantic/force-app/main/default/lwc/quanticTooltip/quanticTooltip.js
[SFINT-5350](https://coveord.atlassian.net/browse/SFINT-5350)
In some specific situations is Salesforce, like in the Hosted Insight Panel for example, the citations tooltip were being cropped because they were displayed inside a Salesforce container that had some stying rules that hide any thing that overflows the container:
In order to avoid such situations, I added a new logic to the Quantic Tooltip component that limits the width of the tooltip relatively to the width of its target.
This way the tooltip will never be too big to be cropped.
Additionally, since we reduced the width, I alsso made the tooltip of the citations display the first 6 lines of the descriptions instead of 4 and this keep always approximately  displaying the same amount  of information. In other words I reduced …
> fix(quantic): adjust citation tooltip width in specific situations inside Salesforce

- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswer/quanticGeneratedAnswer.js
- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswer/templates/generatedAnswer.css
- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswer/templates/generatedAnswer.html
- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswerRephraseButtons/quanticGeneratedAnswerRephraseButtons.html
- packages/quantic/force-app/main/default/lwc/quanticModal/quanticModal.css
[SFINT-5371](https://coveord.atlassian.net/browse/SFINT-5371)
The expandable search box was having a z index greater than the refine modal.
https://github.com/coveo/ui-kit/assets/86681870/0ba1ad86-e240-44f5-a1ea-533a2e886a59
The Quantic Generated Answer component was not very response when being in a narrow space like the Hosted Insight Panel when it's placed in a narrow space of the Salesforce Service Console.
I discussed with the UX team and we aggreed on the following solution, in narrow screens  we keep the toggle button in one line and the feedback and copy to clipboard button in a second line:
https://github.com/coveo/ui-kit/assets/86681870/ea922b35-8628-488e-b0af-a436dcf09db4
https://github.com/coveo/ui-kit/assets/86681870/f1e11e2f-807b-4465-b71b-89d43ed60228
[SFINT-5371]: …
> fix(quantic): fixed couple issues with generated answer and the expandable search box components

- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/__tests__/quanticSearchBoxInput.test.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/quanticSearchBoxInput.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/templates/defaultSearchBoxInput.html
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/templates/expandableSearchBoxInput.html
[SFINT-5374](https://coveord.atlassian.net/browse/SFINT-5374)
- Issue fixed.
- New test added to make sure this bug will not happen again.
- Test improved to execute the whole tests for both the default search box and the standalone searchbox.
The issue appears after executing the following actions:
- Enter a query in the search box, for example: “abc“.
- Click the down arrow key.
- Click the del key to delete the last character in the search box.
- The query transforms to a whole other word.
https://github.com/coveo/ui-kit/assets/86681870/1464d98a-1716-40ac-9441-92225f069856
The issue was occurring because the clicking the Down arrow key was triggering the selection of the first suggestion of the suggestions list, however at the moment of the click on the Down Arrow the suggestions list …
> fix(quantic): fixed issue with the Quantic Search Box Input

- packages/atomic/src/components/insight/atomic-insight-search-box/atomic-insight-search-box.pcss
[SVCC-3415](https://coveord.atlassian.net/browse/SVCC-3415)
Fix atomic-insight-search-box width 
Before:
After:
[SVCC-3415]: https://coveord.atlassian.net/browse/SVCC-3415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(atomic): fix insight search box width

- packages/headless/src/features/search/legacy/search-actions-thunk-processor.ts
After testing against Barca sport, this client side UA event is ultimately un-necessary. 
We just need one to be logged (returned from this function):
```
analyticsAction: logDidYouMeanAutomatic(),
```
Importantly, `logDidYouMeanAutomatic` will log `q={corrected query}`, which is what ML will learn against, and not the typo.
https://coveord.atlassian.net/browse/KIT-2965
> fix(headless): remove un-necessary client side events for new query correction

- packages/atomic/src/components/common/interface/analytics-config.ts
- packages/atomic/src/components/recommendations/atomic-recs-interface/analytics-config.ts
- packages/atomic/src/components/search/atomic-search-interface/analytics-config.spec.ts
- packages/atomic/src/components/search/atomic-search-interface/analytics-config.ts
- packages/headless/src/api/analytics/base-analytics.test.ts
- packages/headless/src/api/analytics/base-analytics.ts
- packages/headless/src/api/analytics/search-analytics.test.ts
- packages/headless/src/api/analytics/search-analytics.ts
- packages/headless/src/api/search/search-api-params.ts
- packages/headless/src/app/engine-configuration.ts
- packages/headless/src/features/configuration/analytics-params.ts
- packages/headless/src/features/configuration/configuration-actions.ts
- packages/headless/src/features/configuration/configuration-slice.test.ts
- packages/headless/src/features/configuration/configuration-slice.ts
- packages/headless/src/features/configuration/configuration-state.ts
- packages/headless/src/integration-tests/analytics-migration.test.ts
- packages/headless/src/test/mock-analytics-state.ts
- packages/headless/src/utils/validate-payload.ts
- packages/headless/src/utils/version.ts
Context, the new schema defined a new place for Coveo frameworks to report their versions: https://github.com/coveo/analytics_schema/pull/292.
This PR:
- Add a new config parameter in headless: `configuration.analytics.atomicVersion`. This will replace the analyticsMiddleware that atomic was using to set its version in the payloads.
- When `analyticsMode=next`, set the Headless version & Atomic Version (if any) to:
- The instantiation parameters of Relay
- The analytics section of the request body of the call made to the Search API
- When `analyticsMode=next`, do not set  `coveoHeadlessVersion` anymore in the customData. 
KIT-2930
> feat(headless,atomic): migrate framework versions from customData to source w/ next analytics

- packages/headless/src/app/undoable.test.ts
- packages/headless/src/app/undoable.ts
- packages/headless/src/controllers/history-manager/headless-history-manager.ts
- packages/headless/src/features/history/history-slice.test.ts
- packages/headless/src/features/history/history-slice.ts
- packages/headless/src/features/history/history-state.ts
- packages/headless/src/state/search-app-state.ts
As discussed on slack, this is a performance fix related to history management in Headless.
* Remove instant result from history management. It is completely un-necessary to keep it in memory to restore history on navigation. This change on it's own would probably fix (most) of the problem for the original maintenance ticket.
* Limit the amount of data kept in memory for `past` history entry, by limiting it to 10 entry. This change on it's own would probably fix (most) of the problem for the original maintenance ticket.
* Do a local optimization in history-manager controller to only compare `current-snapshot` vs `previous-snapshot` with a JSON.stringify compare. This override the "base controller" generic comparison function, which does a full JSON.stringify compare on all properties of …
> fix(headless): limit memory usage and property comparison for history manager

- packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/__tests__/data/defaultResult.json
- packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/__tests__/data/knowledgeArticleResult.json
- packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/__tests__/data/salesforceResult.json
- packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/__tests__/quanticResultPrintableUri.test.js
- packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/quanticResultPrintableUri.html
- packages/quantic/force-app/main/default/lwc/quanticResultPrintableUri/quanticResultPrintableUri.js
- packages/quantic/force-app/main/default/lwc/quanticResultText/quanticResultText.js
[SFINT-5353](https://coveord.atlassian.net/browse/SFINT-5353)
- Added the missing logic in the Quantic Printable URI that displays the printable URI of a result when its parents are not found.
- Added the logic that supports opening the result in Salesforce when the result is a Salesforce record.
https://github.com/coveo/ui-kit/assets/86681870/a4af8331-f133-406d-81d7-4cd39ebfcd97
[SFINT-5353]: https://coveord.atlassian.net/browse/SFINT-5353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): improved the Quantic Printable URI to support opening links inside salesforce

- packages/headless/src/controllers/core/breadcrumb-manager/headless-core-breadcrumb-manager.test.ts
- packages/headless/src/controllers/core/context/headless-core-context.test.ts
- packages/headless/src/controllers/core/did-you-mean/headless-core-did-you-mean.test.ts
- packages/headless/src/controllers/core/facet-manager/headless-core-facet-manager.test.ts
- packages/headless/src/controllers/core/facets/_common/facet-id-determinor.test.ts
- packages/headless/src/controllers/core/facets/category-facet/headless-core-category-facet.test.ts
- packages/headless/src/controllers/core/facets/facet/headless-core-facet.test.ts
Migrating some more controller tests for Redux toolkit 2 support.
> test(headless): migrate more controllers tests for redux tool kit 2

- utils/release/git-publish-all.mjs
I think the ref update of `release/v2` is failing because GH does not recognize the deploy key as our bot and that maketh tables flips.
> chore: use octokit for release branch update

- package-lock.json
- packages/headless/package.json
Bumps the coveo.analytics package to pull in the [changes](https://github.com/coveo/coveo.analytics.js/pull/450) around disabling coveoua not deleting the cookie.
> fix: bump coveo.analytics

- packages/atomic-hosted-page/src/components/utils/options-utils.ts
Using orgEndpoint
https://coveord.atlassian.net/browse/KIT-2996
> fix(hsp): use admin url

- packages/atomic/cypress/e2e/search-box/instant-results/search-box-instant-results.cypress.ts
- packages/atomic/cypress/e2e/search-box/search-box-assertions.ts
https://github.com/coveo/ui-kit/pull/3582 and https://github.com/coveo/ui-kit/pull/3585
merged close together.
One removed a function the other uses.
> test(e2e): oopsie-daisy

- packages/headless/src/api/search/search/product-recommendation.ts
The `documentUriHash` parameter is deprecated and we were asked by the data platform team to add a note to that effect.
> docs(headless): added deprecation note to documentUriHash

- packages/atomic/cypress/e2e/refine-toggle-actions.ts
- packages/atomic/cypress/e2e/refine-toggle.cypress.ts
- packages/atomic/src/components/common/facets/facet-common.tsx
- packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx
- packages/atomic/src/utils/utils.ts
> [!WARNING]
> This PR uses esoteric JavaScript APIs.
>Caffeine consumption/injection is advised before attempting a review.
During #3572, we changed the clone node algorithm:
https://github.com/coveo/ui-kit/blob/12140a1d91ec018a1bae05a94d87b42d70378452/packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx#L168-L190
This algorithm fails as it queries the DOM again for the facet, but only considering the tags of the components, and not taking into account the prefiltering that happened before in the execution stack:
https://github.com/coveo/ui-kit/blob/12140a1d91ec018a1bae05a94d87b42d70378452/packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx#L143-L149
This causes facets to be duplicated when some facets are invisible, such as when …
> fix(refine-modal): Sort facets values based on their DOM position

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/recommendations/atomic-recs-result-template/atomic-recs-result-template.tsx
- packages/atomic/src/components/search/result-templates/atomic-result-template/atomic-result-template.tsx
[DOC-12369](https://coveord.atlassian.net/browse/DOC-12369)
We received feedback that requested examples of the `atomic-result-template` component. I added a link in the descriptions of that component and the recommendations one to the section of the Atomic usage article that covers result templates.
[DOC-12369]: https://coveord.atlassian.net/browse/DOC-12369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(atomic): added usage link to atomic-result-template description

- .github/workflows/e2e-quantic.yml
- .github/workflows/masterbot.yml
- .github/workflows/prbot.yml
- scripts/ci/hasFileChanged.mjs
- Refactor Quantic CI into a reusable workflow
- Skip Quantic on `pull_request` and `merge_group` if no changes on headless, quantic, or the pjson has been detected
> refactor(ci): refactor quantic jobs into reusable workflow

- packages/headless/config/api-extractor/base.json
- packages/headless/src/api/analytics/analytics-relay-client.test.ts
- packages/headless/src/api/analytics/analytics-relay-client.ts
- packages/headless/src/api/analytics/analytics-selectors.test.ts
- packages/headless/src/api/analytics/analytics-selectors.ts
- packages/headless/src/api/analytics/search-analytics.test.ts
- packages/headless/src/api/analytics/search-analytics.ts
- packages/headless/src/app/engine.test.ts
- packages/headless/src/app/engine.ts
- packages/headless/src/case-assist.index.ts
- packages/headless/src/commerce.index.ts
- packages/headless/src/features/analytics/analytics-utils.ts
- packages/headless/src/features/configuration/analytics-params.ts
- packages/headless/src/index.ts
- packages/headless/src/insight.index.ts
- packages/headless/src/product-listing.index.ts
- packages/headless/src/product-recommendation.index.ts
- packages/headless/src/recommendation.index.ts
- packages/headless/src/ssr.index.ts
- packages/headless/src/test/mock-engine-v2.ts
- packages/headless/src/test/mock-engine.ts
- Refactor the configureAnalytics & getAnalyticsSource
- Make them into memoized selectors to shave off some computing
- Exposes Relay onto the engine.
KIT-3018
> feat(headless): expose relay on the engine

- packages/atomic/cypress/e2e/search-box/search-box.cypress.ts
- packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
* In atomic-search-box, remove `@State() private isSearchDisabled` and instead add a `isSearchDisabledForEndUser` function which returns true if either the `disableSearch` prop is set to true, or if the content of the input is not long enough.
* Modify some tests in cypress regarding this.
The reason to have a function to check this is because it's possible that `disableSearch` prop is controlled by implementer for other reasons than the content of the input. 
So it makes sense to have the "disabled because of the generic prop" to be decoupled from the "disabled because of the length of the input", and not conflate them with one another.
Hopefully with the name of the function, it makes it clearer why/when the input actually get disabled for the end user, and that using the prop directly …
> fix(atomic): fix search disabled check for query suggestion

- packages/headless/src/app/product-listing-engine/product-listing-engine-configuration.ts
- packages/headless/src/app/product-recommendation-engine/product-recommendation-engine-configuration.ts
Because the engines are defunct, I acted a bit lazy and decided to copy-paste the schema definitions.
https://coveord.atlassian.net/browse/KIT-2990
> feat(headless): forbid next analytics on defunct engines

- packages/headless/src/controllers/commerce/context/cart/headless-cart.ts
- packages/headless/src/controllers/commerce/context/headless-context.test.ts
- packages/headless/src/controllers/commerce/context/headless-context.ts
- packages/headless/src/features/commerce/context/context-actions.ts
- packages/headless/src/features/commerce/context/context-state.ts
- packages/headless/src/features/commerce/context/context-validation.ts
- packages/headless/src/integration-tests/commerce.test.ts
- packages/headless/tsconfig.json
Jira: https://coveord.atlassian.net/browse/LENS-1589
This branch is to change the type of the currency set in the commerce state (context-state). It was a `string`, it's now switch to `CurrencyCodeISO4217`. 
By doing this, the value set by the user for the commerce context will be type-checked differently (illustrate by the demo below):
https://github.com/coveo/ui-kit/assets/58052881/472fbfd2-b1c6-415e-9107-2076b997d592
> feat(headless/commerce): set currency type as currency code iso4217 instead of string

- .github/workflows/release.yml
By doing the following, we'll leverage the cache mechanism integrated into our setup action.
This will ensure that we have a cache built on the release stage, ready to be used in the `start-deployment` job.
Also, we don't need to build after setup.
> chore: run setup on gh runner first, remove dup build

- .github/actions/setup/action.yml
We need `registry-url` to be able to publish on NPM.
No impact for other use case.
> chore: add missing registry-url

- .github/workflows/release.yml
- utils/release/npm-publish-package.mjs
Should allow to have a ✅ on NPM.
Might become a requirement to comply with CSEC.
> chore: enable npm provenance

- packages/headless/src/controllers/commerce/context/headless-context.test.ts
- packages/headless/src/controllers/commerce/context/headless-context.ts
- packages/headless/src/features/commerce/common/actions.ts
- packages/headless/src/features/commerce/context/context-actions.ts
- packages/headless/src/features/commerce/context/context-slice.test.ts
- packages/headless/src/features/commerce/context/context-state.ts
- packages/headless/src/features/commerce/context/context-validation.ts
- packages/headless/src/features/commerce/query-suggest/query-suggest-actions.ts
- packages/headless/src/integration-tests/commerce.test.ts
The commerce engine was storing `trackingId` under commerce context, but the value was already available under the `configuration` slice. This was creating two sources of truth for `trackingId` on the commerce engine. If `trackingId` was set on init of the engine, it would not be used.
This PR resolves the duplication and uses the value on the `configuration` slice.
We're making this breaking change now to get ahead of customer adoption.
> fix: remove trackingId from commerce context

- .github/workflows/release.yml
Disabling this step for now, we reenable for future release.
In the latest [releases run](https://github.com/coveo/ui-kit/actions/runs/8254691568/job/22579419419) (and a few before), the release log are mangled for this specific action, for unknown reasons.
Manual runs on a 'full clone' of the repo is required/recommended but will likely take a good chunk of time.
We still want to release to the main channels (NPM/S3) in the meantime, so for now, we disable the GH PKG channel publishing
> chore: disable github-pkg

- packages/headless/esbuild.mjs
Build ui-kit, with the immediate use case of Headless, in dev on file change for hot reloading when debugging with Barca Sports. Also, remove minification and add source maps to allow debugging alongside an implementation.
Companion PR in Barca Sports [#192](https://github.com/coveo/barca-sports/pull/192)
Hot reloading example
https://github.com/coveo/ui-kit/assets/15649627/825480c4-79c2-45b6-b9c6-e97fd8309e5c
Debugging with source maps example
Uploading Screen Recording 2024-03-08 at 18.03.23.mov…
Link with Barca sports, using `yarn link` and add console.logs into the the running headless code. Changes should be reflected in the browser.
[CAPI-646]: https://coveord.atlassian.net/browse/CAPI-646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless): in development, rebuild modules with source maps 

- .github/actions/setup-ztsd/action.yml
- .github/workflows/release.yml
Short-story, in a Coveo-Hosted-Runner:
- Without ZTSD: https://github.com/coveo/cross-cache-testing/actions/runs/8257881251/job/22589275437 
- With ZTSD: https://github.com/coveo/cross-cache-testing/actions/runs/8258103042/job/22590308607
TL;DR: Can't hit a Cache made in GitHub if ZTSD is not there.
Long-story:
- `ubuntu-latest` from GitHub includes `ztsd`
- Coveo images does not include ztsd
- This generates a queryParam version. If the version of the cache doesn't match, the cache ain't used.
https://github.com/actions/toolkit/blob/main/packages/cache/src/internal/cacheHttpClient.ts#L78-L101
- As demonstrated in coveo/cross-cache-testing, the versions are not the same if ztsd is not installed (see the unredacted log in the links)
- This is because the compression method is determined …
> chore: add ztsd to coveo-hosted-runner for cache consistency

- scripts/deploy/execute-deployment-pipeline.mjs
Each line was interpreted independently of the other. Oops.
This concat the script, and ensures we have a single whitespace every time
> chore: ensure command stands on a singleline

- utils/release/git-publish-all.mjs
`''.split('\n')` returns `['']` and not `[]`. Oops.
> chore: handle empty message

- .github/workflows/release.yml
- scripts/deploy/execute-deployment-pipeline.mjs
When running the deployment pipeline, we need the full history. This PR adds that
- Do fetch-depth:0
- Mount the repo into the docker
> chore: mount repo into docker

- .github/workflows/release.yml
- scripts/deploy/execute-deployment-pipeline.mjs
- scripts/deploy/trigger-ui-kit-cd.mjs
For various reason, we can't call deployment-pipeline from github.com/coveo anymore.
So let's do it from github.com/coveo-platform/ui-kit-cd
This is very crude, but it (should?) work.
> chore: use side-repo for deployment

- packages/atomic/src/components/insight/atomic-insight-refine-modal/atomic-insight-refine-modal.tsx
- packages/atomic/src/components/ipx/atomic-ipx-refine-modal/atomic-ipx-refine-modal.tsx
Remove double filters title in IPX and Insight since we don't have sorts for IPX and SPs
|   | Before | After |
| ------------- | ------------- | ------------- |
| IPX  | <img width="521" alt="image" src="https://github.com/coveo/ui-kit/assets/64476861/962cb9e0-6c10-4abc-98f1-98e04603fe33">l  | <img width="522" alt="image" src="https://github.com/coveo/ui-kit/assets/64476861/8a1e7fe8-d74b-4e98-bcbe-96f89fe17e43">  |
| Insight  | <img width="528" alt="image" src="https://github.com/coveo/ui-kit/assets/64476861/dc5dcc73-90a5-434d-8011-ec668effb6e0">  | <img width="573" alt="image" src="https://github.com/coveo/ui-kit/assets/64476861/8466382f-0f07-4c01-8e0d-5ff96dbe57a0">  |
> chore(IPX+IP): remove filters top title

- .github/workflows/release.yml
The last CD action fail because it doesn't found the server key, as it tries to read it from packages/quantic/server.key
When checking the other place in the code where it works, this makes sense:
https://github.com/coveo/ui-kit/blob/7bf6c83a69bd37d80dd829bb3314f66e59fe94eb/.github/workflows/create-quantic-package.yml#L45-L50
In this working piece of code, we use the working-directory instruction to put the key where it should be.
[KIT-3025](https://coveord.atlassian.net/browse/KIT-3025)
[KIT-3025]: https://coveord.atlassian.net/browse/KIT-3025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: ensure we write the server key in the right directory

- .deployment.config.json
- scripts/deploy/execute-deployment-pipeline.mjs
We had an incident where, for version v.X.Y.Z, we deployed `/vX/`, `/vY/` and `/vZ/` to our CDN instead of `/vX/`, `/vX.Y/` and `/vX.Y.Z/`.
faeba9fecf72f55da2151fd7ec977e0e652ae8d0 fixes that, and b0a208d0d219561c3bb8d4c583d79daf6720cecd ensure deployment to a given environment can start only after manual approval.
We want the latter to verify our fix is working.
https://coveord.atlassian.net/browse/CDX-1535
> chore(ci): deploy patch&minor at the right place

- packages/headless/src/features/generated-answer/generated-answer-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.test.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.ts
- packages/headless/src/features/generated-answer/generated-answer-state.ts
[SVCC-3597](https://coveord.atlassian.net/browse/SVCC-3597)
Add `isAnswerGenerated` to GenerateAnswerState, to be able to check if the answer was properly generated.
`isAnswerGenerated` is set to `true` when an answer is properly generated.
`isAnswerGenerated` is set to `false` when “sorry message” is returned.
[SVCC-3597]: https://coveord.atlassian.net/browse/SVCC-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless): add isAnswerGenerated to the state

- packages/headless-react/README.md
We forgot to bump the package to v1. oopsie.
[KIT-3065](https://coveord.atlassian.net/browse/KIT-3065)
[KIT-3065]: https://coveord.atlassian.net/browse/KIT-3065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(readme)!: fleshup readme, graduate v1

- packages/atomic/cypress/e2e/generated-answer-selectors.ts
- packages/atomic/src/components/common/generated-answer/atomic-citation/atomic-citation.pcss
- packages/atomic/src/components/common/generated-answer/atomic-citation/atomic-citation.tsx
- packages/atomic/src/components/common/generated-answer/rephrase-buttons.tsx
- packages/atomic/src/components/common/generated-answer/styles/generated-answer.pcss
- packages/atomic/src/components/common/generated-answer/styles/rephrase-buttons.pcss
- packages/atomic/src/components/search/atomic-generated-answer/atomic-generated-answer.tsx
[SVCC-3626](https://coveord.atlassian.net/browse/SVCC-3626)
Adding `part` attribute to some genQA components, regarding Xero feedback.
- The div containing the citation-index element
- The div containing the rephrase-buttons element
- The div containing the rephrase-btn-label element
[SVCC-3626]: https://coveord.atlassian.net/browse/SVCC-3626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(atomic): add part attribute for genQA component

- packages/atomic/cypress/e2e/generated-answer-assertions.ts
- packages/atomic/cypress/e2e/generated-answer-selectors.ts
- packages/atomic/cypress/e2e/generated-answer.cypress.ts
- packages/atomic/src/components/common/generated-answer/generated-answer-common.tsx
- packages/atomic/src/components/common/generated-answer/styles/generated-answer.pcss
- packages/atomic/src/locales.json
[SVCC-3573](https://coveord.atlassian.net/browse/SVCC-3573)
Add Legal disclaimer to the RGA component:
- disclaimer displayed when the response is finished, but can be edited (slot) and removed.
- default text is: `Generated content may contain errors. Verify important information.`
Mobile Layout:
XS mobiel Layout:
https://github.com/coveo/ui-kit/assets/119955059/43e655a0-6500-4c3d-ade7-1b555832d3ed
[SVCC-3573]: https://coveord.atlassian.net/browse/SVCC-3573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(atomic): add rga disclaimer

- packages/headless/src/controllers/commerce/recommendations/headless-recommendations.test.ts
- packages/headless/src/controllers/commerce/recommendations/headless-recommendations.ts
- packages/headless/src/features/commerce/common/actions.ts
[CAPI-724](https://coveord.atlassian.net/jira/software/c/projects/CAPI/boards/1103?assignee=6168b023c5388b006911910a&selectedIssue=CAPI-724)
The real bug wasn't the missing configuration it was forgetting to await a promise of config. Recommendations controller now works as expected.
[CAPI-724]: https://coveord.atlassian.net/browse/CAPI-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(commerce): bugfix missing recs request configuration

- .github/workflows/create-quantic-package.yml
Setup do 99% of the job (node install with cache, build).
Tiny lil thing missing is sfdx
> chore: reuse existing workflow for setup in daily quantic

- packages/headless/src/commerce.index.ts
- packages/headless/src/controllers/commerce/context/headless-context.ts
- packages/headless/src/controllers/commerce/product-listing/headless-product-listing.ts
These exports are unneeded and unused. Let's remove them.
See discussion from which this change stems from: https://github.com/coveo/ui-kit/pull/3734#discussion_r1537951235
[CAPI-761]
[CAPI-761]: https://coveord.atlassian.net/browse/CAPI-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(commerce): remove unused controller state exports

- packages/headless/src/controllers/commerce/core/sub-controller/headless-sub-controller.test.ts
- packages/headless/src/controllers/commerce/core/sub-controller/headless-sub-controller.ts
- packages/headless/src/controllers/commerce/product-listing/headless-product-listing.ts
- packages/headless/src/controllers/commerce/search/headless-search.ts
In follow-up PRs, I will:
- Add pagination to the recs controller
- Make sub-controller state handled separated, to allow multiple solution types to coexist
- Add the facet generator as sub-controller
- Remove the `build[SolutionType]pagination`, `build[SolutionType]sort`, `build[SolutionType]facetGenerator` and similar top-level builders that become sub-controllers
[CAPI-719]
[CAPI-719]: https://coveord.atlassian.net/browse/CAPI-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(commerce): add pagination and sort sub-controllers

- .cspell.json
- packages/atomic/src/pages/examples/commerce-website/cart.html
- packages/atomic/src/pages/examples/commerce-website/commerce-nav.mjs
- packages/atomic/src/pages/examples/commerce-website/engine.mjs
- packages/atomic/src/pages/examples/commerce-website/homepage.html
- packages/atomic/src/pages/examples/commerce-website/listing-pants.html
- packages/atomic/src/pages/examples/commerce-website/listing-surf-accessories.html
- packages/atomic/src/pages/examples/commerce-website/listing-towels.html
- packages/atomic/src/pages/examples/commerce-website/search.html
- packages/atomic/src/pages/header.js
- packages/headless/src/commerce.index.ts
Lots of ugly throwaway/temporary code.
Goal is to have a setup to "fill in the blank" with atomic components in the following weeks.
* Homepage, with 2 recommendations strategy
* 3 listing page
* One search page
* One cart with 2 recommendations strategy
This should allow us to test properly navigation between pages, and how the state will be kept from one page to another in a non SPA scenario
https://coveord.atlassian.net/browse/KIT-3045
> docs(atomic): create poor man's version of barca sport in local setup for atomic

- packages/headless/src/api/commerce/commerce-api-params.ts
- packages/headless/src/controllers/commerce/context/cart/headless-cart-selectors.test.ts
- packages/headless/src/controllers/commerce/context/cart/headless-cart-selectors.ts
- packages/headless/src/controllers/commerce/context/cart/headless-cart.test.ts
- packages/headless/src/controllers/commerce/context/cart/headless-cart.ts
- packages/headless/src/features/commerce/context/cart/cart-selector.ts
- packages/headless/src/features/commerce/context/cart/cart-slice.test.ts
- packages/headless/src/features/commerce/context/cart/cart-slice.ts
- packages/headless/src/features/commerce/context/cart/cart-state.ts
- packages/headless/src/features/commerce/context/cart/cart-validation.ts
- packages/headless/src/integration-tests/commerce.test.ts
[LENS-1761](https://coveord.atlassian.net/browse/LENS-1761)
It was noticed that the `productId` emitted with the cart events (`ec.cartAction` & `ec.purchase`) in Barca sports was actually the sku of the product. To guarantee the uniqueness of the cart item in the state and that we send the right information to EP, we decided to add the `sku` property to the `updateItem` action.
Demo of linking the solution to Barca sports
https://github.com/coveo/ui-kit/assets/58052881/524973b7-ab52-4072-9b38-ce955f96d174
[LENS-1761]: https://coveord.atlassian.net/browse/LENS-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless-cart): allow both productid and SKU when updating a cart item with the cart controller

- packages/headless/src/app/commerce-engine/commerce-engine-configuration.ts
- packages/headless/src/app/commerce-engine/commerce-engine.test.ts
- packages/headless/src/app/commerce-engine/commerce-engine.ts
- packages/headless/src/controllers/commerce/context/headless-context.test.ts
- packages/headless/src/controllers/commerce/context/headless-context.ts
- packages/headless/src/features/commerce/context/context-validation.ts
- packages/headless/src/integration-tests/commerce.test.ts
Requiring the context on engine initialization means we can make the context non-required on the context controller.
[CAPI-650]
[CAPI-650]: https://coveord.atlassian.net/browse/CAPI-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(commerce): require context on engine initialization

- packages/atomic/src/components/common/generated-answer/styles/generated-answer.pcss
- packages/atomic/src/components/common/generated-answer/styles/rephrase-buttons.pcss
[SVCC-3659](https://coveord.atlassian.net/browse/SVCC-3659)
Fix rephrase buttons for small layout. The label should be hidden.
**Before:**
**After:**
_very small layout_
_small layout:_
[SVCC-3659]: https://coveord.atlassian.net/browse/SVCC-3659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(genqa): fix rephrase buttons for very small layout

- packages/headless/src/api/commerce/commerce-api-client.test.ts
- packages/headless/src/api/commerce/commerce-api-params.ts
- packages/headless/src/api/commerce/recommendations/recommendations-request.ts
- packages/headless/src/features/commerce/recommendations/recommendations-actions.ts
[CAPI-754](https://coveord.atlassian.net/jira/software/c/projects/CAPI/boards/1103?selectedIssue=CAPI-754)
Commerce API recommendations will be replacing `id` with `slotId` for slot identifier. This prepares for this change.
[CAPI-754]: https://coveord.atlassian.net/browse/CAPI-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(commerce): use slotId for Commerce recommendations requests

- packages/atomic/cypress/e2e/common-assertions.ts
- packages/atomic/cypress/e2e/facets/facet-depends-on/facet-depends-on.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-components/result-multi-value-text.cypress.ts
- packages/atomic/cypress/fixtures/test-fixture.ts
- packages/atomic/src/components/search/result-template-components/atomic-result-multi-value-text/atomic-result-multi-value-text.tsx
Spec: https://w3c.github.io/aria/#list
The important bit is this:
Essentially, anything but a role=listitem is forbidden under a `role=list`. `ol` is defacto a list, always (afaik). So `role=separator` is a nogo.
Example here: https://louis-bompart.github.io/automatic-octo-spoon/index.html
The obvious: remove the faulty role.
Editorial choice: I don't think the separator has any value whatsoever for a screen reader, so I elected to use `aria-hidden` to make it 'disappear' for all intent and purposes from the standpoint of a screen reader or accessibility tools.
This PR includes flakiness proofing on the accessibility test of this component (the method could be reused on as needed).
The flakiness of the test was reproducable on the client-side, and was indeed a 'false green'. This was …
> fix(atomic): separator should not be consider for ARIA

- packages/atomic/src/components/common/generated-answer/generated-answer-common.tsx
[SVCC-3357](https://coveord.atlassian.net/browse/SVCC-3357)
[Internal Coveo Documentation](https://docs.google.com/document/d/1gX-Kr0yP_Mqog4CT8OYZAbu25YQbkaewjMJw-LewGK0) about the issue and the proposed fix
In Atomic. Removal of the loading in the quantic generative answering component will prevent the UI from glitching
In Atomic
When the generative answering functionalities are enabled, but the model is asked a question it cannot answer, the stream opens and closes very quickly. This cause a jarring movement in the UI.
In Atomic
Removing the loading, letting the component appears only when the answer begins to stream will prevent the component from appearing and disappearing uselessly.  
**Before**
[simplescreenrecorder-2024-04-22_16.30.24.webm](https://github.com/coveo/ui-kit/assets/45 …
> fix(atomic): answer generation component glitch

- packages/headless/src/controllers/commerce/core/pagination/headless-core-commerce-pagination.test.ts
- packages/headless/src/controllers/commerce/core/pagination/headless-core-commerce-pagination.ts
- packages/headless/src/controllers/commerce/search-box/headless-search-box.test.ts
- packages/headless/src/controllers/commerce/search-box/headless-search-box.ts
- packages/headless/src/features/commerce/common/actions.test.ts
- packages/headless/src/features/commerce/common/actions.ts
- packages/headless/src/features/commerce/pagination/pagination-actions.ts
- packages/headless/src/features/commerce/pagination/pagination-slice.test.ts
- packages/headless/src/features/commerce/pagination/pagination-slice.ts
- packages/headless/src/features/commerce/pagination/pagination-state.ts
- packages/headless/src/features/commerce/recommendations/recommendations-actions.ts
To understand changes this enables, see:
- https://github.com/coveo/ui-kit/pull/3854 where the pagination sub-controller is put to use
- https://github.com/coveo/ui-kit/pull/3855 where we expose the facet sub-controllers
- https://github.com/coveo/ui-kit/pull/3857 where we remove now replaced top-level controllers
- https://github.com/coveo/ui-kit/pull/3859 where we expose the breadcrumb manager sub-controller
To understand how we came to this solution, see:
- https://github.com/coveo/ui-kit/pull/3825 where we tried slicing the pagination as a `Record`
- https://github.com/coveo/ui-kit/pull/3800 where we added pagination and sort as sub-controllers
~And see https://github.com/coveo/ui-kit/compare/feat-capi-719-sliced-pagination-states...feat-capi-719-sliced-structured-pagination-states …
> feat(commerce): structure pagination slices by solution types

- packages/atomic/src/components/common/search-box/search-input.tsx
- packages/atomic/src/components/common/search-box/search-text-area.tsx
- packages/atomic/src/components/insight/atomic-insight-search-box/atomic-insight-search-box.tsx
- packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
But hide them when needed.
This will ensure the DOM element referenced by the aria-controls always exists.
That's (kind of) what Google is doing
KIT-3125
> fix: always include suggestions popup in the DOM

- packages/headless/src/api/analytics/analytics-relay-client.test.ts
- packages/headless/src/api/analytics/analytics-relay-client.ts
When headless analytics are disabled, relay events were still being fired.
The PR adjusts relay's initialization to set the correct mode based on how headless is configured.
> fix: disable relay when headless analytics are disabled

- packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.ts
- packages/headless/src/controllers/commerce/core/facets/category/headless-commerce-category-facet.test.ts
- packages/headless/src/controllers/commerce/core/facets/date/headless-commerce-date-facet.test.ts
- packages/headless/src/controllers/commerce/core/facets/generator/headless-commerce-facet-generator.test.ts
- packages/headless/src/controllers/commerce/core/facets/generator/headless-commerce-facet-generator.ts
- packages/headless/src/controllers/commerce/core/facets/headless-core-commerce-facet.ts
- packages/headless/src/controllers/commerce/core/facets/numeric/headless-commerce-numeric-facet.test.ts
- packages/headless/src/controllers/commerce/core/facets/numeric/headless-commerce-numeric-facet.ts
- packages/headless/src/controllers/commerce/core/facets/regular/headless-commerce-regular-facet.test.ts
- packages/headless/src/controllers/commerce/product-listing/facets/headless-product-listing-category-facet.test.ts
- packages/headless/src/controllers/commerce/product-listing/facets/headless-product-listing-date-facet.test.ts
- packages/headless/src/controllers/commerce/product-listing/facets/headless-product-listing-facet-generator.test.ts
- packages/headless/src/controllers/commerce/product-listing/facets/headless-product-listing-numeric-facet.test.ts
- packages/headless/src/controllers/commerce/product-listing/facets/headless-product-listing-regular-facet.test.ts
- packages/headless/src/controllers/commerce/search/facets/headless-search-category-facet.test.ts
- packages/headless/src/controllers/commerce/search/facets/headless-search-date-facet.test.ts
- packages/headless/src/controllers/commerce/search/facets/headless-search-facet-generator.test.ts
- packages/headless/src/controllers/commerce/search/facets/headless-search-numeric-facet.test.ts
- packages/headless/src/controllers/commerce/search/facets/headless-search-regular-facet.test.ts
- packages/headless/src/features/commerce/facets/facet-search-set/category/commerce-category-facet-search-request-builder.ts
- packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.test.ts
- packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.ts
- packages/headless/src/features/commerce/facets/facet-set/interfaces/common.ts
- packages/headless/src/features/commerce/facets/facet-set/interfaces/request.ts
- packages/headless/src/features/commerce/facets/facet-set/interfaces/response.ts
- packages/headless/src/test/mock-commerce-facet-response.ts
https://coveord.atlassian.net/browse/CAPI-720
Initially when we implemented commerce numeric facets, ranges had to be explicitly specified in the CMH configuration.
It is now also possible to configure numeric facets with automatic discrete ranges, or with a single continuous range in the CMH.
Every facet response now includes a `domain` property indicating the `min` and `max` range values that will return products when a set as a selected range's `start` and `end` values respectively.
The `domain` also includes an `increment` property that indicates the number of "steps" between each value. This will always be `0` if the range is continuous, or if there is no regularity between the discrete ranges (e.g., if the discrete ranges overlap or "jump" steps).
The `domain` property is not …
> feat(headless/commerce): support continuous ranges on numeric facets

- packages/atomic/cypress/e2e/generated-answer.cypress.ts
- packages/atomic/src/components/common/generated-answer/generated-answer-common.tsx
[SVCC-3635](https://coveord.atlassian.net/browse/SVCC-3635)
Show `No title` when citation have empty title.
Before:
After:
[SVCC-3635]: https://coveord.atlassian.net/browse/SVCC-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(genQA): show no title in citation when we have empty title

- packages/atomic/src/components/common/facets/category-facet/all-categories-button.tsx
- packages/atomic/src/components/common/facets/category-facet/child-value-link.tsx
- packages/atomic/src/components/common/facets/category-facet/children-as-tree-container.tsx
- packages/atomic/src/components/common/facets/category-facet/parent-as-tree-container.tsx
- packages/atomic/src/components/common/facets/category-facet/parent-button.tsx
- packages/atomic/src/components/common/facets/category-facet/parent-value-link.tsx
- packages/atomic/src/components/common/facets/category-facet/search-results-container.tsx
- packages/atomic/src/components/common/facets/category-facet/search-value.tsx
- packages/atomic/src/components/common/facets/category-facet/value-as-tree-container.tsx
- packages/atomic/src/components/common/facets/category-facet/value-link.tsx
- packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
Simpler refactor than previous story/components:
* Category facet is currently exclusively used for the classic search use case. As such there is way less pollution from `@coveo/headless` in common files related to this one. It also benefits from the previous refactor for `facet-common`. The only one I had to modify was `category-facet/search-value`
* This PR focuses mostly on making sure there is no `"part"` attribute configured at the web component level, and instead extract them into lots of smaller functional components . If you refer to the design doc for  Atomic for commerce epic, one of the goal is to ensure styling consistency through `parts` attribute. So we want to make sure that atomic-commerce-category-facet re-use/output the exact same part name as classic search category …
> refactor(atomic): refactor atomic category facet into function components

- packages/headless/src/features/commerce/query/query-slice.test.ts
- packages/headless/src/features/commerce/query/query-slice.ts
- packages/headless/src/features/commerce/query/query-state.ts
CAPI doesn't like empty/missing query.
https://coveord.atlassian.net/browse/KIT-3161
> fix: default on empty str for query when restoring search params

- packages/atomic/src/pages/index.html
- packages/headless/src/app/__snapshots__/engine.test.ts.snap
- packages/headless/src/app/engine.test.ts
- packages/headless/src/app/engine.ts
Why a crash? Because it's best to stop the devs right in their track if they f-up.
Can't make it more apparent than 'nothing on your page' and some red stuff in your console ;)
https://coveord.atlassian.net/browse/KIT-3137
> feat: crash engine initialization for analyticsMode=next iif no trackingId

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/product-list/product-template-provider.ts
- packages/atomic/src/components/commerce/product-template-components/atomic-product-number/atomic-product-number.tsx
- packages/atomic/src/components/commerce/product-template-components/atomic-product-numeric-field-value/atomic-product-numeric-field-value.tsx
- packages/atomic/src/components/commerce/product-template-components/atomic-product-price/atomic-product-price.tsx
- packages/atomic/src/pages/examples/commerce-website/listing-pants.html
- packages/atomic/src/pages/examples/commerce-website/listing-surf-accessories.html
- packages/atomic/src/pages/examples/commerce-website/listing-towels.html
- packages/atomic/src/pages/examples/commerce-website/search.html
This PR adds the product price template component. This component displays the value of ec_price, in the specified currency. Additionally, it displays the value of ec_promo_price when that value is lower.
> feat(Commerce Atomic): add product price component

- packages/headless/src/commerce.index.ts
- packages/headless/src/controllers/commerce/core/sub-controller/headless-sub-controller.test.ts
- packages/headless/src/controllers/commerce/core/sub-controller/headless-sub-controller.ts
- packages/headless/src/controllers/commerce/product-listing/headless-product-listing.test.ts
- packages/headless/src/controllers/commerce/product-listing/headless-product-listing.ts
- packages/headless/src/controllers/commerce/recommendations/headless-recommendations.ts
- packages/headless/src/controllers/commerce/search/did-you-mean/headless-did-you-mean.test.ts
- packages/headless/src/controllers/commerce/search/did-you-mean/headless-did-you-mean.ts
- packages/headless/src/controllers/commerce/search/headless-search.test.ts
- packages/headless/src/controllers/commerce/search/headless-search.ts
Follow-up to https://github.com/coveo/ui-kit/pull/3859
I also:
- Added tests for sub-controllers
- Tested that listing & search controllers use sub-controllers
- Nested the `did-you-mean` folder for the controller under `search`
> feat(commerce): expose did you mean as sub-controller

- packages/atomic/src/components/common/generated-answer/generated-content/generated-markdown-content.pcss
In some cases, the bold text in rich generated answers could be too light or too heavy compared to other bold elements in the search interface.
This PR updates the styling of `strong` and `th` elements in generated rich answers to rely on the `--atomic-font-bold` variable and maintain a consistent look across the search interface.
[SVCC-3766]: https://coveord.atlassian.net/browse/SVCC-3766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(atomic): use variable to set font-weight of strong and th elements in generated rich answers

- packages/atomic/src/index.ts
- packages/atomic/src/utils/initialization-utils.tsx
Custom components were previously only possible with classic `Bindings` (ie: headless search engine). We need to make it possible with `CommerceBindings` (headless commerce engine)
Modify the exported function to instead expose the fact that it is generic under the hood.
Make it so that it defaults on `Bindings` (search engine use case) for backward compatibility.
https://coveord.atlassian.net/browse/KIT-3156
> fix(atomic): update initializeBindings utility function for commerce custom components

- packages/headless/src/app/commerce-engine/commerce-engine.ts
- packages/headless/src/app/state-key.ts
An improvement/iteration on #3890:
- Hide the state symbol from all methods relying on `[[OwnPropertyKeys]]` [^1]
- Do some error handling to help users if they're facing an error due to a double-load of Headless.
Further improvements to consider for 'next-gen' controller:
- Add safeguards for cross-contaminations on controller instantiation, see [POC](https://louis-bompart.github.io/automatic-eureka/) ([source](https://github.com/louis-bompart/automatic-eureka/tree/main))
[^1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy/ownKeys
> feat: improve state lock-out with reflection

- packages/headless/src/api/commerce/commerce-api-params.ts
- packages/headless/src/app/commerce-engine/commerce-engine-configuration.ts
- packages/headless/src/app/commerce-engine/commerce-engine.test.ts
- packages/headless/src/controllers/commerce/context/cart/headless-cart-selectors.test.ts
- packages/headless/src/controllers/commerce/context/cart/headless-cart-selectors.ts
- packages/headless/src/controllers/commerce/context/cart/headless-cart.test.ts
- packages/headless/src/controllers/commerce/context/cart/headless-cart.ts
- packages/headless/src/features/commerce/common/actions.test.ts
- packages/headless/src/features/commerce/common/actions.ts
- packages/headless/src/features/commerce/context/cart/cart-actions.ts
- packages/headless/src/features/commerce/context/cart/cart-selector.ts
- packages/headless/src/features/commerce/context/cart/cart-slice.test.ts
- packages/headless/src/features/commerce/context/cart/cart-slice.ts
- packages/headless/src/features/commerce/context/cart/cart-state.test.ts
- packages/headless/src/features/commerce/context/cart/cart-state.ts
- packages/headless/src/features/commerce/context/cart/cart-validation.ts
- packages/headless/src/features/commerce/query-suggest/query-suggest-actions.ts
- packages/headless/src/integration-tests/commerce.test.ts
The cart controller stored products according to `sku` value. Sku isn't returned from the Commerce API, nor is used by any Coveo systems. Consequently `sku` has been removed from the keys. This poses an additional problem now, in that the events should contain duplicate `productId` when a product is in the cart at different prices. To address this the cart stores products grouped by price, to cater to this use case.
Updates have been made to Commerce base request builder and QuerySuggest to return cart products with deduped productIds.
[CAPI-851]: https://coveord.atlassian.net/browse/CAPI-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(commerce): capi 851 commerce context cart should sent product id instead of SKU

- packages/headless/src/api/commerce/search/query-suggest/query-suggest-response.ts
- packages/headless/src/commerce.index.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-category-field-suggestions.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions-generator.test.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions.ts
- packages/headless/src/features/commerce/facets/field-suggestions-order/field-suggestions-order-slice.test.ts
- packages/headless/src/features/commerce/facets/field-suggestions-order/field-suggestions-order-state.ts
These properties (`displayName` and `field`) should make it easier to build a field suggestions component.
[CAPI-868]
[CAPI-868]: https://coveord.atlassian.net/browse/CAPI-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(commerce): expose additional field suggestions properties on state

- packages/headless/src/api/search/search-api-params.ts
- packages/headless/src/features/configuration/analytics-params.test.ts
- packages/headless/src/features/configuration/analytics-params.ts
- packages/headless/src/integration-tests/analytics-migration.test.ts
**Context**
The server event schema was recently tightened to require document referrer to be a url if specified. The schema definition is available [here](https://github.com/coveo-platform/analytics_schema/blob/master/schemas/common/types.json#L289).
Headless' behavior is to forward the originLevel3 value, which by default is set to the string `default`.
This causes all server events sent by headless to be marked as invalid.
**Approach**
When the `analyticsMode` is `next` and originLevel3 is `default`, headless will send `null` instead of `default`.
> fix(headless): send referrer as null when originLevel3 is default

- packages/atomic/cypress/e2e/generated-answer.cypress.ts
[SVCC-3781](https://coveord.atlassian.net/browse/SVCC-3781)
Flaky test in citation test suite:
The test `should display the citation card` is flaky due to the citation not available yet in the DOM.
The test `when a citation is right-clicked` is flaky due to the previous test click.
Before:
After:
[SVCC-3781]: https://coveord.atlassian.net/browse/SVCC-3781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(genqa): fix citation flaky test

- packages/headless/src/features/commerce/pagination/pagination-slice.test.ts
- packages/headless/src/features/commerce/pagination/pagination-slice.ts
- packages/headless/src/features/commerce/parameters/parameters-actions.ts
- packages/headless/src/features/commerce/parameters/parameters-selectors.ts
- packages/headless/src/features/commerce/parameters/parameters-serializer.test.ts
- packages/headless/src/features/commerce/parameters/parameters-serializer.ts
- packages/headless/src/features/commerce/sort/sort-slice.test.ts
- packages/headless/src/features/commerce/sort/sort-slice.ts
- packages/headless/src/features/search-parameters/search-parameter-serializer.ts
- packages/headless/src/state/commerce-app-state.ts
Add support for sort and pagination in the url and parameter managers.
I initially piggy-backed on the existing sort criterion serialization/deserialization logic, but writing our own leads to a simpler implementation.
To test, run `yarn link @coveo/headless` on https://github.com/coveo/barca-sports/pull/270.
🎩 
[CAPI-907]
[CAPI-907]: https://coveord.atlassian.net/browse/CAPI-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(commerce): handle sort and pagination in url and parameter managers

- packages/atomic/src/components/commerce/atomic-commerce-pager/atomic-commerce-pager.tsx
- packages/atomic/src/components/common/pager/pager-buttons.tsx
- packages/atomic/src/components/common/pager/pager-navigation.tsx
- packages/atomic/src/components/insight/atomic-insight-pager/atomic-insight-pager.tsx
- packages/atomic/src/components/search/atomic-pager/atomic-pager.tsx
This PR adds a label to the role="radiogroup" element inside PagerPageButtons. This label is required on elements with this role.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radiogroup_role#associated_wai-aria_roles_states_and_properties:~:text=aria%2Dlabelledby%20/,aria%2Dlabel.
https://coveord.atlassian.net/browse/KIT-3211
> fix(atomic): add label on atomic-pager radiogroup

- packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
This PR adds padding to the carousel to prevent the buttons from overlapping with the recommendations content.
https://coveord.atlassian.net/browse/KIT-3187
> fix(Commerce Atomic): prevent recs carousel buttons from overlapping with text

- .github/actions/commit-generated-files/action.yml
- .github/workflows/prbot.yml
This ensures that the CI does not skip generated files that are auto-commited.
See #4035 for demonstration
> chore: commit generated files w/ GitHub App

- packages/atomic/src/components/common/facets/facet-value-checkbox/facet-value-checkbox.pcss
This PR prevents the checkbox and label from facet values from overlapping when a font-size value lower than 100%/16px is set on the root html element
Before:
After:
https://coveord.atlassian.net/browse/KIT-3215
> fix(atomic): prevent facet value checkbox and label overlap

- packages/atomic/src/components/insight/atomic-insight-facet/atomic-insight-facet.tsx
- packages/atomic/src/components/insight/atomic-insight-numeric-facet/atomic-insight-numeric-facet.tsx
- packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx
- packages/atomic/src/components/search/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
https://coveord.atlassian.net/browse/KIT-3242
The regression was introduced in https://github.com/coveo/ui-kit/pull/3850.
`atomic-insight-timeframe-facet` and  `atomic-timeframe-facet` were not affected because they use the `timeframeFacetCommon`'s `disconnectedCallback` which has a guard to return when `this.props.host.isConnected` is `true`
Similarly, `atomic-color-facet`, `atomic-category-facet`, `atomic-rating-facet`, and `atomic-rating-range-facet` were not affected by the refactoring because they didn't rely on the `facetCommon`'s `disconnectedCallback` in the first place, and their respective `disconnectedCallback` methods already had a proper guard clause in place.
> fix(atomic) Fix dependent facet regression

- packages/atomic/src/components/commerce/product-template-components/atomic-product-field-condition/atomic-product-field-condition.tsx
The `atomic-product-field-condition` component has been moved to the `product-template-components` directory to better organize the commerce-related components.
> refactor(commerce): move atomic-product-field-condition to new directory

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.tsx
- packages/atomic/src/pages/examples/commerce-website/engine.mjs
- packages/headless/src/app/commerce-engine/commerce-engine-configuration.ts
- packages/headless/src/app/commerce-engine/commerce-engine.test.ts
- packages/headless/src/app/commerce-engine/commerce-engine.ts
- packages/samples/atomic-react/src/pages/CommerceSearchPage.tsx
https://coveord.atlassian.net/browse/KIT-3042
> feat(headless): enforce organization endpoints usage for headless commerce

- packages/atomic/src/components/commerce/product-template-components/atomic-product-price/atomic-product-price.tsx
JIRA ticket describes the problem pretty well.
Truncate  + no word break on very small screen: 
https://coveord.atlassian.net/browse/KIT-3232
> fix(atomic): no break word for product-price + truncate/wrap

- packages/headless/src/features/commerce/pagination/pagination-slice.test.ts
- packages/headless/src/features/commerce/pagination/pagination-slice.ts
- packages/headless/src/features/commerce/search/search-actions.ts
Pagination wasn't being reset because `deselectAllBreadcrumbs` wasn't handled in the pagination slice. Now it is, so it properly resets the pagination before executing the search.
[CAPI-1023]
[CAPI-1023]: https://coveord.atlassian.net/browse/CAPI-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(commerce): reset pagination on search box submit

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/facets/atomic-commerce-category-facet/atomic-commerce-category-facet.tsx
- packages/atomic/src/components/commerce/facets/atomic-commerce-facet/atomic-commerce-facet.tsx
- packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
- packages/atomic/src/components/commerce/facets/atomic-commerce-timeframe-facet/atomic-commerce-timeframe-facet.tsx
`atomic-commerce-facets` sets the `isCollapsed` prop in its `render()` function: However they were not configured as property correctly on each component, just an internal state variable. So nothing was happening.
https://coveord.atlassian.net/browse/KIT-3300
> fix(atomic): fix collapse-facets-after support for atomic-commerce-facets

- packages/headless/doc-parser/use-cases/commerce.ts
- packages/headless/src/commerce.index.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions-generator.ts
- packages/headless/src/controllers/commerce/recent-queries-list/headless-recent-queries-list.ts
- packages/headless/src/controllers/commerce/standalone-search-box/headless-standalone-search-box.ts
- packages/headless/src/features/commerce/product-templates/product-templates-manager.ts
We already generate [hidden docs](https://docs.coveo.com/en/headless/latest/reference/commerce) for several headless commerce controllers and actions, this PR covers more controllers.
https://coveord.atlassian.net/browse/KIT-3304
> docs(headless): generate documentation for new headless commerce controllers

- packages/headless/src/api/commerce/commerce-api-client.test.ts
- packages/headless/src/api/commerce/commerce-api-client.ts
- packages/headless/src/api/commerce/commerce-api-params.ts
- packages/headless/src/api/commerce/commerce-metadata.ts
- packages/headless/src/api/commerce/common/request.ts
- packages/headless/src/api/commerce/recommendations/recommendations-request.ts
- packages/headless/src/api/preprocess-request.ts
- packages/headless/src/features/commerce/common/actions.test.ts
- packages/headless/src/features/commerce/common/actions.ts
- packages/headless/src/features/commerce/query-suggest/query-suggest-actions.ts
I also made it so the `requestMetadata` is populated on commerce api requests in https://github.com/coveo/ui-kit/commit/dd3b3698ef001883db7344fbdea4c7c0bd063150#. This enables hooking into requests with `preprocessRequest` on a commerce api `method`, instead of matching on an url path.
[CAPI-1053]
[CAPI-1053]: https://coveord.atlassian.net/browse/CAPI-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(commerce): forward analytics source on `context.source`

- packages/atomic/src/components/common/generated-answer/styles/generated-answer.pcss
https://coveord.atlassian.net/browse/KIT-3313
Right now, the linear-gradient is hardcoded to white rather than to the background atomic colour. This will create issues when clients modify their background colour to something other than white, like we doc on the docs site when in dark mode.
It doesn't seem possible for clients to change the linear-gradient. Probably because it requires targeting a pseudo-element of a part with a certain class. So, in this PR, I use the atomic-background colour instead.
> fix(atomic): collapsed answer gradient colour

- packages/headless/src/controllers/insight/pager/headless-insight-pager.ts
- packages/headless/src/controllers/insight/results-per-page/headless-insight-results-per-page.ts
- packages/headless/src/controllers/pager/headless-pager.ts
- packages/headless/src/features/analytics/legacy-search-action-cause.ts
- packages/headless/src/features/analytics/search-action-cause.ts
- packages/headless/src/features/insight-search/insight-search-actions.ts
- packages/headless/src/features/insight-search/insight-search-analytics-actions.ts
- packages/headless/src/features/pagination/pagination-analytics-actions.ts
- packages/headless/src/features/pagination/pagination-insight-analytics-actions.ts
- packages/headless/src/features/search/search-actions.ts
- packages/headless/src/integration-tests/analytics-migration.test.ts
- packages/headless/src/integration-tests/insight-analytics-migration.test.ts
The search action cause `pagerScrolling` has been updated to `browseResults` in the `insight-search` and `pagination` features. This change ensures consistent logging of user navigation actions.
https://coveord.atlassian.net/browse/KIT-2983
> feat: update search action cause to browseResults in insight-search and pagination

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.tsx
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-interface/atomic-commerce-recommendation-interface.tsx
- packages/atomic/src/components/common/interface/interface-common.tsx
* Remove the default `@Prop` value for `language` in `atomic-commerce-interface` and `atomic-commerce-recommendation-interface`. Instead fallback on the value set in commerce engine.
* Modify `CommonAtomicInterfaceHelper` so that `language` is an optional property, and add the fallback to `en` there instead (ie: limit the amount of code changes for other types of interfaces that are not commerce). 
https://coveord.atlassian.net/browse/KIT-3318
> fix(atomic): fallback language to commerce engine value instead of always defaulting to english

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/product-template-components/atomic-product-price/atomic-product-price.tsx
- packages/samples/atomic-react/src/pages/CommerceSearchPage.tsx
Remove `currency` as a property from `atomic-product-price`, as it it mandatory to configure it from Headless, and it should be the source of truth in all scenarios.
https://coveord.atlassian.net/browse/KIT-3317
> fix(atomic): use currency from context instead of prop for atomic-product-price

- packages/headless/src/features/commerce/common/actions.test.ts
- packages/headless/src/features/commerce/common/actions.ts
- packages/headless/src/features/commerce/facets/facet-search-set/category/commerce-category-facet-search-request-builder.test.ts
- packages/headless/src/features/commerce/facets/facet-search-set/category/commerce-category-facet-search-request-builder.ts
- packages/headless/src/features/commerce/facets/facet-search-set/commerce-facet-search-actions.ts
- packages/headless/src/features/commerce/facets/facet-search-set/regular/commerce-regular-facet-search-request-builder.test.ts
- packages/headless/src/features/commerce/facets/facet-search-set/regular/commerce-regular-facet-search-request-builder.ts
- packages/headless/src/features/commerce/product-listing/product-listing-actions.ts
- packages/headless/src/features/commerce/query-suggest/query-suggest-actions.ts
- packages/headless/src/features/commerce/recommendations/recommendations-actions.ts
- packages/headless/src/features/commerce/search/search-actions-thunk-processor.test.ts
- packages/headless/src/features/commerce/search/search-actions-thunk-processor.ts
- packages/headless/src/features/commerce/search/search-actions.ts
- packages/headless/src/features/commerce/standalone-search-box-set/standalone-search-box-set-actions.ts
https://coveord.atlassian.net/browse/KIT-3335
> feat(headless commerce): retrieve clientId from Relay instead of coveoua when building commerce API requests

- .github/workflows/release.yml
Quantic release create a discussion, but needs the right perm for it
> chore: +w discussions GH_TOKEN permissions

- packages/atomic/src/components/commerce/atomic-commerce-interface/store.ts
- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-interface/store.ts
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.tsx
- packages/atomic/src/components/commerce/product-template-components/atomic-product-children/atomic-product-children.tsx
- packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.tsx
- packages/headless/src/controllers/commerce/instant-products/headless-instant-products.test.ts
- packages/headless/src/controllers/commerce/instant-products/headless-instant-products.ts
- packages/headless/src/controllers/commerce/product-listing/headless-product-listing.test.ts
- packages/headless/src/controllers/commerce/product-listing/headless-product-listing.ts
- packages/headless/src/controllers/commerce/recommendations/headless-recommendations.test.ts
- packages/headless/src/controllers/commerce/recommendations/headless-recommendations.ts
- packages/headless/src/controllers/commerce/search/headless-search.test.ts
- packages/headless/src/controllers/commerce/search/headless-search.ts
- packages/headless/src/features/commerce/instant-products/instant-products-actions.ts
- packages/headless/src/features/commerce/instant-products/instant-products-slice.test.ts
- packages/headless/src/features/commerce/instant-products/instant-products-slice.ts
- packages/headless/src/features/commerce/product-listing/product-listing-actions.ts
- packages/headless/src/features/commerce/product-listing/product-listing-slice.test.ts
- packages/headless/src/features/commerce/product-listing/product-listing-slice.ts
- packages/headless/src/features/commerce/recommendations/recommendations-actions.ts
- packages/headless/src/features/commerce/recommendations/recommendations-slice.test.ts
- packages/headless/src/features/commerce/recommendations/recommendations-slice.ts
- packages/headless/src/features/commerce/search/search-actions.ts
- packages/headless/src/features/commerce/search/search-slice.test.ts
- packages/headless/src/features/commerce/search/search-slice.ts
Instead of mutating the received products from the API, I propose we dynamically find the corresponding parent and children in the reducer. This _seems_ less error-prone to me, because we don't need to mutate products in every place we fulfill a request containing `products`, at the cost of being less performant, as we iterate on every product every time a children is promoted. Thoughts?
An other option to consider would be to mutate the products directly in the commerce api client.
https://coveord.atlassian.net/browse/KIT-3221
> fix(commerce): expose child product directly on `promoteChildToParent`

- packages/headless/src/api/knowledge/answer-slice.ts
- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/features/configuration/configuration-state.ts
- packages/headless/src/features/pipeline/select-pipeline.ts
- packages/headless/src/features/query/query-selectors.ts
- packages/headless/src/features/search-hub/search-hub-selectors.ts
This update introduces a client to manage the new AnswerApi stream, serving RGA model answers. The client leverages [Redux Toolkit Query](https://redux-toolkit.js.org/rtk-query/overview).
`baseKnowledgeAPISlice.ts`
This file contains the baseQuery, which can be used for simple API implementations, and the main slice definition, which can be used to create the Redux entry in the state.
`answerApiSlice.ts`
This file defines the endpoint that will manage the streaming, completing the Redux API slice.
While the `dynamicBaseQuery` pattern sets up a basic structure for adding new knowledge endpoints in the future, the code-splitting pattern is useful for maintaining a separation of concerns between generic code and endpoint-specific code.
This feature creates an entry in the state, forming the …
> feat(knowledgeAPI): api slice

- package.json
- scripts/esbuild/build.mjs
This PR prevents esbuild from stopping when in watch mode. This was preventing Hot Module Replacement from triggering when making changes in headless while using atomic in dev mode. 
https://coveord.atlassian.net/browse/KIT-3359
> chore:  do not dispose esbuild context in watch mode

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/facets/atomic-commerce-category-facet/atomic-commerce-category-facet.tsx
- packages/atomic/src/components/commerce/facets/atomic-commerce-facet/atomic-commerce-facet.tsx
This was reported in our internal slack channel about support for atomic-commerce with PS.
They need access to these properties to power an advance customization
https://coveord.atlassian.net/browse/KIT-3373
> docs(atomic): remove internal flag for atomic-commerce-facet

- packages/headless/src/app/engine.ts
https://coveord.atlassian.net/browse/KIT-3374
> fix(headless): defensive code against clientID access from relay

- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/app/engine.ts
- packages/headless/src/controllers/core/generated-answer/headless-core-generated-answer.ts
- packages/headless/src/features/generated-answer/generated-answer-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-selectors.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.ts
- packages/headless/src/features/generated-answer/generated-answer-state.ts
Updates to the Answer Api client to make sure the error handling is proper. Some little extras needed for it to work proper that will make the subsequent review a bit easier.
The Answer Api is almost just a proxy for the stream coming from reveal. And for some technical reasons, the call to the answer api will return an error message but will not return downright error status codes like 400s when the stream fails.
That said, we can rely on the stream end message in case the stream is not working properly, and since its better to give the user or the devs all the information we can, this increment makes sure that the error will appear in the logs and in the state in case we want to leverage the error message in the front end component.
> feat(answer): error handling

- package-lock.json
- packages/headless/package.json
- packages/headless/src/api/analytics/analytics-relay-client.test.ts
- packages/headless/src/features/analytics/analytics-utils.test.ts
- packages/headless/src/features/attached-results/attached-results-analytics-actions.test.ts
- packages/headless/src/features/case-assist/case-assist-analytics-actions.test.ts
- packages/headless/src/features/generated-answer/generated-answer-analytics-actions.test.ts
- packages/headless/src/features/generated-answer/generated-answer-insight-analytics-actions.test.ts
- packages/headless/src/features/insight-search/insight-analytics-actions.test.ts
- packages/headless/src/features/instant-results/instant-result-analytics-actions.test.ts
- packages/headless/src/features/question-answering/question-answering-analytics-actions.test.ts
- packages/headless/src/features/question-answering/question-answering-insight-analytics-actions.test.ts
- packages/headless/src/features/recommendation/recommendation-analytics-actions.test.ts
- packages/headless/src/features/result-actions/result-actions-insight-analytics-actions.test.ts
- packages/headless/src/features/result-preview/result-preview-analytics-actions.test.ts
- packages/headless/src/features/result-preview/result-preview-insight-analytics-actions.test.ts
- packages/headless/src/features/result/result-analytics-actions.test.ts
- packages/headless/src/features/result/result-insight-analytics-actions.test.ts
- packages/headless/src/test/mock-engine-v2.ts
Includes changes about defensive access to local storage.
`clearStorage()` was also removed from relay interface in `0.7.9`
https://coveord.atlassian.net/browse/KIT-3374
> fix(headless): bump relay version

- packages/headless/src/controllers/commerce/core/facets/generator/headless-commerce-facet-generator.test.ts
- packages/headless/src/controllers/commerce/core/facets/generator/headless-commerce-facet-generator.ts
- packages/headless/src/controllers/commerce/core/sub-controller/headless-sub-controller.ts
- packages/headless/src/controllers/facets/automatic-facet-generator/headless-automatic-facet-generator.test.ts
- packages/headless/src/controllers/facets/automatic-facet-generator/headless-automatic-facet-generator.ts
This PR exposes the `deselectAll` method on the commerce facet generator controller.
It also removes the method from automatic facet generator added in #4067
https://coveord.atlassian.net/browse/KIT-3358
> feat(headless commerce): expose deselectAll method on facet generator controller

- packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.test.ts
- packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.ts
https://coveord.atlassian.net/browse/KIT-3385
> fix(headless commerce): correctly determine hasBreadcrumbs value for category facets

- .devcontainer/devcontainer.json
Instead, rebuild when changes are made in master.
Codespaces should be ready to use in less than 5' with that.
> chore: do not rebuild everytime the container starts

- packages/atomic/src/components/common/interface/analytics-config.ts
- packages/headless/src/api/analytics/analytics-selectors.test.ts
- packages/headless/src/api/analytics/analytics-selectors.ts
- packages/headless/src/features/commerce/common/actions.test.ts
Also, append instead of prepend Headless version to replace Headless-Atomic-Relay order by Atomic-Headless-Relay
https://coveord.atlassian.net/browse/KIT-3308
> fix: add atomic version in the analytics initial config for Headless

- packages/headless/src/features/facets/automatic-facet-set/automatic-facet-set-slice.test.ts
- packages/headless/src/features/facets/automatic-facet-set/automatic-facet-set-slice.ts
https://coveord.atlassian.net/browse/KIT-3417
Before:
After:
> fix(headless): ensure facet value from URL are always considered for auto-facets

- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/templates/expandableSearchBoxInput.css
- Min width removed from the styling of the search box input to avoid the following issue:
[SFINT-5595]: https://coveord.atlassian.net/browse/SFINT-5595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): styling of the search box input adjusted

- packages/headless/src/controllers/core/facets/range-facet/date-facet/date-range.ts
- packages/headless/src/features/facets/range-facets/date-facet-set/interfaces/request.ts
https://coveord.atlassian.net/browse/KIT-3416
> docs(headless): link fix

- packages/atomic/src/components/commerce/atomic-commerce-query-summary/e2e/page-object.ts
https://coveord.atlassian.net/browse/KIT-3369
fixes this strict selector error : 
Retry #1 ───────────────────────────────────────────────────────────────────────────────────────
Error: expect.toBeVisible: Error: strict mode violation: getByText(/^Product 1 of 1 for kayak$/) resolved to 2 elements:
1) <div role="status" aria-live="polite" id="aria-live-eypty-query-summary">Product 1 of 1 for kayak</div> aka locator('#aria-live-eypty-query-summary')
2) <div part="container" class="text-on-background">…</div> aka locator('#code-root').getByText('Product 1 of 1 for kayak')
> test(commerce): fix flaky commerce query summary tests

- packages/headless/src/api/knowledge/answer-slice.ts
- packages/headless/src/api/knowledge/post-answer-evaluation.ts
- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.test.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
[simplescreenrecorder-2024-07-30_16.55.09.webm](https://github.com/user-attachments/assets/79153f5a-19e6-42ec-8a3b-1c3921783e81)
This PR make it so we can send CRGA evaluations from the feedback modal to the AnswerApi
- The endpoint that we can POST evaluations to has been added
- The Steam answer client will get the header of the stream response and set the Answer ID in its state
- The Controller now overrides the `SendFeedback` method in order to POST the feedback to the answer api
A RTK query Endpoint have been added to the Answer slice
A little modification to the dynamicBaseQuery was beneficial to make the endpoint definition simpler.
We use the `x-answer-id` from the stream call to identify the feedback when we send it to the evaluation endpoint.
The native `sendFeedback` method …
> feat(answerApi): evaluations

- packages/atomic/src/components/common/facets/facet-date-input/facet-date-input.tsx
- packages/atomic/src/components/search/facets/atomic-timeframe-facet/atomic-timeframe-facet.new.stories.tsx
- packages/atomic/src/components/search/facets/atomic-timeframe-facet/e2e/atomic-timeframe-facet.e2e.ts
- packages/atomic/src/components/search/facets/atomic-timeframe-facet/e2e/fixture.ts
- packages/atomic/src/components/search/facets/atomic-timeframe-facet/e2e/page-object.ts
This PR ensures that the min/max attributes of the `atomic-timeframe-facet` date input get reset correctly when clearing the filters.
https://coveord.atlassian.net/browse/KIT-3448
> fix(atomic): clear min/max for atomic-timeframe-facet when clearing filters

- packages/headless/src/app/commerce-engine/commerce-engine.ts
- packages/headless/src/commerce.index.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-category-field-suggestions.test.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-category-field-suggestions.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions-generator.test.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions-generator.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions.test.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions.ts
- packages/headless/src/integration-tests/commerce.test.ts
Field suggestion values weren't updating when the query changed. To fix this, we fetch the facet search state using a selector, just like we do for facets (thanks @fbeaudoincoveo!).
I've also fixed a few other things:
- Load the proper reducers in field suggestions controllers
- Add the reducer to the commerce engine
- Type the reducer loaders
- Replace the `Subscribable` type to `Controller` on field suggestions controllers
- Adjusted the field suggestions integration test to rely on controllers instead of engine state updates. This was actually a clue that the current behavior was broken, as it was not possible to await state changes on the field suggestions controllers 😅 
[CAPI-1201]
[CAPI-1201]: https://coveord.atlassian.net/browse/CAPI-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
> fix(commerce): fix field suggestions state update

- packages/headless/src/controllers/commerce/field-suggestions/headless-category-field-suggestions.test.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-category-field-suggestions.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions-generator.test.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions.test.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions.ts
- packages/headless/src/features/commerce/facets/facet-search-set/category/commerce-category-facet-search-request-builder.test.ts
- packages/headless/src/features/commerce/facets/facet-search-set/category/commerce-category-facet-search-request-builder.ts
- packages/headless/src/features/commerce/facets/facet-search-set/commerce-facet-search-actions.ts
- packages/headless/src/features/commerce/facets/facet-search-set/regular/commerce-regular-facet-search-request-builder.ts
- packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.test.ts
- packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.ts
- packages/headless/src/features/facets/facet-search-set/category/category-facet-search-set-slice.ts
- packages/headless/src/features/facets/facet-search-set/facet-search-reducer-helpers.ts
- packages/headless/src/features/facets/facet-search-set/specific/specific-facet-search-set-slice.ts
Since facets in a global search configuration are used to power both field suggestions and facets, it's possible that field suggestions for a field be active at the same time that a facet search for the same field is. This means that updating the text on a field suggestions controller would cause a facet's facet search values to be updated as well. This is because both the field suggestions and facet search were powered by the same state.
To prevent this issue, I namespace the `facetId` used for field suggestions **only** on the facet search reducers (the regular, and category one).
I opted for this approach instead of reversing the dependency on the facet search controller to read state from selectors since it would've lead to much more changes in the controllers.
[CAPI-1201] …
> fix(commerce): namespace field suggestions to prevent clash with facet search

- packages/atomic-angular/project.json
This PR adds the release:phase1 target to the atomic-angular package. This should ensure that the package gets updated.
https://coveord.atlassian.net/browse/CDX-1585
> chore(ci): fix release for atomic-angular

- packages/atomic/src/components/commerce/product-template-components/atomic-product-link/atomic-product-link.tsx
- packages/atomic/src/components/commerce/product-template-components/product-utils.ts
- packages/atomic/src/utils/result-utils.ts
This PR ensures that atomic-product-link uses the value of hrefTemplate to generate the href attribute value.
https://coveord.atlassian.net/browse/KIT-3455
> fix(atomic): use the hrefTemplate value in atomic-product-link

- packages/headless/src/features/generated-answer/generated-answer-slice.test.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.ts
- packages/quantic/cypress/e2e/default-2/generatedAnswer/generated-answer.cypress.ts
[SVCC-4029](https://coveord.atlassian.net/browse/SVCC-4029)
- Filter citations that points to same documents.
Before:
After:
[SVCC-4029]: https://coveord.atlassian.net/browse/SVCC-4029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(genqa): filter citations that points to same document

- packages/headless/src/api/knowledge/stream-answer-api.ts
[SVCC-4057](https://coveord.atlassian.net/browse/SVCC-4057)
The end of stream was no handled after a 'sorry' message.
The `answerGenerated` is false with the 'sorry' message, and this was the condition to handle the end of stream.
The effect of this bug was that the cursor was not removed when the answer was 'sorry'.  Plus, the buttons to rephrase weren't showing.  Removing the possibility to rephrase.
We now check if there is an answer that was outputed beside the official `answerGenerated`.
We now send the `contentFormat` in the payload, like we do with the SearchApi
[SVCC-4057]: https://coveord.atlassian.net/browse/SVCC-4057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(answerStream): handle end of stream

- packages/quantic/force-app/main/default/lwc/quanticFacet/quanticFacet.html
- Fixed issue with the `more matches found` label in the Quantic Facet component.
[SFINT-5636]: https://coveord.atlassian.net/browse/SFINT-5636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): styling issue fixed with quantic facet search component

- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
[SVCC-4040](https://coveord.atlassian.net/browse/SVCC-4040)
**Problems:**
1. states of the answer aren't reset after a new request: when you click on like/dislike/expand for example, the new query doesn't reset the state, we still can see the button liked or disliked clicked for example from the previous query.
2. When you submit a feedback, and re-click on likes/disliked, the feedback modal still shows even if the feedback was successfully submitted.
**Solutions:**
1. Reset the state when we perform a new query.
2. update `feedbackSumbitted` state when calling `sendFeedback` in the new pattern.
**DEMO:**
https://github.com/user-attachments/assets/3377b367-5985-4045-8ad6-e072f81c9645
[SVCC-4040]: https://coveord.atlassian.net/browse/SVCC-4040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
> fix(headless): fix answer state using the new pattern

- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/__tests__/quanticSearchBoxInput.test.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/quanticSearchBoxInput.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/templates/defaultSearchBoxInput.html
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/templates/expandableSearchBoxInput.html
The issue: 
- On blur and without submitting,  the value of the suggestion or the recent query was not persisted as the value of the search box input.
- On pressing the `Escape` key, the input content was automatically deleted.
https://github.com/user-attachments/assets/8f55f144-f445-4d6b-9d65-418d4ca6ef48
The solution:
- Updated the logic that handles the value of the input to allow persisting the values of the suggestions/recent queries before submitting them.
- prevented the default behaviour of the input on Escape key click.
- unit tests added.
https://github.com/user-attachments/assets/cb0ebc17-d34f-407e-b091-3f3571bb38a4
[SFINT-5665]: https://coveord.atlassian.net/browse/SFINT-5665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): fix issue with persisting search box suggestion value on blur

- packages/quantic/cypress/e2e/default-2/generatedAnswer/generated-answer-expectations.ts
- packages/quantic/cypress/e2e/default-2/generatedAnswer/generated-answer-selectors.ts
- packages/quantic/cypress/e2e/default-2/generatedAnswer/generated-answer.cypress.ts
- packages/quantic/force-app/examples/main/lwc/exampleQuanticGeneratedAnswer/exampleQuanticGeneratedAnswer.html
- packages/quantic/force-app/examples/main/lwc/exampleQuanticGeneratedAnswer/exampleQuanticGeneratedAnswer.js
- packages/quantic/force-app/main/default/lwc/quanticCitation/__tests__/quanticCitation.test.js
- packages/quantic/force-app/main/default/lwc/quanticCitation/quanticCitation.css
- packages/quantic/force-app/main/default/lwc/quanticCitation/quanticCitation.html
- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswer/quanticGeneratedAnswer.js
- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswer/templates/generatedAnswer.html
- packages/quantic/project.json
1. SFINT-5661: Add an option (default false), to show the rephrase buttons
- We want to ultimately completely remove the rephrase buttons (with V3), but meanwhile we will simply hide them by default, customers can still bring them back with an option for now.
- But the data proves very low usage, and most of the usage is to "try" and get an answer when there were no answer generated in the first place.
- The display format will be markdown for everyone as it provides the best format of answer anyway.
2. SFINT-5660: Remove the numbers next to the citations in the RGA component. (They were judged not useful by product).
I also re-organized a little bit the e2e tests for the quanticGeneratedAnswer component.
The new logic is basically this:
1. When no streamID is returned
2. When a streamID …
> feat(quantic): Add option for rephrase buttons, remove citations numbers

- packages/headless/src/features/generated-answer/generated-answer-slice.test.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.ts
Fixing a regression when resetting the answer in the new answerAPI flow. 
When we need to reset a RGA answer
e.g. right after a new query has been submitted
The `answerConfigurationId` must be kept in the state whenever the answer API flow is used.
We pass the actual state answerConfigurationID to the new state created by the reset action.
> fix(rga): state reset keep configid

- packages/atomic/src/components/commerce/product-template-components/atomic-product-image/e2e/atomic-product-image.e2e.ts
- packages/atomic/src/components/commerce/product-template-components/atomic-product-image/e2e/fixture.ts
- packages/atomic/src/components/commerce/product-template-components/atomic-product-image/e2e/page-object.ts
- packages/atomic/src/components/common/image-carousel/image-carousel.tsx
When you click on an element within another, you are clicking both.
This is why you must 'stop' the event propagation at the target in this situation. (otherwise, if the parent & the child elements have listeners, both will be triggered)
https://coveord.atlassian.net/browse/KIT-3477
> fix(atomic): prevent item click when carousel buttons are clicked

- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.tsx
- packages/atomic/src/components/commerce/atomic-commerce-search-box/e2e/atomic-commerce-search-box.e2e.ts
- packages/atomic/src/components/commerce/atomic-commerce-search-box/e2e/page-object.ts
- packages/atomic/src/components/commerce/product-template/atomic-product-template.new.stories.tsx
- packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.tsx
- packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-query-suggestions/atomic-commerce-search-box-query-suggestions.tsx
- packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-recent-queries/atomic-commerce-search-box-recent-queries.tsx
- packages/atomic/src/components/common/suggestions/suggestions-common.ts
- packages/atomic/src/components/search/atomic-search-box/atomic-search-box.new.stories.tsx
- packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
- packages/atomic/src/components/search/atomic-search-box/e2e/atomic-search-box.e2e.ts
- packages/atomic/src/components/search/atomic-search-box/e2e/page-object.ts
- packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.tsx
- packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-query-suggestions/atomic-search-box-query-suggestions.tsx
- packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.tsx
- packages/atomic/storybookUtils/search/search-interface-wrapper.tsx
- packages/headless/src/controllers/commerce/standalone-search-box/headless-standalone-search-box-options.ts
- packages/headless/src/controllers/commerce/standalone-search-box/headless-standalone-search-box.test.ts
- packages/headless/src/controllers/commerce/standalone-search-box/headless-standalone-search-box.ts
- packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box-options.ts
- packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.test.ts
- packages/headless/src/controllers/standalone-search-box/headless-standalone-search-box.ts
- packages/headless/src/features/commerce/standalone-search-box-set/standalone-search-box-set-actions-loader.ts
- packages/headless/src/features/commerce/standalone-search-box-set/standalone-search-box-set-actions.ts
- packages/headless/src/features/commerce/standalone-search-box-set/standalone-search-box-set-slice.test.ts
- packages/headless/src/features/commerce/standalone-search-box-set/standalone-search-box-set-slice.ts
- packages/headless/src/features/standalone-search-box-set/standalone-search-box-set-actions-loader.ts
- packages/headless/src/features/standalone-search-box-set/standalone-search-box-set-actions.ts
- packages/headless/src/features/standalone-search-box-set/standalone-search-box-set-slice.test.ts
- packages/headless/src/features/standalone-search-box-set/standalone-search-box-set-slice.ts
When updating the `redirection-url`, references to the 'old' controller persisted and broke the suggestions.
To alleviate this issue:
0. Ensure SB ID unicity per component
1. Allow SSB controllers to receive an update to their redirection URL.
2. Clean-up then rebuild controllers when the redirection-url attribute is updated. When rebuilding a SSB controller, allow the state associated to the ID to be overwritten.
3. Use 'getter-like' functions instead of direct reference for the controller in the suggestion-manager.
KIT-3471
> fix(atomic): search-box suggestions should be resilient to search-box redirection-url changes

- packages/atomic/cypress/e2e/breadbox.cypress.ts
- packages/atomic/src/components/search/atomic-refine-modal/atomic-refine-modal.tsx
- packages/atomic/src/components/search/facets/atomic-category-facet/atomic-category-facet.tsx
- packages/atomic/src/components/search/facets/atomic-color-facet/atomic-color-facet.tsx
- packages/atomic/src/components/search/facets/atomic-facet/atomic-facet.tsx
- packages/atomic/src/components/search/facets/atomic-numeric-facet/atomic-numeric-facet.tsx
- packages/atomic/src/components/search/facets/atomic-rating-facet/atomic-rating-facet.tsx
- packages/atomic/src/components/search/facets/atomic-rating-range-facet/atomic-rating-range-facet.tsx
- packages/atomic/src/components/search/facets/atomic-segmented-facet/atomic-segmented-facet.tsx
- packages/atomic/src/components/search/facets/atomic-timeframe-facet/atomic-timeframe-facet.tsx
- packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.new.stories.tsx
- packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/atomic-tab-manager.e2e.ts
- packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/page-object.ts
This PR ensures that the facets in the refine modal are shown/hidden based on which tab is open. Prior to this fix, the refine modal would show the facets of the previous active tab, not the current one.
https://coveord.atlassian.net/browse/CDX-1586
> fix(atomic): Facets don't update correctly in the refine modal when changing tabs

- .github/workflows/release.yml
- utils/release/git-publish-all.mjs
Akin to #4319 , but for the mainline: We now use the release/v3 branch as the tag for "where's the latest v3"
https://coveord.atlassian.net/browse/KIT-3497
> ci: replace release/v2 by release/v3

- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
- packages/atomic/src/components/common/template-provider/template-provider.ts
- packages/atomic/src/components/search/atomic-result/e2e/page-object.ts
- packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.new.stories.tsx
- packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.tsx
- packages/atomic/src/components/search/result-lists/atomic-result-list/e2e/atomic-result-list.e2e.ts
- packages/atomic/src/components/search/result-lists/atomic-result-list/e2e/fixture.ts
- packages/atomic/src/components/search/result-lists/atomic-result-list/e2e/page-object.ts
Current behaviour: All `atomic-result/product` are clickable and default to a 'default' atomic-result/product-link.
Expected behaviour: That should have been the case only with the grid layout.
KIT-3508
Backport of #4355
> fix(atomic): do not add click outside of grid layout

- packages/quantic/force-app/main/default/labels/CustomLabels.labels-meta.xml
- packages/quantic/force-app/main/default/lwc/quanticResultLink/quanticResultLink.js
- packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/quanticSearchBoxInput.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxSuggestionsList/quanticSearchBoxSuggestionsList.js
- packages/quantic/force-app/main/translations/fr.translation-meta.xml
[SFINT-4696](https://coveord.atlassian.net/browse/SFINT-4696)
- [SFINT-4696](https://coveord.atlassian.net/browse/SFINT-4696): 
Removed unused `useCase` property from the `QuanticResultQuickview` and the `QuanticResultLink` components. 
- [SFINT-5319](https://coveord.atlassian.net/browse/SFINT-5319) : Removed unused custom label `quantic_OpensInSalesforceSubTab`.
- [SFINT-5646](https://coveord.atlassian.net/browse/SFINT-5646) : Removed unused exposed method of the Quantic Search Box input: `resetSelection` and `blur` cause they are no longer useful.
[SFINT-4696]: https://coveord.atlassian.net/browse/SFINT-4696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SFINT-4696]: https://coveord.atlassian.net/browse/SFINT-4696?atlOrigin=eyJpIjoiNWRkNTljN …
> fix(quantic)!: deleted unnecessary properties, methods and labels

- packages/headless/src/features/insight-search/insight-analytics-actions.test.ts
- packages/headless/src/features/insight-search/insight-analytics-actions.ts
[SFINT-5419](https://coveord.atlassian.net/browse/SFINT-5419)
- removed unused parameters from the `logExpandToFullUI` action, `caseId` and `caseNumber` are grabbed from the state instead of from the passed parameters.
[SFINT-5419]: https://coveord.atlassian.net/browse/SFINT-5419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(headless)!: removed unused parameters from logExpandToFullUI action

- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tsx
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
- packages/atomic/src/components/common/item-list/display-grid.tsx
- packages/atomic/src/components/ipx/atomic-ipx-recs-list/atomic-recs-list/atomic-ipx-recs-list.tsx
- packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx
- packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.tsx
`DisplayGrid` is a "generic" file, used by different use cases. However, it hardcoded `atomic-result` as a selector, which is specific to the search use case.
https://coveord.atlassian.net/browse/KIT-3513
> fix(atomic): fix atomic-commerce product card click invalid selector

- packages/atomic/src/components/commerce/facets/atomic-commerce-category-facet/atomic-commerce-category-facet.tsx
- packages/atomic/src/components/commerce/facets/atomic-commerce-facet/atomic-commerce-facet.tsx
- packages/atomic/src/components/commerce/facets/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tsx
- packages/atomic/src/components/commerce/facets/atomic-commerce-timeframe-facet/atomic-commerce-timeframe-facet.tsx
In commerce facets, we were missing defensive code around unsubscribe/resubscribe VS connectedCallback/disconnectedCallback (ie: stencil lifecycle when a facet gets moved around in the DOM).
End result is that we end up with a facet that is no longer subscribed to controller state changes for re-render.
Technically could have done it with "unsubscribe only if the host is also disconnected" kinda logic, but this should do just as well.
https://coveord.atlassian.net/browse/KIT-3517
> fix(atomic): fix commerce facets being re-attached to the DOM

- package-lock.json
- utils/release/bump-package.mjs
- utils/release/package.json
https://coveord.atlassian.net/browse/KIT-3522
Tested manually:
- `npm run nx:graph`
- `npm run publish:bump` -> See that v3 exists where it should
- `IS_PRERELEASE=true npm run publish:bump` -> See that the bump is a pre of v3, and not a full fledge v3.
> ci: use pure conventionalcommits.org commit convention

- packages/atomic/src/components/search/atomic-sort-dropdown/atomic-sort-dropdown.new.stories.tsx
- packages/atomic/src/components/search/atomic-sort-dropdown/atomic-sort-dropdown.tsx
- packages/atomic/src/components/search/atomic-sort-dropdown/e2e/atomic-sort-dropdown.e2e.ts
- packages/atomic/src/components/search/atomic-sort-dropdown/e2e/fixture.ts
- packages/atomic/src/components/search/atomic-sort-dropdown/e2e/page-object.ts
https://coveord.atlassian.net/browse/KIT-3480
Field sort criteria are stored as query expression, (i.e. field are prefixed with @), and we don't have the @ in the expression attribute. oops
> fix(atomic): field sort should be applied when selected

- package-lock.json
- packages/headless/package.json
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
- packages/headless/src/features/generated-answer/generated-answer-analytics-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-insight-analytics-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-selectors.test.ts
- packages/headless/src/features/generated-answer/generated-answer-selectors.ts
- patches/coveo.analytics+2.30.38.patch
SVCC-4021
The answer id will be sent to the custom event
The search api stream ID will be sent with the custom event
It was decided that we should send a distinct key in the custom event when using the answer api stream id. So I modified the selector to return the `answerAPIEnabled` is boolean that will help determine what key to use when sending the event. Not sure if this could have been done in a better way.
> feat(generatedAnswerAnalyticsAction): stream id

- packages/rollup-plugin-replace-with-ast/project.json
This causes https://github.com/coveo/ui-kit/blob/1ba2c94a209c78447e7bd0cde8d1eaab72e15a41/nx.json#L100-L112
to run in the context of packages/rollup-plugin-replace-with-ast, which does not make sense (and fails because bump is missing in its package.json, rightfully so)
https://coveord.atlassian.net/browse/KIT-3569
For testing, I nooped most of the release:phase1 script in nx.json, except the bump itself.
Then, I analyzed the result of the bump to make sure it was sound and expected.
> chore: - release:phase1 from ast plugin

- packages/atomic-react/rollup.config.mjs
- packages/atomic/stencil.config.ts
This ensures the code we deployed to the CDN is environment agnostic.
Currently for example, we try to use Headless from static.cloud.coveo.com in Atomic from staticdev.cloud.coveo.com
https://coveord.atlassian.net/browse/KIT-3571
See https://developer.mozilla.org/en-US/docs/Web/API/URL_API/Resolving_relative_references#root_relative
> fix(atomic, atomic-react): use root-relative URL for CDN

- packages/atomic/.storybook/main.mts
- packages/atomic/stencil.config.ts
https://coveord.atlassian.net/browse/KIT-3575
Copy from https://github.com/coveo/ui-kit/pull/4434
> chore: ensure absolute paths are not resolved as local when building for the CDN

- packages/headless/src/api/knowledge/tests/stream-answer-api-state-mock.ts
- packages/headless/src/controllers/core/generated-answer/headless-core-generated-answer.test.ts
- packages/headless/src/controllers/core/generated-answer/headless-core-generated-answer.ts
- packages/headless/src/controllers/core/generated-answer/headless-searchapi-generated-answer.test.ts
- packages/headless/src/controllers/core/generated-answer/headless-searchapi-generated-answer.ts
- packages/headless/src/features/generated-answer/generated-answer-actions.test.ts
- packages/headless/src/features/generated-answer/generated-answer-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.test.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.ts
- packages/headless/src/features/generated-answer/generated-answer-state.ts
This PR adds a way to disable/enable the generated answer controller.
https://coveord.atlassian.net/browse/CDX-1587
> feat(headless): add a way to disable/enable the generated answer controller

- packages/samples/headless-ssr/app-router/src/app/react/page.tsx
- packages/samples/headless-ssr/common/components/common/search-engine-config.ts
- packages/samples/headless-ssr/common/components/common/tab-manager.tsx
- packages/samples/headless-ssr/common/components/common/tab.tsx
- packages/samples/headless-ssr/common/components/generic/facet.tsx
- packages/samples/headless-ssr/common/components/generic/search-page.tsx
- packages/samples/headless-ssr/common/components/generic/tab.tsx
- packages/samples/headless-ssr/common/components/generic/tabs-manager.tsx
- packages/samples/headless-ssr/common/components/react/facets.tsx
- packages/samples/headless-ssr/common/components/react/tab-manager.tsx
- packages/samples/headless-ssr/common/components/react/tab.tsx
- packages/samples/headless-ssr/common/lib/react/engine.ts
- packages/samples/headless-ssr/cypress/e2e/smoke.cy.ts
- packages/samples/headless-ssr/cypress/e2e/ssr-search-parameter-manager.cy.ts
- packages/samples/headless-ssr/pages-router/src/pages/react/index.tsx
https://coveord.atlassian.net/browse/CDX-1588
> docs(headless SSR): add tabs to ssr samples

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components.d.ts
- packages/atomic/src/components/search/atomic-generated-answer/atomic-generated-answer.tsx
- packages/atomic/src/pages/examples/tabs.html
- packages/samples/headless-ssr/common/components/common/tab.tsx
- packages/samples/headless-ssr/common/components/react/tab.tsx
This PR allows atomic-generated-answer to be visible/hidden based on the currently active tab in the tab manager.
https://coveord.atlassian.net/browse/CDX-1557
> feat(atomic): add tab support for atomic-generated-answer

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/insight/atomic-insight-generated-answer/atomic-insight-generated-answer.tsx
- packages/headless/src/controllers/insight/generated-answer/headless-insight-generated-answer.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
[SVCC-4206](https://coveord.atlassian.net/browse/SVCC-4206)
Add support for the `answer-configuration-id` parameter in `atomic-insight-generated-answer`, which switches from the Search API to the Answer API flow
[SVCC-4206]: https://coveord.atlassian.net/browse/SVCC-4206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add answer configuration id to atomic-insight-generated-answer

- packages/samples/atomic-react/project.json
- packages/samples/headless-commerce-react/project.json
- packages/samples/headless-react/project.json
- packages/samples/headless-ssr-commerce/project.json
- packages/samples/headless-ssr/app-router/project.json
- packages/samples/headless-ssr/pages-router/project.json
- packages/samples/iife/project.json
- packages/samples/stencil/project.json
- packages/samples/vuejs/project.json
https://coveord.atlassian.net/browse/KIT-3602
Copy what was in the angular sample and other sample relying on Atomic, for the same reason (but expanded to all the sample now that Bueno is an external of Headless).
Will be revisited in post-ga tech debts
> chore: skip sample build for cdn

- package-lock.json
- packages/headless/package.json
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
- packages/headless/src/features/generated-answer/generated-answer-analytics-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-insight-analytics-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-selectors.test.ts
- packages/headless/src/features/generated-answer/generated-answer-selectors.ts
- patches/coveo.analytics+2.30.38.patch
This PR backports https://github.com/coveo/ui-kit/pull/4405 into the V2 branch.
Since we should not backport features to the V2 branch, I will defend that this PR is indeed a fix for the whole answer api feature on V2.
Without this. The whole feature is unusable for customers to test the answerAPI properly. And will furthermore hinder the momentum we could have to incentive them to move to v3 with the rest of the feature we will add to the answerAPI in the next sprints.
> fix(answerApi): custom event

- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/__tests__/quanticSearchBoxInput.test.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/quanticSearchBoxInput.js
[SFINT-5711](https://coveord.atlassian.net/browse/SFINT-5711)
**Description:**
The clear input button is not being displayed on first render when the query is not empty after selecting a suggestion/recent query on first render
https://github.com/user-attachments/assets/633ddd45-f993-454c-b571-42c8b8e55b34
Modified the `isQueryEmpty` getter to add the `&& !this.inputValue;` to the check. This makes the `isQueryEmpty` getter evaluate properly and therefore display the clear icon.
https://github.com/user-attachments/assets/a7b878c4-aaca-47ee-b3b7-3cebb07277ee
[SFINT-5711]: https://coveord.atlassian.net/browse/SFINT-5711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): Clear icon not being displayed after selecting a suggestion in quantic searchbox

- packages/quantic/force-app/main/default/lwc/quanticCaseAssistInterface/quanticCaseAssistInterface.js
- packages/quantic/force-app/main/default/lwc/quanticInsightInterface/quanticInsightInterface.js
- packages/quantic/force-app/main/default/lwc/quanticRecommendationInterface/quanticRecommendationInterface.js
- packages/quantic/force-app/main/default/lwc/quanticSearchInterface/quanticSearchInterface.js
[SFINT-5762](https://coveord.atlassian.net/browse/SFINT-5762)
The document referrer currently includes the query params which sometimes makes it exceed the limit of 256 characters and cause an error. 
We want to limit this before we send it in quantic interfaces to avoid such error. Moreover, the first 256 chars should be enough to indicate how and from where the end user landed in the search interface
For example : 
https://inspiration-page-9768-dev-ed.scratch.lightning.force.com/visualEditor/appBuilder.app?id=support__Case_rec_L_3col&recordId=500DR00000AaeL6YAJ&cloneable=true&retUrl=https%3A%2F%2Finspiration-page-9768-dev-ed.scratch.lightning.force.com%2Flightning%2Fr%2FCase%2F500DR00000AaeL6YAJ%2Fview”
was causing:
We keep only the first 256 chars
[SFINT-5762]: …
> fix(quantic): Limit the document.referrer to 256 chars in quantic interfaces

- packages/quantic/force-app/coveo-token/main/default/classes/InsightTokenProvider.cls
The execute query privilege should be part of the Insight Token Provider.
This privilege is mandatory for RGA answers to be returned in the insight panel, otherwise it would return 403 errors.
[SFINT-5747]: https://coveord.atlassian.net/browse/SFINT-5747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): added missing privilege to insight token provider class

- packages/quantic/cypress/e2e/default-2/document-suggestion/document-suggestion-selectors.ts
- packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html
[SFINT-5720](https://coveord.atlassian.net/browse/SFINT-5720)
[SFINT-5720]: https://coveord.atlassian.net/browse/SFINT-5720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): fix quick view modal close icon after salesforce winter 25

- packages/quantic/force-app/main/default/labels/CustomLabels.labels-meta.xml
- packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.html
In Salesforce winter 25 version, Salesforce started displaying the format of the expected date format with the date inputs to improve the a11y: https://help.salesforce.com/s/articleView?id=release-notes.rn_lc_base_component_accessibility.htm&release=252&type=5
This broke the alignment of the label of these inputs in our timeframe facet:
https://github.com/user-attachments/assets/0ce1083e-75ee-4520-993b-564aa1018072
[SFINT-5722]: https://coveord.atlassian.net/browse/SFINT-5722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): alignment of time frame facet inputs fixed

- packages/atomic/src/components/search/result-template-components/atomic-quickview/atomic-quickview.tsx
This PR prevents the quickview from reopening when changing tab. This issue occurs when the two tabs have different result lists enabled.
https://coveord.atlassian.net/browse/KIT-3557
> fix(atomic): prevent quickview from reopening when changing tab

- packages/atomic/src/components/common/tab-manager/tab-dropdown.tsx
- packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.pcss
- packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.tsx
This PR ensures that the atomic-tab-manager is automatically displayed whenever there is not enough space to display all tabs. It also improves the appearance of the dropdown.
https://coveord.atlassian.net/browse/KIT-3548
> fix(atomic): show atomic-tab-manager dropdown based on available space instead of fixed breakpoint

- packages/atomic/src/components/common/tab-manager/tab-dropdown-option.tsx
- packages/atomic/src/components/common/tab-manager/tab-dropdown.tsx
This PR fixes a text color issue with the select dropdown of tabs. This issue is specific to window/linux. Additionally, the select dropdown is now full width on mobile.
https://coveord.atlassian.net/browse/KIT-3549
> fix(atomic): fix styling issues with atomic tabs

- packages/atomic/src/utils/date-utils.ts
- packages/quantic/force-app/main/default/lwc/quanticUserAction/__tests__/quanticUserAction.test.js
- packages/quantic/force-app/main/default/lwc/quanticUtils/quanticUtils.js
- Fixed timezone of the dates displayed in the user actions timeline, instead of displaying the dates in the UTC timezone we need to display them in the local timezone.
[SFINT-5765]: https://coveord.atlassian.net/browse/SFINT-5765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic,atomic): fixed timezone issue with user actions timeline

- packages/atomic/src/components/search/atomic-external/e2e/atomic-external.e2e.ts
https://coveord.atlassian.net/browse/CDX-1594
> test(atomic): fix flaky atomic-external tests

- packages/atomic/src/components/ipx/atomic-ipx-modal/atomic-ipx-modal.tsx
We need a new export part to define a bit of CSS in the Search interface service for max-height/width. 
https://coveord.atlassian.net/browse/SVCC-4197
> feat(ipx): add exportparts to atomic-ipx-body

- package-lock.json
- packages/headless/src/features/generated-answer/__snapshots__/generated-answer-analytics-actions.test.ts.snap
- packages/headless/src/features/generated-answer/__snapshots__/generated-answer-insight-analytics-actions.test.ts.snap
- packages/headless/src/features/generated-answer/generated-answer-analytics-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-insight-analytics-actions.ts
- packages/quantic/cypress/e2e/default-1/case-classification/case-classification-selectors.ts
- packages/quantic/cypress/e2e/default-1/case-classification/case-classification.cypress.ts
- packages/quantic/cypress/e2e/default-2/document-suggestion/document-suggestion.cypress.ts
- packages/quantic/cypress/e2e/default-2/generatedAnswer/generated-answer.cypress.ts
- packages/quantic/cypress/e2e/default-2/smart-snippet-suggestions/smart-snippet-suggestions.cypress.ts
- packages/quantic/cypress/e2e/default-2/smart-snippet/smart-snippet.cypress.ts
- packages/quantic/cypress/e2e/next-analytics-expectations.ts
- packages/quantic/cypress/page-objects/search.ts
- packages/quantic/force-app/main/default/lwc/quanticCaseClassification/quanticCaseClassification.html
- packages/quantic/package.json
1.  Fixed a typo in type of the event sent when submiting feedback for RGA, it's now `Rga.SubmitFeedback` instead of `Rga.SubmitRgaFeedback`.
- Fixed all the E2E tests that were previously skipped because of the latest breaking changes that occurs to schemas of the EP events, in this tests we check that the right payload is sent and that each analytics call is valid by sending it to the `validate` endpoint of the Event api.
[SFINT-5732]: https://coveord.atlassian.net/browse/SFINT-5732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(quantic): ep analytics tests fixed in the e2e

- packages/atomic/src/components/commerce/atomic-product/atomic-product.pcss
This PR hides the product image carousel buttons when **imageSize** is set to icon. This prevent the buttons from overlapping with the icon.
https://coveord.atlassian.net/browse/KIT-3612
> fix(atomic): hide carousel buttons when image size is set to icon

- packages/atomic/src/components/common/item-list/styles/mixins.pcss
This PR adds the hover effect and pointer cursor for atomic-product clickable elements in mobile screen size and grid display mode. This will communicate clearly that clicking anywhere on the element will open the product page.
https://coveord.atlassian.net/browse/KIT-3643
> fix(atomic): add hover effect for atomic-product clickable element in mobile/grid

- .github/labeler.yml
- .github/workflows/label.yml
Quickwin: Label all PR open against with v2 with the v2 label so that we can identify quickly what's in v2, what ain't
https://coveord.atlassian.net/browse/KIT-3639
> chore: add auto-label for v2 PRs

- packages/atomic/src/components/common/image-carousel/image-carousel-indicators.tsx
This PR prevents the product page from opening when clicking the indicator buttons of the atomic-product-image carousel.
https://coveord.atlassian.net/browse/KIT-3652
> fix(atomic): prevent clicks on atomic-product-image indicators from opening the product page

- packages/atomic/src/components/commerce/product-template-components/atomic-product-children/atomic-product-children.tsx
This PR prevents the product page from opening when touching the product variants/children on mobile. This was preventing switching between variants on mobile devices.
https://coveord.atlassian.net/browse/KIT-3649
> fix(atomic): prevent touch events on atomic-product-children from opening the product page

- packages/atomic/src/components/commerce/atomic-product/atomic-product.pcss
This PR fixes the product variant icons from taking the full width of the product element when the imageSize is set to none
https://coveord.atlassian.net/browse/KIT-3608
> fix(atomic): fix layout issue on product variants with imageSize set to none

- packages/quantic/cypress/e2e/default-1/case-classification/case-classification-selectors.ts
- packages/quantic/cypress/e2e/default-1/refine-modal-content/refine-modal-content.cypress.ts
- packages/quantic/cypress/e2e/facets-2/timeframe-facet/timeframe-facet-selectors.ts
- packages/quantic/cypress/e2e/facets-2/timeframe-facet/timeframe-facet.cypress.ts
- packages/quantic/force-app/main/default/lwc/quanticCaseClassification/quanticCaseClassification.html
[SFINT-5779](https://coveord.atlassian.net/browse/SFINT-5779)
This PR backports the fix made [here](https://github.com/coveo/ui-kit/pull/4559).
It is mandatory in order to be able to merge other Quantic fixes in `v2`.
[SFINT-5779]: https://coveord.atlassian.net/browse/SFINT-5779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(quantic): fixed quantic e2e after salesforce 25 winter release

- packages/atomic/src/components/common/generated-answer/generated-content/markdown-utils.test.ts
- packages/atomic/src/components/common/generated-answer/generated-content/markdown-utils.ts
- packages/quantic/force-app/main/default/lwc/quanticUtils/__tests__/markdownUtils.test.js
- packages/quantic/force-app/main/default/lwc/quanticUtils/markdownUtils.js
[SVCC-4245](https://coveord.atlassian.net/browse/SVCC-4245)
A CRGA model generally generates markdown headings like this:
```
```
However, in some cases, it can generate headings this way:
```
**Title**
=====
```
When it does, the HTML returned by the `generated-answer` component is broken and the heading reads like this:
```
Title>Title
```
The core of the issue is in the custom Marked renderer. When the heading has formatting, the `text` parameter contains the HTML rendering of the heading content. Inserting non-escaped HTML into the `aria-label` attribute then breaks the `div` element.
This PR fixes the issue by affecting only the heading text content to the `aria-label` attribute. To do so, the HTML elements are removed from the heading content when setting `aria-label`. The heading …
> fix(atomic,quantic): broken HTML because of formatting in CRGA markdown heading

- .prettierignore
- packages/atomic-react/package.json
- packages/atomic-react/project.json
- packages/atomic-react/scripts/fix-loader-import-paths.js
- packages/atomic/.eslintrc.cjs
- packages/atomic/package.json
- packages/atomic/project.json
- packages/atomic/stencil.config.ts
- packages/samples/stencil/stencil.config.ts
https://coveord.atlassian.net/browse/KIT-3666
This PR allows the `defineCustomElements()` function to be deployed to the CDN by simply adding it into the `/dist` folder instead of it's custom folder. 
It causes a problem in atomic-react where the `defineCustomElements` import becomes `"import { defineCustomElements } from '@coveo/atomic/dist/loader';"`. 
That import is invalid because of the added `exports` field in atomic V3. To fix this, we need to change the import back to how it was. I created a script to do this. It changes it back to `"import { defineCustomElements } from '@coveo/atomic/loader';"`.
> fix(atomic): allow atomic loader to be deployed to the CDN

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/product-template-components/atomic-product-field-condition/atomic-product-field-condition.tsx
- packages/atomic/src/components/insight/result-templates/atomic-insight-result-children-template/atomic-insight-result-children-template.tsx
- packages/atomic/src/components/insight/result-templates/atomic-insight-result-template/atomic-insight-result-template.tsx
- packages/atomic/src/components/recommendations/atomic-recs-result-template/atomic-recs-result-template.tsx
- packages/atomic/src/components/search/result-template-components/atomic-field-condition/atomic-field-condition.tsx
- packages/atomic/src/components/search/result-template-components/atomic-result-localized-text/atomic-result-localized-text.ts
- packages/atomic/src/components/search/result-templates/atomic-result-children-template/atomic-result-children-template.tsx
- packages/atomic/src/components/search/result-templates/atomic-result-template/atomic-result-template.tsx
https://coveord.atlassian.net/browse/KIT-3663
If you look in …/atomic-angular/…/stencil-generated/component.ts and look for atomic-field-condition, you can find that mustMatch and mustNotMatch are not in “inputs”.
A solution for this is to add @Prop before every @MapProp, I will see if I can try to add the Prop decorator behavior inside of the @MapProp code.
> fix(atomic-angular): add @Prop decorator to @MapProp props so they are generated in the angular-output

- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.test.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
https://coveord.atlassian.net/browse/SVCC-4254 
SVCC-4254
When the answer-api is enabled
**TLDR**
Whenever a search request was made after a precedent search request is made with an empty query, the answerAPI was called two times with the same parameters. hitting the RTK query cache while painting red in the console.
**Further**
The last params with which a search was triggered are kept in a variable used to compare with the current params the listener current run uses. The comparison between the lastParams and the current ones determines if we should call the answerAPI or not. Because the query in the state is not updated at the same time than the request ID,the listener is run twice. If we do not update the `lastTriggerParams` when the query is empty, the condition will receive a wrong …
> fix(answerAPI): controller search listener

- packages/atomic-react/src/components/commerce/CommerceProductListWrapper.tsx
- packages/atomic-react/src/components/commerce/CommerceRecommendationListWrapper.tsx
- packages/atomic-react/src/components/recommendation/RecsListWrapper.tsx
- packages/atomic-react/src/components/search/ResultListWrapper.tsx
https://coveord.atlassian.net/browse/KIT-3561
At the moment, we're rendering the default link container (i.e., an AtomicProductLink) even on list and table display, making the entire result clickable. This should only be the case in grid display.
**Before fix**:
<video src=https://github.com/user-attachments/assets/24d6321c-f8d7-48de-9a35-b8da3b8f9345 />
**After fix**:
<video src=https://github.com/user-attachments/assets/b35e26b3-3586-4c20-9e04-5310345fd48b />
> fix(atomic-react): render empty link container when display is other than grid

- packages/headless/src/features/commerce/facets/facet-set/facet-set-reducers.ts
- packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.test.ts
[CAPI-1470](https://coveord.atlassian.net/browse/CAPI-1470)
Barca is crashing on page refresh when a numerical range facet is used because headless isn't refresh the `facetSet` in the way it does for other facets.
Test on barca and now works as expected.
Before:
https://github.com/user-attachments/assets/6bf6faed-87df-42c2-90a1-5ad5193eaaf3
Now:
https://github.com/user-attachments/assets/55de9da9-9ad1-4bd3-b524-84a756342371
[CAPI-1470]: https://coveord.atlassian.net/browse/CAPI-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless): restore range facet state after refresh

- packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.ssr.ts
- packages/headless/src/controllers/commerce/core/facets/date/headless-commerce-date-facet.ts
- packages/headless/src/controllers/commerce/core/facets/generator/headless-commerce-facet-generator.ssr.ts
- packages/headless/src/controllers/commerce/core/facets/numeric/headless-commerce-numeric-facet.ts
- packages/headless/src/ssr-commerce.index.ts
- packages/samples/headless-ssr-commerce/app/_components/breadcrumb-manager.tsx
- packages/samples/headless-ssr-commerce/app/_components/pages/listing-page.tsx
- packages/samples/headless-ssr-commerce/app/_components/pages/search-page.tsx
- packages/samples/headless-ssr-commerce/app/_lib/commerce-engine-config.ts
https://coveord.atlassian.net/browse/KIT-3464
This PR adds the breadcrumb manager definer function and a sample for it.
> feat(headless): add support for breadcrumb manager in commerce ssr

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tsx
- packages/atomic/src/components/ipx/atomic-ipx-recs-list/atomic-recs-list/atomic-ipx-recs-list.tsx
- packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.tsx
- packages/atomic/src/components/recommendations/atomic-recs-result/atomic-recs-result.tsx
- packages/atomic/src/pages/index.html
This PR ensures that clicks on grid display mode result cards open the result/product for `atomic-recs-list`, `atomic-ipx-recs-list` and `atomic-commerce-recommendation-list`, as with other types of result lists.
https://coveord.atlassian.net/browse/KIT-3705
> fix(atomic): fix clicks for recommendation lists in grid display mode

- packages/atomic/src/components/common/generated-answer/styles/generated-answer.pcss
https://coveord.atlassian.net/browse/SVCC-4300
We need to support a more compact RGA component for IPX use case. This adds a variable to the collapsed height of the component.
To test, you can add that style to the IPX demo page: 
```
(with
search: {
pipeline: 'genqatest',
},)
:root {
--atomic-crga-collapsed-height: 8rem;
}
atomic-generated-answer::part(container) {
padding: 1.5rem;
}
atomic-generated-answer::part(generated-container) {
margin-top: 1rem;
}
atomic-generated-answer::part(generated-answer-footer) {
margin-top: 1rem;
}
```
and it will now look like that:
https://github.com/user-attachments/assets/e1d5aee0-38dd-4058-8dda-af199e864ef4
> feat(atomic): add variable for collapsed rga height

- package-lock.json
- packages/atomic-hosted-page/package.json
The atomic-hosted-page has the same major version in both v2 and master branches.
Thus, we do not want to bump its version on this branch
https://coveord.atlassian.net/browse/KIT-3717
> ci: skip atomic-hosted-page publish

- packages/bueno/src/values/string-value.test.ts
- packages/bueno/src/values/string-value.ts
- packages/bueno/tsconfig.json
The previous URL validation disallowed localhost and 127.0.0.1-type endpoints. Instead of using a regex to parse the URL, defer the parsing to the URL constructor, which is more flexible.
To do so, I updated the TypeScript configuration to allow the use of DOM-related types in the project.
This change came up as I was attempting to use `proxyBaseUrl` in headless to call a locally-running instance of a service, which was exposed on localhost. See https://coveo.slack.com/archives/G016TA2G485/p1730933467640229
> fix(bueno): use URL constructor to parse url

- packages/headless/src/app/commerce-engine/commerce-engine.ssr.ts
- packages/headless/src/app/logger-middlewares.ts
- packages/headless/src/app/search-engine/search-engine.ssr.ts
- packages/samples/headless-ssr-commerce/app/_lib/commerce-engine-config.ts
This PR improves the way error messages get logged in headless to ensure enough information is available in server-side errors. 
It does this by returning error code + message from the error payload if available.
Before:
> {"level":50,"time":1730911352023,"pid":41408,"hostname":"WKS-002579","name":"@coveo/headless","msg":"Rejected"}
After:
> {"level":50,"time":1730910931049,"pid":41408,"hostname":"WKS-002579","name":"@coveo/headless","msg":"NO_CATALOG_MATCHES_REQUEST - Could not find catalog mapping for organization 'searchuisamples', trackingId 'sports-ui-samples', language: 'egn', country: 'US', currency: 'USD'"}
https://coveord.atlassian.net/browse/KIT-3409
> feat(headless ssr): Improve server-side error logging

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/product-template-components/atomic-product-multi-value-text/atomic-product-multi-value-text.tsx
In the release, I noticed this atomic commerce component that should be hidden, so here you go 🙂 
https://coveord.atlassian.net/browse/KIT-3723
> docs(atomic): hide a component

- .github/actions/e2e-atomic-angular/action.yml
- .github/actions/e2e-atomic-next/action.yml
- .github/actions/e2e-atomic-react/action.yml
- .github/actions/e2e-atomic-screenshots/action.yml
- .github/actions/e2e-atomic/action.yml
- .github/actions/e2e-headless-ssr-app-dev/action.yml
- .github/actions/e2e-headless-ssr-app-prod/action.yml
- .github/actions/e2e-headless-ssr-pages-dev/action.yml
- .github/actions/e2e-headless-ssr-pages-prod/action.yml
- .github/actions/e2e-iife/action.yml
- .github/actions/e2e-quantic/action.yml
- .github/actions/e2e-stencil/action.yml
- .github/actions/e2e-vuejs/action.yml
https://coveord.atlassian.net/browse/KIT-3725
Main change are that they are immutable now. We were never mutating them so not much work to update to v4
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
> ci: update upload-artifacts & download-artifacts to v4

- packages/headless/src/controllers/core/result-list/headless-core-result-list.ts
I somehow made a mistake in one of the links in my Typedoc PR that was merged 1-2 weeks ago. Fix here.
> docs(headless): fix broken link in comment

- packages/quantic/.gitignore
- packages/quantic/project.json
https://coveord.atlassian.net/browse/KIT-3736
The two commands were running in parallel and not deleting the .tmp folder so it showed in the git untracked files thus breaking the commit generated files action.
> ci: fix .tmp quantic folder breaking commit generated files 

- scripts/deploy/execute-deployment-pipeline.mjs
Right now nothing deploy because, well, it's not the right value for "IS NOT NIGHTLY"
CDX-764
> chore: make is-not-nightly=nightly

- packages/samples/headless-ssr-commerce/app/products/[productId]/page.tsx
- packages/samples/headless-ssr-commerce/components/providers/standalone-provider.tsx
Add missing provider on PDP
https://coveord.atlassian.net/browse/KIT-3739
> docs(headless-react): add standalone provider in sample

- packages/headless/src/api/knowledge/stream-answer-api.ts
SVCC-4353
https://coveord.atlassian.net/browse/SVCC-4353
See https://github.com/coveo/ui-kit/pull/4681 for the V3 PR.   :spaghetti: Copy pasta of the description :point_down: 
Upon interacting with a stream response, all headless selectors relying on the `generatedAnswer` slice after a response fetched by the answerAPI client aren't working properly because the state of the answerAPI client is not mapped to the actual `generatedAnswer` slice.
e.g. the custom events
The answer API client is now dispatching what is relevant to the `generatedAnswer` state. The selectors will then return the same value as the generated answer controller state whenever it gets its answer from the client getting its answer directly from reveal or from the answer api.
> fix(generatedAnswer): map state with answerAPI

- packages/atomic/src/components/common/breadbox/breadcrumb-content.tsx
https://coveord.atlassian.net/browse/KIT-3733
> fix(atomic): add space after ':' in breadcrumb buttons

- packages/headless/src/controllers/history-manager/headless-history-manager.ts
- packages/headless/src/controllers/triggers/headless-query-trigger.ts
- packages/headless/src/features/analytics/search-action-cause.ts
- packages/headless/src/features/history/history-analytics-actions.ts
- packages/headless/src/features/search/search-actions.ts
- packages/headless/src/features/triggers/trigger-analytics-actions.ts
https://coveord.atlassian.net/browse/KIT-3742
These and many more events in headless executeSearch calls are invalid and should be removed. This is only the first two. The rest will come from [this spike](https://coveord.atlassian.net/browse/CDX-1600) . (more context in the spike)
> fix(headless): send null instead of noResultsBack & undoQuery

- packages/atomic/src/components/search/result-template-components/atomic-result-image/atomic-result-image.new.stories.tsx
- packages/atomic/src/components/search/result-template-components/atomic-result-image/atomic-result-image.tsx
- packages/atomic/src/components/search/result-template-components/atomic-result-image/e2e/atomic-result-image.e2e.ts
- packages/atomic/src/components/search/result-template-components/atomic-result-image/e2e/fixture.ts
- packages/atomic/src/components/search/result-template-components/atomic-result-image/e2e/page-object.ts
https://coveord.atlassian.net/browse/KIT-3747
> fix(atomic): actually use alt field value

- renovate.json
https://coveord.atlassian.net/browse/KIT-282
Let's try to enable it back to not let it pile up too much.
Let's try to use dependency dashboard to help us manage the dependency updates ;)
> chore: enable back renovate, w/ dependency dashboard

- packages/headless/esbuild.mjs
- packages/headless/ponyfills/global-this-shim.js
- packages/quantic/config/project-scratch-def.json
Locker Service doesn't support `globalThis` but this was added to the library coveo.analytics.js in the last version.
This meant all of Quantic components didn't load with Locker turned on.
This also made us realize that all of our Quantic test are only running with LWS and not Locker, while the SFINT package tests are running on Locker.
At least this way we cover both environments. Out of scope for this PR, but in the future we will probably revert to testing on Locker with Quantic too, and perhaps had smoke tests with LWS.
LWS being the "more recent" of the two, we expect less issues with LWS than with Locker.
> fix(headless): add globalThis shim to quanticUmd build to fix a bug with Locker Service

- packages/headless/src/features/sort/sort.ts
- packages/headless/src/ssr-commerce.index.ts
- packages/samples/headless-ssr-commerce/components/sort.tsx
- packages/samples/headless-ssr-commerce/e2e/listing/listing.fixture.ts
- packages/samples/headless-ssr-commerce/e2e/listing/listing.spec.ts
- packages/samples/headless-ssr-commerce/e2e/page-objects/sort.page.ts
https://coveord.atlassian.net/browse/KIT-3700
> fix(Commerce SSR): export the appropriate sort criteria for commerce

- packages/headless/src/controllers/breadcrumb-manager/headless-breadcrumb-manager.ts
- packages/headless/src/controllers/facets/category-facet/headless-category-facet.ts
- packages/headless/src/controllers/facets/facet/headless-facet.ts
- packages/headless/src/controllers/facets/range-facet/date-facet/headless-date-facet.ts
- packages/headless/src/controllers/facets/range-facet/numeric-facet/headless-numeric-facet.ts
- packages/headless/src/controllers/history-manager/headless-history-manager.ts
- packages/headless/src/controllers/insight/breadcrumb-manager/headless-insight-breadcrumb-manager.ts
- packages/headless/src/controllers/insight/facets/category-facet/headless-insight-category-facet.ts
- packages/headless/src/controllers/insight/facets/facet/headless-insight-facet.ts
- packages/headless/src/controllers/insight/facets/range-facet/date-facet/headless-insight-date-facet.ts
- packages/headless/src/controllers/insight/facets/range-facet/numeric-facet/headless-insight-numeric-facet.ts
- packages/headless/src/controllers/static-filter/headless-static-filter.ts
- packages/headless/src/controllers/triggers/headless-query-trigger.ts
- packages/headless/src/features/analytics/search-action-cause.ts
- packages/headless/src/features/facets/facet-set/facet-set-analytics-actions.ts
- packages/headless/src/features/history/history-analytics-actions.ts
- packages/headless/src/features/search/search-actions.ts
- packages/headless/src/features/static-filter-set/static-filter-set-actions.ts
- packages/headless/src/integration-tests/analytics-migration.test.ts
- packages/headless/src/integration-tests/insight-analytics-migration.test.ts
https://coveord.atlassian.net/browse/KIT-3748
Stop sending to EP events that are not in that [list](https://github.com/coveo-platform/analytics_schema/blob/de502f0877eeaae8e523c78a08e92222f8b26eee/schemas/common/types.json#L267-L292) as they are invalid. This ended up taking 20 minutes so I just did it now.
> fix(headless): stop sending invalid actionCause for event protocol

- packages/headless/src/app/navigatorContextProvider.ts
https://coveord.atlassian.net/browse/KIT-3758
While drafting Commerce SSR docs, I noticed that we had no annotations for NavigatorContext, which I thought would be useful.
> docs(headless): navigator context annotations

- .deployment.config.json
- packages/atomic-react/scripts/fix-loader-import-paths.js
- packages/atomic/package.json
- packages/atomic/project.json
- packages/atomic/stencil.config.ts
This PR ensures that the atomic loader is deployed to the CDN under the atomic/v*/loader path.
https://coveord.atlassian.net/browse/KIT-3710
> chore: add atomic loader to CDN deployment config

- packages/headless-react/src/ssr-commerce/index.ts
This PR reorders the ssr-commerce exports in headless-react to ensure that defineCommerceEngine is loaded from coveo/headless instead of coveo/headless-react
https://coveord.atlassian.net/browse/KIT-3737
> feat(ssr): reorder headless react exports

- packages/atomic/src/components/search/atomic-did-you-mean/atomic-did-you-mean.new.stories.tsx
- packages/atomic/src/components/search/atomic-did-you-mean/e2e/atomic-did-you-mean.e2e.ts
- packages/atomic/src/components/search/atomic-external/e2e/atomic-external.e2e.ts
https://coveord.atlassian.net/browse/CDX-1595
I don't know why but this makes it less flaky locally.
> test(atomic): fix flaky atomic did you mean tests

- .github/workflows/prbot.yml
- .github/workflows/release.yml
https://coveord.atlassian.net/browse/KIT-3423
See the github action to download it in the doc repo - > https://github.com/coveo/doc_jekyll-public-site/pull/12275
tested here as a similar repo to ui-kit (public repo): https://github.com/shutter-org/artifact-giver
tested here as a similar repo to docs jekyll getting the artifact from a public repo: https://github.com/shutter-org/artifact-receiver
> docs(headless): release headless typedoc site as an artifact

- packages/headless/src/controllers/commerce/core/facets/numeric/headless-commerce-numeric-facet.ts
- packages/headless/src/features/commerce/common/actions.test.ts
- packages/headless/src/features/commerce/common/actions.ts
- packages/headless/src/features/commerce/facets/facet-set/facet-set-reducers.ts
- packages/headless/src/features/commerce/parameters/parameters-selectors.ts
[CAPI-1587](https://coveord.atlassian.net/browse/CAPI-1587)
Fix for a couple of issues in headless, as found in Barca with numerical range facets (manual range facets in Headless)
- Remove duplicate facet's from the CAPI request
- Remove duplicate facet state from URL fragment
- Remove deselected numerical facet values from URL fragment
Curious I found a bug in the `actions.test.ts` file that meant the test should have been failing due to the duplicate facet in CAPI request bug but it passed. Fixing the bug now passes with the fixed code.
Current:
https://github.com/user-attachments/assets/9a075b2e-7dcb-4d65-b813-7f8ea8dc6129
Fix:
https://github.com/user-attachments/assets/0d78b0b2-dab0-400d-9483-23de0391912c
[CAPI-1587]: https://coveord.atlassian.net/browse/CAPI-1587?atlOrigin=eyJpIjoiNWR …
> fix(headless): capi 1587 facets are duplicated in capi request payload when using manual numeric facets

- packages/quantic/.npmignore
ignored e2e folder in the `.npmignore` file to avoid having the e2e folders used for new playwright e2e tests included in the Quantic npm package.
[SFINT-5841]: https://coveord.atlassian.net/browse/SFINT-5841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): ignored e2e tests folder when building npm quantic package

- packages/headless/esbuild.mjs
This PR ensures that the nodejs build for headless generates sourcemaps.
https://coveord.atlassian.net/browse/KIT-3771
> chore(headless): add sourcemaps for nodejs esm build

- packages/atomic/src/components/common/suggestions/suggestion-manager.ts
https://coveord.atlassian.net/browse/KIT-3781
See the ticket
> fix(atomic): fix error when hovering recent result containing double quotes

- packages/headless/src/features/generated-answer/__snapshots__/generated-answer-analytics-actions.test.ts.snap
- packages/headless/src/features/generated-answer/__snapshots__/generated-answer-insight-analytics-actions.test.ts.snap
- packages/headless/src/features/generated-answer/generated-answer-analytics-actions.ts
- packages/headless/src/features/generated-answer/generated-answer-insight-analytics-actions.ts
- packages/quantic/cypress/e2e/default-2/generatedAnswer/generated-answer.cypress.ts
We want to send the searchId with all the RGA EP events so every event can properly be tied back to a search event when processing the translations EP → UA events.
We were previously sending the `stream id` as a response id in the RGA events, but we figured that will this cause for us issue when it comes to trying to tie RGA events to the search events that were made with it so we are doing this update.
https://github.com/user-attachments/assets/a6e3e029-1e28-4576-8b36-7b04414a3c5f
[SFINT-5854]: https://coveord.atlassian.net/browse/SFINT-5854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(headless): update the rga events to send the searchId instead of the streamId as response id

- packages/headless/src/controllers/commerce/core/parameter-manager/headless-core-parameter-manager.ts
https://coveord.atlassian.net/browse/KIT-3462
> fix(headless commerce): make parameter manager prop.initialState optional

- packages/atomic/src/components/common/button.tsx
- packages/atomic/src/components/common/tab-manager/tab-button.tsx
- packages/atomic/src/components/common/tabs/tab-popover.tsx
This PR fixes the missing hover effect on tab buttons. To ensure consistent styling, the tabs now use our `Button` component instead of a `HTMLButtonElement`.
https://coveord.atlassian.net/browse/KIT-3777
> fix(atomic): fix missing hover effect on more tab button

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/common/button.tsx
- packages/atomic/src/components/common/tab-manager/tab-button.tsx
- packages/atomic/src/components/common/tab-manager/tab-manager-bar.tsx
- packages/atomic/src/components/common/tabs/tab-bar.tsx
- packages/atomic/src/components/common/tabs/tab-popover.tsx
- packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.tsx
This PR ensures that the "More" tab list of atomic-tab-manager follows accessibility best practices.
It implements this pattern:
https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/
It also fixes the same issue for the insight panel tabs since they use tab-popover too.
https://coveord.atlassian.net/browse/KIT-3778
> fix(atomic): accessibility issues on "More" tab list

- packages/atomic/src/components/common/items-per-page/choices.tsx
- packages/atomic/src/components/common/pager/pager-buttons.tsx
- packages/atomic/src/components/common/pager/pager-navigation.tsx
- packages/atomic/src/components/common/radio-button.tsx
- packages/atomic/src/components/search/atomic-results-per-page/atomic-results-per-page.tsx
This PR fixes the accessibility issues with the pager/results per page buttons. More specifically, it was not possible to navigating between pager or results per page buttons without selecting one, triggering a refresh of the results. 
The solution is to have the buttons inside a toolbar and implement the logic described here:
https://www.w3.org/WAI/ARIA/apg/patterns/radio/#:~:text=For%20Radio%20Group%20Contained%20in%20a%20Toolbar
https://coveord.atlassian.net/browse/KIT-3767
> fix(atomic): fix accessibility issues with pager/results per page buttons

- packages/atomic/src/components/commerce/product-template-components/atomic-product-numeric-field-value/atomic-product-numeric-field-value.new.stories.tsx
- packages/atomic/src/components/commerce/product-template-components/atomic-product-numeric-field-value/e2e/atomic-product-numeric-field-value.e2e.ts
- packages/atomic/src/components/commerce/product-template-components/atomic-product-numeric-field-value/e2e/fixture.ts
- packages/atomic/src/components/commerce/product-template-components/atomic-product-numeric-field-value/e2e/page-object.ts
This PR adds tests for `atomic-product-numeric-field-value`
https://coveord.atlassian.net/browse/KIT-3270
> test(atomic): add tests for atomic-product-numeric-field-value

- packages/atomic/src/components/ipx/atomic-ipx-body/atomic-ipx-body.pcss
- packages/atomic/src/components/ipx/atomic-ipx-modal/atomic-ipx-modal.pcss
- packages/atomic/src/components/ipx/atomic-ipx-refine-modal/atomic-ipx-refine-modal.pcss
[SVCC-4253](https://coveord.atlassian.net/browse/SVCC-4253)
Adds some style to IPX to handle big zoom levels and mobile view. See video.
Before
https://github.com/user-attachments/assets/26f6ff5f-b8ac-4477-8ba3-8836d08ae6fc
After
https://github.com/user-attachments/assets/7018a7e1-fd03-430b-b2bb-780e5c876692
[SVCC-4253]: https://coveord.atlassian.net/browse/SVCC-4253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(atomic): fix IPX with high zoom levels

- nx.json
https://coveord.atlassian.net/browse/KIT-3817
https://nx.dev/deprecated/legacy-cache#nxrejectunknownlocalcache.
our ci currently rebuilds everytime without caching since nx 20
> chore: add back nx legacy cache

- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api.test.ts
https://coveord.atlassian.net/browse/SVCC-4482
This is a backport of https://github.com/coveo/ui-kit/pull/4800 for v2.
When perfoming a CRGA request, an "end of stream" Usage Analytics event should be sent even when no answer is generated. However, when sending the request to the Answer API, the "end of stream" Usage Analytics event is sent only when an answer is generated.
This PR fixes the issue. In addition, tests have been added to cover the handling of the various event source messages.
> fix(headless): send end of stream event even when no answer is generated

- packages/atomic/cypress/integration-insight-panel/insight-panel-selectors.ts
- packages/atomic/cypress/integration-insight-panel/insight-panel.cypress.ts
- packages/atomic/src/components.d.ts
- packages/atomic/src/components/common/tab-manager/tab-manager-bar.pcss
- packages/atomic/src/components/common/tab-manager/tab-manager-bar.tsx
- packages/atomic/src/components/common/tabs/tab-bar.tsx
- packages/atomic/src/components/common/tabs/tab-popover.tsx
- packages/atomic/src/components/insight/atomic-insight-tabs/atomic-insight-tabs.tsx
- packages/atomic/src/components/ipx/atomic-ipx-tabs/atomic-ipx-tabs.tsx
- packages/atomic/src/components/search/tabs/atomic-tab-manager/e2e/page-object.ts
https://coveord.atlassian.net/browse/KIT-3773
For the upcoming new lazy loader made with `lit` (new framework replacing stencil), it would be very helpful if all custom elements had the prefix `atomic-` ! 
All components affected in this PR are not supposed to be public, they are "internal" components.
> fix(atomic): make all components start with `atomic-`

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic-angular/scripts/build-lit.mjs
i.e. generation stays the same if components stay the same
https://coveord.atlassian.net/browse/KIT-3862
> chore: ensure atomic-angular component file is stable

- packages/atomic/src/directives/localized-string.ts
- packages/atomic/src/utils/jsx-utils.tsx
Replace the functional component with a custom lit directive
```ts
render () {
return (
<LocalizedString
key={i18nKey}
i18n={this.bindings.i18n}
params={...}
/>
):
}
```
```ts
render () {
return html`
${localizedString({
key: i18nKey,
i18n: this.bindings.i18n,
params: {...},
})}
`;
}
```
It's hard to make perf adjustments to this code (e.g. using a regex instead of splitting the string) since the directive can also accept DOM values. For example
```ts
html`${localizedString({
i18n: i18n,
key: "search-instead-for",
params: {
query: html`
<button
class="link py-1"
part="undo-btn"
onClick={() => onClick()}
>
${originalQuery}
</button>`
}
`
```
Which returns something like that
In the code example above, moving out the `<button>` Element from the directive would imply some big refactor on the …
> feat(atomic): add localizedString directive

- packages/atomic/src/components/common/tab-manager/tab-button.tsx
- packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.tsx
This PR adds distinct part names for active tab button and active tab button container. This makes it possible to style them differently from other buttons.
https://coveord.atlassian.net/browse/CDX-1604
> fix(atomic): add separate part name for active tab

- .github/workflows/release.yml
JIRA: https://coveord.atlassian.net/browse/KIT-3424
This PR changes the logic of how the Typedoc site is uploaded as an artifact. This is to streamline the process of publishing the generated docs at docs.coveo.com (the project that I'm working on these days).
I tested this approach in a local fork of this repo, you can look at the latest run that uses the same logic as suggested in this PR: https://github.com/npushkarskii/ui-kit/actions/runs/12832730326
----
> [!NOTE]
> * archiving in the workflow wasn't required as it resulted in creating an archive inside an archive. GH automatically creates an archive when we upload anything as an artifact.
>
> * the archive's names stays `headless-docs-{VERSION}.zip` (didn't change)
The structure of the resulting archive will now be in the format: …
> docs(headless): updates the Headless typedoc uploading logic

- .deployment.config.json
This pull request includes a change to the `.deployment.config.json` file to modify the deployment behavior for the `searchuibuilds` team.
Deployment configuration change:
* [`.deployment.config.json`](diffhunk://#diff-b4ad9e880162c29d04fd77a0c4a3b154b4bbabd31a0c6b46ae8f4cac17d7eb76L12-R12): Changed the `start_environment_automatically` setting from `true` to `false` to prevent automatic starting of the environment.
CDX-764
> chore: disable automatic environment graduation

- packages/headless/src/api/service/insight/get-interface/get-interface-config-response.ts
- packages/headless/src/features/insight-interface/insight-interface-slice.test.ts
[SFINT-5919](https://coveord.atlassian.net/browse/SFINT-5919)
- Added answerConfigId to the InsightInterface to be supported in insight use case
[SFINT-5919]: https://coveord.atlassian.net/browse/SFINT-5919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(headless): Add answerConfigId to the InsightInterface to be supported in insight use case

- renovate.json
KIT-282
We are not immediately ready for this so we should separate it to not block renovate.
> chore: isolate tailwind in a separate renovate PR for easier migration

- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.pcss
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.pcss
- packages/atomic/src/components/insight/result-lists/atomic-insight-folded-result-list/atomic-insight-folded-result-list.pcss
- packages/atomic/src/components/insight/result-lists/atomic-insight-result-list/atomic-insight-result-list.pcss
- packages/atomic/src/components/ipx/atomic-ipx-recs-list/atomic-recs-list/atomic-ipx-recs-list.pcss
- packages/atomic/src/components/recommendations/atomic-recs-list/atomic-recs-list.pcss
- packages/atomic/src/components/search/result-lists/atomic-folded-result-list/atomic-folded-result-list.pcss
- packages/atomic/src/components/search/result-lists/atomic-result-list/atomic-result-list.pcss
https://coveord.atlassian.net/browse/KIT-3775
Inspired by https://bbellmyers.github.io/2020/09/27/fouc-stencil.html.
Not a definitive fix: When Lit migration is done for the atomic-result, we should validate for regression on that front, and also try to improve the behavior even so slightly.
It might also be preferable to migrate all result components first, so that we can "cut" this behavior neatly. (would likely not happen because I _think_ we scan documentFragment from template element, so we should have all the element defined by then (tho maybe not because of race conditions, in which case https://www.abeautifulsite.net/posts/flash-of-undefined-custom-elements might be adapted for our needs)
> fix(atomic): hide unhydrated results

- packages/headless/src/controllers/commerce/context/cart/headless-cart.ssr.ts
- packages/headless/src/controllers/commerce/context/headless-context.ssr.ts
- packages/headless/src/controllers/commerce/core/breadcrumb-manager/headless-core-breadcrumb-manager.ssr.ts
- packages/headless/src/controllers/commerce/core/facets/generator/headless-commerce-facet-generator.ssr.ts
- packages/headless/src/controllers/commerce/core/pagination/headless-core-commerce-pagination.ssr.ts
- packages/headless/src/controllers/commerce/core/parameter-manager/headless-core-parameter-manager.ssr.ts
- packages/headless/src/controllers/commerce/core/sort/headless-core-commerce-sort.ssr.ts
- packages/headless/src/controllers/commerce/core/summary/headless-core-summary.ssr.ts
- packages/headless/src/controllers/commerce/field-suggestions/headless-field-suggestions-generator.ssr.ts
- packages/headless/src/controllers/commerce/instant-products/headless-instant-products.ssr.ts
- packages/headless/src/controllers/commerce/product-list/headless-product-list.ssr.ts
- packages/headless/src/controllers/commerce/product-view/headless-product-view.ssr.ts
- packages/headless/src/controllers/commerce/recent-queries-list/headless-recent-queries-list.ssr.ts
- packages/headless/src/controllers/commerce/recommendations/headless-recommendations.ssr.ts
- packages/headless/src/controllers/commerce/search-box/headless-search-box.ssr.ts
- packages/headless/src/controllers/commerce/search/did-you-mean/headless-did-you-mean.ssr.ts
- packages/headless/src/controllers/commerce/standalone-search-box/headless-standalone-search-box.ssr.ts
- packages/headless/src/controllers/commerce/triggers/headless-notify-trigger.ssr.ts
- packages/headless/src/controllers/commerce/triggers/headless-query-trigger.ssr.ts
- packages/headless/src/controllers/commerce/triggers/headless-redirection-trigger.ssr.ts
https://coveord.atlassian.net/browse/KIT-3690
headless/ssr-commerce is public !
> chore(headless): make ssr-commerce definers public

- packages/headless/src/controllers/commerce/core/pagination/headless-core-commerce-pagination.ssr.ts
- packages/headless/src/controllers/commerce/core/pagination/headless-core-commerce-pagination.ts
- packages/headless/src/ssr-commerce.index.ts
https://coveord.atlassian.net/browse/KIT-3950
I noticed that we weren't documenting PaginationOptions.
https://docs.coveo.com/en/headless-react/latest/reference/interfaces/SSR_Commerce.index.PaginationProps.html#options
This PR fixes it:
> docs(headless-react): pagination typedoc reference 

- CODEOWNERS
Change code owners since the SVCINT team does not exist anymore
https://coveord.atlassian.net/browse/SVCC-4716
> chore: change codeowners for IPX

- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.tsx
- packages/atomic/src/components/insight/atomic-insight-search-box/atomic-insight-search-box.tsx
- packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
- packages/atomic/src/locales.json
https://coveord.atlassian.net/browse/KIT-3893
The voice reader won't announce if it's value stays the same. This PR makes it so it's value always changes on every input change thus always rereading the amount of suggestions.
> fix(atomic): search-box announces new suggestions even when count stays the same

- packages/headless/src/features/commerce/configuration/configuration-slice.test.ts
- packages/headless/src/features/commerce/configuration/configuration-slice.ts
https://coveord.atlassian.net/browse/KIT-3949
This is most likely what's causing issues in projects migrating from v2 to v3 that have a renewAccessToken function.
> fix(headless commerce): handle action dispatched by renew access token middleware in commerce configuration slice

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components.d.ts
- packages/atomic/src/components/search/atomic-generated-answer/atomic-generated-answer.tsx
- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswer/quanticGeneratedAnswer.js
https://coveord.atlassian.net/browse/SVCC-4631
As we are releasing the KnowledgeHub and the Answer manager. It is now legitimate to show this property on the Quantic an Atomic Generate Answer components.
> fix(answerConfigurationId): remove internal tag

- packages/atomic/scripts/dev.mjs
- packages/atomic/scripts/generate-component.mjs
- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.tsx
- packages/atomic/src/components/commerce/atomic-commerce-search-box/e2e/atomic-commerce-search-box.e2e.ts
- packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.spec.ts
- packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-query-suggestions/atomic-commerce-search-box-query-suggestions.spec.ts
- packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-recent-queries/atomic-commerce-search-box-recent-queries.spec.ts
- packages/atomic/src/components/common/suggestions/suggestion-manager.ts
- packages/atomic/src/components/search/atomic-search-box/atomic-search-box.spec.ts
- packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
- packages/atomic/src/components/search/atomic-search-box/e2e/atomic-search-box.e2e.ts
- packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-instant-results/atomic-search-box-instant-results.spec.ts
- packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-query-suggestions/atomic-search-box-query-suggestions.spec.ts
- packages/atomic/src/components/search/search-box-suggestions/atomic-search-box-recent-queries/atomic-search-box-recent-queries.spec.ts
https://coveord.atlassian.net/browse/KIT-3910
We now have a new variable in suggestions-manager that tracks they keyboard use. When someone press Enter when having a suggestion/result/recent query selected with the keyboard, it will trigger it's onClick event.
Whenever we stop using the keyboard and using the mouse it resets again which will make the Enter event trigger the query in the search box instead.
I added a lot of tests to write in vitest.
> fix(atomic): don't redirect when hovering a instant result & pressing Enter

- packages/atomic/src/components/insight/atomic-insight-interface/store.ts
https://coveord.atlassian.net/browse/KIT-3959
> fix(atomic): add isMobile to insight store

- packages/headless/README.md
- packages/headless/typedoc/lib/index.tsx
- packages/headless/typedoc/lib/insertBetaNote.ts
https://coveord.atlassian.net/browse/DOC-16522
I only noticed yesterday that we have public reference documentation for the ssr-commerce package under headless (the one in headless-react is already covered). It's in open beta, so I add a string to that effect in the relevant titles.
E.g.:
> docs(headless): typedoc beta note for ssr-commerce

- packages/atomic-angular/scripts/build-lit.mjs
- packages/atomic/scripts/build.mjs
https://coveord.atlassian.net/browse/KIT-3978
For the transformer to affect both js and d.ts, you need it in `before` & `afterDeclarations`.
https://github.com/microsoft/TypeScript/issues/29543#issuecomment-456873917
> chore(atomic): fix tsc path transformer for declaration files

- .github/PULL_REQUEST_TEMPLATE/atomic-stencil-lit-migration.md
- .github/pull_request_template.md
- .github/workflows/apply_pr_template.yml
- .github/workflows/update-pr-template-lit-migration.yml
This pull request introduces a new PR template for the migration of Stencil components to Lit components, along with an automated workflow to apply this template dynamically based on specific labels. 
1. Create the PR. You will see this new pull request template displayed
2. Select `new-lit-component` label and wait for the `Update PR for Lit Component Migration` action to complete
3. The description will automatically be updated
https://coveord.atlassian.net/browse/KIT-3986
> ci: add Pull Request template

- .github/workflows/release.yml
In `release.yml`, there's a step responsible for notifying the docs repo about the fact ot the release.
This PR moves the step to the bottom, after the Typedoc sites are generated. Otherwise, the automation on docs's end fails because it tries to fetch Typedoc artifacts that don't exist yet.
> fix(headless): moves the docs notification step to the bottom

- packages/headless/src/api/commerce/common/product.ts
Keeping the misspelled property to avoid introducing a breaking change.
https://coveord.atlassian.net/browse/KIT-3983
> fix(headless commerce): add product.excerptHighlights property and deprecate misspelled one

- .github/actions/playwright-atomic-theming/action.yml
- .github/workflows/prbot.yml
- packages/atomic/dev/playwright.config.ts
- packages/atomic/dev/tests/smoke.spec.ts
- packages/atomic/dev/themingTests.html
This PR adds tests to ensure our components styles can be customized using our `--atomic-*` css variables. Tests to verify that our styles dont escape our components have also been added.
https://coveord.atlassian.net/browse/KIT-3966
https://coveord.atlassian.net/browse/KIT-3965
> test(atomic): styling smoke tests

- packages/atomic/src/components/common/refine-modal/modal.tsx
Added missing "backdrop" part to the exported parts to have a possibility to style this element by using CSS.
https://coveord.atlassian.net/browse/KIT-4011
> fix(atomic): Added missed "backdrop" part to the exported parts in the refine modal

- packages/atomic/cypress/e2e/common-assertions.ts
- packages/atomic/cypress/e2e/search-interface.cypress.ts
https://coveord.atlassian.net/browse/KIT-4006
Many tests check that there are no console warnings, but with a lit component there will always be this message printed : “Lit is in dev mode. blablabla”. We need to exclude this warning from the tests.
> test(atomic): exclude lit console warning in cypress assert

- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswerContent/templates/generatedMarkdownContent.css
After some trials, I found that adding this small style to the `.scrollable-table` fix the overflow issue without changing the table style when it is bigger.
https://coveord.atlassian.net/browse/SVCC-4598
> fix(atomic): fix generated answer scrollable table overflow when table too small

- .github/workflows/masterbot.yml
- internal-docs/release-process.md
- nx.json
- package.json
- packages/atomic-angular/project.json
- packages/atomic-hosted-page/project.json
- packages/atomic-react/project.json
- packages/atomic/project.json
- packages/auth/project.json
- packages/bueno/project.json
- packages/headless-react/project.json
- packages/headless/project.json
- packages/quantic/project.json
https://coveord.atlassian.net/browse/KIT-4036
This is needed since we should not bump the root package.json when deploying the CDN to dev on each commit. It should stay the same. It was impossible since it was part of phase2.
> ci: create new release phase for bumping the root package.json version

- packages/atomic/src/components/common/load-more/button.ts
- packages/atomic/src/utils/functional-component-utils.ts
https://coveord.atlassian.net/browse/KIT-4033
From the lit doc
> Prefer using nothing over other falsy values as it provides a consistent behavior between various expression binding contexts.
> 
> In child expressions, undefined, null, '', and nothing all behave the same and render no nodes. In attribute expressions, nothing removes the attribute, while undefined and null will render an empty string. In property expressions nothing becomes undefined.
> chore(atomic): use nothing instead of undefined for functional components

- packages/quantic/playwright/page-object/searchObject.ts
[SFINT-6040](https://coveord.atlassian.net/browse/SFINT-6040)
The search response was not properly overriden so it was not properly setting the facet order in the response and therefore was ordering facets with the default ordering.
Instead of using `route.continue` to override, we now use `route.fullfill` in the mocked search response
The tests now pass without flakyness (locally)
https://github.com/user-attachments/assets/565af54f-86c6-4c3d-af9a-01cd748e6dd3
[SFINT-6040]: https://coveord.atlassian.net/browse/SFINT-6040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): failing playwright tests for facet manager in quantic

- .github/workflows/masterbot.yml
https://coveord.atlassian.net/browse/KIT-4049
Disabling DEBUG in that command will fix the failing prerelease since quantic won't have to print over `80mb` of text during it's build:doc phase 😆 . I am not sure why but it ends up exiting before the text can print. Not sure why but we definitely don't need to enable DEBUG for this.
I tested it with a custom github action and confirmed it was passing without `DEBUG: '*'` and was failing with it.
> ci: fix failing quantic:release:phase1 during prerelease

- packages/atomic/dev/tests/smoke.spec.ts
Some of the theming smoke tests where failing due to source changes. Added a query so that the results are always the same (connect.coveo.com).
https://coveord.atlassian.net/browse/KIT-4052
> chore(atomic): fix flaky theming smoke tests

- packages/atomic/src/components/common/generated-answer/generated-content/generated-markdown-content.pcss
fix overflowing tables on small screens in generated answer components
Before:
After:
[SVCC-4598](https://coveord.atlassian.net/browse/SVCC-4598)
[SVCC-4598]: https://coveord.atlassian.net/browse/SVCC-4598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(atomic): fix overflowing tables in generated answer components

- package-lock.json
- packages/atomic/package.json
- renovate.json
https://coveord.atlassian.net/browse/KIT-282
Currently this [all-dependencies renovate](https://github.com/coveo/ui-kit/pull/5068) PR is failing because there some problems with newer versions of tailwind.
Also, the [major update one](https://github.com/coveo/ui-kit/pull/5069) is grouping tailwind with it even though it is a patch. Don't know why. Isolating it makes it easier.
I also updated `tailwindcss` to match `@tailwindcss/vite` & `@tailwindcss/postcss.` With this they would all be 4.0.8.
> chore: isolate tailwind dependency

- packages/quantic/force-app/main/default/lwc/quanticGeneratedAnswer/quanticGeneratedAnswer.js
This field shows as required in the generated doc and I assume its because no default value was specified.
> fix(quanticDocs): answer config id default value

- packages/headless/src/app/case-assist-engine/case-assist-engine.test.ts
- packages/headless/src/app/case-assist-engine/case-assist-engine.ts
- packages/headless/src/app/engine.ts
- packages/headless/src/app/insight-engine/insight-engine.test.ts
- packages/headless/src/app/insight-engine/insight-engine.ts
- packages/headless/src/controllers/generated-answer/headless-generated-answer.test.ts
- packages/headless/src/controllers/generated-answer/headless-generated-answer.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.test.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
- packages/headless/src/controllers/smart-snippet-questions-list/headless-smart-snippet-questions-list.test.ts
- packages/headless/src/controllers/smart-snippet-questions-list/headless-smart-snippet-questions-list.ts
- packages/headless/src/controllers/smart-snippet/headless-smart-snippet.test.ts
- packages/headless/src/controllers/smart-snippet/headless-smart-snippet.ts
We are noticing an increasing number of clients that miss-configure their Quantic and Atomic interfaces by enabling the Event Protocol for analytics reporting while using the Coveo For Service feature.
These Coveo For Service can be identified as the following:
- Insight Panel.
- Case Assist.
- CRGA.
- Smart Snippets
Having Clients use EP while using these features is dangerous as all events schemas for these feature are not set in stone and are not GA,  and are likely to change considerably overtime, so having clients logging their events EP could expose them to various breaking changes.
While we are limited to what we can do in this situation because we wanna avoid breaking changes, the solution here is by  raising awareness about this problem by logging this big message whenever we …
> fix(headless): started logging a warning message when event protocol is used for coveo for service features

- packages/quantic/force-app/main/default/lwc/quanticQuickviewContent/quanticQuickviewContent.js
- packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.html
- packages/quantic/force-app/main/default/lwc/quanticResultQuickview/quanticResultQuickview.js
This issue started to happen after adding `quantic__` as  prefix for the event names sent from Quantic. the event `loadingstatechange` was forgotten.
so the fix was going from `onloadingstatechange` to `onquantic___loadingstatechange`.
This should be tested as part of the following PR: https://github.com/coveo/ui-kit/pull/5087
https://github.com/user-attachments/assets/58645022-ec32-4ac1-a061-1f91d9e210ef
https://github.com/user-attachments/assets/e6f03b74-6040-49aa-9796-c06c4c672cc2
[SFINT-6042]: https://coveord.atlassian.net/browse/SFINT-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): fixed how the quantic__loadingstatechange event is handled 

- packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.spec.tsx
- packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.tsx
Adapt the `atomic-tab-manager.tsx` component to use the i18n library for localization of the `label` and `name` parameters.
* Update the `label` and `name` properties to use `this.bindings.i18n.t` for localization.
* Add a new test file `atomic-tab-manager.spec.tsx` to check if the `label` and `name` parameters are localized using `bindings.i18n.t`.
https://coveord.atlassian.net/browse/KIT-4051
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/coveo/ui-kit/pull/5071?shareId=d7b4bdc1-b90a-48ba-bffd-f069c24e16cf).
> feat(atomic): localize tab name & label

- packages/quantic/.npmignore
- packages/quantic/package.json
- Made sure test folders excluded from quantic npm package.
- previously the paths to the tests folder `.npmignore` have been overridden by the files specified in the `package.json`. 
[SFINT-6078]: https://coveord.atlassian.net/browse/SFINT-6078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): made sure test folders are excluded from quantic npm package

- packages/quantic/force-app/main/default/lwc/quanticNumberButton/quanticNumberButton.html
- Unneeded key attribute removed from quantic number button  element
[SFINT-5985]: https://coveord.atlassian.net/browse/SFINT-5985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): unneeded key attribute removed from quantic number button  element

- packages/atomic/src/mixins/children-update-complete-mixin.spec.ts
- packages/atomic/src/mixins/children-update-complete-mixin.ts
This PR adds a mixin that can be used on Lit components to override their getUpdateComplete method so that the component can wait for its children to be ready (with `updateComplete` for Lit components, and `componentOnReady()` for Stencil components)
https://lit.dev/docs/components/lifecycle/#getUpdateComplete
https://coveord.atlassian.net/browse/KIT-4073
> chore(atomic): add ChildrenUpdateCompleteMixin mixin

- packages/atomic/package.json
- packages/headless/package.json
https://coveord.atlassian.net/browse/KIT-4041
Making typescript 5 an optional peer deps because of moduleResolution only being available in typescript 5 +
> chore(atomic, headless): make typescript 5 an optional peer dependency

- packages/headless-react/src/ssr-commerce/commerce-engine.tsx
- packages/headless-react/src/ssr-commerce/providers.tsx
[DOC-16854](https://coveord.atlassian.net/browse/DOC-16854)
Certain links in the TypeDoc site were showing up in a duplicated format:
i.e.
https://docs.coveo.com/en/headless-react/latest/reference/functions/docs.coveo.com/en/obif0156#define-the-commerce-engine-and-controllers
When they should have been in the format:
https://docs.coveo.com/en/obif0156#define-the-commerce-engine-and-controllers
The comments these links were pulled from were missing the scheme, "https://", and thus showing up in the above formatting. Upon adding the missing scheme to the links, they functioned again as expected.
[DOC-16854]: https://coveord.atlassian.net/browse/DOC-16854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(headless-react): address broken typedoc links

- packages/atomic/src/components/common/button.spec.ts
- packages/atomic/src/components/common/button.ts
- packages/atomic/src/components/common/heading.spec.ts
- packages/atomic/src/components/common/heading.ts
- packages/atomic/src/components/common/load-more/button.ts
- packages/atomic/src/utils/functional-component-utils.ts
https://coveord.atlassian.net/browse/KIT-4081
Removing 'children' from the interface to make it easier to read render functions in larger sets of functional lit components.
> chore(atomic): remove 'children' from FunctionalComponentWithChildren interface

- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.test.ts
- packages/headless/src/features/generated-answer/generated-answer-slice.ts
- packages/headless/src/features/generated-answer/utils/generated-answer-citation-utils.test.ts
- packages/headless/src/features/generated-answer/utils/generated-answer-citation-utils.ts
Reverted this PR change https://github.com/coveo/ui-kit/commit/09ca081702d364d1379cc4cd7fc70747ee069652 and added the same citation duplicate filter logic from the reducer in the controller in order to fix the bug where the citations are not reset correctly.
[SVCC-4945](https://coveord.atlassian.net/browse/SVCC-4945)
Demo showing that there is no citation duplications and the generated answer component disappear correctly when resetting the query: https://github.com/user-attachments/assets/db0c594d-bb5c-434c-9b9b-cafae814eca6
[SVCC-4945]: https://coveord.atlassian.net/browse/SVCC-4945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(generated answer): fix citations not being reset correctly when clearing the query

- packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/__tests__/quanticBreadcrumbManager.test.js
- packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.html
- packages/quantic/force-app/main/default/lwc/quanticBreadcrumbManager/quanticBreadcrumbManager.js
Breadcrumb values were not displayed correctly when a numeric filter or a date filter were selected.
this is because the filters are registered in the Headless state always with the facet id of the facet that owns the filter in addition to the suffix `_input`:
https://github.com/coveo/ui-kit/blob/bbb30961fedc4168dcae81aad561f5c864d7c4a5/packages/quantic/force-app/main/default/lwc/quanticNumericFacet/quanticNumericFacet.js#L340-L344
https://github.com/coveo/ui-kit/blob/bbb30961fedc4168dcae81aad561f5c864d7c4a5/packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.js#L490-L492
However, in the Quantic store, only the facet id of the facet that owns the filter is stored.
In order to get the necessary data to display the breadcrumbs for a filter, we need to …
> fix(quantic): breadcrumb value not displayed for date and numeric filters

- packages/quantic/cypress/e2e/facets-2/timeframe-facet/timeframe-facet.cypress.ts
- packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/__tests__/quanticTimeframeFacet.test.js
- packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.html
- packages/quantic/force-app/main/default/lwc/quanticTimeframeFacet/quanticTimeframeFacet.js
This PR addresses the issue described in [Jira: Quantic Timeframe Facet filter input is always displayed](https://coveord.atlassian.net/browse/SFINT-6077), where the **timeframe facet** displays the date picker inputs even when it doesn’t contain any facet values. This leads to unnecessary UI elements being shown when the facet field is irrelevant due to applied filters.
https://github.com/user-attachments/assets/735d4deb-18ac-4a79-bcdb-dba0fcefb0f1
When the `with-date-picker` property is set to `true`, the date filter inputs **should only be displayed when the filter is actually applicable and can filter the current result set**.
Introduced a new computed property to determine when to show the date picker:
```ts
/**
* Indicates whether to display the date picker.
*/
get …
```
> fix(quantic): improved condition that indicates when to display timeframe facet 

- packages/atomic/src/converters/boolean-converter.spec.ts
- packages/atomic/src/converters/boolean-converter.ts
https://coveord.atlassian.net/browse/KIT-3972
By default, with Lit, boolean attributes need to be omitted to be converted to `false`. `attribute="false"` is considered `true`. This is different from Stencil where attribute="false" is considered `false`. This PR adds a boolean converter so that `attribute="false"` gets converted to `false` and so we don't make breaking changes.
> chore(atomic): add a boolean converter for Lit

- .eslintrc.js
- package-lock.json
- packages/atomic-angular/scripts/build-lit.mjs
- packages/atomic/scripts/build.mjs
- packages/atomic/scripts/generate-lit-exports.mjs
- packages/atomic/scripts/process-css.mjs
- packages/atomic/src/components/commerce/index.ts
- packages/atomic/src/components/commerce/lazy-index.ts
- packages/atomic/src/components/common/index.ts
- packages/atomic/src/components/common/lazy-index.ts
- packages/atomic/src/components/index.ts
- packages/atomic/src/components/insight/index.ts
- packages/atomic/src/components/insight/lazy-index.ts
- packages/atomic/src/components/ipx/index.ts
- packages/atomic/src/components/ipx/lazy-index.ts
- packages/atomic/src/components/lazy-index.ts
- packages/atomic/src/components/recommendations/index.ts
- packages/atomic/src/components/recommendations/lazy-index.ts
- packages/atomic/src/components/search/index.ts
- packages/atomic/src/components/search/lazy-index.ts
- packages/atomic/stencil-plugin/atomic-angular-module/index.ts
- packages/atomic/stencil-proxy/cjs/loader.cjs.js
- packages/atomic/stencil-proxy/esm/index.js
- packages/atomic/stencil-proxy/esm/loader.js
- packages/samples/iife/build-assets.mjs
- packages/samples/iife/package.json
This PR add a step to the Lit component build script that will automatically update the index.ts and lazy-index.ts files when Lit components are added/removed.
It also improves the console output for the build script
https://coveord.atlassian.net/browse/KIT-4090
> chore(atomic): improve build for lit components

- packages/atomic/scripts/process-css.mjs
Tailwind generates some utilities that has escaped characters:
```css
.py-3\.5 {
...
}
.py-\[50px\] {
...
}
```
Since Lit CSS templates use the same character to escape special characters, these utilities do not work currently.
This PR escapes the backslashes to fix this issue. 
https://coveord.atlassian.net/browse/KIT-4101
> chore(atomic): escape backslashes in css

- packages/atomic-react/scripts/build-lit.mjs
- packages/atomic/scripts/build.mjs
- packages/atomic/scripts/dev.mjs
- packages/atomic/scripts/format-with-prettier.mjs
- packages/atomic/scripts/generate-component.mjs
- packages/atomic/scripts/generate-lit-exports.mjs
https://coveord.atlassian.net/browse/KIT-4090
Currently building Lit results in a uncommitted file because the generated files are not being formatted by prettier. 
This PR fixes that and formats index & lazy-index files.
> chore(atomic): prettier generated lit files

- packages/atomic-hosted-page/src/autoloader/index.ts
- packages/atomic/src/autoloader/index.ts
Ensures discovery logic runs after DOMContentLoaded
Wraps discovery logic in a function to improve readability
and registers it to execute after DOMContentLoaded.
Handles cases where the document is already loaded.
Improves reliability of dynamic element detection.
KIT-4094
https://coveord.atlassian.net/browse/KIT-4094
> fix(autoloader): wrap initial discovery and observer setup in DOMContentLoaded event

- .deployment.config.json
Hi there 🤠!
In order to make the config easier to use in the context of the Multi-Account Framework, we are running 🏃‍️🎽👟 a script to migrate deployment configurations!
While the change is not breaking 💥 since the revise is done automatically when you create a package 📦, updating your code will just make it so that you don't have drift 🏎️ between the config you submit and what the pipeline actually see 👀.
See [the announcement 📢 in Confluence](https://coveord.atlassian.net/wiki/spaces/CM/pages/5024317641/Deployment+Config+version+19+Changes+for+Overrides+and+more) for the details
The script also updates `deployment_config_version` so that it does not need to run every time 🕛️ you create a package in the future. Please forgive any formatting changes as those are hard to avoid 🙏.
I hope you …
> chore(pipeline): Migrate deployment configuration of ui-kit [DT-7842]

- packages/atomic/package.json
- packages/atomic/project.json
- packages/quantic/package.json
- packages/quantic/project.json
Move the tests orchestration to `nx`, this allow to ensure tasks are parallelized when they could, and that their dependencies runs when they should
This should help with `ENOENT: no such file or directory, open '../../node_modules/@coveo/headless/dist/quantic/headless.js` error that happens in UT.
> chore(atomic,quantic): move tests scripts orchestrations to nx

- packages/atomic/src/components/insight/atomic-insight-interface/e2e/atomic-insight-interface.e2e.ts
- packages/atomic/src/components/insight/atomic-insight-interface/e2e/page-object.ts
- Introduces a helper method to ensure results are visible before tests in the refine modal suite.
- Enhances test reliability by preventing race conditions during execution.
Without this, we may click the filter button _before_ the first search is completed and/or the interface is fully loaded.
https://coveord.atlassian.net/browse/SVCC-5059
> test(insight): adds wait for results in refine modal tests

- packages/atomic/src/utils/init-queue.ts
- packages/atomic/src/utils/initialization-lit-stencil-common-utils.ts
- packages/atomic/src/utils/initialization-utils.tsx
This PR fixes an issue preventing initialization of lit components when using the initializeBindingsMixin mixin to retrieve bindings.
https://coveord.atlassian.net/browse/KIT-4161
> chore(atomic): fix init issue for lit components when using initializeBindingsMixin

- packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.test.ts
- packages/headless/src/features/commerce/facets/facet-set/facet-set-slice.ts
- packages/headless/src/features/facets/facet-set/facet-set-slice.test.ts
- packages/headless/src/features/facets/facet-set/facet-set-slice.ts
This PR ensures that when selecting a facet search value, the first idle value does not get replaced by it. Instead, the new value will be inserted before the first idle value, pushing each other values down, with the last one getting removed.
When there are no idle values the new value will get added after the last active value, as was the case before.
Before:
After:
> fix(headless): prevent selected facet search values from replacing idle values

- packages/atomic/src/utils/accessibility-utils.spec.ts
- packages/atomic/src/utils/accessibility-utils.ts
https://coveord.atlassian.net/browse/KIT-4143
```
@AriaLiveRegion('search-box')
protected searchBoxAriaMessage!: string;
```
```
protected searchBoxAriaMessage = new AriaLiveRegionController(
this,
'search-box'
);
```
> chore(atomic): replace AriaLiveRegion decorator with a lit controller

- packages/headless/src/controllers/core/facets/range-facet/date-facet/headless-date-facet-options.ts
- packages/headless/src/controllers/core/facets/range-facet/numeric-facet/headless-numeric-facet-options.ts
- packages/headless/src/controllers/dictionary-field-context/headless-dictionary-field-context.ts
- packages/headless/src/features/dictionary-field-context/dictionary-field-context-state.ts
- packages/headless/src/features/facets/range-facets/date-facet-set/date-facet-actions.ts
- packages/headless/src/features/facets/range-facets/numeric-facet-set/numeric-facet-actions.ts
- packages/headless/src/state/state-sections.ts
[DOC-17007](https://coveord.atlassian.net/browse/DOC-17007)
A few field pages are changing on docs.coveo.com and it will affect links.
To be merged after https://github.com/coveo/doc_jekyll-public-site/pull/13160
[DOC-17007]: https://coveord.atlassian.net/browse/DOC-17007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(headless,atomic): link updates

- packages/samples/headless-commerce-ssr-remix/app/components/parameter-manager.tsx
- packages/samples/headless-commerce-ssr-remix/app/components/search-box.tsx
- packages/samples/headless-commerce-ssr-remix/app/hooks/use-recent-queries.ts
- packages/samples/headless-react/src/components/recent-queries/recent-queries.class.tsx
- packages/samples/headless-react/src/components/recent-queries/recent-queries.fn.tsx
- packages/samples/headless-ssr-commerce-nextjs/components/recent-queries.tsx
- packages/samples/headless-ssr-commerce-nextjs/components/search-box.tsx
- packages/samples/headless-ssr-commerce-nextjs/hooks/use-recent-queries.ts
This PR adds recent queries persistence to the headless-commerce-ssr-remix, headless-react and headless-commerce-ssr samples.
https://coveord.atlassian.net/browse/KIT-4136
> chore(headless-react, headless-commerce-ssr): persist recent queries in headless react samples

- .github/workflows/cron-release.yml
- .github/workflows/manual-release.yml
- .github/workflows/release.yml
Adjusts the release workflow schedule to trigger at 02:00 UTC on Wednesdays, aligning with 21:00 ETC on Tuesdays for improved timing suitability.
> chore: release workflow cron schedule

- packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.ts
- packages/atomic/src/components/common/interface/i18n-stencil.ts
- packages/atomic/src/components/common/interface/interface-common-stencil.tsx
- packages/atomic/src/components/common/interface/interface-common.ts
This PR fixes an issue with Lit component interfaces where the wrong path would be used to retrieve the language assets, for example with the CDN build of atomic.
https://coveord.atlassian.net/browse/KIT-4186
> fix(atomic): ensure correct path for locales

- packages/quantic/force-app/main/default/lwc/jsconfig.json
- packages/quantic/force-app/main/default/lwc/quanticAriaLive/__tests__/quanticAriaLive.test.js
- Added Jest  unit tests for the Quantic Aria Live component.
[SFINT-6069]: https://coveord.atlassian.net/browse/SFINT-6069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(quantic): added unit tests for quantic aria live

- .deployment.config.json
Disable the deployment of atomic, atomic storybook, and atomic react on their major & minor directories (vX & vX.Y)
https://coveord.atlassian.net/browse/KIT-4208
> chore: disable cdn deployment for atomic

- .github/workflows/manual-release.yml
From what I understand from [GitHub Doc](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example-returning-a-json-data-type), we need to coerce all contextual values because they are passed along as "literals", thus losing their 'typing'.
> chore: use fromJSON to coerce values

- packages/headless/src/api/knowledge/post-answer-evaluation.ts
https://coveord.atlassian.net/browse/SVCC-4958
Submitting a CRGA feedback throws in the console. This has to be fixed
The way [redux toolkit query](https://redux-toolkit.js.org/rtk-query/overview) handles mutations is unknown and not really documented
During the initial implementation, the implementer (me) wrongly assumed that a HTTP post had to be handled with a `builder.mutation`. Seems like its not the case. 
Using `builder.mutation` throws, while using `builder.query` doesn't throw. I couldn't find why by looking at the documentation or by debugging directly in the lib.
Load the RGA demo and submit a feedback
[simplescreenrecorder-2025-05-01_11.46.46.webm](https://github.com/user-attachments/assets/b4857925-12b0-4c54-bc53-a47578aee786)
I do not think we really have a way to test this.
> fix(answerAPI): post feedback

- package-lock.json
- packages/headless/package.json
Relay support custom environments (see https://github.com/coveo-platform/relay/pull/158), enabling it to work in non browser environments. Headless currently does not support this option. This PR adds support for custom relay environments through headless, enabling relay to work correctly in non browser environments.
In particular this option will be used by the shopify package in order to support hydrogen style implementations.
We will utilise the `generateUUID` option, to enable us to properly generate a client id for shopify visitors, rather than dropping a cookie, which will only work in the browser.
UPDATE:
Rather than adding an additional option, we will try to update relay after initialization. This is to avoid making the headless arguments more complicated since they already have …
> feat(headless): add support for custom relay environments

- packages/atomic/src/autoloader/index.ts
We need to go through all elements because Stencil lazy-loader eagerly define the element in the registry
> fix(atomic): ensure **all** custom-elements are scanned

- packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.new.stories.tsx
- packages/atomic/src/components/commerce/atomic-commerce-search-box/e2e/atomic-commerce-search-box.e2e.ts
- packages/atomic/src/components/commerce/atomic-commerce-text/atomic-commerce-text.new.stories.tsx
- packages/atomic/src/components/commerce/search-box-suggestions/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.new.stories.tsx
- packages/atomic/src/components/common/suggestions/suggestions-common.ts
- packages/atomic/storybook-utils/commerce/commerce-search-box-wrapper.tsx
Reuse the mechanism from `children-update-complete-mixin.ts` to ensure the listener is registered before shooting the event.
> test(atomic): improve stability around suggestions/sb

- packages/atomic/src/components/common/pager/pager-buttons.ts
If we don't; the `atomic-icon` might be missing.
> fix(atomic): add missing import in atom

- .github/workflows/prbot.yml
- packages/atomic/src/components/commerce/atomic-commerce-interface/store.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-sort-dropdown/atomic-commerce-sort-dropdown.ts
- packages/atomic/src/components/context/bindings-context.ts
If we don't, the consumer may shoot first, and their request may be lost to the wind
> fix(atomic): ensure context root is declared when context is used

- packages/atomic/src/components/insight/result-templates/atomic-insight-result-children-template/atomic-insight-result-children-template.tsx
- packages/atomic/src/components/insight/result-templates/atomic-insight-result-template/atomic-insight-result-template.tsx
- packages/atomic/src/components/recommendations/atomic-recs-result-template/atomic-recs-result-template.tsx
- packages/atomic/src/components/search/result-templates/atomic-result-children-template/atomic-result-children-template.tsx
- packages/samples/angular/src/app/app-routing.module.ts
- packages/samples/angular/src/app/app.component.html
- packages/samples/angular/src/app/app.module.ts
- packages/samples/angular/src/app/atomic-angular-recommendation-page/atomic-angular-recommendation-page.component.css
- packages/samples/angular/src/app/atomic-angular-recommendation-page/atomic-angular-recommendation-page.component.html
- packages/samples/angular/src/app/atomic-angular-recommendation-page/atomic-angular-recommendation-page.component.ts
https://coveord.atlassian.net/browse/KIT-4224
The `atomic-recs-result-template` was throwing errors in Angular because its host element's parent wasn't defined when we were creating the `ResultTemplateCommon` instance in the constructor.
I applied the same fix to `atomic-recs-result-template` that was applied to `atomic-result-template` here: https://github.com/coveo/ui-kit/pull/5070/files#diff-869c29501cc46796f3035d2f9e0b3d564509824dd998c0c24d49efe4f2dd0423, i.e., creating he `ResultTemplateCommon` instance in the component's `connectedCallback` instead of in the constructor.
I also included a recommendation interface in the Angular sample.
For good measure, I preemptively applied the fix to other result template components that create `ResultTemplateCommon` instances …
> fix(atomic): fix atomic-recs-result-template rendering error

- .deployment.config.json
This reverts commit e35ccc371361c13b0bb1b2ba9f817a82120ad26e & reenable CDN deployment of Atomic.
KIT-4209
> chore: reenable deployment of major & minor directories

- .github/workflows/release.yml
Despite the "skipped" approval, ensure the subsequent task (e.g. npm-prod) are not skipped
https://coveord.atlassian.net/browse/KIT-4236
> chore: ensure "dependent" tasks runs on CRON

- README.md
- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api-state-mock.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api.test.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
[SVCC-5073](https://coveord.atlassian.net/browse/SVCC-5073) The `analytics` request body parameter is not forwarded to the Answer API's `generate` endpoint.
* Adds the analytics data to the payload sent to /generate on the Answer API.
* Modify how RTK Query serializes our `getAnswer` endpoint to exclude serialization of the `clientTimestamp`. We're using that state in the key to the Redux store.
Headless.
Once this PR is approved, I'll have to backport the fix into V2.
[SVCC-5073]: https://coveord.atlassian.net/browse/SVCC-5073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(headless): analytics body param not forwarded

- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api-state-mock.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api.test.ts
- packages/headless/src/features/search/search-request.ts
- packages/headless/src/features/static-filter-set/static-filter-set-selectors.test.ts
- packages/headless/src/features/static-filter-set/static-filter-set-selectors.ts
[SVCC-5083](https://coveord.atlassian.net/browse/SVCC-5083) 
During the review of another PR it was found we were missing support for static filters when we call the answer API.
- Support for static filters in Advanced Search Query Parameters
- Extract `getStaticFilterExpressions` to separate file in /features
- Replace use in `search-request`. I did not replace the use in`legacy`, not sure if we should modify/update legacy since it's legacy
- Add tests for `getStaticFilterExpressions`
Run `npx nx run headless:test`
Headless.
[SVCC-5083]: https://coveord.atlassian.net/browse/SVCC-5083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: support static filters search params

- packages/atomic/src/components/common/breadbox/breadcrumb-content.tsx
- packages/atomic/src/components/common/breadbox/breadcrumb-types.ts
https://coveord.atlassian.net/browse/KIT-4259
This 'content' property was never used... Probably a relic of the past.
> chore(atomic): remove VNode type from breadcrumb interface

- packages/headless/src/features/facets/range-facets/generic/range-facet-reducers.test.ts
- packages/headless/src/features/facets/range-facets/generic/range-facet-reducers.ts
https://coveord.atlassian.net/browse/KIT-4196
The url parameters should not make every range value "idle". It should just put the values from the url as "selected". It should not touch values that are not present in the url.
Fix #5234
> fix(headless): preserve selected state for filter ranges after restore

- packages/atomic/src/components/common/smart-snippets/atomic-smart-snippet-answer/atomic-smart-snippet-answer.pcss
https://coveord.atlassian.net/browse/KIT-4276
> fix(atomic): restore smart-snippets styling to pre-Tailwind v4 appearance

- packages/atomic/src/components/common/facets/facet-value-checkbox/facet-value-checkbox.spec.ts
- packages/atomic/src/components/common/facets/facet-value-checkbox/facet-value-checkbox.ts
- packages/atomic/src/components/common/facets/facet-value-checkbox/stencil-facet-value-checkbox.tsx
- packages/atomic/src/components/common/facets/facet-value-exclude/facet-value-exclude.spec.ts
- packages/atomic/src/components/common/facets/facet-value-exclude/facet-value-exclude.ts
- packages/atomic/src/components/common/facets/facet-value-exclude/stencil-facet-value-exclude.tsx
https://coveord.atlassian.net/browse/KIT-4173
For better accessibility.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-hidden
> aria-hidden="true" should not be used on elements that can receive focus. Additionally, since this attribute is inherited by an element's children, it should not be added onto the parent or ancestor of a focusable element.
- Also refactored the two test files affected since there was an unnecessary amount of lines
- Also removed a bunch of unused props from facetValueExclude
> fix(atomic): move exclusion button out of aria-hidden label to restore accessibility

- packages/shopify/src/utilities/index.test.ts
- packages/shopify/src/utilities/index.ts
We would like to use the constants exported by the shopify package without importing the whole commerce module. This is to reduce the size of the webpixel package.
> feat(shopify): export constants in utils package

- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api-state-mock.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api.test.ts
https://coveord.atlassian.net/browse/SVCC-5134
Fixes an issue where undefined would be appended to `cq` when `cq` was empty in `loadAdvancedSearchQueryActions`.
Before:
After:
To test:
in `tabs.html`, add advanced queries actions:
```
<script type="module">
import {loadAdvancedSearchQueryActions} from 'https://static.cloud.coveo.com/atomic/v1/headless/headless.esm.js';
...
const advQueriesActions = loadAdvancedSearchQueryActions(searchInterface.engine);
searchInterface.engine?.dispatch(
advQueriesActions.updateAdvancedSearchQueries({
aq: '@fileType=html',
cq: '',
dq: '',
lq: '',
})
);
```
Also add an `<atomic-generated-answer>` component on line 225 of the same file:
```
<atomic-generated-answer
answer-configuration-id="fc581be0-6e61-4039-ab26-a3f2f52f308f"
></atomic-generated-answer>
``` …
> fix(headless): ensure cq is defined before appending it to expressions

- .github/workflows/prbot.yml
- packages/atomic/src/components/commerce/atomic-commerce-search-box-instant-products/atomic-commerce-search-box-instant-products.new.stories.tsx
- packages/atomic/src/components/commerce/atomic-commerce-search-box-query-suggestions/atomic-commerce-search-box-query-suggestions.new.stories.tsx
- packages/atomic/src/components/commerce/atomic-commerce-search-box-recent-queries/atomic-commerce-search-box-recent-queries.new.stories.tsx
- packages/atomic/storybook-utils/common/search-box-suggestions-parameters.ts
https://coveord.atlassian.net/browse/KIT-4298
so it has more space
> docs(atomic): better spacing for search box suggestions storybook doc

- packages/headless-react/.eslintrc.cjs
- packages/headless-react/project.json
- packages/headless-react/src/client-utils.test.tsx
- packages/headless-react/src/ssr-commerce/commerce-engine.test.tsx
- packages/headless-react/src/ssr-commerce/commerce-engine.tsx
- packages/headless-react/src/ssr-commerce/common.test.tsx
- packages/headless-react/src/ssr-commerce/common.tsx
- packages/headless-react/src/ssr-commerce/providers.tsx
- packages/headless-react/src/ssr-commerce/types.ts
- packages/headless-react/src/ssr/common.test.tsx
- packages/headless-react/src/ssr/common.tsx
- packages/headless-react/src/ssr/search-engine.test.tsx
- packages/headless-react/src/ssr/search-engine.tsx
- packages/headless-react/src/ssr/types.ts
- packages/headless-react/tsconfig.build.json
- packages/headless-react/tsconfig.json
The current provider has a fundamental flaw: When we change the parent element where the children are rendered, the children are remounted.
To solve this, I mashed up the static & hydrated provider together essentially.
And while at it, I reckon we should deprecate the hydrated & static because they alone are a bit useless IMO compared to the "isomorphic" one.
> fix(headless-ssr-react): ensure provider's children are not remounted on hydration

- packages/headless/src/app/commerce-ssr-engine/factories/static-state-factory.test.ts
- packages/headless/src/app/commerce-ssr-engine/factories/static-state-factory.ts
- packages/headless/src/app/navigator-context-provider.ts
- packages/headless/src/app/search-engine/search-engine.ssr.test.ts
- packages/headless/src/app/search-engine/search-engine.ssr.ts
- packages/headless/src/app/ssr-engine/augment-preprocess-request.test.ts
- packages/headless/src/app/ssr-engine/augment-preprocess-request.ts
- packages/headless/src/test/mock-navigator-context-provider.ts
- packages/samples/headless-commerce-ssr-remix/lib/navigator-context.ts
- packages/samples/headless-ssr-commerce-nextjs/lib/navigatorContextProvider.ts
- packages/samples/headless-ssr/app-router/src/navigatorContextProvider.ts
- packages/samples/headless-ssr/common/lib/navigatorContextProvider.ts
- packages/samples/headless-ssr/pages-router/src/navigatorContextProvider.ts
Updates `NavigatorContext` to include a `forwardedFor` field so the X-Forwarded-For header can be automatically injected at `preprocessRequest`.
⸻
https://coveord.atlassian.net/browse/KIT-4294
> feat(headless SSR): augment request with x-forwarded-for header

- packages/quantic/cypress/e2e/default-2/search-box/search-box-selectors.ts
- packages/quantic/cypress/e2e/default-2/standalone-search-box/standalone-search-box-selectors.ts
- packages/quantic/force-app/examples/main/lwc/actionLocalStorage/actionLocalStorage.html
- packages/quantic/force-app/examples/main/lwc/actionLocalStorage/actionLocalStorage.js
- packages/quantic/force-app/examples/main/lwc/actionLocalStorage/actionLocalStorage.js-meta.xml
- packages/quantic/force-app/examples/main/lwc/exampleQuanticSearchBox/exampleQuanticSearchBox.html
- packages/quantic/force-app/examples/main/lwc/exampleQuanticSearchBox/exampleQuanticSearchBox.js
- packages/quantic/force-app/main/default/lwc/quanticPager/e2e/fixture.ts
- packages/quantic/force-app/main/default/lwc/quanticPager/e2e/quanticPager.e2e.ts
- packages/quantic/force-app/main/default/lwc/quanticResultList/e2e/fixture.ts
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/__tests__/quanticSearchBoxInput.test.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/templates/defaultSearchBoxInput.html
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxInput/templates/expandableSearchBoxInput.html
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxSuggestionsList/__tests__/quanticSearchBoxSuggestionsList.test.js
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxSuggestionsList/e2e/fixture.ts
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxSuggestionsList/e2e/pageObject.ts
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxSuggestionsList/e2e/quanticSearchBoxSuggestionsList.e2e.ts
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxSuggestionsList/quanticSearchBoxSuggestionsList.html
- packages/quantic/force-app/main/default/lwc/quanticSearchBoxSuggestionsList/quanticSearchBoxSuggestionsList.js
- packages/quantic/force-app/main/default/lwc/quanticStandaloneSearchBox/templates/standaloneSearchBox.html
- packages/quantic/playwright/page-object/analytics.ts
- packages/quantic/playwright/page-object/querySuggestObject.ts
- packages/quantic/playwright/page-object/searchObject.ts
- packages/quantic/playwright/utils/requests.ts
- Added unit tests for the QuanticSearchBoxSuggestionsList
- Added e2e tests for the QuanticSearchBoxSuggestionsList (leveraging the exampleSearchbox page)
- Created a new ActionLocalStorage LWC to be used in tests to read/set a value in the localStorage, this allows us to correctly handle the localStorage even between the different versions of LockerService and Lightning Web Security.
- Created a new QuerySuggestObject to use in tests to intercept and mock calls to the /querysuggest API.
- Updated some other tests that were testing the same stuff I was adding, 
- for example, modified the QuanticSearchboxInput tests to remove the tests that were testing the rendering of querySuggestions, to instead test that the right data is passed to the QuanticSearchBoxSuggestionsList component. …
> test(quantic): Tests for QuanticSearchBoxSuggestionsList

- packages/atomic/src/decorators/light-dom.spec.ts
- packages/atomic/src/decorators/light-dom.ts
- packages/atomic/src/mixins/bindings-mixin.ts
- packages/atomic/src/mixins/children-update-complete-mixin.ts
- packages/atomic/src/mixins/commerce-layout-mixin.spec.ts
- packages/atomic/src/mixins/commerce-layout-mixin.ts
- packages/atomic/src/mixins/mixin-common.ts
Added the `CommerceLayoutMixin` for Lit components, which automatically injects dynamic layout styles and manages the layout breakpoint. 
Instead of manually injecting styles and IDs in lifecycle hooks, components can now simply extend the mixin:
The mixin handles:
- Unique ID assignment
- Dynamic and static style injection
- Consistent mobileBreakpoint management
This results in cleaner, more reusable, and more maintainable layout components.
```tsx
export class MyElement implements InitializableComponent<Bindings> {
@InitializeBindings() public bindings!: Bindings;
public componentDidLoad() {
const id = this.host.id || randomID('atomic-commerce-layout-');
this.host.id = id;
const styleSheet = new CSSStyleSheet();
styleSheet.replaceSync(
buildCommerceLayout(this.host, …
```
> chore(atomic): add commerce-layout mixin

- packages/atomic/src/components/common/search-box/submit-button.spec.ts
- packages/atomic/src/components/common/search-box/submit-button.ts
https://coveord.atlassian.net/browse/KIT-4344
I dont like extending from a partial buttonProps as it can lead to forgotten props. `disabled` and `title` were forgotten since in stencil we were doing a destructuring `...otherProps
`
> chore: add missing props in renderSubmitButton

- packages/atomic/src/components/commerce/atomic-commerce-query-summary/atomic-commerce-query-summary.tsx
- packages/atomic/src/components/search/atomic-query-summary/atomic-query-summary.tsx
https://coveord.atlassian.net/browse/KIT-4358
It's a mistake, there is no "results" part in this component.
> chore(atomic): remove "results" part from query-summary components

- packages/atomic/src/components/commerce/atomic-commerce-breadbox/e2e/atomic-commerce-breadbox.e2e.ts
This PR updates the atomic-commerce-breadbox e2e test to reflect backend data changes that have modified the facet structure.
- Updated expected breadcrumb text from `Color:${firstValueText}` to `Brand:${firstValueText}` in the e2e test
- This change aligns the test expectations with the actual facet structure now being used in the commerce breadbox component
Backend data changes have modified the facet structure, requiring test updates to match the new expected behavior. The test was previously expecting "Color:" as the facet label but the actual implementation now uses "Brand:".
The e2e test should now pass with the corrected expectation.
---
Related Jira Issue: [KIT-4373](https://coveord.atlassian.net/browse/KIT-4373)
[KIT-4373]: …
> test(atomic): update breadbox e2e test for backend data changes

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/commerce/atomic-commerce-no-products/atomic-commerce-no-products.tsx
- packages/atomic/src/components/search/atomic-no-results/atomic-no-results.tsx
This PR addresses KIT-4377 by documenting the undocumented slot in no-items components.
- Added `@slot default` documentation to `atomic-no-results` component
- Fixed component name in JSDoc for `atomic-commerce-no-products` component (was incorrectly named `atomic-no-products`)
- Both components now properly document the default slot that allows additional content to be slotted inside
- Fixes KIT-4377
- Jira: https://coveord.atlassian.net/browse/KIT-4377
- Documentation changes only, no functionality affected
- The slot was already working, this just adds proper documentation for it
> docs(atomic): document slot in no-items components

- .github/instructions/general.instructions.md
- packages/atomic/.gitignore
- packages/atomic/.vscode/settings.json
Right now, it is not possible to use copilot prompts/instructions if you open a specific package, for example atomic, instead of the full ui-kit repo.
With workspace settings inside a package, it is possible to set custom paths to the prompts/instructions files
This PR adds this to the atomic package only. We can add the same file to other packages later if needed. 
https://coveord.atlassian.net/browse/KIT-4436
> chore: add support for using copilot prompts/instructions from atomic

- packages/atomic/src/components/commerce/atomic-commerce-search-box-instant-products/e2e/atomic-commerce-search-box-instant-products.e2e.ts
https://coveord.atlassian.net/browse/KIT-4448
This test is failing sometimes but rightfully so. I logged a bug to fix the behavior KIT-4449
> ci: skip rightfully failing test in instant-products

- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
- packages/headless/src/features/search/legacy/search-actions.ts
https://coveord.atlassian.net/browse/SVCC-5218
No call was ever sent to the /generate endpoint of the answer API when analytics were set to legacy mode
In the [search-actions controller](https://github.com/coveo/ui-kit/blob/fix/SVCC-5218/packages/headless/src/features/search/search-actions.ts#L118), when we are in legacy mode, we use the legacy execute search and we thus skip the setting of the action cause in the new [execute search controller](https://github.com/coveo/ui-kit/blob/fix/SVCC-5218/packages/headless/src/features/search/search-actions.ts#L126).  Since we were waiting for the actionCause to be in the store before dispatching the /generate call,  we never sent any calls.
In the legacy execute search, dispatch an update of the actionCause in the state. 
Note that we don't wait …
> fix(headless): send action cause in legacy analytics mode

- packages/atomic/src/components/commerce/atomic-product-multi-value-text/e2e/atomic-product-multi-value-text.e2e.ts
https://coveord.atlassian.net/browse/KIT-4278
It was actually probably fixed in a previous PR when `await` was added to the floating isVisible() promise.
> ci: enable back flaky test

- packages/samples/atomic-react/tests/smoke.spec.ts
https://coveord.atlassian.net/browse/KIT-4465
I was able to reproduce the flakiness locally and it gets fixed by waiting for the query summary to be rendered before doing the query.
> ci: properly fix flakiness in atomic-react tests

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components/commerce/atomic-product-text/atomic-product-text.spec.ts
- packages/atomic/src/components/commerce/atomic-product-text/atomic-product-text.ts
This PR disables shadow DOM for atomic-product-text, as it was with the stencil version. Shadow DOM was causing styling issues when using atomic-product-text inside of atomic-product-link.
https://coveord.atlassian.net/browse/KIT-4492
> chore(atomic): make atomic-product-text light dom

- biome.json
https://coveord.atlassian.net/browse/KIT-3614
Enables the noFloatingPromises rule as a warning to catch potential issues with unhandled promises in the codebase.
This will help identify places where promises are created but not properly handled (not awaited, returned, or caught), which can lead to silent failures and hard-to-debug issues.
> feat(lint): enable biome noFloatingPromises rule

- packages/create-atomic-template/package.json
- packages/create-atomic-template/project.json
- packages/create-atomic/package.json
- packages/create-atomic/project.json
Scripts were still using "CLI" release process references. This address that.
https://coveord.atlassian.net/browse/KIT-4543
> chore(ci): change create-atomic release process from cli to ui-kit

- .github/workflows/copilot-setup-steps.yml
- lint-staged.config.js
see https://docs.github.com/en/copilot/how-tos/agents/copilot-coding-agent/customizing-the-development-environment-for-copilot-coding-agent#preinstalling-tools-or-dependencies-in-copilots-environment
also, yml is not supported for fmt/lint by biome
https://coveord.atlassian.net/browse/KIT-4544
> chore: add copilot-setup-steps.yml

- packages/create-atomic-template/src/pages/index.html.hbs
- packages/create-atomic-template/stencil.config.ts
This pull request updates the `create-atomic-template` package to ensure template placeholders are used when they should. The changes primarily focus on improving flexibility in project naming and styling.
> fix(create-atomic): missing templating & update html template

- packages/quantic/force-app/solutionExamples/main/lwc/exampleInsightPanel/e2e/exampleInsightPanel.e2e.ts
[SFINT-6228](https://coveord.atlassian.net/browse/SFINT-6228)
We commented out the console.error check that was causing the test to be flaky/failing. It will be fixed next sprint by [SFINT-6227](https://coveord.atlassian.net/browse/SFINT-6227)
[SFINT-6228]: https://coveord.atlassian.net/browse/SFINT-6228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SFINT-6227]: https://coveord.atlassian.net/browse/SFINT-6227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(quantic): ignore console error check in flaky/failing test

- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.ts
- packages/atomic/src/components/search/atomic-search-box/atomic-search-box.tsx
https://coveord.atlassian.net/browse/KIT-4595
At the moment, if you select a suggestion through keyboard arrow navigation, submit a query, and then modify the search box input (e.g., by pressing backspace, or by entering characters and/or whitespaces in the input), pressing 'Enter' will not submit the query, because the `keyboardActiveDescendant` will still be set to the ID of the suggestion that was selected.
Clearing the keyboard active descendant fixes that.
> fix(atomic): clear keyboard active descendant when search box input changes due to keypress

- packages/headless/src/api/knowledge/stream-answer-api.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api-state-mock.ts
- packages/headless/src/api/knowledge/tests/stream-answer-api.test.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.test.ts
- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer.ts
- packages/headless/src/features/insight-search/insight-search-actions.ts
https://coveord.atlassian.net/browse/SVCC-5272
When using the answer-api no ua events were sent for streamingEnd, like/dislike buttons or copy to clipboard action. This was because of the way we were retrieving the data from the answerAPI request from the state. Here is the step by step explanation of the origin of the bug:
1. In [generated-answer-analytics-actions](https://github.com/coveo/ui-kit/blob/65c2238aff401a813cff3ec5c116938c1dc1c716/packages/headless/src/features/generated-answer/generated-answer-analytics-actions.ts#L353), we need to have the rgaID to be able to make the analytics call, but that `rgaID` is `undefined`
2. The reason it is `undefined` is because, when selecting the answer from the Redux Toolkit Query, we pass the `constructAnswerQueryParams(...)` to the selector. …
> fix(headless): fix ua events not firing with answer-api

- packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.test.ts
- packages/headless/src/features/facets/category-facet-set/category-facet-set-slice.ts
https://coveord.atlassian.net/browse/KIT-4608
We now set `previousState: 'idle'` on the currently selected value (and set it to undefined on its parent value if necessary) when toggling selection in a category facet.
> fix(headless): align logic for setting category facet previousState with expectations from RFC

- packages/atomic/src/components.d.ts
- packages/atomic/src/components/insight/atomic-insight-generated-answer/atomic-insight-generated-answer.tsx
- packages/atomic/src/components/search/atomic-generated-answer/atomic-generated-answer.tsx
When you set a custom `fields-to-include-in-citations` value in the `atomic-generated-answer` and `atomic-insight-generated-answer` components, the call to the backend does not include the required fields for citation anchoring to work (`filetype`).
In this PR, I edit the logic in order to always add a list of required fields to `fieldsToIncludeInCitations`, even when customers set a custom value.
https://github.com/user-attachments/assets/46ade44f-0ee4-4a30-a1d7-b65b9b6f593f
This change was tested locally by modifying the `genqa.html` file.
Line 27:
```
await searchInterface.initialize({
accessToken: '{access-token}',
organizationId: 'lbergeronsfdevt1z2624x',
environment:'dev',
search: {
pipeline: 'LBergeron RGA Wood',
},
}); 
```
Line 119:
```
<atomic-generated-answer …
```
> fix(atomic): always add fileType to the list of fieldsToIncludeInCitations

- packages/atomic/src/components/search/tabs/atomic-tab-manager/atomic-tab-manager.tsx
https://coveord.atlassian.net/browse/KIT-4646
> doc(atomic): expose tab-popover and tab-bar parts in the atomic-tab-manager public documentation

- packages/atomic/src/utils/props-utils.ts
https://coveord.atlassian.net/browse/KIT-4639
Turns out we can simply use `type: Array`, we should deprecate to avoid searching for a solution like I did.
https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG5cbiAgQHByb3BlcnR5KClcbiAgbmFtZSA9ICdTb21lYm9keSc7XG4gIFxuICBAcHJvcGVydHkoe3R5cGU6IEFycmF5fSlcbiAgYXJyYXkgPSAnW10nXG5cbiAgcmVuZGVyKCkge1xuICAgIGNvbnNvbGUubG9nKHRoaXMuYXJyYXkpXG4gICAgcmV0dXJuIGh0bWxgPHA-SGVsbG8sICR7dGhpcy5uYW1lfSE8L3A-YDtcbiAgf …
> chore(atomic): deprecate internal ArrayProp

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/copilot-setup-steps.yml
- packages/atomic/src/noop.ts
KIT-4686
relates to https://github.com/vercel/turborepo/issues/9320
essentially, turborepo runs `git rev-parse localBranchName`,  but `actions/checkout` do not create local branches for all remote branch, especially in `pull_request` where no branch (I think) are created, given that we are checking out a detached head.
> chore: fix affected in ci

- .github/workflows/cd.yml
- .github/workflows/copilot-setup-steps.yml
Been overzealous; on the workflow changed in this pr, `main` exists already, so the git branch fails. see https://github.com/coveo/ui-kit/actions/runs/16755155429/job/47435786385 for example
> chore: remove turborepo workaround on non-pr workflow

- packages/atomic/scripts/build.mjs
- packages/atomic/scripts/process-css.mjs
This PR changes the CSS processing step of the build process to allow using [CSSStyleSheets] (https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet) instead of CSS files for lit component styles.
This works with both separate files or inline styles. It is also still possible to use normal CSS files like before.
`atomic-product-multi-value-text.tw.css`
```css
:host {
> ul {
display: flex;
list-style: none;
margin: 0;
padding: 0;
li {
display: inline-block;
}
}
}
.separator {
&::before {
display: inline;
content: ",\00a0";
}
}
```
`atomic-product-multi-value-text.ts`
```typescript
...
import styles from './atomic-product-multi-value-text.tw.css';
@customElement('atomic-product-multi-value-text')
@bindings()
@withTailwindStyles
export class AtomicProductMultiValueText
extends …
```
> chore(atomic): add postcss/tailwindcss support for CSSStylesheets

- packages/atomic/scripts/build.mjs
- packages/atomic/scripts/process-css.mjs
- packages/atomic/src/components/commerce/atomic-product-multi-value-text/atomic-product-multi-value-text.ts
- packages/atomic/src/utils/tailwind.global.tw.css
This PR fixes an issue where the base font size defined in tailwind.global.tw.css would take precedence over the font size `atomic-product-multi-value-text`, because it comes from a different component, atomic-product. Due to how constructed stylesheets get applied, we can't fix this by using css layers. Instead, we need to have the styles directly on the stylesheet of `atomic-product-multi-value-text`
This one is an interesting one, as it showcases how to migrate product template component styles from `template-system.pcss` to a component's stylesheet.
For most product template components, this change will be required first:
https://github.com/coveo/ui-kit/pull/5802/files#diff-913ab5c20cb2c3af53f6e5de776c7b0cd155ecfbae2b4fdf6e241cefee4c0a91
Then you can do something like:
```css …
```
> chore(atomic): atomic-product-multi-value-text font size override not applied correctly

- turbo.json
[coveord.atlassian.net/browse/KIT-4720](https://coveord.atlassian.net/browse/KIT-4720)
Same as https://github.com/coveo/ui-kit/pull/5842 for promote.
Tho, I don't think we need the OIDC/GitHub variables, because the provenance is set when the version is published. Here, we are just moving the "latest" sticker from one place to another
> chore: allow npm env for promote/tag update

- packages/atomic/src/autoloader/index.ts
In some off-case race conditions, it is possible for the hydrated class to be added to a given stencil element before its shadowRoot is attached. This solves this race condition by observing until we find a shadowRoot (even if none may come)
https://coveord.atlassian.net/browse/KIT-4734
> fix: observer stencil more and always

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components/commerce/atomic-commerce-category-facet/atomic-commerce-category-facet.ts
- packages/atomic/src/components/commerce/atomic-commerce-facet/atomic-commerce-facet.ts
- packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.ts
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-interface/atomic-commerce-recommendation-interface.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-timeframe-facet/atomic-commerce-timeframe-facet.ts
- packages/atomic/src/components/common/atomic-facet-date-input/atomic-facet-date-input.ts
This PR removes all uses of `InitializeBindingsMixin` on atomic commerce components and replaces them with the bindings decorator, as all the interface components have been migrated to lit.
https://coveord.atlassian.net/browse/KIT-4740
> chore(atomic commerce): remove InitializeBindingsMixin on atomic commerce components

- packages/atomic/src/utils/initialization-utils.tsx
https://coveord.atlassian.net/browse/KIT-4760
`initializeBindings` should not be deprecated as it is framework-agnostic and used by custom components. Its logic is currently duplicated in `fetchBindings`. This PR removes the deprecation and refactors initializebindings to use fetchBindings
> chore(atomic): remove deprecation mark on initializeBindings

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components/commerce/atomic-product-link/atomic-product-link.ts
- packages/atomic/src/mixins/slots-for-no-shadow-dom-mixin.spec.ts
- packages/atomic/src/mixins/slots-for-no-shadow-dom-mixin.ts
- packages/atomic/src/utils/slot-utils.spec.ts
- packages/atomic/src/utils/slot-utils.ts
This PR improves and simplify the way `SlotsForNoShadowDOMMixin` works. This includes removing a second initialization step during connectedCallback, which was causing an issue when `atomic-suggestion-renderer` moves the instant products suggestions on hover/selection
https://coveord.atlassian.net/browse/KIT-4647
> fix(atomic): fix error with atomic-product-link when selecting instant product

- packages/atomic/src/components/commerce/atomic-commerce-breadbox/atomic-commerce-breadbox.ts
- packages/atomic/src/components/commerce/atomic-commerce-breadbox/atomic-commerce-breadbox.tw.css.ts
- packages/atomic/src/components/commerce/atomic-commerce-category-facet/atomic-commerce-category-facet.ts
- packages/atomic/src/components/commerce/atomic-commerce-category-facet/atomic-commerce-category-facet.tw.css.ts
- packages/atomic/src/components/commerce/atomic-commerce-facet-number-input/atomic-commerce-facet-number-input.ts
- packages/atomic/src/components/commerce/atomic-commerce-facet-number-input/atomic-commerce-facet-number-input.tw.css.ts
- packages/atomic/src/components/commerce/atomic-commerce-facet/atomic-commerce-facet.ts
- packages/atomic/src/components/commerce/atomic-commerce-facet/atomic-commerce-facet.tw.css
- packages/atomic/src/components/commerce/atomic-commerce-layout/atomic-commerce-layout.ts
- packages/atomic/src/components/commerce/atomic-commerce-layout/atomic-commerce-layout.tw.css.ts
- packages/atomic/src/components/commerce/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.ts
- packages/atomic/src/components/commerce/atomic-commerce-numeric-facet/atomic-commerce-numeric-facet.tw.css
- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.ts
- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.tw.css.ts
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.ts
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-list/atomic-commerce-recommendation-list.tw.css.ts
- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.ts
- packages/atomic/src/components/commerce/atomic-commerce-search-box/atomic-commerce-search-box.tw.css
- packages/atomic/src/components/commerce/atomic-commerce-timeframe-facet/atomic-commerce-timeframe-facet.ts
- packages/atomic/src/components/commerce/atomic-commerce-timeframe-facet/atomic-commerce-timeframe-facet.tw.css
- packages/atomic/src/components/commerce/atomic-product-link/atomic-product-link.ts
- packages/atomic/src/components/commerce/atomic-product-link/atomic-product-link.tw.css
- packages/atomic/src/components/commerce/atomic-product-link/atomic-product-link.tw.css.ts
- packages/atomic/src/components/commerce/atomic-product-rating/atomic-product-rating.ts
- packages/atomic/src/components/commerce/atomic-product-rating/atomic-product-rating.tw.css
- packages/atomic/src/components/commerce/atomic-product/atomic-product.ts
- packages/atomic/src/components/commerce/atomic-product/atomic-product.tw.css.ts
- packages/atomic/src/components/common/atomic-rating/atomic-rating.tw.css
- packages/atomic/src/components/common/item-list/styles/mixins.pcss
- packages/atomic/src/utils/coveo.tw.css
This PR converts all the component-level stylesheets for atomic commerce to css-in-js files. For stylesheets that contain a small number of styles, these are instead added directly in the static style property of their component. 
https://coveord.atlassian.net/browse/KIT-4746
> chore(atomic): convert .css.tw component stylesheets to css-in-js

- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.ts
- packages/atomic/src/components/commerce/atomic-product-children/atomic-product-children.spec.ts
- packages/atomic/src/components/commerce/atomic-product-children/atomic-product-children.ts
- packages/atomic/src/components/commerce/atomic-product-children/e2e/atomic-product-children.e2e.ts
- packages/atomic/src/components/commerce/atomic-product-children/e2e/page-object.ts
- packages/atomic/src/components/commerce/atomic-product-text/e2e/atomic-product-text.e2e.ts
- packages/atomic/src/components/commerce/atomic-product-text/e2e/page-object.ts
- packages/atomic/src/components/commerce/atomic-product/atomic-product.spec.ts
- packages/atomic/src/components/commerce/atomic-product/atomic-product.ts
https://coveord.atlassian.net/browse/KIT-4758
Problem: 
The product children are buttons and don't currently do anything when clicked. From the feedback we got, it feels like they should open the product page. 
Proposed solution: 
1. To make a template component clickable, we need to make the `link-container` available for all types of product list displays. We can achieve that by changing the `getEmptyLinkTemplateContent` call by `getLinkTemplateContent`.
2. Then for it to not be clicked in displays other than `grid`, we need to handle that logic in `atomic-product`.
3. Then to make a template component clickable, we first make the `clickLinkContainer` function public and then we can use `closest` to query it's `atomic-product` and call it's public `clickLinkContainer` function.
> fix(atomic): make product children click open the product page

- .github/workflows/ci.yml
- scripts/deploy/execute-deployment-pipeline.mjs
- utils/ci/npm-publish-package.mjs
- Replace TAG_SUFFIX by PR_NUMBER for consistency
- Remove `!cancelled()` for `prerelease-*-merge` to ensure we only release succesful merges
- Fix `execute-deployment-pipeline` to always consider the full version for paths: We do use `X.Y.Z-pre.SHA` for dev, and because of the `.slice(0,3)` we were dropping the `-pre.SHA` 🤦
> chore: fix dev ci and improve consistency in ci

- packages/create-atomic/src/plopfile.ts
https://coveord.atlassian.net/browse/KIT-4522
Plop was updated from 3.x to 4.x semi recently. With 4.x, we don't need that `customList` hack anymore.
> fix(cli): fix plop choice type to simple list

- scripts/deploy/execute-deployment-pipeline.mjs
:rage1::rage2::rage3::rage4::hurtrealbad::finnadie:
It happens that version.prerelease[0] is, always, at best `pre` and nothing more :finnadie:
> chore: ensure we use **ALL** components of the prerelesase and not only the `pre`

- packages/atomic/.storybook/preview.ts
- packages/atomic/src/autoloader/index.spec.ts
- packages/atomic/src/autoloader/index.ts
- packages/atomic/src/components/commerce/atomic-product-excerpt/atomic-product-excerpt.ts
- packages/atomic/src/components/commerce/atomic-product-template/atomic-product-template.ts
- packages/atomic/vitest.config.ts
This PR ensures that the autoloader will detect the custom elements inside `template` tags. It also removes the product template imports we had added to atomic-product-template as a workaround to this issue.
https://coveord.atlassian.net/browse/KIT-4785
> fix(atomic commerce): fix loader not detecting components in template elements

- packages/atomic/src/global/global.pcss
This PR ensures that the refine modal always disappears fully when closed, even in rare situation where it stays in view.
Ideally we would want to transition to `display:none;` on browsers that support `transition-behavior: allow-discrete;` However we cannot as firefox returns truthy for `@supports (transition-behavior: allow-discrete) ` even though it cannot transition on the display property specifically. This would cause the modal to instantly disappears instead of fading out on firefox.
Note that `aria-hidden="true"` is added to the modal when closed, so It will not be visible to screenreaders
https://github.com/mdn/browser-compat-data/issues/26155
https://coveord.atlassian.net/browse/KIT-4774
> fix(atomic): fully hide modal on close

- .github/workflows/ci.yml
This pull request updates the CI workflow conditions for pre-release jobs to improve build reliability and prevent unnecessary executions. Now, the pre-release NPM and CDN jobs will only run if the workflow has not been cancelled, the `is-valid` job succeeded, and the event is a `merge_group`.
**CI workflow improvements:**
* Updated the condition for the `prerelease-npm-merge` job in `.github/workflows/ci.yml` to require that the workflow is not cancelled, the `is-valid` job succeeded, and the event is a `merge_group`.
* Updated the condition for the `prerelease-cdn-merge` job in `.github/workflows/ci.yml` with the same checks as above.
> chore: update conditions for prerelease jobs in CI workflow

- packages/atomic/src/components/commerce/atomic-product-section-badges/atomic-product-section-badges.ts
- packages/atomic/src/components/common/template-system/cell-desktop.pcss
- packages/atomic/src/components/common/template-system/cell-mobile.pcss
- packages/atomic/src/components/common/template-system/row-desktop.pcss
- packages/atomic/src/components/common/template-system/row-mobile.pcss
- packages/atomic/src/components/common/template-system/sections/section-badges.css
- packages/atomic/src/components/common/template-system/sections/sections.css
- packages/atomic/src/components/common/template-system/template-system.pcss
- packages/atomic/src/components/common/template-system/with-sections.pcss
This PR migrates the styles for atomic-*-section-badges to custom utilities that can be used directly on the section components.
[coveord.atlassian.net/browse/KIT-4800](https://coveord.atlassian.net/browse/KIT-4800)
> chore(atomic): migrate atomic-*-section-badges styles

- packages/atomic/src/components/commerce/atomic-product-description/atomic-product-description.spec.ts
- packages/atomic/src/components/commerce/atomic-product-description/atomic-product-description.ts
- packages/atomic/src/components/commerce/atomic-product-excerpt/atomic-product-excerpt.spec.ts
- packages/atomic/src/components/commerce/atomic-product-excerpt/atomic-product-excerpt.ts
- packages/atomic/src/utils/tailwind-utilities/min-lines.css
- packages/atomic/vitest-utils/testing-helpers/fixtures/atomic/commerce/atomic-product-fixture.ts
This PR fixes an issue that prevented the min-lines-* utilities from being generated, which in turned led to atomic-product-excerpt and atomic-product-description to not have the min-height required to keep the product grid aligned correctly.
https://coveord.atlassian.net/browse/KIT-4836
> fix(atomic commerce): missing min-height for atomic-product-excerpt/description

- packages/atomic/src/components/commerce/atomic-product-section-description/atomic-product-section-description.ts
- packages/atomic/src/components/commerce/atomic-product/atomic-product.tw.css.ts
- packages/atomic/src/components/common/template-system/cell-desktop.pcss
- packages/atomic/src/components/common/template-system/cell-mobile.pcss
- packages/atomic/src/components/common/template-system/row-desktop.pcss
- packages/atomic/src/components/common/template-system/row-mobile.pcss
- packages/atomic/src/components/common/template-system/sections/section-excerpt.css
- packages/atomic/src/components/common/template-system/sections/sections.css
- packages/atomic/src/components/common/template-system/with-sections.pcss
This PR migrates the styles for atomic-*-section-excerpt to custom utilities that can be used directly on the section components.
[coveord.atlassian.net/browse/KIT-4797](https://coveord.atlassian.net/browse/KIT-4797)
> chore(atomic): migrate atomic-*-section-excerpt styles

- packages/atomic/src/components/commerce/atomic-commerce-layout/atomic-commerce-layout.ts
> docs: document default slot of `atomic-commerce-layout`

- packages/atomic/src/components/commerce/atomic-product-section-name/atomic-product-section-name.ts
- packages/atomic/src/components/commerce/atomic-product/atomic-product.tw.css.ts
- packages/atomic/src/components/common/template-system/cell-desktop.pcss
- packages/atomic/src/components/common/template-system/cell-mobile.pcss
- packages/atomic/src/components/common/template-system/row-desktop.pcss
- packages/atomic/src/components/common/template-system/row-mobile.pcss
- packages/atomic/src/components/common/template-system/sections/section-title.css
- packages/atomic/src/components/common/template-system/sections/sections.css
- packages/atomic/src/components/common/template-system/with-sections.pcss
This PR migrates the styles for atomic-*-section-title to custom utilities that can be used directly on the section components.
[coveord.atlassian.net/browse/KIT-4794](https://coveord.atlassian.net/browse/KIT-4794)
> chore(atomic): migrate atomic-*-section-title styles

- packages/atomic/src/components/commerce/atomic-product-section-visual/atomic-product-section-visual.ts
- packages/atomic/src/components/commerce/atomic-product/atomic-product.tw.css.ts
- packages/atomic/src/components/common/template-system/cell-desktop.pcss
- packages/atomic/src/components/common/template-system/cell-mobile.pcss
- packages/atomic/src/components/common/template-system/row-desktop.pcss
- packages/atomic/src/components/common/template-system/row-mobile.pcss
- packages/atomic/src/components/common/template-system/sections/section-visual.css
- packages/atomic/src/components/common/template-system/sections/sections.css
- packages/atomic/src/components/common/template-system/with-sections.pcss
This PR migrates the styles for atomic-*-section-visual to custom utilities that can be used directly on the section components.
[coveord.atlassian.net/browse/KIT-4793](https://coveord.atlassian.net/browse/KIT-4793)
> chore(atomic): migrate atomic-*-section-visual styles

- packages/atomic/src/components/commerce/atomic-product/atomic-product.tw.css.ts
- packages/atomic/src/components/common/template-system/template-system.css
This PR extracts the common styles from atomic-template-system to a custom tailwind utility. Most of these styles control the product/result grid template layout, and which layout to use depending on display modes and viewport width.
**All the sections must be migrated to the new system before this can be merged.**
https://coveord.atlassian.net/browse/KIT-4807
> chore(atomic): migrate template system common styles to custom utilities

- packages/atomic/dev/examples/commerce-website/search.html
- packages/atomic/src/components/commerce/atomic-commerce-products-per-page/atomic-commerce-products-per-page.pcss
- packages/atomic/src/components/commerce/atomic-product-price/atomic-product-price.ts
- packages/atomic/src/components/commerce/atomic-product-rating/atomic-product-rating.ts
- packages/atomic/src/components/commerce/atomic-product/atomic-product.tw.css.ts
- packages/atomic/src/components/common/atomic-rating/atomic-rating.pcss
- packages/atomic/src/components/common/atomic-rating/atomic-rating.tw.css.ts
- packages/atomic/src/components/common/template-system/template-system.css
This PR ensures that the product children section is always placed last in all modes.
It also adds the atomic-product-section-badges and atomic-product-section-actions sections to the search.html example as we currently have no example with those sections.
**This PR can only be merged once all the product sections have been migrated to the new system.**
https://coveord.atlassian.net/browse/KIT-4703
> fix(atomic): fix product children placement in grid mode

- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-product-list/atomic-commerce-product-list.ts
This PR fixes a bug that was causing a scroll to top when selecting/hovering on a product children in grid mode.
https://coveord.atlassian.net/browse/KIT-4901
> fix(atomic commerce): prevent scroll to top on product children selection/hover in grid mode

- packages/atomic/src/components/commerce/atomic-commerce-query-summary/atomic-commerce-query-summary.ts
Removed request duration info for the `atomic-commerce-query-summary` component
> (docs): Remove request duration info on the  atomic-commerce-query-summary component

- .deployment.config/dev.json
- .deployment.config/prd.json
We are now using `#dxui-deployments` to track our deployments, so let's change it ;)
> chore: change slack channel to dxui-deployments

- packages/headless/src/controllers/knowledge/generated-answer/headless-answerapi-generated-answer-mocks.ts
- packages/headless/src/features/generated-answer/generated-answer-request.ts
Fixed an issue that was recently introduced where the facets were sent in the following format in the payload to the `/generate` endpoint:
```
"facets": {
"0": { ... },
"1": { ... },
"2": { ... }
},
```
while what's accepted is the following format:
```
"facets": [
{ ... },
{ ... },
{ ... }
],
```
https://github.com/user-attachments/assets/34fb45d2-b307-4796-a943-d1a3ce9dd1e3
https://github.com/user-attachments/assets/b2b67b54-9f64-495d-8c00-c7bf44c82bfd
[SFINT-6349]: https://coveord.atlassian.net/browse/SFINT-6349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(headless): fixed payload of the generate call

- packages/atomic/src/components/ipx/atomic-ipx-body/atomic-ipx-body.tsx
- packages/atomic/src/utils/tailwind.global.tw.css
Tailwind V4 removes the default border color, so we added a fallback:
[Default border color](https://tailwindcss.com/docs/upgrade-guide#default-border-color) 
However, this fallback is used only once, so we end up with the fallback styles added to a lot of files for no real benefit. This PR removes the fallback and adds border-neutral where it was missing.
https://coveord.atlassian.net/browse/KIT-4908
> chore(atomic): remove border-color fallback from global styles

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/angular-component-lib/utils.ts
- patches/@stencil+angular-output-target+0.8.4.patch
The atomic-angular wrapper sets the properties directly instead of setting the attributes. This prevents the Lit attributes converters from running, as they only get called when the attribute value change, not when the property is set.
This PR ensures that the wrapper sets the value on the attributes instead of the properties
https://coveord.atlassian.net/browse/KIT-5070
> fix(atomic angular): ensure lit attribute converters get called

- packages/atomic-angular/projects/atomic-angular/src/lib/stencil-generated/components.ts
- packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-interface/atomic-commerce-interface.ts
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-interface/atomic-commerce-recommendation-interface.spec.ts
- packages/atomic/src/components/commerce/atomic-commerce-recommendation-interface/atomic-commerce-recommendation-interface.ts
Essentially, I copied what we do in atomic-commerce-recommendation-interface and adapted it for atomic-commerce-interface.
I also added a check (on both interfaces) to ensure that we only dispatch the action to update the context only if the new locale would be different from the current one in the context state. The reason for this is that in Commerce, you would normally use the same engine for all interfaces on a page, so when you update the locale through the method on the different interfaces, you don't want to dispatch the action multiple times if the state has already been updated previously.
I also updated the tests accordingly.
https://coveord.atlassian.net/browse/KIT-4366
> chore(atomic commerce): deprecate language property and add updateLocale method on atomic-commerce-interface

- packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.spec.ts
- packages/atomic/src/components/search/atomic-search-interface/atomic-search-interface.ts
This PR ensures that when fieldsToInclude is changed, and during initialization, the interface store and headless get updated with the correct values.
https://coveord.atlassian.net/browse/KIT-5091
> fix(atomic): ensure fieldsToInclude always get updated/registered when changed and during init

- packages/atomic/cypress/e2e/common-assertions.ts
- packages/atomic/cypress/e2e/facets/automatic-facet/automatic-facet.cypress.ts
- packages/atomic/cypress/e2e/facets/category-facet/category-facet.cypress.ts
- packages/atomic/cypress/e2e/facets/color-facet/color-facet.cypress.ts
- packages/atomic/cypress/e2e/facets/facet/facet.1.cypress.ts
- packages/atomic/cypress/e2e/facets/facet/facet.2.cypress.ts
- packages/atomic/cypress/e2e/facets/numeric-facet/numeric-facet.cypress.ts
- packages/atomic/cypress/e2e/facets/rating-facet/rating-facet.cypress.ts
- packages/atomic/cypress/e2e/facets/rating-range-facet/rating-range-facet.cypress.ts
- packages/atomic/cypress/e2e/facets/segmented-facet/segmented-facet.cypress.ts
- packages/atomic/cypress/e2e/facets/timeframe-facet/timeframe-facet.cypress.ts
- packages/atomic/cypress/e2e/result-list/result-list.commons.ts
As discussed in Slack, with the migration of the Search Interface, Cypress crashes a lot when running facet test suites.
The boons are not worth the cost here, let's shut them down, and focus on replacing them by Playwright/Storybook a11y tests instead as we migrates.
https://coveord.atlassian.net/browse/KIT-5107
> chore(atomic): disable flaky facet tests

- package-lock.json
- package.json
- packages/atomic-angular/package.json
- packages/atomic-hosted-page/package.json
- packages/atomic-react/package.json
- packages/atomic/package.json
- packages/auth/package.json
- packages/bueno/package.json
- packages/create-atomic-component-project/template/package.json
- packages/create-atomic-component/template/src/components/sample-component/package.json
- packages/create-atomic-result-component/template/src/components/sample-result-component/package.json
- packages/create-atomic-rollup-plugin/package.json
- packages/create-atomic/package.json
- packages/create-atomic/scripts/preparePackageJsonTemplate.mjs
- packages/headless-react/package.json
- packages/headless/package.json
- packages/quantic/package.json
- packages/shopify/package.json
- samples/atomic/search-commerce-angular/package.json
- samples/atomic/search-commerce-react/package.json
- samples/atomic/search-nextjs-app-router/package.json
- samples/atomic/search-nextjs-pages-router/package.json
- samples/atomic/search-vuejs/package.json
- samples/headless-ssr/commerce-express/src/lib/navigatorContext.ts
- samples/headless-ssr/commerce-express/src/middleware.ts
- utils/cdn/package.json
- utils/cdn/scripts/deploy-local-cdn.mjs
- utils/cdn/scripts/serve.mjs
- utils/ci/copy-files.mjs
- utils/ci/rm-rf.mjs
Continuation of 
https://coveord.atlassian.net/browse/KIT-5013
* Added a script for `copy-files.mjs`, and removed `ncp` from multiples packages
* Added a script for `rm-rf.mjs`, and removed `rimraf` from multiple packages
* Small miscellaneous dependencies cleanup
> chore: more cleanup of dependencies in multiples packages
